### ISSUE TITLE
Design for really long token names or balances

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1000]
There are several places where either a really long token name or a long balance can break the UI. In these cases we should design for what to do, e.g. truncate or wrap.

Here are the places these problems can show up:

- [ ] Balances on homepage
- [ ] Send dropdown
- [ ] Latest transaction

**Comment by whoabuddy** [comment]
Noting this is something we may encounter with CityCoins, they have 0 decimal places and block rewards are 250,000 citycoins for every Stacks block in the first 10,000 blocks.

**Comment by aulneau** [comment]
it should be the case that they will be abbreviated to `250k` as we have code to handle this. have you run into it being an issue @whoabuddy

**Comment by whoabuddy** [comment]
No not yet, will test more extensively once we have the latest contract deployed to testnet :pray:

**Comment by jasperjansz** [comment]
Closing — I'll fold this work into #1605
