### ISSUE TITLE
[Send] Form improvements

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1001]
![image](https://user-images.githubusercontent.com/25477905/108508557-4c08df00-72bc-11eb-9e0f-8bb9eec72a13.png)

1a. The contents of this dropdown should not wrap. This is related to a design task (#1000 ), and to making the width wider (#985 )
1b. These improvements will also make it less likely to wrap:
- Token name and balance should be C1 (14px) instead of 16px
- Make token icon 20x20px
- Make margin-right of the icon 8px instead of 24px
- Hard to tell because it wraps, but the margin between dropdown icon and balance should be smaller too (8px)
2. The placeholder amount should have two decimals instead of one
3. Can we inset the 'send max' button?
4. Include fees. I don't think it's a must have because they'll be on the next screen, but if there's space, why not?

**Comment by andresgalante** [comment]
This is looking good enough these days
