### ISSUE TITLE
Sheet component improvements

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1002]
Couple of improvements to the sheet component:

![image](https://user-images.githubusercontent.com/25477905/108509325-64c5c480-72bd-11eb-8942-24ea75e9f397.png)

1. Top corner radius: 16px instead of 24px
2. Header:
- Type style (should be open sauce, correct color, etc. I assume this is a UI library issue)
3. Icon
- Icon should be centered vertically with the title
- Use the correct icon and color: https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/%E2%9D%96-Design-System?node-id=1167%3A0
- You can find the title component with close icon here: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=231%3A8212
4. The content has a margin-top of 24px. See the component on the right with the blue area for the content and the margin between the content and the title.
5. Same as above, but margin-bottom between the content and the actions. Also 24px.
6. The buttons need to be updated, I assume this is a UI library task. We're tracking this here: https://github.com/blockstack/ui/issues/78. This is a minor point, but they look better with 12px margin between them.

You can find the Sheet component design here: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=323%3A24744

**Comment by markmhendrickson** [comment]
These changes appear pending still:

![image](https://user-images.githubusercontent.com/28991/114562663-fb37b600-9c6e-11eb-8317-f836e1216720.png)

**Comment by andresgalante** [comment]
This one is fixed in the current version
