### ISSUE TITLE
[Onboarding] Stacks Wallet is installed improvements

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1005]
![image](https://user-images.githubusercontent.com/25477905/108527665-d8260100-72d2-11eb-8200-4c77897b42c6.png)

1. Replace logo, find it here: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=231%3A10153
2. Mainnet mode indicator, don't think we need this at this point. There's no way to switch so might as well remove it?
3. Type styles, I assume is a UI lib issue. Title should be Ink/100 and subtitle Ink/90.
4. Reduce space between text and actions. It should be 24px
5. Use blue link style for the secondary link instead of grey

General: Content is way too wide, this content should have a max-width of 400px.

Edit: Also suggest changing copy to:
"Are you new to Stacks or do you already have a Secret Key?" and "I’m new to Stacks" as the CTA. It should be clear you can use it with any Stacks-compatible key.

Design: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=323%3A17197

**Comment by markmhendrickson** [comment]
This appears resolved

![image](https://user-images.githubusercontent.com/28991/111173037-9f620a80-85a6-11eb-996d-255880d73de3.png)
