### ISSUE TITLE
[Web Stacks Wallet] Contract post conditions replaced by standard conditions

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#1013]
A tx with contract post condition and standard post conditions are shown in the same way. See screenshot:
![Screenshot from 2021-02-22 09-08-38](https://user-images.githubusercontent.com/1449049/108679976-945b1380-74ed-11eb-94f4-b46a0152e306.png)

The contract post condition should mention the contract

**Comment by friedger** [comment]
It looks like the contract post condition is replaced by a standard post condition, making it impossible to transfer stx from a contract.
The contract call code below results in two standard post conditions:

Code:
![Screenshot from 2021-02-22 09-21-54](https://user-images.githubusercontent.com/1449049/108681452-72629080-74ef-11eb-8de1-9db750b59258.png)

Post conditions in explorer:
![Screenshot from 2021-02-22 09-19-55](https://user-images.githubusercontent.com/1449049/108681345-56f78580-74ef-11eb-89f2-dbe7e5747fd2.png)

**Comment by hstove** [comment]
It's actually worse than this - the current post conditions logic assumed that post conditions could only be applied to the tx-sender. Jude recently updated some wording in this SIP that clears this up. So, the Stacks Wallet actually overwrites every post condition with the current account's STX address.

Related: https://github.com/blockstack/ux/issues/969

**Comment by 314159265359879** [comment]
Can fixing this get a higher priority. This is making it impossible to test ft-transfers using the explorer sandbox or any other app.

**Comment by hstove** [comment]
I agree that it's important, and we have this bucketed in our highest-priority milestone. But, for testing purposes, you don't have to add post conditions for addresses other than the sender. You should in production, but to get the tx to go through, you only need to add them for the sender.

**Comment by friedger** [comment]
Removing the contract condition does not help: https://explorer.stacks.co/txid/0xa14334f26ff547516135b5510809dee33db5797c836f8954c0ed45c2fb51f87b?chain=testnet

On https://speed-spend.org/poxlite it is not possible to redeem stingers because the post condition for the sender of STX, i.e. the smart contract can't be specified in the stacks web wallet.

https://github.com/friedger/speed-spend/commit/c3b30b6bdda2637e573d0aa2c06088ba24aaccac

**Comment by hstove** [comment]
What I'm suggesting is that it would be better for that tx to just have no post conditions at all. Because the `tx-sender` is not actually transferring any assets, the tx will be successful, even in `Deny` mode.

**Comment by unclemantis** [comment]
> What I'm suggesting is that it would be better for that tx to just have no post conditions at all. Because the `tx-sender` is not actually transferring any assets, the tx will be successful, even in `Deny` mode.

Can you be more clear?

**Comment by unclemantis** [comment]
> What I'm suggesting is that it would be better for that tx to just have no post conditions at all. Because the `tx-sender` is not actually transferring any assets, the tx will be successful, even in `Deny` mode.

Wait.  I will try that.  Thanks.

**Comment by hstove** [comment]
Fixed and released in version 2.3.0 :+1:
