### ISSUE TITLE
[tx signing] contract link not working

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1018]
![image](https://user-images.githubusercontent.com/25477905/108701631-7e0e8100-7508-11eb-91d1-abf555c537cf.png)

The link to the contract source isn't working. Also think we should show the arrow to indicate it will open a new window to the explorer.

**Comment by aulneau** [comment]
I am going to take this on today, and i'm planning on going through the app and making sure we are linking to anything and everything we can.
