### ISSUE TITLE
[tx signing] When editing a post condition the amount is in microstacks

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1022]
Main view:

![image](https://user-images.githubusercontent.com/25477905/108704841-d8114580-750c-11eb-99e0-b5b79e709809.png)

Edit view:

![image](https://user-images.githubusercontent.com/25477905/108704872-e2cbda80-750c-11eb-9a9a-756a75ae621b.png)

These amounts should be the same. I think the former (0.00001) is better.

**Comment by pete-watters** [comment]
@markmhendrickson I think this is outdated now, can we close it off?

**Comment by markmhendrickson** [comment]
Yep, good catch
