### ISSUE TITLE
Connect not Connecting

### ISSUE THREAD

**Issue by Agent2222** [leather-io/extension#1027]
Can't find any clear documentation to get connect working -Coding Vanilla js-. All other stacks modules import correctly. I keep getting this error.
<img width="507" alt="Screen Shot 2021-02-21 at 2 33 39 PM" src="https://user-images.githubusercontent.com/47956945/108744870-70f19200-7508-11eb-83e9-1bfb69a624dd.png">

**Comment by markmhendrickson** [comment]
Thanks for this report. Mind indicating the documentation or other instructions you're following to get this installed so we can fix them? Are you going off this page by chance?

https://docs.blockstack.org/build-apps/guides/authentication

**Comment by Agent2222** [comment]
@aulneau was able to help me. I added this script tag: <script src="https://unpkg.com/@stacks/connect@4.3.16-alpha.2a1d243.0/dist/bundle.js" /> and this require('@stacks/connect-ui/dist/loader/index.cjs.js').

There's no clear documentation.

**Comment by markmhendrickson** [comment]
Thanks for the follow-up. I've created an issue here in the documentation repo to track the addition of this script tag guidance: https://github.com/blockstack/docs/issues/1091
