### ISSUE TITLE
Blank secret key screen when calling contract or opening extension

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1029]
![image](https://user-images.githubusercontent.com/25477905/109007497-7a1b6400-76ac-11eb-9786-e77fbe72484c.png)

Trying to call a contract or opening the extension is just showing me a blank secret key screen

![image](https://user-images.githubusercontent.com/25477905/109007644-a800a880-76ac-11eb-92ee-de53b4cf4323.png)

Not sure what has changed since the last time I used it

edit: using Chrome

**Comment by dantrevino** [comment]
I had the same issues.  As a workaround, I had to completely remove the extension and re-add it.

**Comment by timstackblock** [comment]
Regression of this issue from January
https://github.com/blockstack/ux/issues/760

**Comment by markmhendrickson** [comment]
This happened to me after coming back to the extension the day after authenticating initially.

**Comment by hstove** [comment]
Duplicate of #760, and should be fixed in production right now
