### ISSUE TITLE
Minor cosmetic bug - Create your data vault button cut off on the " How data vault works" screen

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#103]
Create your data vault button cut off on the " How data vault works" screen. Slight cut off at the bottom but still clickable and funtional.

<img width="1267" alt="Screen Shot 2020-02-05 at 11 14 27 AM" src="https://user-images.githubusercontent.com/49165468/73859882-c1685580-4808-11ea-9a3e-c0d7caf8d158.png">

**Comment by markmhendrickson** [comment]
I'm not sure this is a bug. When I make my window height just such to cover the bottom of the button, then I scroll the modal all the way down, I see proper margin below the button. Do you not find the same behavior?

<img width="1440" alt="Screen Shot 2020-02-06 at 11 05 02" src="https://user-images.githubusercontent.com/28991/73926861-a06b3780-48d0-11ea-9406-e3dec990dd60.png">

**Comment by timstackblock** [comment]
I should have specified the browser sorry for the confusion. Your picture is from Chrome, in chrome the window scrolls well. The issue with the cut off button is in Firefox. I can access most of the button and click it without issue so it is not a major problem but the padding at the bottom of the window does not display in firefox when the window is  minimized, I have to enter full screen mode to see the padding.

**Comment by kyranjamie** [comment]
A ridiculous bug 😂, well spotted https://bugzilla.mozilla.org/show_bug.cgi?id=748518

**Comment by timstackblock** [comment]
Definitely a P4 issue please prioritize as you see fit.
