### ISSUE TITLE
Set password not working

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1030]
Related to #1029 

I set a password but its loading indefinitely

![image](https://user-images.githubusercontent.com/25477905/109007836-e007eb80-76ac-11eb-97c4-094191dbac56.png)

**Comment by hstove** [comment]
Can anyone reproduce this? I set a password all the time and haven't seen this issue. I'm sure the issue did appear, but without steps to reproduce it, I'm not sure what we can do.

**Comment by andresgalante** [comment]
@timstackblock can you please check if you can reproduce it and what are the steps?

**Comment by aulneau** [comment]
I think this has been resolved, I have not seen this in any of my experiences with the latest. I am very confident this has been fixed. I'm going to close, and if it comes back up we can re-open.
