### ISSUE TITLE
Improve repository structure

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#1046]
@aulneau brought up some really good suggestions that I think we all have felt, so I'm writing them down here.

This repo is a "monorepo", but the strength of this monorepo has dissolved. At first it was a good idea, because we were constantly modifying Connect and the UI library in tandem with the wallet. However, now the UI library is in it's own repo, and Connect is much more stable. It is now uncommon for a PR to make modifications to Connect.

Work required:

- [ ] Move Connect (and `connect-react`, `connect-ui`) into Stacks.js. Or, if the Stacks.js team would prefer that we maintain the repo, we can simply move all the Connect libraries into their own repo.
- [ ] Remove the monorepo. Simply have the stacks wallet code live at the root of the repo.
- [ ] Rename the Github repository to `stacks-wallet-web` or similar
- [ ] Move the `test-app` into something like an `example` folder. It's still required to keep it in this repo for integration tests, but we definitely do not need a monorepo.
- [ ] Update versioning to use a different mechanism (i.e. not lerna)
- [ ] Remove all lerna stuff

Another awesome benefit this gives us is that we can fully take advantage of our conventional commit style and produce a top-level `CHANGELOG.md` that is automatically generated, and will easily highlight changes to the wallet. Or, even better would be to also use Changesets, as Thomas has implemented in the explorer.

**Comment by markmhendrickson** [comment]
Related: https://github.com/blockstack/ux/issues/952 https://github.com/blockstack/ux/issues/954 https://github.com/blockstack/ux/issues/953

**Comment by aulneau** [comment]
related: https://github.com/blockstack/ux/issues/1049
