### ISSUE TITLE
Refactor routing in extension

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#1048]
Currently the [router.tsx](https://github.com/blockstack/ux/blob/fix/layout-improvements/packages/app/src/components/routes.tsx#L41) file we have controlling all the routing of the extension is a bit out of sorts. This is due to many reasons, but mostly it's due to tech debt from days gone where we were handling this application as both a web app and extension. Since we are now only an extension, we can be smarter about how we are doing routing.

The biggest issue I have here is that every route is wrapped in this [`PopupContainer`](https://github.com/blockstack/ux/blob/08af719997c135d3b4334a750ea9d47fc37a662f/packages/app/src/pages/popup/index.tsx#L43), but all routes share the same layout (mostly). Each time a route changes, this component is re-rendered in a way that isn't needed. 

Additionally, the current routes file is a bit hard to grok by looking at it, and I think with a refactor it will be much cleaner, and probably prevent certain edge cases where there are blank screens. 

-------------------------------

@kyranjamie edit: 

+1 on refactoring routing. I think we're mixing patterns a little bit. For example, we have code such as: 

https://github.com/blockstack/stacks-wallet-web/blob/55684b197c3b196d8a1377a1c435d16010addea7/src/routes.tsx#L58-L67

Rather than conditionally rendering a component for a given route, shouldn't each component/page have its own route, and we conditionally switch to said route? This is how this react router guard library is implemented https://www.npmjs.com/package/react-router-guards

The concept of guards is sound, but this is our own implementation, versus a feature of the router. I've used [Angular's route guards with success](https://angular.io/api/router/CanActivate).

First step here is to investigate how we might be able to leverage features of the router to achieve the same as is implemented here with `<AccountGateRoute />`

- [x] Investigate possible alternatives
- [x] Describe next steps

2021-11-5: With the release of `react-router@6`, I've taken a deeper look at the routing, and realising there's more to it than I initially thought. Upgrading to 6 stable breaks the app in many places. Imo we're taking quite a non-standard, mixed approach to routing. 

- Much of the routing is more complex than it needs to be owing to the fact the current set up was built on top the legacy hosted connect authenticator. There's loads of legacy code hanging about still, that makes it especially hard to navigate.
- We're relying on component re-renders to display the correct view. Consider
https://github.com/hirosystems/stacks-wallet-web/blob/245caaea5191affe0e2427ef2bea4d7e2fc0a663/src/routes.tsx#L59-L68 on load, these values are falsy so it would load the `<Installed />` component, but 5 or 6 renders later, they're passed in from the background and the home screen is displayed. We shouldn't rely on component rerenders to display the correct view.
- Account guards should be wrapper components that use the `<Navigate to={...}`>` component to switch routes a given condition. Currently, the guards conditionally render multiple different components to the same route. [See the auth example on the react router docs.](https://reactrouter.com/docs/en/v6/examples/auth)
- We're sharing route paths with different names https://github.com/hirosystems/stacks-wallet-web/blob/245caaea5191affe0e2427ef2bea4d7e2fc0a663/src/common/types.ts#L25-L30 three different names with the same route 🤷🏼‍♂️ 
- The component `PopupContainer` is used to catch app-wide level functionality (as well as apply some styles). With a routing system, this isn't necessary. We can create an upper "naked" route, and nest everything under that. Which would look something this, sparing us the need to repeat the component everywhere
```ts
const Container = () => {
  const x = useAppWideLogic();
  return <Outlet />
}
<Route path="/" element={<Container />} />
  <Route path="/" element={<Home />} />
</Route>
```

Next steps:
- [x] #2069
- [x] Ensure each view has its own route. No sharing routes.
- [x] Refactor `AccountGuard` to use `Navigate`
- [x] Refactor relying on rerender process to load correct route
- [x] Remove `PopupContainer` https://github.com/hirosystems/stacks-wallet-web/issues/2020
- [x] #2070

**Comment by markmhendrickson** [comment]
@aulneau is this issue still relevant given recent refactor work?

**Comment by fbwoolf** [comment]
Linking this PR as it needed to be done as a temp fix prior to refactoring routing: https://github.com/blockstack/stacks-wallet-web/pull/1785

**Comment by fbwoolf** [comment]
Noting as part of this, we need to address duplicate routes: https://github.com/blockstack/stacks-wallet-web/blob/77032ee544b10cf347efb8f38d73ef08c84eda9d/src/common/types.ts#L34

And, remove what is possibly legacy code:
https://github.com/blockstack/stacks-wallet-web/blob/77032ee544b10cf347efb8f38d73ef08c84eda9d/src/common/types.ts#L48

**Comment by fbwoolf** [comment]
All of the issues related to the routing refactor have been merged into dev. I am going to close this issue.
