### ISSUE TITLE
Move Connect packages to its own repository

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#1055]
With #1052, Connect is no longer in this repository.

We need to create a new repository (lets call it `connect`), and simply copy the Connect packages into it. We can keep the lerna monorepo structure that exisits.

- [ ] Create new repository called `connect` (cc @kantai)
- [ ] Move UX monorepo into it
- [ ] Remove all packages except `connect`, `connect-ui`, and `connect-react`
- [ ] Remove all CI except for the NPM related jobs

**Comment by aulneau** [comment]
@hstove are you cool taking this on?
