### ISSUE TITLE
Automate publishing to the extension stores

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#1056]
We need to determine:

- How we publish new releases to the FF and Chrome stores
- What kind of automation we can utilize
  - Likely can automate a lot for Chrome, but FF still needs to be manual
- Who owns this stuff? Who manually publishes new versions and handles reviewer conversations on the FF store?

**Comment by CharlieC3** [comment]
@hstove Having trouble understanding what step in the GH workflow does the actual upload to the Chrome/FF store. Do the Chrome and FF stores reference our GCS bucket when users download the addon through their site?
* https://github.com/blockstack/stacks-wallet-web/blob/main/.github/workflows/publish-extensions.yml#L35
* https://github.com/blockstack/stacks-wallet-web/blob/main/.github/workflows/publish-extensions.yml#L59

Also, it doesn't seem like Chrome is requiring us to sign the plugin before uploading to GCS like Firefox does. If there is a signing step available for that process, I'd like to look into that as well.

**Comment by hstove** [comment]
The GCS bucket is not relevant to actually publishing on the stores - that's just our temporary workaround. Publishing to the stores will be a similar, but different process.

For Chrome, we can almost fully automate the publishing process from CI.

For Firefox, we already have the `web-ext` integration setup, and it's publishing to our "unlisted" channel. Publishing to the "production" version of the store requires simply changing a flag to `--channel listed`, but that still requires a human to log in and:
- add a changelog
- add review notes
- add the raw source code (basically the zip)

So I'm less bullish on automating the FF process, since it might cause more hassle

**Comment by markmhendrickson** [comment]
Should we assign @CharlieC3 here if he's the one mainly looking in this at the moment?

**Comment by markmhendrickson** [comment]
@CharlieC3 Mind providing an update here when you have a chance?

**Comment by CharlieC3** [comment]
@markmhx No update as of yet, but will start on this ticket this week.

**Comment by markmhendrickson** [comment]
@hstove Do we need to provide any justifications here for the Chrome listing?

![image](https://user-images.githubusercontent.com/28991/115933539-5a77a080-a48f-11eb-8ee9-2b87a2d993e1.png)
