### ISSUE TITLE
Fix inconsistent token symbols

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#1057]
In the web wallet, we make up a ticker for the `micro-nothing` contract as simply `MIC` (first three letters). On the explorer, it is displayed as `MNO`. Even though we'll soon support standardized tokens, we should at least be consistent for non-standard assets.

**Comment by Eshwari007** [comment]
@aulneau @kyranjamie Wrapped nothing is displayed as WMNO,thought its not the first three letters,is this accurate?
<img width="310" alt="Screen Shot 2021-05-28 at 4 11 45 PM" src="https://user-images.githubusercontent.com/38872890/120037395-91316100-bfcf-11eb-8310-f1a0ea190635.png">

**Comment by aulneau** [comment]
WMNO is correct, it's coming directly from the contract
