### ISSUE TITLE
Extension new window is no longer centered

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#1069]
There has been a regression such that when a user authenticates/signs transactions (anything that opens a new _window_), the window popout is no longer centered on the browser window that opened it.

**Comment by markmhendrickson** [comment]
From @psq:

> In multi screen setup (3, on Mac OS), the extension window opens on the left of the "main" screen (the one with the menu bar on the Displays OS preferences), really not the most convenient behavior, often you don't even see it appear because of the distance.
> 
> At least, it should open on the same screen as the browser window that the user is using, and at best, possibly remember the last position is was moved to.

**Comment by markmhendrickson** [comment]
Also, related: https://github.com/blockstack/stacks-wallet-web/issues/473
