### ISSUE TITLE
Design visual for the intro modal

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1071]
![image](https://user-images.githubusercontent.com/25477905/111199460-ef4dcb00-85c0-11eb-8ed7-22f1577da21e.png)

This intro modal is what people see when they're prompted to download the web wallet — it's their first interaction with our product. We should add a visual here to get people excited about Stacks and our wallet.

I'm not married to the modal size or anything like that. Here's a draft for the modal you could take: 
https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%96%A5-Wallet-web?node-id=1827%3A5

**Comment by andresgalante** [comment]
When designing this, think about different viewport sizes. We never know the width or height of the window.

There are several [media queries](https://css-tricks.com/a-complete-guide-to-css-media-queries/) that we could take advantage of to accommodate different images to different sizes but don't overthink it because it became a nightmare to maintain.

Let me know if I can help

**Comment by ginny-d** [comment]
Added illustration here: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%96%A5-Wallet-web?node-id=1823%3A37183

There's the main version with grain texture, and a clean version without grain. Please try the first one and if it breaks or there are issues with it, opt for the clean one

thank you!

**Comment by jasperjansz** [comment]
I've added it to all flows here: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%96%A5-Wallet-web?node-id=1844%3A37574

There's a 64x64 spot reserved for the app logo — don't include this placeholder in the export.

**Comment by aulneau** [comment]
@fbwoolf you can export them and included them as needed

**Comment by fbwoolf** [comment]
@jasperjansz I just have the arrow left by `About Stacks Wallet`, that is a feather icon? Also, where should that link go at this point?

**Comment by jasperjansz** [comment]
@fbwoolf that's an Inter glyph: https://rsms.me/inter/glyphs/?g=rightArrow. The link should go to hiro.so/wallet

**Comment by fbwoolf** [comment]
PR is in connect: https://github.com/blockstack/connect/pull/140
