### ISSUE TITLE
Fix ability to authenticate with expired username

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#1073]
One of my accounts has a name which is picked up by the extension, however it is expired. This causes auth to fail.

**Comment by markmhendrickson** [comment]
Related: https://github.com/blockstack/stacks-wallet-web/issues/465

**Comment by markmhendrickson** [comment]
This issue may become particularly relevant again soon since usernames are set to expire en masse after their 1-year extension upon the launch of Stacks 2.0.

**Comment by markmhendrickson** [comment]
@janniks do you expect this issue to be resolved fully app-side with https://github.com/hirosystems/stacks.js/pull/1230?

**Comment by janniks** [comment]
yes pretty sure — but to be safe @aulneau could test with the wallet test-app which does NOT include the username check: https://stacks-wallet-8lgt59q7j-blockstack.vercel.app (which should NOT throw any errors for expired usernames or incorrectly registered usernames) :sparkles:

and to verify here is the old version of the same test-app: https://stacks-wallet-web-66lehyghi-blockstack.vercel.app/ (which will throw errors and get stuck in the problematic username cases) :boom:

pls test with production wallet *(doesn't need to be tested w/ the build from the PR)*
