### ISSUE TITLE
Add new list to password verification

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#1081]
Potentially find more updated dictionaries and/or libraries for validating password strength

**Comment by andresgalante** [comment]
Reach out to Least Authority and decide if we need to do this now or later.

**Comment by kyranjamie** [comment]
https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/Common-Credentials/10-million-password-list-top-1000000.txt

**Comment by andresgalante** [comment]
@kyranjamie there are some amazing gems on that list 😂

**Comment by andresgalante** [comment]
Reopening this issue to add more and stronger lists of passwords.

While working on this I'd suggest that we also tackle #1205

**Comment by markmhendrickson** [comment]
@andresgalante @kyranjamie mind providing some details on what step(s) we want to take here exactly before publishing the report?

**Comment by kyranjamie** [comment]
There are no steps required. LA approved it in its current state, and while improvements can be made, don't believe the need to delay publish of the report.

**Comment by markmhendrickson** [comment]
I've retitled this issue so it's oriented more clearly around adding the specific password list mentioned by @kyranjamie above: 

https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/Common-Credentials/10-million-password-list-top-1000000.txt
