### ISSUE TITLE
Display micro values properly for token balances

### ISSUE THREAD

**Issue by unclemantis** [leather-io/extension#1083]
I have micro throughout the contract and when minting micro the tokens show up as whole numbers in the wallet.  Is it the wallet or the contract?

**Comment by andresgalante** [comment]
@markmhx is this a known issue?

**Comment by markmhendrickson** [comment]
I'd heard of this discrepancy but it doesn't appear we have an issue for it yet, so let's track this one.

**Comment by markmhendrickson** [comment]
I'm closing this issue since it's captured here: https://github.com/blockstack/stacks-wallet-web/issues/1070
