### ISSUE TITLE
STX transfers in window/extension should be the same

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#1085]
Currently if an app creates a token transfer event, it uses a completely different component than what is used to send STX from within the extension/app. We should combine these and have them be the same.

**Comment by aulneau** [comment]
Sorry, I should have been more clear @hstove 

- When an app does a stx token transfer, we use the "sign transaction" flow, not the send flow
- figma only has 1 version of the "send" flow which is different than the "sign transaction" flow from an app
- Is it the case that the "send" flow from an app should be the same as "sign transaction"? (I think we should have them be the same, personally)

The bug element is:
- The "notification" pop out is using older code that causes this https://github.com/blockstack/stacks-wallet-web/issues/1067, so it could be part of https://github.com/blockstack/stacks-wallet-web/pull/1084 to fix, and the design be a different issue

**Comment by hstove** [comment]
Sorry, can we make this a little simpler, I think I'm following. There are two ways to make a transaction currently:

- From the extension, clicking the "Send" button. Call it "native" (just for this discussion)
- From an app, using the popup with transaction details specified by the app. Let's call this "popup"

I personally like the idea of re-using the popup UI regardless of if the app requests a `stx_transfer`, `contract_call`, or `smart_contract` (deploy) transaction. Obviously with slight tweaks. Are you suggesting we don't do this?

Then there is the question of how "editable" the popup should be. Should you be allowed to change params? We allow you to change the post conditions. Even just for simplicity, I would prefer that we keep all params (other than post conditions) static for an app-triggered TX.

Maybe there are no designs in the new Figma for a `stx_transfer` popup, but there was at one point, and it was different than the "native" send flow.

**Comment by aulneau** [comment]
> I personally like the idea of re-using the popup UI regardless of if the app requests a stx_transfer, contract_call, or smart_contract (deploy) transaction. Obviously with slight tweaks. Are you suggesting we don't do this?

I agree with this, however, I think we should make an adjustment to the in-extension/native send flow, adding the view described above as the "confirm" view from within the extension.

To outline this a bit better, I'm suggesting that these two paths have the same "confirmation screen"

- [native] user starts a stx transfer from send, fills out the form, is then presented with the confirm view
- [popup] a user does some action in app to generate one of these: `stx_transfer`, `contract_call`, or `smart_contract`, the popup opens and you are presented with the confirm view

So the similarities would be in the final step.

**Comment by aulneau** [comment]
agreed! cc @jasperjansz

**Comment by jasperjansz** [comment]
Will do. The confirmation screen in the regular send flow was also missing, I imagine we can make them one and the same.
