### ISSUE TITLE
STX transfer from app doesn't switch to logged in account

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#1086]
When an app creates a transaction signing event, the extension does not switch to the account that it originated from. The extension should automatically switch to the account that originated the action. Additionally, there could be instances in which an app is signed in with an entirely different keychain than what is in the extension. We should create an error state for that, too.

**Comment by hstove** [comment]
> there could be instances in which an app is signed in with an entirely different keychain than what is in the extension

This should be fixed in #1092 

> the extension does not switch to the account that it originated from

Hm, really? What app are you seeing this in? This was 'fixed' in a more recent version of Connect, which includes the STX address that the user "authenticated" with

**Comment by aulneau** [comment]
This is now fixed, closing :)
