### ISSUE TITLE
I can not start the web version of the wallet.

### ISSUE THREAD

**Issue by X3nX3n** [leather-io/extension#1089]
Hello, when I start Todo and register a wallet, a window opens app.blockstack.org for registration wallet, but when I tried to write my application by copying Todo, the web version does not open, it only offers to install the wallet. I recently started to learn JS, please help. How to launch the web version of the wallet?
![WrkWeb](https://user-images.githubusercontent.com/47632045/111691264-334e0380-883f-11eb-8fa2-db7c29d3cad8.png)
![NtWrkWeb](https://user-images.githubusercontent.com/47632045/111691238-2c26f580-883f-11eb-8ef5-623cbf20d2c3.png)

**Comment by markmhendrickson** [comment]
It appears we need to update the todos app to the latest version of @stacks/connect to trigger extension usage: https://github.com/blockstack/todos/issues/70

I'm closing this out in favor of the issue in the todos repo. Please submit a PR for that change if you have the opportunity!
