### ISSUE TITLE
Can not add more than one restraint

### ISSUE THREAD

**Issue by unclemantis** [leather-io/extension#1091]
I am trying to add a FT restraint greater than 0 and stacks restraint greater than 0. I am trying to redeem a token for stacks in my clarity script. Example code.

`(define-public (redeem-stinger (amount uint))
  (let ((recipient tx-sender))
    (let ((b (ft-get-balance stinger recipient)))
      (if (>= b amount)
          (begin
            ;;(try! (as-contract (ft-transfer? stinger amount recipient tx-sender)))
            (try! (as-contract (stx-transfer? amount tx-sender recipient)))
            (ok true)
          )
          (err u9)))))`

**Comment by markmhendrickson** [comment]
Is this an issue with passing post conditions into the Stacks Wallet for transaction signing? And if so, how does it manifest itself exactly? Is there an error message?

**Comment by Zk2u** [comment]
> Is this an issue with passing post conditions into the Stacks Wallet for transaction signing? And if so, how does it manifest itself exactly? Is there an error message?

this is regarding transaction signing. i don't believe there is an error message, rather there is no option to add multiple restraints. @unclemantis can we get some more info? screenshots maybe?

**Comment by unclemantis** [comment]
Fixed.  Have not tried it yet.
