### ISSUE TITLE
You can transfer stuff (ft, or stx) to a contract using post conditions, however a contract can't when you burn stuff

### ISSUE THREAD

**Issue by hozzjss** [leather-io/extension#1093]
While testing out DecentDelegate on Mocknet I discovered this bug I don't think it's within the wallet itself but rather the underlying api or blockchain, I am not certain, but a reproduction of this can be done through getting some $WMNO (wrapped nothing) and unwrapping it with a tx through the wallet, there shouldn't be any post conditions, as you're not spending anything, right? except when you're expected to burn stuff, also that doesn't work

To reproduce try getting $WMNO and unwrapping through the contract
The contract on testnet: https://explorer.stacks.co/txid/ST21T5JFBQQPYQNQJRKYYJGQHW4A12G5ENBBA9WS7.gastric-gold-mouse?chain=testnet

I'd send anybody testnet $MNO, but I mean, why not test on mainnet, much more fun, and with the [faucet](https://nothingtoken.com)

Example of failed txs:
without post conditions:
https://explorer.stacks.co/txid/0xfae3f508a329448f52707aaa0c22e4f3f6f78842cff05d92c29b9fdcad14a000?chain=mainnet

with post conds:
https://explorer.stacks.co/txid/0x805a7d9b445f920bfa9d774014d9866d5b073dd6d13ea28aa7bcbf924a9acffb?chain=mainnet

Example successful tx: post condition mode allowed
https://explorer.stacks.co/txid/0xf40f4e4fa3b744f111762b8e622b53856ee87744e142ba1a2cbaeae580f7cc32?chain=mainnet

**Comment by 314159265359879** [comment]
Thanks for posting this, I was wondering why I was unable to unwrap my WMNO

**Comment by hstove** [comment]
#969 is the issue and that issue is being worked on this week

**Comment by hstove** [comment]
The temporary workaround is to not set any post conditions when calling the `unwrap` method. You only _need_ to set post conditions when `tx-sender` is transferring an asset - but for `unwrap`, it's only the contract that is making a transfer.

**Comment by hstove** [comment]
Where are these transactions being generated? If you're not using the web wallet, then the issue is that you need to change the post condition "from" address to the contract - not the recipient as is in your example. But if you're using the web wallet, then you're not able to do this at the moment, because of #969

**Comment by hozzjss** [comment]
That makes sense @hstove
