### ISSUE TITLE
Add headers to all api requests

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#1094]
Let's create a wrapped fetcher that will always append product specific headers to the API. 

@hstove @kyranjamie what should the standard be for headers? `X-HIRO-PRODUCT: 'stacks-web-wallet-VERSION'`?

**Comment by kyranjamie** [comment]
@wileyj suggested an object (didn't realise you can set header objects 🤔 ) https://github.com/hirosystems/devops/issues/667

If not obj, then maybe 2 headers is better?

**Comment by hstove** [comment]
+1 to 2 headers (or an object if that works)

**Comment by markmhendrickson** [comment]
Related: https://github.com/blockstack/stacks-wallet/issues/700 https://github.com/blockstack/explorer/issues/413

**Comment by markmhendrickson** [comment]
I'm reopening this so that @Eshwari007 can QA that all API requests include the intended headers.

**Comment by Eshwari007** [comment]
@markmhx @aulneau Believe the ticket hasnt reopened.
Kindly provide more information on the API request and the intended headers to be tested.

**Comment by Eshwari007** [comment]
Notes:

Environment:Stacks Explorer

Use case:

- Validating all the API calls in Dev tools for explorer is accurate.Mostly the API call as attached and also on all the links in explorer page is calling the accurate version of the API call.

- Developer tool>Network>XHR is where we can find the API call requests.

Snapshots included for verification:
<img width="583" alt="Screen Shot 2021-06-08 at 9 34 25 AM" src="https://user-images.githubusercontent.com/38872890/121194772-0bb67800-c83d-11eb-8fb3-a3a3be880db7.png">

**Comment by Eshwari007** [comment]
Created an issue related to this ticket:https://github.com/blockstack/explorer/issues/451
Will close the parent ticket for now and retest both child and parents ticket upon the ticket above code fix

cc @markmhx @andresgalante
