### ISSUE TITLE
extension window should open on the same screen as the browser window

### ISSUE THREAD

**Issue by psq** [leather-io/extension#1114]
In multi screen setup (3, on Mac OS), the extension window opens on the left of the "main" screen (the one with the menu bar on the Displays OS preferences), really not the most convenient behavior, often you don't even see it appear because of the distance.

At least, it should open on the same screen as the browser window that the user is using, and at best, possibly remember the last position is was moved to.

**Comment by markmhendrickson** [comment]
I think this may be a duplicate with https://github.com/blockstack/stacks-wallet-web/issues/1069. I'll close and add your notes there.
