### ISSUE TITLE
making the extension window too tall prevents scrolling all the way down

### ISSUE THREAD

**Issue by psq** [leather-io/extension#1115]
Hopefully a picture will help explain better than a long decription.

When validating a contract call, if you make the height of the window too high, the scrolling area does not expand all the way down, and also prevents scrolling all the way down.  With the following screenshot, that's all you can see, and scrolling is no longer possible.  Fortunately, reducing the size of the window will allow scrolling again, no need to close and reopen.

<img width="576" alt="Screen Shot 2021-04-17 at 1 56 53 AM" src="https://user-images.githubusercontent.com/255/115107547-57753100-9f20-11eb-96db-c7e437417d6f.png">

**Comment by psq** [comment]
I disagree with the `enhancement` and P4 categorization, it makes for a poor user experience (you can't even get to the commit button any more after you've resized, at least till you resize back to the original size of smaller)

**Comment by markmhendrickson** [comment]
P2 works for me. Just to note that P3 and P4 are _non-critical_ bugs (affecting a lot or few users respectively) and resizing the window does appear to unblock the user here.
