### ISSUE TITLE
doContractCall onFinish called multiple times

### ISSUE THREAD

**Issue by psq** [leather-io/extension#1116]
Using connect-react, click on a button that calls `doContractCall`, just close the extension window without doing anything, repeat 4 times, then the 5th time, click confirm.

The `onFinish` callback will be called 5 times, with the same values each time.

It should only be called once.

**Comment by psq** [comment]
yes, which is really surprising if this was known.  Why wasn't this prioritized to be fixed asap?

**Comment by aulneau** [comment]
> yes, which is really surprising if this was known. Why wasn't this prioritized to be fixed asap?

Client side apps can fix it in the interim by wrapping the on finish callback in a useCallback hook @psq

**Comment by psq** [comment]
sure, I know I can work around it, it is just that it leaves a bad mouth feel kinda of thing...  plus makes you wonder what else is in an inconsistent state inside connect/web wallet...

When there will be real money at stake, you can't have these kind of things left untouched.

If the developer can't fully trust the framework/tools, how can you expect the users to?

Just my 0.02 STX observation, of course

**Comment by aulneau** [comment]
> sure, I know I can work around it, it is just that it leaves a bad mouth feel kinda of thing... plus makes you wonder what else is in an inconsistent state inside connect/web wallet...
> 
> When there will be real money at stake, you can't have these kind of things left untouched.
> 
> If the developer can't fully trust the framework/tools, how can you expect the users to?
> 
> Just my 0.02 STX observation, of course

Well I mean the extension is still in an alpha version, not officially released with big warnings about how it should not be used in production or that it's ready for anything of the sort.

We just completed an extensive security audit and are working to wrap up any remaining changes from that, and then continue on with this exact kind of bug fix before trying to officially release the extension. 

We have no intention of leaving these kinds of things untouched @psq.

**Comment by markmhendrickson** [comment]
I would add as well that we really appreciate you vocalizing support for issues like this one @psq since it helps us prioritize where developers are encountering the most pain or annoyance.

I'm going to close out this issue so we can continue working on and discussing the fix on the other one linked above.
