### ISSUE TITLE
Cannot log in app when using stacks-wallet-web firefox extension

### ISSUE THREAD

**Issue by paradigma-cl** [leather-io/extension#1118]
If using Firefox 88 (64 bit) for win10 cannot Log In App https://pr-1103.testnet-demo.stacks.engineering/.  It does nothing.
Console logs are:
Content Security Policy: Ignorando "'unsafe-inline'" dentro de script-src o style-src: nonce-source o hash-source especificado
Type error for parameter details (Error processing tabId: Integer -1 is too small (must be at least 0)) for browserAction.setIcon. 2 background_page.js:483
Type error for parameter details (Error processing tabId: Integer -1 is too small (must be at least 0)) for browserAction.setIcon. background_page.js:483
POSThttps://time.is/cantbeevil-csp-report
[HTTP/2 404 Not Found 606ms]

Content Security Policy: Ignorando "'unsafe-inline'" dentro de script-src o style-src: nonce-source o hash-source especificado
Content Security Policy: Ignorando "'unsafe-inline'" dentro de script-src o style-src: nonce-source o hash-source especificado
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
rikaichamp-content.js:4379
Type error for parameter details (Error processing tabId: Integer -1 is too small (must be at least 0)) for browserAction.setIcon. background_page.js:483
Type error for parameter details (Error processing tabId: Integer -1 is too small (must be at least 0)) for browserAction.setIcon. background_page.js:483
Type error for parameter details (Error processing tabId: Integer -1 is too small (must be at least 0)) for browserAction.setIcon. background_page.js:483
Type error for parameter details (Error processing tabId: Integer -1 is too small (must be at least 0)) for browserAction.setIcon. background_page.js:483
POSThttps://www.economist.com/cantbeevil-csp-report
[HTTP/2 404 Not Found 904ms]

POSThttps://docs.google.com/cantbeevil-csp-report
[HTTP/2 404 Not Found 157ms]

POSThttps://time.is/cantbeevil-csp-report
[HTTP/2 404 Not Found 575ms]

POSThttps://docs.google.com/cantbeevil-csp-report
[HTTP/2 404 Not Found 158ms]

Content Security Policy: Ignorando "'unsafe-inline'" dentro de script-src o style-src: nonce-source o hash-source especificado
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 692"  data: no] L10nRegistry.jsm:692:19
Type error for parameter details (Error processing tabId: Integer -1 is too small (must be at least 0)) for browserAction.setIcon. background_page.js:483
POSThttps://docs.google.com/cantbeevil-csp-report
[HTTP/2 404 Not Found 192ms]

Content Security Policy: Ignorando "'unsafe-inline'" dentro de script-src o style-src: nonce-source o hash-source especificado 2
getScreenshot(https://opengraph.githubassets.com/7ee67841512ff2ed19861d01880fc29e68c1a4e1e19e5d6e0ca33a9202c1f579/blockstack/stacks-wallet-web) failed: Error: page-thumbnail:error

When trying to Log In https://crosscheck.paradigma.global no response and console logs are:
Content Security Policy: Ignorando "'unsafe-inline'" dentro de script-src o style-src: nonce-source o hash-source especificado

When trying to Log In https://blocksurvey.io no response either and console logs are:
Error de Seguridad: Contenido en https://blocksurvey.io/ no podrá cargar o enlazar a moz-extension://77f1b812-289b-480f-9a6e-c8e4ef2e4da5/index.html#/sign-in?authRequest=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJzZW5kVG9TaWduSW4iOnRydWUsImFwcERldGFpbHMiOnsibmFtZSI6IkJsb2NrU3VydmV5IiwiaWNvbiI6Imh0dHBzOi8vYmxvY2tzdXJ2ZXkuaW8vYXNzZXRzL2ltYWdlcy9sb2dvL2Jsb2Nrc3VydmV5LWxvZ28tbG9naW4uc3ZnIn0sImNvbm5lY3RWZXJzaW9uIjoiMi4xMi4yLWFscGhhLjUxZjlhZTkuMCIsImp0aSI6Ijg0MWM1ZmZlLWY5MDEtNGE2YS1hOGYzLTBmNzM5ZTQ3NTY4YiIsImlhdCI6MTYxODg2MjQ5OCwiZXhwIjoxNjE4ODY2MDk4LCJpc3MiOiJkaWQ6YnRjLWFkZHI6MTJ0VDRiSEtacUV3aXRqTllCdk52UGdVTko3azd0dGNmTiIsInB1YmxpY19rZXlzIjpbIjAzZDNhZmVkNzljZTI2NzRiMmM3ZDliYjQzNDFhZDgwZTQwOWRkNjI1MWMwZWM1MGVhODU3NTI2MWZjY2UyZGI0MSJdLCJkb21haW5fbmFtZSI6Imh0dHBzOi8vYmxvY2tzdXJ2ZXkuaW8iLCJtYW5pZmVzdF91cmkiOiJodHRwczovL2Jsb2Nrc3VydmV5LmlvL21hbmlmZXN0Lmpzb24iLCJyZWRpcmVjdF91cmkiOiJodHRwczovL2Jsb2Nrc3VydmV5LmlvL2Rhc2hib2FyZCIsInZlcnNpb24iOiIxLjMuMSIsImRvX25vdF9pbmNsdWRlX3Byb2ZpbGUiOnRydWUsInN1cHB
TypeError: (destructured parameter) is undefined Grammarly-bg.js:2:1311909
Content Security Policy: Ignorando "'unsafe-inline'" dentro de script-src o style-src: nonce-source o hash-source especificado

**Comment by aulneau** [comment]
> https://pr-1103.testnet-demo.stacks.engineering/.

This app will never work with the extension, as it's made to work with the legacy authentication app (app.blockstack.org).

It seems to me that all of these apps are meant to work with the older version. You can try https://explorer.stacks.co/sandbox to test out the proper authentication flow

**Comment by paradigma-cl** [comment]
It happens also in other machine under win10 and Linux ubuntu

**Comment by paradigma-cl** [comment]
> 
> 
> > https://pr-1103.testnet-demo.stacks.engineering/.
> 
> This app will never work with the extension, as it's made to work with the legacy authentication app (app.blockstack.org).
> 
> It seems to me that all of these apps are meant to work with the older version. You can try https://explorer.stacks.co/sandbox to test out the proper authentication flow
I understand this case.  And in these cases, what do you think?:

When trying to Log In https://crosscheck.paradigma.global no response and console logs are:
Content Security Policy: Ignorando "'unsafe-inline'" dentro de script-src o style-src: nonce-source o hash-source especificado

When trying to Log In https://blocksurvey.io no response either and console logs are:
Error de Seguridad: Contenido en https://blocksurvey.io/ no podrá cargar o enlazar a moz-extension://77f1b812-289b-480f-9a6e-c8e4ef2e4da5/index.html#/sign-in?authRequest=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJzZW5kVG9TaWduSW4iOnRydWUsImFwcERldGFpbHMiOnsibmFtZSI6IkJsb2NrU3VydmV5IiwiaWNvbiI6Imh0dHBzOi8vYmxvY2tzdXJ2ZXkuaW8vYXNzZXRzL2ltYWdlcy9sb2dvL2Jsb2Nrc3VydmV5LWxvZ28tbG9naW4uc3ZnIn0sImNvbm5lY3RWZXJzaW9uIjoiMi4xMi4yLWFscGhhLjUxZjlhZTkuMCIsImp0aSI6Ijg0MWM1ZmZlLWY5MDEtNGE2YS1hOGYzLTBmNzM5ZTQ3NTY4YiIsImlhdCI6MTYxODg2MjQ5OCwiZXhwIjoxNjE4ODY2MDk4LCJpc3MiOiJkaWQ6YnRjLWFkZHI6MTJ0VDRiSEtacUV3aXRqTllCdk52UGdVTko3azd0dGNmTiIsInB1YmxpY19rZXlzIjpbIjAzZDNhZmVkNzljZTI2NzRiMmM3ZDliYjQzNDFhZDgwZTQwOWRkNjI1MWMwZWM1MGVhODU3NTI2MWZjY2UyZGI0MSJdLCJkb21haW5fbmFtZSI6Imh0dHBzOi8vYmxvY2tzdXJ2ZXkuaW8iLCJtYW5pZmVzdF91cmkiOiJodHRwczovL2Jsb2Nrc3VydmV5LmlvL21hbmlmZXN0Lmpzb24iLCJyZWRpcmVjdF91cmkiOiJodHRwczovL2Jsb2Nrc3VydmV5LmlvL2Rhc2hib2FyZCIsInZlcnNpb24iOiIxLjMuMSIsImRvX25vdF9pbmNsdWRlX3Byb2ZpbGUiOnRydWUsInN1cHB
TypeError: (destructured parameter) is undefined Grammarly-bg.js:2:1311909
Content Security Policy: Ignorando "'unsafe-inline'" dentro de script-src o style-src: nonce-source o hash-source especificado

**Comment by paradigma-cl** [comment]
> 
> 
> > https://pr-1103.testnet-demo.stacks.engineering/.
> 
> This app will never work with the extension, as it's made to work with the legacy authentication app (app.blockstack.org).
> 
> It seems to me that all of these apps are meant to work with the older version. You can try https://explorer.stacks.co/sandbox to test out the proper authentication flow
The plug-in works with the sandbox.
Nevertheless, it does not work our dapp https://crosscheck.paradigma.global.
The app https://crosscheck.paradigma.global works with the Stacks wallet web plugin for Chromium.  But the same, it does not work with the Stacks wallet web plugin.  We have dug in our app to find something without any results.

**Comment by markmhendrickson** [comment]
I find that on initial load of Crosscheck, the "Secure Login with Stacks" does _not_ detect my extension install. But if I refresh the page manually, it _does_ detect it.

The introductory modal and authentication screens both reference the "Todos" app, suggesting a configuration issue with app details at least. @paradigma-cl can you double check that all parameters are configured as intended with the Connect integration?

![image](https://user-images.githubusercontent.com/28991/115445791-9fdd6900-a216-11eb-9f92-55330e909158.png)
![image](https://user-images.githubusercontent.com/28991/115445992-dc10c980-a216-11eb-9b1a-d017e3420102.png)

**Comment by paradigma-cl** [comment]
Managed to detect and solve issues with Firefox plugin.  Thank you for the help!
