### ISSUE TITLE
PostConditions.allow message confusing

### ISSUE THREAD

**Issue by psq** [leather-io/extension#1120]
The message you get when setting PostConditions.allow is the same as having an empty array of postconditions with PostConditions.deny, which is confusing, or misleading.

It tells you nothing will be transferred, instead it should say that the contract can do anything it wants with the user account.

**Comment by aulneau** [comment]
@psq can you provide a screenshot?

**Comment by psq** [comment]
<img width="434" alt="Screen Shot 2021-05-11 at 4 53 52 PM" src="https://user-images.githubusercontent.com/255/117898457-da687d80-b279-11eb-9cc1-f6d56e01dd6a.png">

code is using:
```
      postConditionMode: PostConditionMode.Allow,  // TODO(psq): allow for now, there is no api to retrieve the token in sip-010!!!
```
and not setting `postConditions`, and will execute and transfer tokens

Looks like this is the same thing you'd get with `Deny` and no postConditions

**Comment by markmhendrickson** [comment]
I'm closing this out in favor of https://github.com/blockstack/stacks-wallet-web/issues/1152, wherein we want to improve the "allow" mode UX generally, inclusive of this case.
