### ISSUE TITLE
Update build instructions to clarify script vs. Docker

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1131]
Mozilla's reviewer for Firefox Add-ons reported the following when trying to build the extension using the instructions found at https://github.com/blockstack/stacks-wallet-web#building-browser-extensions

> I tried to build your add-on on Ubuntu 18.04.02 using node 10.16.0, npm 6.9.0, but I'm getting errors. I'm pasting here the build log:
> 
> sh build-ext.sh
> 🛠  Installing dependencies.
> yarn install v1.22.5
> [1/5] Resolving packages...
> warning Resolution field "schema-inspector@2.0.0" is incompatible with requested version "schema-inspector@^1.7.0"
> success Already up-to-date.
> Done in 1.65s.
> 🛠  Compiling extension.
> yarn run v1.22.5
> $ cross-env NODE_ENV=production EXT_ENV=prod webpack --config webpack/webpack.config.prod.js
> fatal: not a git repository (or any of the parent directories): .git
> [webpack-cli] Failed to load '/home/test/Downloads/stacks-wallet-2.4.3-src/stacks-wallet-web-> > > main/webpack/webpack.config.prod.js' config
> [webpack-cli] Error: Command failed: git rev-parse --abbrev-ref HEAD
> fatal: not a git repository (or any of the parent directories): .git
> 
>     at checkExecSyncError (child_process.js:635:11)
>     at execSync (child_process.js:671:15)
>     at getBranch (/home/test/Downloads/stacks-wallet-2.4.3-src/stacks-wallet-web-> main/webpack/webpack.config.base.js:28:18)
>     at getVersion (/home/test/Downloads/stacks-wallet-2.4.3-src/stacks-wallet-web-main/webpack/webpack.config.base.js:41:18)
  >   at Object.<anonymous> (/home/test/Downloads/stacks-wallet-2.4.3-src/stacks-wallet-web-main/webpack/webpack.config.base.js:46:17)
>     at Module._compile (/home/test/Downloads/stacks-wallet-2.4.3-src/stacks-wallet-web-main/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>     at Module.require (internal/modules/cjs/loader.js:887:19) {
>   status: 128,
>   signal: null,
>   output: [
>     null,
>     '',
>     'fatal: not a git repository (or any of the parent directories): .git\n'
>   ],
>   pid: 67562,
>   stdout: '',
>   stderr: 'fatal: not a git repository (or any of the parent directories): .git\n'
> }
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> Command failed: /home/test/.yvm/versions/v1.22.5/bin/yarn.js build
> 🛠  Packaging Browser Extension
> build-ext.sh: 7: cd: can't cd to dist
> 
> Let me know if I'm missing any details. In addition to this, please test your build in a clean environment to make sure it is reproducible. If necessary, update the source package and/or the instructions to build.

**Comment by markmhendrickson** [comment]
@hstove Should we simply remove the non-Docker instructions here and refer to the Docker ones as the primary ones for Mozilla and others?

**Comment by hstove** [comment]
@markmhx yes, I'd say we should just point them to the Docker instructions. In the past I believe they were able to use Docker

**Comment by markmhendrickson** [comment]
Is it worth even keeping the non-Docker instructions here though, or should we excise?

**Comment by hstove** [comment]
In my opinion, yes - the Docker image just runs the same script, but with a bunch of overhead. Using Docker is really only more convenient when you're building the extension from a .zip of the source code. If you used git to download the repo, then using the script is much easier and faster.

**Comment by markmhendrickson** [comment]
Makes sense. Let's simply update the README to indicate that the Docker instructions are suitable for building from .zip and those for the script are suitable for building from git?
