### ISSUE TITLE
Graphical issues on transaction screen with long arguments

### ISSUE THREAD

**Issue by MarvinJanssen** [leather-io/extension#1138]
Long arguments compress the table layout and can cause horizontal scroll bars. Maybe we want the left-side to never wrap and the right side to have a `word-break: break-all`.

<img width="554" alt="Screenshot 2021-05-05 at 9 40 16 PM" src="https://user-images.githubusercontent.com/5727806/117242873-f936c200-adea-11eb-83f3-8054b8029c58.png">

**Comment by aulneau** [comment]
yep agreed! i've added it for the attachment row -> https://github.com/blockstack/stacks-wallet-web/pull/1137/commits/741ed9fdd6de24576eaceec39bc47510f91c0f1a

**Comment by beguene** [comment]
@andresgalante I tested, this is working fine now, the whole component has changed recently and that fixed the issue.
I am not sure if I should close this or it should be moved to another state like 'in qa'

**Comment by andresgalante** [comment]
It seems like a small fix, I'd skip QA for this one. If you tested it and it's fixed, then close the issue and it'll move to done automaticlaly
