### ISSUE TITLE
[2.3.0] Bug: wallet keeps flipping to testnet

### ISSUE THREAD

**Issue by mijoco-btc** [leather-io/extension#1143]
Bug found testing Stacks Wallet for Web.

### Error

**Loadable**: `transaction.contract-interface`
**Message**: `Unable to fetch interface for contract SP3QSAJQ4EA8WXEDSRRKMZZ29NH91VZ6C5X88FGZQ.appmap-v1`

The error is that the wallet keeps toggling to Testnet and failing to find the contract but the contract is deployed on mainnet and wallet is on mainnet when calling openContractCall?

Triggering Tx with 
import { openSTXTransfer, openContractDeploy, openContractCall } from '@stacks/connect'
...        openContractCall(txOptions).catch((error) => {

package.json
version : "@stacks/connect": "^5.0.5"

Wallet version
  "name": "Stacks Wallet",
  "author": "Hiro PBC",
  "version": "2.4.0",

### Environment

**Version**: `2.3.0`
**Branch**: `main`
**Commit**: `18453a9`
<img width="465" alt="Screenshot 2021-05-10 at 10 26 29" src="https://user-images.githubusercontent.com/4384929/117637929-377d0a00-b17a-11eb-8dcd-914d54c154e7.png">

**Comment by markmhendrickson** [comment]
Are you finding this for all contract calls for mainnet or just this particular contract? @psq @friedger ever seen this by chance?

**Comment by mijoco-btc** [comment]
My previous comment was a red herring - please ignore.

The toggle issue is fixed by passing the network from the client ... e.g.

`import { StacksTestnet, StacksMainnet } from '@stacks/network'`
`const testnet = new StacksTestnet()
const mainnet = new StacksMainnet()`

`network: (configuration.network === 'mainnet') ? mainnet : testnet,`

**Comment by mijoco-btc** [comment]
You can - its a client side error really although the UI in the wallet is a little confusing as it switches from mainnet to testnet without user involvement.
