### ISSUE TITLE
Force 'deny' mode for transaction signing

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1151]
This is important and one of the core tenets of the design of the web wallet, without it post conditions aren't nearly as valuable.

![image](https://user-images.githubusercontent.com/25477905/117717060-9d997980-b1da-11eb-93bb-630e97800ad1.png)

**Comment by markmhendrickson** [comment]
@jasperjansz to create discussion and share with @psq and others so we can hash out the pros and cons here.
