### ISSUE TITLE
Improve transaction signing experience for "allow" mode

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1152]
Not having to pass all post conditions would be useful for devs who want to test, and don't quite care about post conditions just yet. They should be able to sign transactions in 'allow' mode somehow, but for users it should be forced to 'deny' mode. Maybe an advanced toggle somewhere.

![image](https://user-images.githubusercontent.com/25477905/117717412-13054a00-b1db-11eb-9322-bdde8f2ffd84.png)

**Comment by jasperjansz** [comment]
@markmhx 

> Is this indeed the case? I haven't personally encountered the requirement of passing post conditions in my (limited) with integration transaction signing with Connect (example).

You will have to when we force the web wallet in deny mode (#1151).

**Comment by psq** [comment]
> Yeah I am not positive the best choice is to simply blanket force deny mode, but make it clear what could happen if it was in allow mode

yes, definitely for that, and currently, the message is incorrect (#1120)

**Comment by psq** [comment]
> Not sure I follow. The user wants to swap x for some amount of y (plus or minus some slippage). Aren't those your post conditions?

unless there is some metadata available, swapr does not know what the token names to put conditions on are.  The only thing it knows about the tokens are their contract principal (.e.g `ST31HHVBKYCYQQJ5AQ25ZHA6W2A548ZADDQ6S16GP.plaid-token-v0a`, `ST31HHVBKYCYQQJ5AQ25ZHA6W2A548ZADDQ6S16GP.stx-token-v0a`, and `ST31HHVBKYCYQQJ5AQ25ZHA6W2A548ZADDQ6S16GP.tokensoft-token-v0a`, so ft-token is `plaid` in the first case, not an ft-token in the second case, and `tokensoft-token` in the third case).  And going the static analysis route is **NOT** a rabbit hole I want to get into...

so, the plan is that if some metadata is available, `swapr` will use that, or use `Allow` if it is not available.  Yet an other addition to sip-010, or some addendum to write

**Comment by aulneau** [comment]
@jasperjansz would you be able to work on a design for displaying this information in the wallet? (what mode the current transaction is in, and an option to switch)

**Comment by markmhendrickson** [comment]
See related discussion with my suggestions here for "allow" mode:

> - Clearly indicate this mode with some sort of warning saying "There are no guarantees this contract will do anything it's promising!". With post conditions, this could go in place of the "...or the transaction will abort" guidance in "deny" mode, or as a standalone message if no post conditions are passed.
> - Soften the framing of post conditions. E.g. instead of "You'll send" for each condition, "You may send".

https://github.com/blockstack/stacks-wallet-web/discussions/1359

**Comment by markmhendrickson** [comment]
Let's tackle the problem here with "allow" mode and _no_ conditions provided better as well per https://github.com/blockstack/stacks-wallet-web/issues/1120

**Comment by jasperjansz** [comment]
Here's our latest proposal for contract calls in allow mode: https://www.figma.com/file/ebj00CNeRhipdzBgxPmgnS/%F0%9F%94%8E-Transactions?node-id=15%3A521

Currently, the web wallet does not differentiate between deny and allow mode. While we'll still enable allow mode, this will change the design of allow mode in the following ways:
- In allow mode, we'll show a warning to the user that any of their tokens could be transferred if they confirm
- In allow mode, even tokens not covered by any post-conditions can be transferred, voiding the post-conditions' security guarantees. That's why we choose not to display any post-conditions that were passed.
- In allow mode, the primary call to action is to go back (which will close the indow), though users could still confirm and make the contract call.

Deny mode (left) vs. Allow mode (right)
![image](https://user-images.githubusercontent.com/25477905/129565752-93ca5857-6256-4c62-abef-0bee778762c8.png)

Moving this to be bottom of the dev backlog, but please chime in if you have feedback! Here's the Spec link: https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=199%3A4000

**Comment by markmhendrickson** [comment]
I would just note that this change is urgent given that we currently _do_ show post conditions while allow mode is enabled, which could lead users into believing incorrectly that the transaction is protected by deny mode. Currently the developer can claim any number of false things about the transfers involved.

**Comment by LNow** [comment]
One remark - `This contract is not secure` indicates that there is or might be something wrong with contract. However contract is not responsible for composing and setting transaction parameters. This is something done by external app. 

Scammers will make copies of well known projects websites, then they'll prepare TX in a way to steal tokens from users.
Under the hood they might call legit contracts and execute legit logic, but call it in a malicious way.

Therefore we should indicate that result of this particular transaction cannot be determined or that it is not secure.


`Outcome of this transaction cannot be guarantee.` or `Transaction conditions can't be assured.` or `This Transaction is not secure` sounds a bit better.
