### ISSUE TITLE
[ci] add comment on commit denoting status

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#1164]
It would be great to be able to have an action that will comment on a given commit if the publishing to stores was successful or not.

**Comment by CharlieC3** [comment]
@aulneau Would you mind creating a new issue in the DevOps repo for this so we can prioritize this on our board?

**Comment by CharlieC3** [comment]
@aulneau Is this issue still relevant/needed?

**Comment by aulneau** [comment]
It's complete!
