### ISSUE TITLE
post-conditions principal is overwritten

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#1172]
I've noticed bug where when an app provides a post-condition with a principal of one of the additional accounts for a given user, the extension will overwrite the address and set it to the index 1 address, rather than the correct account. (i have a fix for this already)

**Comment by MarvinJanssen** [comment]
I ran into this too, as mentioned on Discord. This bug makes it impossible to transfer BNS names via the Web Extension right now.

**Comment by markmhendrickson** [comment]
@MarvinJanssen I presume you need this merged and released ahead of your launch on Monday?

**Comment by MarvinJanssen** [comment]
@markmhx that would be fantastic 😁
