### ISSUE TITLE
[token standards] use read only contract calls to fetch fungible token data

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#1177]
There are some apps coming up that will be using the FT trait defined in SIP 010, and we want to support them in the extension.

While a longer term solution is in the works on the API side, we are going to do a short term implementation to support decimals, symbol (ticker), and name. [See here for the list of methods found in the trait.](https://github.com/stacksgov/sips/blob/557602cd52c6fa276fffd6d5466c1bf542c2ba0b/sips/sip-010/sip-010-fungible-token-standard.md#trait-implementation).

To do this, we should fetch and cache heavily and fungible token data from the `v2` endpoints. If they don't conform to the traits, then we should use the default behavior we have implemented currently.

related: https://github.com/blockstack/stacks-wallet-web/issues/1070

**Comment by markmhendrickson** [comment]
cc @psq @whoabuddy who should be happy to see this is coming together:

![image](https://user-images.githubusercontent.com/28991/118640177-f66ba200-b7d8-11eb-8ff9-e4fd07722366.png)
