### ISSUE TITLE
Upgrade to a manifest v3 extension

### ISSUE THREAD

**Issue by kyranjamie** [leather-io/extension#1180]
**Edit: 2021-10-5: Blocked by lack of support in Firefox and Safari**

---------------

https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/

![image](https://user-images.githubusercontent.com/1618764/118785681-5e7dbf00-b891-11eb-8044-b989f9db53f3.png)

**Comment by markmhendrickson** [comment]
Are there any particular benefits here to the upgrade you have in mind?

**Comment by kyranjamie** [comment]
Some [benefits are discussed in this article](https://cezaraugusto.net/posts/what-changes-in-chrome-extension-manifest-v3/).

But I opened this issue mostly because we don't really want to be ramping up development on an outdated format (accruing technical debt).

**Comment by kyranjamie** [comment]
The Chrome web store now tells us to upgrade as well 
![image](https://user-images.githubusercontent.com/1618764/129210237-8d72dfe5-50bd-43f6-9250-fcb2bcdff82c.png)

**Comment by markmhendrickson** [comment]
Google isn't accepting _new_ extensions after January 22, 2022 without v3.

We have until **January 2023** as an existing extension to upgrade per https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/.

Note that our builds have been getting approved recently within hours despite using v2, but we should keep monitoring this in case approvals slow down again and the version may be a culprit.

![image](https://user-images.githubusercontent.com/28991/144392084-af768577-8cb5-4b6b-9a32-c1eb27f05059.png)


![image](https://user-images.githubusercontent.com/28991/144391668-31f737ec-2bb3-4e94-831e-b91b3ddd69cb.png)

**Comment by kyranjamie** [comment]
Related https://github.com/hirosystems/stacks-wallet-web/issues/1746

**Comment by markmhendrickson** [comment]
Another reason for this upgrade: Google plans to start placing "Featured" badges on extensions that fulfill their [best practices](https://developer.chrome.com/docs/webstore/best_practices/), which includes Manifest v3 support. Once upgraded, we'll be able to submit a request to Google that they place such a badge on the extension, which could help with discovery and installation conversion.

In any case, we have only three more quarters to tackle this before the January 2023 "end of life" deadline for v2 as mentioned above. We should consider this next during Q3 planning.

From email notification:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/28991/162688577-bdd06c30-953a-4314-96ed-36c2710be354.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/28991/162688634-b5cb85bf-f5ed-4acc-b8b5-a2a50e70c50f.png">

**Comment by andresgalante** [comment]
A month ago I talked to someone who has done the move from manifest v2 to v3. They told me that the scope of the work was larger than they anticipated and it wasn't an easy task.

Just a heads up to avoid under estimate this effort and leave it to the last minute.
