### ISSUE TITLE
Refactor how we handle canceling transaction and auth requests

### ISSUE THREAD

**Issue by fbwoolf** [leather-io/extension#1181]
Revisit when we refactor messaging. We should just handle the promise correctly so there is an `onCancel` triggered with the promise rejection in `connect`.

https://github.com/blockstack/stacks-wallet-web/pull/1175
https://github.com/blockstack/connect/pull/122

**Comment by markmhendrickson** [comment]
Do we want to tackle this refactor for the completion of https://github.com/blockstack/stacks-wallet-web/issues/959 specifically or might the refactor extend beyond that issue?

**Comment by fbwoolf** [comment]
We all discussed circling back to refactor messaging overall so this would be addressed after that. We don't need to complete this for #959.
