### ISSUE TITLE
Fix placement of pending indicator upon selecting account

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1187]
Currently it's pressed up against the content on the left whereas I believe it should be justified to the right:

<img width="453" alt="Screen Shot 2021-05-05 at 18 57 29" src="https://user-images.githubusercontent.com/28991/118796098-8f62f180-b89b-11eb-97a7-66553b85bbc2.png">

**Comment by Eshwari007** [comment]
@aulneau @markmhx Test looks good in new pending status.Do revert of you need any further enhancement.
Attaching snapshot for perusal
<img width="613" alt="Screen Shot 2021-06-10 at 12 27 30 PM" src="https://user-images.githubusercontent.com/38872890/121562499-83280b00-c9e7-11eb-91d4-1845da9e284e.png">

**Comment by markmhendrickson** [comment]
The screenshot in https://github.com/blockstack/stacks-wallet-web/issues/1187#issuecomment-858768198 appears unrelated to the account selection UX captured in this issue per se?

**Comment by Eshwari007** [comment]
@markmhx Lets sync up on what is the expected output from this ticket as well.

**Comment by Eshwari007** [comment]
@markmhx Attaching the screenshot upon new account creation
<img width="388" alt="Screen Shot 2021-06-16 at 4 20 58 PM" src="https://user-images.githubusercontent.com/38872890/122287402-e968ce00-cebe-11eb-91cd-001d8fac87b5.png">
