### ISSUE TITLE
Audit and improve post conditions editing

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#1189]
The current version of the components that are used for creating/editing/removing post-conditions could do with some clean up. Both in the UI and in the code behind it all.

**Comment by andresgalante** [comment]
@markmhx where do we put this issue?

What if we create a milestone in the webwallet so @fbwoolf @aulneau and @kyranjamie add the issues that we should do as part of the DX and UI improvements?

**Comment by markmhendrickson** [comment]
Let's just put them all in the backlog (bottom by default, unless there's a strong intuition something should go up higher) then review them as a team synchronously sometime next week.

**Comment by mijoco-btc** [comment]
Hey - am passing in a StandardSTXPostCondition  with a condition of LE 10000 STX (1x10^11 micro stx) but the wallet display this as LE 10 STX.

Is this a known issue or should I report it?

**Comment by aulneau** [comment]
> Hey - am passing in a StandardSTXPostCondition with a condition of LE 10000 STX (1x10^11 micro stx) but the wallet display this as LE 10 STX.
> 
> Is this a known issue or should I report it?

Can you paste in the code you're using to generate the post condition?

**Comment by markmhendrickson** [comment]
@aulneau to close in favor of a separate issue for adding post conditions editing back into the wallet generally
