### ISSUE TITLE
Make it easier to send stx between accounts

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#1192]
Currently, either when testing or in real life usage, it's very cumbersome to send stx between your accounts. Currently you have to do this:

- click menu
- click switch account
- select the account you want
- click copy address button
- click menu
- click switch account
- select previous account
- click send
- continue as normal

Ideally it'd be like this:
- click send
- have the ability to select any of your other addresses as recipient
- optional: generate new address and select that one

**Comment by jasperjansz** [comment]
Hi, I had already changed this: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/Wallet-%F0%9F%8C%90-web?node-id=1852%3A40497

The current design opens a dropdown with a list of your other accounts when you focus the 'to' field. If you don't have any other accounts it shouldn't open.

**Comment by kyranjamie** [comment]
This was added a while back with the recipient modal
