### ISSUE TITLE
Issues with transactions failing when deploying contracts through the Explorer Sandbox

### ISSUE THREAD

**Issue by jdbender66** [leather-io/extension#1197]
This week I've been working with @agraebe and @pgray-hiro on configuring our NFT onboarding flow for new Stacks developers. It includes a series of tutorials where a user claims an NFT creating by Hiro, then develops their own NFT, deploys it on-chain, and claims an edition. 

During this time I was experimenting with deploying our potential contract, and running into a lot of issues with the web wallet and sandbox interacting correctly. Diwaker pointed out that there was a mismatch between the nonce of my account, and the nonce of my transactions. I'm not entirely sure how the nonces got misaligned. 

Here is one of the failed transactions: https://explorer.stacks.co/txid/0x0e2f39798fc095761200a11f379e021cad85ff0c51e2b6a54a81496975424a99?chain=mainnet

I tried on mainnet, testnet, and regtest. Sometimes even a simple STX token transfer to a new account (to have the funds to deploy a contract) would fail. I did eventually get the default, pre-loaded contract in the explorer sandbox deployed, by using a totally new account on regtest. But then when I immediately went to deploy the NFT contract, it would fail, making me think something could be wrong with the clarity code. 

This is the testnet template contract I was able to deploy. It includes an automatically minted NFT for the tx-sender, so it was promising to see I could at least receive and see NFTs in my wallet: https://explorer.stacks.co/txid/0x93baf73a369f2a9c504d90215ef9abf3f8dda4dd1664290548cd9c3684df16e5?chain=testnet

Here is another one of my failed deployments on testnet: https://explorer.stacks.co/txid/0x4bc98024a45d3f262726a7fe8ed103a73797c8bcf873b086637384096e90bfe7?chain=testnet

Have tried on multiple machines, Windows and Mac. Google chrome on both computers.

**Comment by markmhendrickson** [comment]
@aulneau it might make sense for you and @jdbender66 here to walk through these problems and perhaps break out this issue out into concrete bug issues as identified, either for the wallet or explorer specifically?

**Comment by Eshwari007** [comment]
@aulneau The issue seems to be reproducible as you had deployed the tokens to my add and it failed as well:https://explorer.stacks.co/txid/0x6389c837979326a9f2c25bc4428215584e654b1e49f2c0c26885c9aefb85551b?chain=testnet. Are this related?
