### ISSUE TITLE
Inconsistent results with password verification

### ISSUE THREAD

**Issue by whoabuddy** [leather-io/extension#1204]
I'm using Brave browser and Stacks Web Wallet extension `2.8.0`, and I ran into some odd issues when setting a password.

If I enter a password that doesn't meet the requirements, such as `t`, then the requirements are shown to me. However, from this point typing in a password longer than 12 characters gets me stuck in a loop where the screen resets to the first one without requirements, then back to the one with requirements, and the only way to get around this is to close the extension modal and open it again.

Also, if I use a really long, all lowercase password that does not meet the requirements, such as `thisisareallylongpasswordalllowercase`, it is still accepted.

Please see the video below for reference:

https://user-images.githubusercontent.com/9038904/119136036-c6084b80-ba04-11eb-8eaf-950ffde02f04.mp4

**Comment by GinaAbrams** [comment]
@markmhx Thinking about this issue ahead of the launch of the app. would it be possible for this to be fixed before EOW?

**Comment by markmhendrickson** [comment]
We'll discuss as a team during kick-off today 💪

**Comment by muneeb-ali** [comment]
Great to hear! Had a few folks ping me about this issue as well. Seems like a road blocker.

**Comment by GinaAbrams** [comment]
@andresgalante think that we might be able to have this fix live in the extension stores by Thursday 5/27? 🙏

**Comment by andresgalante** [comment]
Maybe.

Assuming @kyranjamie works on it tomorrow and finds a fix that gets review and merge, we can submit it to the stores by the EOD and might get approved by Thursday.

In a perfect world it should, but I wouldn't plan around it considering that the release timeframes are out of our hands.

@aulneau @fbwoolf, if possible, please be ready to assist Kyran with this fix and review the result soon after it's ready.

**Comment by aulneau** [comment]
I would say we can't bet on that. It might make it through the chrome store, but the FF review process has been pretty slow and unreliable. Releases can't really happen ASAP anymore.

@kyranjamie let me know if you'd like me to jump on it tomorrow.

**Comment by GinaAbrams** [comment]
Thx all 🙏
