### ISSUE TITLE
Refactor messaging

### ISSUE THREAD

**Issue by fbwoolf** [leather-io/extension#1207]
Refactor/rename messaging folders, files, and code to better coordinate and understand message flow.

Note: There is a related issue for creating a `Manifest` folder with separate manifests for each browser type.
https://github.com/blockstack/stacks-wallet-web/issues/1206

Questions/concerns:
1. `App` seems misused in our naming, or at least it is unclear.
2. Why do we sometimes use the `backgroundPort` and other times not?

Tasks:
- [x] Remove `extension` folder and restructure so we clearly define context of the script (`scripts` folder)
- [x] Rename `message-bus` to `content-script`
- [x] Remove `Background` folder and rename `index` to `background`
- [x] Relocate `popup.ts` to scripts folder
- [x] Refactor `message-types` to clearly define what message type goes with which context
   - [x] Separate `Methods` into `InternalMethods` and `ExternalMethods`
   - [x] Remove unused `walletResponse` from methods
   - [x] Rename `walletRequest` to something more inline with the other internal methods for the vault, `getWallet`?
   - [x] Rename `MessageFromApp` to `VaultActions` (bc the vault is setup like a reducer)

**Comment by fbwoolf** [comment]
Proposing these changes?

![image](https://user-images.githubusercontent.com/6493321/119198091-62a30b80-ba4e-11eb-9d72-a33fbb2e0381.png)

**Comment by aulneau** [comment]
I'm personally not a fan of "scripts" as the name for the folder. to me, scripts typically refer to files that run to help with build/ci work, and not to do with the application itself. Why move away from "extension"?

**Comment by fbwoolf** [comment]
I think bc this folder supports the messaging scripts, mainly the `background` and `content-script`. We referenced MetaMask and they had it setup using a `scripts` folder structure. I definitely think it could be better. Maybe, `messaging` or `message-scripts`?  It seems like the entire repo is the `extension` so it seemed a bit off to name one folder that?

**Comment by fbwoolf** [comment]
When I look at it being used in imports, I don't like just `scripts` either.

**Comment by kyranjamie** [comment]
Agree on not using `scripts`. I suggested removing away from extension. This was a relic from when we also had the app, I thought. I think everything should be in `src` and categorised by JS context. `background`, `context`, `wallet/popup`, `inpage`.

**Comment by fbwoolf** [comment]
Ok, I misunderstood that part. So, each one of those would be it's own folder in `src`?

**Comment by fbwoolf** [comment]
I ended up changing the folder to `messaging` and pushed it up. Definitely open to reverting it though ...just was experimenting a bit.

**Comment by fbwoolf** [comment]
I think I'll try another version today separating them by contexts and see how that goes.

**Comment by aulneau** [comment]
For me personally when it comes to organization of this repo, this is what I'd like

```
src
  common
  background
  content-scripts
  inpage
  app
```
- common: anything shared between 2+ contexts (background/inpage/app)
- background: anything to do with the background context\
- content-scripts: anything to do with the content-scripts context
- inpage: anything to do with the inpage context
- app: the react frontend for the extension

Something else we should try to consider is we should form the structure of the directories to map to entry points in our wepback config https://github.com/blockstack/stacks-wallet-web/blob/main/webpack/webpack.config.base.js#L81-L85

This is helpful reading: https://developer.chrome.com/docs/extensions/mv3/architecture-overview

**Comment by fbwoolf** [comment]
Yep, I like that ...I think that is the direction Kyran wanted us to go in too. I'll refactor today and reorganize it this way ...makes sense to me for sure. Thanks for the feedback.

**Comment by fbwoolf** [comment]
O yeah, this is a lot better! Will push up changes soon. I didn't move stuff into an `app` folder yet but definitely can.
