### ISSUE TITLE
Unable to finish 1st login after trying a weak password on first attempt

### ISSUE THREAD

**Issue by gamenerds** [leather-io/extension#1210]
1. Download the extension
2. Enter passphrase
3. On password screen, enter something it won't accept, such as M!K#2021
4. Observe message about password needing to be 12+ chars, etc. Try to type a long password and watch the field reset itself to empty after certain number of characters typed. The "Done" button doesn't become enabled. 
5. Can't get out of this loop of it telling me my password needs to be X and then field resetting itself while I type.

**Comment by jasperjansz** [comment]
Ran into the same bug:


https://user-images.githubusercontent.com/25477905/119348121-bc991080-bc9c-11eb-852b-cce6ea2bb461.mov
