### ISSUE TITLE
Account avatar shows first digit when it should show full index with no username present

### ISSUE THREAD

**Issue by GinaAbrams** [leather-io/extension#1212]
<img width="425" alt="Screen Shot 2021-05-24 at 12 09 56 PM" src="https://user-images.githubusercontent.com/30627583/119375694-1a236200-bc89-11eb-93c5-9998dec248c0.png">

**Comment by aulneau** [comment]
@GinaAbrams when making issues can you provide some more context? Is the issue that there are 60 accounts, or something else?

**Comment by GinaAbrams** [comment]
The numbers on the left drop a number, (just 5 instead of 58) unless that is intentional?

**Comment by GinaAbrams** [comment]
This happens for all numbers above 10 (so 11 is 1 too on the left) when clicking sign in and scrolling through accounts to select one to sign into an app with.

**Comment by kyranjamie** [comment]
![image](https://user-images.githubusercontent.com/1618764/121875953-4f135980-cd09-11eb-87ba-5670adfc244d.png)

I believe this is no longer an issue
