### ISSUE TITLE
Name display in Stacks Wallet 

### ISSUE THREAD

**Issue by GinaAbrams** [leather-io/extension#1216]
Name not showing up in screenshot below - I have a name registered for this account and it definitely has a zone file. However when I open the web wallet to this account, all i see is the number 5 instead of the name.  

<img width="494" alt="Screen Shot 2021-05-25 at 1 47 03 PM" src="https://user-images.githubusercontent.com/30627583/119544823-1ca4bb00-bd60-11eb-9618-cde366419e8e.png">

**Comment by aulneau** [comment]
> Name not showing up in screenshot below - I have a name registered for this account and it definitely has a zone file. However when I open the web wallet to this account, all i see is the number 5 instead of the name.
> 
> <img alt="Screen Shot 2021-05-25 at 1 47 03 PM" width="494" src="https://user-images.githubusercontent.com/30627583/119544823-1ca4bb00-bd60-11eb-9618-cde366419e8e.png">

This seems to be a very out of date version of the extension, can you make sure you're on 2.8.0?

**Comment by GinaAbrams** [comment]
Strange - I might have had two versions of the web wallet downloaded at once. Still seeing this though: 
<img width="382" alt="Screen Shot 2021-05-26 at 6 01 04 PM" src="https://user-images.githubusercontent.com/30627583/119737385-35d76580-be4d-11eb-80da-62583d963a71.png">

**Comment by aulneau** [comment]
@GinaAbrams If you've registered this name through the BTC app, it needs to add the profile.json to the zonefile, if it doesn't, the stacks-node-api cannot find the name, take my name for example: https://stacks-node-api.stacks.co/v1/names/aulneau.btc (i used a different app to register it, one that added the correct profile.json to it.) Check the name you expect to see with that url and let me know what it shows. cc @MarvinJanssen

**Comment by MarvinJanssen** [comment]
@aulneau really? I had names that definitely did not have a profile URL (or no zonefile at all) show up in the Extension. Regardless, all names registered from this point on will have the profile URL per your instructions. If the entry is missing the app will display a button to add it back in.

**Comment by aulneau** [comment]
It might be that I'm slightly off for sure, I'd be curious to hear from @zone117x to learn more about why certain names might not show up, eg https://stacks-node-api.stacks.co/v1/names/aulneau.stx, but querying the bns contract directly returns an expected value of my name (owner: SP3N4FPBG1PXMKEW0Y4K2MCSWDXHZP42YV5YW3AY4)
![Screen Shot 2021-05-26 at 8 52 29 PM](https://user-images.githubusercontent.com/11803153/119753431-5f4fbb80-be64-11eb-85ce-95843434016f.png)

**Comment by zone117x** [comment]
@aulneau https://github.com/blockstack/stacks-blockchain-api/issues/614
