### ISSUE TITLE
Remember network

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1226]
I'm trying to test some things on Testnet and anytime I open the extension it defaults to mainnet. This is while my wallet is connected to the Explorer set to testnet.

It seems best for me to remember the network until the user switches in the extension, or until they connect to an app on a different network.

**Comment by aulneau** [comment]
regression in https://github.com/blockstack/stacks-wallet-web/pull/1221, works correctly in prod

**Comment by Eshwari007** [comment]
@aulneau @jasperjansz Test passed in Web Wallet latest Version Packages #1276
