### ISSUE TITLE
Remove "you've used this acc with x other apps"

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1227]
When I see this dialog I think two things:
1. What is this and why is it interrupting me?
2. I don't care

My assumption is most users don't care either. My suggestion is to not have a flow-breaking dialog unless we have evidence that the information is important to the user and that it would lead them to make a different decision than simply continuing.

**Comment by markmhendrickson** [comment]
Dupe 😄  https://github.com/blockstack/stacks-wallet-web/issues/978
