### ISSUE TITLE
Add Storybook

### ISSUE THREAD

**Issue by kyranjamie** [leather-io/extension#1230]
We've discussed using Storybook a few times, I think it'd be especially helpful for the extension.

We could use it to:
- View all extension pages in a single place
- Adjust styles without having to run through onboarding flows repeatedly
- Shorten feedback loop for design changes

**Comment by andresgalante** [comment]
When I used storybooks it proved to be successful to test components but not full screens since people will have to update 2 places and it's hard to keep the real app with the storybook in sync.

@fbwoolf you have experience with storybooks, what do you think?

**Comment by fbwoolf** [comment]
I have only used it as a component library. We used it instead of opting to import an external package. We didn't actually build full pages with it.

**Comment by aulneau** [comment]
I think it makes a lot more sense to use storybook in the UI library. It would be hard and error prone to try and keep duplicates of pages in it unfortunately. I wonder if we can do something else though that can accomplish this goal

**Comment by kyranjamie** [comment]
Agreed on using for UI library as well, but don't see that as a reason why it wouldn't also be valuable here, nor why this would require frequent "updating in two places" or result in any duplication.

Consider the onboarding flow. Each step defines its own story. You can change anything internal a component with no story edits required, it just implements the page's component.

```ts
// onboarding.stories.tsx
export default {
  title: 'OnboardingSignUp',
  component: Onboarding,
  decorators: [],
} as Meta;

const Template: Story = args => <InstalledSignIn {...args} />;
```

There are many reasons why this is valuable. Foremost, it's difficult to get insight into all states of the wallet. Not only do you need to download and install the wallet build of a given PR, but you may not even be able to see all the pages/features implemented, as your given address might not: have enough balance, the right amount of tokens, a type of NFT, sufficient account activity etc. 

An example: say someone builds a tx list component. Great, I want to see how it looks with 0, 1, 5, and 1000 items. Have fun waiting around on the testnet to replicate that IRL.

With Storybook, each PR can publish a new build that lets reviewers and onlookers see the resulting work, in all the supported states, or viewports, without any of that hassle. 

Screen components asides, there are plenty of UI components we can, and should, create stories for. 
Check out [Metamask's storybook.](https://metamask.github.io/metamask-storybook/)

**Comment by aulneau** [comment]
I think this makes a lot of sense, and want to be clear that I totally agree with you that this would be so useful! The only areas in which I would be concerned is I want to avoid a situation in which we have to manually construct screens or components to only work within the context of storybook, while the way that the components work in the app will be different. For example, I would very much prefer to not modify our app such that state is no longer coming from recoil but instead can be passed via arbitrary props. 

The area that will get complex is that almost all of our components and pages are the result of state, not props being passed. I'd be much more interested in how we could mock state to be whatever we want, and be able to select from different scenarios. eg maybe we could devise a system such that we can have any number of "snapshots" of mocked state, like the example you put forward of a list of 1000x transactions. 

Maybe there is some combination of both?

**Comment by kyranjamie** [comment]
> I think this makes a lot of sense, and want to be clear that I totally agree with you that this would be so useful! 

☮️   &nbsp; &nbsp;🕊️ 

Indeed, some degree of mocking would be needed. Storybook has the concept of _decorators_ which are applied to stories (React contexts in our case), in order to provision global dependencies/state.

Valid concern on global state reliance. This could be mocked and shared between stories. Though, I would question to what extent components should rely on global state. Both in a Redux/Recoil world, it's a good practice to keep components as dumb as possible. That's not to say we have a big page component and drill all the props down. But to consider component structures where one is responsible for accessing global state, the other for presenting the content. Perhaps a big ask for a whole page's component, but the drawers/menus etc shouldn't inherently reply on global state.

**Comment by aulneau** [comment]
> Both in a Redux/Recoil world, it's a good practice to keep components as dumb as possible.
> but the drawers/menus etc shouldn't inherently reply on global state.

Recoil isn't "global" state ;)

I both agree and disagree. We should keep base components dumb and take certain props, but those are typically the smallest elements of a given component that we're actually interested in. For those smaller elements, I think a story book is really the way to go, but for larger components it gets really hard, and I don't think we need to worry as much about the "smart vs dumb" component pattern, as the logic is still not contained in the component, but in its reliance of a hook.

Let's take a look at a few examples, starting with the [networks list component found here](https://github.com/blockstack/stacks-wallet-web/blob/fix/improve-state/src/components/drawer/networks-drawer.tsx#L14-L65). The components are pretty dumb as is, and they could be made to be a bit dumber. We have a component for a single item, a list of items, and the specific drawer, extending and using a more generic drawer component. In this example, I'd say we would be able to benefit greatly from having a more generic row item component. However, I really don't think we should do much (if any) prop drilling of real data. In my mind, most "real" data does and should come from state, as our application UI is _only_ a function of state, and nothing else.

**Comment by pete-watters** [comment]
This task is OLD but we will be doing this soon and adding storybook into our monorepo
