### ISSUE TITLE
Improve onboarding design

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1232]
There are many steps involved from getting a user who starts out cold to using apps. Map out all the steps and make sure we support the user during every step. Cut out all the unnecessary steps or steps that can be deferred.

Then design the part of the onboarding flow that is in the web wallet. Besides efficient and helpful, we're also trying to make it exciting.

**Comment by markmhendrickson** [comment]
@jasperjansz to lay out specific changes already included in Figma designs for onboarding to this issue's description.

**Comment by markmhendrickson** [comment]
@jasperjansz will decompose this issue into new issues that correspond to the following:

1. All improvements to the existing sequential screens during initial authentication (e.g. illustrations, copy, layout for Secret Key and password screens). Preferably one issue per updated screen.
2. Formatting the authenticated home screen for full screen mode
3. Adding new CTAs to the authenticated home screen (buy STX, register name, back up key, explore apps)

All of these issues should go into the "Improve onboarding" milestone, placed into "Awaiting triage" on the board, and the related discussion should be updated with links to them: https://github.com/blockstack/stacks-wallet-web/discussions/1358.

This issue should then be closed.

**Comment by markmhendrickson** [comment]
@jasperjansz please indicate any desired illustrations in the issues above and assign @eugeniadigon to them as needed.

**Comment by jasperjansz** [comment]
closing in favour of specific issues I created for each individual screen
