### ISSUE TITLE
Remove rounding for transaction fees

### ISSUE THREAD

**Issue by philiphacks** [leather-io/extension#1237]
using web wallet from the Chrome store (2.9.0)

I don't have a video of this, and it doesn't seem to happen consistently, but can try to replicate this in a video if needed. This happens relatively often though. For instance just right now:

When signing a transaction, the TX got assigned a nonce of 5 with v2.9.0. It would be stuck in pending so the TX would not be picked up by my local mocknet miner. I then installed the web wallet v2.0.7 (a local build I still had) and did 4 or 5 transactions (nonce 0 to 4), after which my nonce was correct and the initial TX would be picked up and correctly mined. 

Is this a known issue? It seems to happen every now and then. Sometimes when I reinstall the wallet, it disappears, but often appears again.. seems like the nonce is picked up wrong.

fyi: v2.0.7 seems to always send the correct nonce, while the Chrome published wallet doesn't.. did the nonce calculation change?

**Comment by philiphacks** [comment]
I was able to replicate in a video, file is too bug to upload here, so put it on WeTransfer (expires in 1 week): https://we.tl/t-7CYtobpTr2

**Comment by markmhendrickson** [comment]
Might this be the same as reported with https://github.com/blockstack/stacks-wallet-web/issues/1197? If so, mind trying the build here in QA to see if it resolves it? https://github.com/blockstack/stacks-wallet-web/pull/1208

cc @aulneau

**Comment by philiphacks** [comment]
@markmhx @aulneau 

just tested the build from #1208, that one works! I'll use that build and monitor.

fyi - it seems to round down the tx fee to 0
![image](https://user-images.githubusercontent.com/577420/120170273-1780b980-c201-11eb-8e5b-ee5d732b5107.png)

shows up correct in explorer
![image](https://user-images.githubusercontent.com/577420/120170331-249da880-c201-11eb-9e23-34b6973a9e94.png)

**Comment by markmhendrickson** [comment]
I'm glad to hear it! I'll modify this issue title to reflect the fee rounding error, which doesn't appear tracked yet. 🙏

**Comment by aulneau** [comment]
The fee rounding issue should be resolved by #1221
