### ISSUE TITLE
Token balances are retained despite switching to another token 

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1239]
Environment:Mainet

User created two accounts:
Account 1
One account with 0 STX and 2000 WMNO

Account 2
One account with 0 STX

User was testing send WMNO tokens between the two accounts and everything looked good.
After few attempts,user casually selects STX token from dropdown where the value should be 0 has 2000 being displayed
User then tried to send abt some # token to valid address and no error was thrown.
When user selects preview,no errors were thrown but the page were spinning .
Attaching the screen shots of 
<img width="1437" alt="Screen Shot 2021-06-01 at 2 58 01 PM" src="https://user-images.githubusercontent.com/38872890/120377028-94d42900-c2ea-11eb-9738-308f81c787dd.png">
<img width="1438" alt="Screen Shot 2021-06-01 at 2 58 21 PM" src="https://user-images.githubusercontent.com/38872890/120377032-94d42900-c2ea-11eb-86f9-88b7745ca192.png">
<img width="831" alt="Screen Shot 2021-06-01 at 2 58 31 PM" src="https://user-images.githubusercontent.com/38872890/120377033-94d42900-c2ea-11eb-8ff7-3dc2c80ef98e.png">
<img width="783" alt="Screen Shot 2021-06-01 at 2 58 36 PM" src="https://user-images.githubusercontent.com/38872890/120377034-956cbf80-c2ea-11eb-85bb-fb3fdea789f0.png">

the issue

**Comment by markmhendrickson** [comment]
I'm noticing a typo here in the screenshots as well: "You will transfer **extactly**"

**Comment by aulneau** [comment]
Both the typo and this balance bug is fixed on `main`
