### ISSUE TITLE
[2.9.0] Bug: No idea but this just popped up on the screen when creating sk

### ISSUE THREAD

**Issue by v-stickykeys** [leather-io/extension#1242]
Bug found testing Stacks Wallet for Web.

### Error

**Loadable**: `api.account-data`
**Message**: `TypeError: Network request failed`

### Environment

**Version**: `2.9.0`
**Branch**: `refs/heads/main`
**Commit**: `5461a43420d4a814f19130102927c7529decf61e`

**Comment by markmhendrickson** [comment]
Are you still seeing this error? We were experiencing some issues with the underlying API yesterday that may have been resolved by now.
