### ISSUE TITLE
[2.9.0] Bug: SyntaxError: JSON.parse

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#1243]
Bug found testing Stacks Wallet for Web.

I setup stacks-local-dev, I used clarinet deploy --mocknet and launch the explorer locally. Then I tried to make a contract call from my app via stacks wallet for web.

### Error

**Loadable**: `transaction.contract-interface`
**Message**: `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

### Environment

**Version**: `2.9.0`
**Branch**: `refs/heads/main`
**Commit**: `5461a43420d4a814f19130102927c7529decf61e`

**Comment by aulneau** [comment]
Hi @friedger can you try the latest? 2.10.0

**Comment by aulneau** [comment]
otherwise it's likely fixed in https://github.com/blockstack/stacks-wallet-web/pull/1221

**Comment by friedger** [comment]
I tried 2.8.0.55 and got the correct error message.
