### ISSUE TITLE
can only seem to sign in with one account w/ stacks web wallet 

### ISSUE THREAD

**Issue by alexrudloff** [leather-io/extension#1245]
I have two accounts on my stacks wallet. I can only sign in to btc.us with the first one, not the second one. I've noticed weird behavior on other stacks applications thats similar. 

No idea if its a stacks wallet bug, or an implementation bug per blocks app, or a user error on my side :\

Video attached

https://user-images.githubusercontent.com/1984999/120539042-34f68480-c3b5-11eb-9fda-8e86752f0874.mov

**Comment by markmhendrickson** [comment]
Thanks for the report! @MarvinJanssen have you seen this behavior by chance?

@alexrudloff any chance you could try this while having the developer console for the .BTC app in your browser open while you try to sign in with these accounts? To see if any particular errors are thrown.

**Comment by alexrudloff** [comment]
Couple more observations 
* The _blockstack_ extension Pravica uses seems to create accounts and sign in to them fine, except my first account apparently signs me in as someone else (or is including someone else's name by default on their end)

See: https://twitter.com/alexrudloff/status/1400438829253906433

* The Stacks wallet extension doesn't have the menu to create accounts on the sign in screen, but does when I open the wallet itself. If I create a new account, I can sign into btc.us just fine with it. 
* The account I can't sign into btc.us with was created using Pravica's blockstack extension not the stacks wallet. 
* The newly created third account, created with stacks wallet, is not available on Pravica to sign in with. 

Looking at console, the sign in issue on btc.us seems to be caused by a 404 on `https://core.blockstack.org/v1/names/alexander.id.stx`, which is the name registered for via Pravica.

The other two accounts don't have id's associated to them. It's either something to do with named accounts not working, some sort of conflict between blockstack/stack web wallets, or pravica creating a weirdo account somehow?

**Comment by markmhendrickson** [comment]
> The blockstack extension Pravica uses seems to create accounts and sign in to them fine, except my first account apparently signs me in as someone else (or is including someone else's name by default on their end)

Pravica for desktop web uses an older version of Blockstack authentication, so mileage will likely vary.

> The Stacks wallet extension doesn't have the menu to create accounts on the sign in screen, but does when I open the wallet itself. If I create a new account, I can sign into btc.us just fine with it.

This is an omission we'll rectify per https://github.com/blockstack/stacks-wallet-web/issues/1252

> The account I can't sign into btc.us with was created using Pravica's blockstack extension not the stacks wallet.

The app shouldn't be hitting `core.blockstack.org` anymore since there's a new API available that replaces it at `stacks-node-api.mainnet.stacks.co`. @MarvinJanssen you may need to update Stacks.js?

@aulneau and I noticed this issue with a different app (todos sample app) recently, but I'm not entirely sure what resolved the issue. He may know better.

**Comment by MarvinJanssen** [comment]
Interesting. The 404 should not affect anything but curious that it hits core indeed. @markmhx is it possible the difference in behaviour is due to something different in the zone file / `profile.json` for that account?

**Comment by markmhendrickson** [comment]
@aulneau mentioned during our weekly meeting yesterday that he's been looking into this a bit and will share some observations.

**Comment by markmhendrickson** [comment]
I'm going to close this issue as stale, but @alexrudloff please let us know if you're still facing this and we'll reopen.
