### ISSUE TITLE
View Secret Key should require the password

### ISSUE THREAD

**Issue by 314159265359879** [leather-io/extension#1246]
Currently when "view secret key" is clicked it shows the key phrase right away (Chrome and Firefox on Windows).
![image](https://user-images.githubusercontent.com/33360391/120591795-0cb26880-c43d-11eb-8a2f-2a8c5419e434.png)

That means if anyone has access to the computer when the wallet is not locked they can view the private key. It would be a lot more secure if this required the wallet password. 

**Environment

Version: 2.9.0
Branch: main**

**Comment by markmhendrickson** [comment]
@jasperjansz says we should use the same design as here for unlocking the wallet, but modify the final copy as "...to view your Secret Key."

![image](https://user-images.githubusercontent.com/28991/133616213-47231a51-5f8f-4069-8685-75ba49e6e136.png)
