### ISSUE TITLE
Bug: fungible tokens not recognised in post condition + rounded down to zero

### ISSUE THREAD

**Issue by philiphacks** [leather-io/extension#1247]
Was testing the web wallet build 2.9.0.804 in preparation of Arkadiko testnet, and noticed the following. xUSD is not recognised in the post conditions (is a SIP10 token) and the amount is rounded down to 0. I was paying 0.009782 xUSD and it is displayed as 0.

![image](https://user-images.githubusercontent.com/577420/120610979-ff54a880-c453-11eb-91df-fdc0a267ec08.png)

**Comment by philiphacks** [comment]
just FYI, the transaction goes through successfully (so the post condition of 0.009782 xUSD is passed to the transaction), but it is shown incorrectly.

**Comment by psq** [comment]
why is this being closed?  even though the transaction goes through, the information being displayed to the user is not helpful, if not not misleading.  The code should try to display enough significant digits, not just round.

**Comment by markmhendrickson** [comment]
@andresgalante was this addressed in a recent build or something?
