### ISSUE TITLE
extension defaulting to testnet for tx signing despite being connected on mainnet

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1248]
v2.9.0

this is on heystack:
- Connect wallet to app on mainnet (see address)
- Claim HEY
- Tx signing popup opens in testnet

![image](https://user-images.githubusercontent.com/25477905/120624608-282f6a80-c461-11eb-8733-e43d17db82fe.png)

**Comment by aulneau** [comment]
This is not a bug, the hey stack app is passing regtest into the extension for those transactions

**Comment by markmhendrickson** [comment]
It seems like we could iron out the mapping of networks and addresses between the app and wallet more in general. Right now the experience seems quite loose between what the user expects as far as their network or chosen account and what the app expects or sets.

**Comment by aulneau** [comment]
I'm closing this as this is not a bug but something we need to discuss further
