### ISSUE TITLE
Disable network switching within transaction signing flow

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1250]
v2.9.0

Switching network doesn't work

https://user-images.githubusercontent.com/25477905/120624413-f74f3580-c460-11eb-8970-431f8cf7c3af.mov

**Comment by aulneau** [comment]
This functionality should be disabled imo. If a function call is set to calling a contract at a testnet address, the contract will never be found on mainnet, unless we did some conversion of the address

**Comment by markmhendrickson** [comment]
I've retitled this issue so it's about removing the switching capability entirely within the tx signing flow.

**Comment by markmhendrickson** [comment]
This appears resolved.
