### ISSUE TITLE
Add dates to activity

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1263]
![image](https://user-images.githubusercontent.com/25477905/120801295-49678800-c541-11eb-95b9-7a1d09e6a741.png)
![image](https://user-images.githubusercontent.com/25477905/120801464-7b78ea00-c541-11eb-9622-5352518c8408.png)

reference: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/Wallet-%F0%9F%8C%90-web?node-id=1852%3A36176
feed component: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/Wallet-%F0%9F%8C%90-web?node-id=1584%3A28690

**Comment by Eshwari007** [comment]
@aulneau @jasperjansz Test passed in Testnet for the date feature
