### ISSUE TITLE
Use consistent list styles

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1265]
There are many lists in the wallet; popovers, sheets, dropdowns. Currently, they're not styled consistently (some have margin, some don't). Let's use a consistent style for all with margins.

popover and list component: https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/%E2%9D%96-Design-System?node-id=2081%3A3747
Sheet: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/Wallet-%F0%9F%8C%90-web?node-id=1852%3A58613

**Comment by andresgalante** [comment]
This is fixed in production
