### ISSUE TITLE
Ensure usernames are shown for accounts

### ISSUE THREAD

**Issue by GinaAbrams** [leather-io/extension#1274]
Hi there, I have experienced this and others are reporting the same. In some instances the display name in the Stacks Web Wallet does not update to reflect a name. 

Sharing an example: 
<img width="390" alt="Screen Shot 2021-06-09 at 10 14 24 AM" src="https://user-images.githubusercontent.com/30627583/121371696-beeda280-c90b-11eb-99aa-0cc3b34c26a7.png">

**Comment by aulneau** [comment]
This is likely not an issue with the wallet but the API, https://github.com/blockstack/stacks-blockchain-api/issues/614

**Comment by markmhendrickson** [comment]
I noticed today that the username showed up on the home screen but not in the transaction signing window.

Could this be a separate bug or related to the API and some sort of caching that helped it show on the home screen despite API problems?

<img width="514" alt="Screen Shot 2021-06-14 at 12 15 11" src="https://user-images.githubusercontent.com/28991/121899801-08cbf380-cd25-11eb-90ac-7fe8899d98d2.png">

**Comment by aulneau** [comment]
@markmhx which version are you on? this might be fixed in our latest, unreleased version

**Comment by markmhendrickson** [comment]
I'm on the latest released version. I'll try the newest build 👍

**Comment by markmhendrickson** [comment]
This is resolved for me

![image](https://user-images.githubusercontent.com/28991/123175994-008d5a00-d483-11eb-97bc-1a33c42d240d.png)
