### ISSUE TITLE
Switch account after encountering 'Not Enough Funds' does not switch account

### ISSUE THREAD

**Issue by mijoco-btc** [leather-io/extension#1277]
Stacks Wallet for Web
Tested on Chrome / Macbook pro

Just noticed that after encountering ```You don't have enough STX to make this transfer. Try switching accounts, switching networks, or adding STX to this account.```

<img width="477" alt="Screenshot 2021-06-10 at 07 48 41" src="https://user-images.githubusercontent.com/4384929/121478733-3cbfb580-c9c1-11eb-9606-c2fdff25ed93.png">

**Comment by mijoco-btc** [comment]
Just realised it keeps you on the same account as the one you are logged into app with - so maybe the message should read 'try logging into the app with a different account or adding stx etc - or the app could get an error to handle this?

**Comment by aulneau** [comment]
@radicleart this seems to be an outdated version of the wallet, can you confirm the version you're using?
