### ISSUE TITLE
Add testnet URL to transaction window to make clear which testnet you're on

### ISSUE THREAD

**Issue by kyranjamie** [leather-io/extension#1279]
~~See video. Gist is that, while I have a testnet balance is STX, it doesn't appear in the popup when trying to claim `HEY`.~~

https://user-images.githubusercontent.com/1618764/121517209-61cb1d00-c9ef-11eb-82a8-852fe20825ba.mp4

Issue is simply that it was looking for balances on a different network. By adding the testnet url (testnet only, this is needed for), then we can avoid this confusion.

**Comment by aulneau** [comment]
Do you have regtest stx?

**Comment by kyranjamie** [comment]
Just came to update with same conclusion. Indeed, that's the issue. Really confusing, though (having forgot that it's on regtest). 

We should add the network url to the popup in testnet to make this more obvious.

**Comment by aulneau** [comment]
I think displaying the label as regtest would be useful too
