### ISSUE TITLE
Remove Connect screen

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#128]
![Screen Shot 2020-02-13 at 13.39.26.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/bca158e4-6f56-46d9-8f35-0e181775483b)

**Comment by hstove** [comment]
@markmhx I moved this to `app`, which is where the relevant change would be made. I think we may have lost Zenhub metadata, please re-add if necessary.

**Comment by markmhendrickson** [comment]
@hstove @aulneau could one of you tackle this one today since @kyranjamie is going offline soon?

**Comment by hstove** [comment]
Yes, I'll take it.

**Comment by hstove** [comment]
Hey @timstackblock , can you QA this?

The change is that we removed the final sign up screen where you re-enter your secret key. Now, when you click "I've saved it", you should finish authentication.

I just updated Banter to use this - it should be deployed in ~5 minutes.

**Comment by timstackblock** [comment]
this is working as expected on Banter
