### ISSUE TITLE
Duplicate transaction in new account

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1283]
Environment:Testnet

User created a new account #3
User send 10 tokens from account # 1 to account # 3
User noticed that the tokens were received and there were another transaction with was also pending
attached the screenshot for perusal
<img width="762" alt="Screen Shot 2021-06-10 at 4 40 36 PM" src="https://user-images.githubusercontent.com/38872890/121594468-19b9f380-ca0b-11eb-9c22-063a26fc27f5.png">

**Comment by kyranjamie** [comment]
Noticed this as well. Appears to be an API issue, I'm currently getting the same tx in both of these reqs
- https://stacks-node-api.regtest.stacks.co/extended/v1/tx/mempool?address=STGQFFRQCMC20E5VJ5ZNJE2B2AH324SBRN4TVJ0Q
- https://stacks-node-api.regtest.stacks.co/extended/v1/address/STGQFFRQCMC20E5VJ5ZNJE2B2AH324SBRN4TVJ0Q/transactions?limit=50

cc/ @zone117x
