### ISSUE TITLE
Set Password dialogue misaligned

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1290]
Environment:Testnet

User downloaded the latest version package from Version Package
User was able to use existing secret phase but then noticed that the set password dialogue went misaligned.

https://user-images.githubusercontent.com/38872890/121759855-c6709f80-caf5-11eb-86f1-8824dda37b9d.mov

**Comment by aulneau** [comment]
resolved by https://github.com/blockstack/stacks-wallet-web/pull/1292

**Comment by Eshwari007** [comment]
Test passed in testnet
