### ISSUE TITLE
[Microblocks] Transaction history timeline component

### ISSUE THREAD

**Issue by kyranjamie** [leather-io/extension#1295]
![image](https://user-images.githubusercontent.com/1618764/122022413-d8d52c80-cdc6-11eb-85cc-4c8d81d708f8.png)

Create a new component that displays transaction events in the 

[Figma link](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/Wallet-%F0%9F%8C%90-web?node-id=2223%3A66044)

**Comment by markmhendrickson** [comment]
@kyranjamie to confirm: the API doesn't support this yet does it?

**Comment by kyranjamie** [comment]
Correct, it doesn't.

**Comment by 314159265359879** [comment]
![image](https://user-images.githubusercontent.com/33360391/156537192-ece580ae-4d29-43fa-9988-9e18c7367250.png)

@falkenprods it looks like there is a plan to solve the issue you experienced. I see the distinction is made between confirmations in microblocks in the explorer but not in the activities tab on the web wallet. Does that mean the API does support it now? What can be done to help this along?

**Comment by andresgalante** [comment]
In the web wallet a transaction state would change from being in a microblock to being in an anchor block when it lands in an anchor block. So it does show the state, just with not as much detail as in the Explorer.

The work to standardize the activity list between wallet and Explorer is on the pipe, but there are other priorities to focus on, and we haven't got to it yet.
