### ISSUE TITLE
Create transaction details view

### ISSUE THREAD

**Issue by kyranjamie** [leather-io/extension#1296]
![image](https://user-images.githubusercontent.com/1618764/122023301-b263c100-cdc7-11eb-8320-d2a4897da058.png)

Create route and associated transaction details view

[Figma link](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/Wallet-%F0%9F%8C%90-web?node-id=1852%3A36843)

**Comment by markmhendrickson** [comment]
This view should include all of the transfer consequences of a given transaction, removing those details from activity itself

**Comment by markmhendrickson** [comment]
Actually closing this issue in favor of https://github.com/leather-wallet/extension/issues/2684 with more details
