### ISSUE TITLE
Include app domain and name in all event tracking calls as properties

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#130]

**Comment by hstove** [comment]
@timstackblock , are you setup to QA event tracking stuff with Segment?

If not, I can help show you how to do so, or we can just assign it to Mark. Whatever works for you!

**Comment by timstackblock** [comment]
I have not received the invite to segment via email. Could some one please send this to me so I have access. Once this is done I should be able to QA the tracking issues.

**Comment by markmhendrickson** [comment]
I just sent you an email invite to Segment

**Comment by timstackblock** [comment]
I'm in thanks Mark

**Comment by timstackblock** [comment]
<img width="1188" alt="Screen Shot 2020-03-06 at 8 26 35 AM" src="https://user-images.githubusercontent.com/49165468/76087514-4d92a780-5f84-11ea-84a4-9af1f72b9684.png">

**Comment by timstackblock** [comment]
Working as expected

<img width="564" alt="Screen Shot 2020-03-06 at 8 30 09 AM" src="https://user-images.githubusercontent.com/49165468/76087722-bd089700-5f84-11ea-8085-41b402534f4b.png">
