### ISSUE TITLE
Resolve blank screen error (u is undefined) and show message for similar errors

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#1318]
When making a contract call, I get a blank screen and the following error in the console:
```
![Screenshot from 2021-06-18 10-55-28](https://user-images.githubusercontent.com/1449049/122535955-58ac0280-d024-11eb-8243-c82ee7fc6de5.png)

Uncaught (in promise) TypeError: u is undefined
    l clarityValue.js:111
    l clarityValue.js:133
    l clarityValue.js:124
    P contract-call-details.tsx:27
    Preact 107
```

Version 2.11.1

![Screenshot from 2021-06-18 10-55-28](https://user-images.githubusercontent.com/1449049/122536114-7b3e1b80-d024-11eb-917b-814d3b285b3d.png)

**Comment by friedger** [comment]
The underlying error should be fixed by upgrading to pending PR here https://github.com/blockstack/stacks.js/pull/1034 
However, a general error handling should be added, I think.

**Comment by markmhendrickson** [comment]
This should be resolved once https://github.com/blockstack/stacks.js/pull/1034 is deployed to npm.
