### ISSUE TITLE
activity list displays dates in the future

### ISSUE THREAD

**Issue by psq** [leather-io/extension#1320]
I guess it is probably using GMT, instead of local times, which is probably not helpful to most users.

Current time is 6:15pm 6/18/21, but here's the display:

<img width="389" alt="Screen Shot 2021-06-18 at 6 14 49 PM" src="https://user-images.githubusercontent.com/255/122626836-603dcc80-d061-11eb-957a-698c73e1050b.png">

**Comment by aulneau** [comment]
@beguene will take this on
