### ISSUE TITLE
[2.11.1] Bug: <describe issue>

### ISSUE THREAD

**Issue by Zerepcano** [leather-io/extension#1327]
Bug found testing Stacks Wallet for Web.

### Error

**Loadable**: `transactions/SIGNED_TRANSACTION`
**Message**: `Error: String length exceeds maximum bytes 128`

### Environment

**Version**: `2.11.1`
**Branch**: `refs/heads/main`
**Commit**: `d807ddc6c0ec9aceaa773c1bb8f25d31a950562e`

**Comment by aulneau** [comment]
> Bug found testing Stacks Wallet for Web.
> 
> ### Error
> **Loadable**: `transactions/SIGNED_TRANSACTION`
> **Message**: `Error: String length exceeds maximum bytes 128`
> 
> ### Environment
> **Version**: `2.11.1`
> **Branch**: `refs/heads/main`
> **Commit**: `d807ddc6c0ec9aceaa773c1bb8f25d31a950562e`

What app were you using?

**Comment by Zerepcano** [comment]
Hiro .so y clarity

**Comment by aulneau** [comment]
> String length exceeds maximum bytes 128

this error typically means that a value for a clarity string is too big when trying to sign a transaction

**Comment by Zerepcano** [comment]
y que puedo hacer ??..perdona mi ignorancia pero soy nuevo en esto ...
gracias
