### ISSUE TITLE
Add the security audit report to the repo

### ISSUE THREAD

**Issue by andresgalante** [leather-io/extension#1339]
Following a post in the forum, we'd like to add the final report to the repo for easy reference.

The tasks involve:

- Finding a good place to put it, Should it be in the root?
- Updating the readme to have a note that links to the report.

The fie is 427kb, would that be a problem to add it to the repo?

[Least_Authority_-_Blockstack_-_Stacks_Wallet_Extension_-_Final_Audit_Report.pdf](https://github.com/blockstack/stacks-wallet-web/files/6702223/Least_Authority_-_Blockstack_-_Stacks_Wallet_Extension_-_Final_Audit_Report.pdf)

**Comment by kyranjamie** [comment]
No that's fine, we can add it here
