### ISSUE TITLE
Nonce error while transferring token between addresses

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1342]
Environment:Testnet

User send Stella token from account #1 to account #2-test passed
User send Stx from account# 1 to account #2-failed with error below.
attaching Video recording for perusal

https://user-images.githubusercontent.com/38872890/123159943-9ef5cd00-d43b-11eb-9814-a26f103fb7e2.mov

**Comment by marshallbtc** [comment]
I'm getting a very similar nonce error. But instead of "Nonce conflict, try again soon." I'm getting "Incorrect nonce." 

Can't do anything with my funds right now. Hope this helps

**Comment by aulneau** [comment]
@Eshwari007 I just tested this with latest, and I cannot reproduce. Can you confirm that you find this same issue in https://github.com/blockstack/stacks-wallet-web/actions/runs/1004532397

**Comment by marshallbtc** [comment]
I'm still running into the "Incorrect nonce." error. I've deleted and re-downloaded the extension on both Chrome and Brave -- error persists.

Is there another way to ensure I'm using the most updated version?
Happy to answer any questions or provide other details that would be helpful.

**Comment by aulneau** [comment]
> I'm still running into the "Incorrect nonce." error. I've deleted and re-downloaded the extension on both Chrome and Brave -- error persists.
> 
> Is there another way to ensure I'm using the most updated version?
> Happy to answer any questions or provide other details that would be helpful.

Can you walk me through how you're getting the error?

If you're interested in trying out an unreleased version to test, you can download the assets here: https://github.com/blockstack/stacks-wallet-web/actions/runs/1004532397 and follow these steps: https://github.com/blockstack/stacks-wallet-web#install-from-source. We are still doing some final QA on it, but it has been working well for me.

**Comment by marshallbtc** [comment]
Just tried the version you provided, and the error remains.
I don't have any tokens in my wallet besides STX, so I can't do the Stella token test like @Eshwari007 did in testnet.

But, what she does in the second half of the video she attached (0:40-1:01) is exactly what I'm doing. The only difference is the error message I'm getting. "Incorrect nonce."

Let me know what you'd like to test next and I'm happy to help.

**Comment by aulneau** [comment]
> Just tried the version you provided, and the error remains.

hmm -- can you walk me through step by step what you're doing? and provide your address if possible?

eg:
- sign in
- hit send
- enter address "SPsdfsdf"
- etc

**Comment by marshallbtc** [comment]
Happy to. Could we email or message via discord privately?

**Comment by aulneau** [comment]
sure, add me on discord -> aulneau#8426

**Comment by marshallbtc** [comment]
Would you mind momentarily allowing friend requests?

**Comment by markmhendrickson** [comment]
@aulneau @thisMonkeyBytes could one of you provide an update about what you learned via messaging privately?

**Comment by marshallbtc** [comment]
@markmhx I was never able to get in touch privately with @aulneau because his Discord doesn't allow others to add him as a friend.

**Comment by markmhendrickson** [comment]
Feel free to message me there with the same requested details: Mark Hendrickson#3708

**Comment by marshallbtc** [comment]
@markmhx sent you a friend request

**Comment by markmhendrickson** [comment]
I must have accepted it since I don't see any pending. Can you message me the information there now?

![image](https://user-images.githubusercontent.com/28991/127305483-e567f86c-4a06-40e6-92db-578e5c23f5ad.png)

**Comment by andresgalante** [comment]
Related to https://github.com/blockstack/stacks-wallet-web/issues/934

check if this issue gets closed once #934 is resolved

**Comment by beguene** [comment]
I just tested, this is working fine. To be tested along with https://github.com/blockstack/stacks-wallet-web/issues/934

**Comment by 314159265359879** [comment]
Is this related I am on an account that has no transactions pending. 
a. I log into account 2, with the web wallet, and copy the address. 
b. Switch to account 3 and send 5 stx to account 2. 
Account 3 is on nonce 2
Account 2 is on nonce 8
--> The transaction from account 2 is (5 stx to account 2) is send with nonce 9 and ofc can not be mined. 

Will this be resolved too with #934?

What about offering an option to web wallet users to edit the nonce (as a sort of advanced setting) that way we can always work around this kind of issues?

**Comment by markmhendrickson** [comment]
@beguene may be able to comment on whether the scenario you describe should be solved by #934.

Please open a separate issue for tracking the possible enhancement in which users can edit their own nonce values manually 🙏

**Comment by beguene** [comment]
@markmhx Yes it should be fixed by #934.
