### ISSUE TITLE
Token transfer was successful despite quantity amount is larger than balance

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1348]
Environment:Testnet

User has only 2 Rocket token.
User input in larger amount than 2 with the address where token to be delivered.
The preview was activated
The transaction was submitted successfully as well
However the activity record didnt produce any transaction activity for the issue

Attaching video recording for perusal

https://user-images.githubusercontent.com/38872890/123308776-171eca00-d4f2-11eb-8819-aa5acf43c176.mov

**Comment by Eshwari007** [comment]
@aulneau Attaching a video recording of the issue I found while testing the above.Seems to be reproducible from my end

https://user-images.githubusercontent.com/38872890/124796904-aaf38b80-df1f-11eb-9697-7a69f96a8176.mov

**Comment by markmhendrickson** [comment]
@Eshwari007 it appears we can re-QA this one now that https://github.com/blockstack/stacks-wallet-web/issues/1400 is merged

**Comment by Eshwari007** [comment]
Thanks @markmhx ,will re test the issue and keep the team posted on the findings

**Comment by Eshwari007** [comment]
Test passed hence moving it to done
cc @markmhx @aulneau

**Comment by markmhendrickson** [comment]
Please close out when moving to done in general 🙏
