### ISSUE TITLE
Warn when attempting to transfer with insufficient funds to cover fees

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1353]
Environment:Mainnet

User sends 10000 out of 1 M of non STX token between two accounts in Mainnet
receiving insufficient fund error.

https://user-images.githubusercontent.com/38872890/123476335-8f58be80-d5ca-11eb-865b-88e02f9ba8a5.mov

**Comment by Eshwari007** [comment]
Closing the issue as there were STX in order to pay the network fees

**Comment by kyranjamie** [comment]
I think we can keep this open. You shouldn't be able to proceed past the form if you don't have any funds. The notification is nice but easy to miss. Enhancement rather than a bug, though.

**Comment by markmhendrickson** [comment]
@jasperjansz do we already have design guidance for this error state or do we need to create it?

**Comment by fbwoolf** [comment]
Do we know what we want to do for this one yet?

**Comment by markmhendrickson** [comment]
poke @jasperjansz ☝️

**Comment by jasperjansz** [comment]
I haven't added this error to the send flow yet, but you can use the error from the transaction signing in the meantime as the components are the same: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/Wallet-%F0%9F%8C%90-web?node-id=1852%3A49570. Let me know if you need more guidance and I can create a screen for the send flow.
