### ISSUE TITLE
[Choose username] Styling fixes

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#137]
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/e66b663d-2363-449b-a296-e68955e8371a)

- [x] 1. Change header font style to Display Large (Matter, 24px) There's an issue for this in the ui library.
- [x] 2. Maybe we can autofocus this field? 
- [x] 4. Padding-left and right 24px 
- [x] 5. Powered by Blockstack caption regular instead of caption medium. 6px margin between "powered by" and logo
- [x] 6. Button height 48px, this goes for all buttons except the 'continue' on sign in (sorry I previously said 40, my bad)

**Comment by timstackblock** [comment]
@jasperjansz This looks good the only thing I noticed is button height was 46 not 48 not sure if that makes a large difference.

Header font 24
![Screen Shot 2020-02-19 at 9.01.43 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/6eba025b-7be8-4637-b8ba-137793eb396a)

Button height set to 46 NOT 48

![Screen Shot 2020-02-19 at 9.04.25 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/8b7315db-3bcc-4aac-9b70-8fa31aa4e5e6)

Padding set to 24
![Screen Shot 2020-02-19 at 9.00.17 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/d6ae3f68-fcdc-486a-afc5-b0ab038ba1b5)
