### ISSUE TITLE
Resolve error "Unable to fetch account data from https://stacks-node-api.mainnet.stacks.co"

### ISSUE THREAD

**Issue by GreatSmiles** [leather-io/extension#1388]
Bug found testing Stacks Wallet for Web.

### Error

**Loadable**: `api.account-data`
**Message**: `Unable to fetch account data from https://stacks-node-api.mainnet.stacks.co`

### Environment

**Version**: `1.20.16.453`
**Branch**: `release/canary`
**Commit**: `34aff46`

**Comment by markmhendrickson** [comment]
Thanks for the report. Is this error message persistent / does it show up again when trying today?

**Comment by GreatSmiles** [comment]
HI Mark,

Yes, it just shows up consistently.  The currant update and the last.  I just checked again.

-Jared

________________________________
