### ISSUE TITLE
[2.11.1] Bug: Attempting to create account by clicking "Create your decentralized account" on the checkout page for a domain. 

### ISSUE THREAD

**Issue by nickhastreiter** [leather-io/extension#1391]
Bug found testing Stacks Wallet for Web.

### Error

**Loadable**: `accounts/CURRENT_ACCOUNT_DATA`
**Message**: `SyntaxError: Unexpected token < in JSON at position 0`

### Environment

**Version**: `2.11.1`
**Branch**: `refs/heads/main`
**Commit**: `d807ddc6c0ec9aceaa773c1bb8f25d31a950562e`

**Comment by markmhendrickson** [comment]
To be clear, this happens when using the .BTC app, correct? cc @MarvinJanssen
