### ISSUE TITLE
[2.11.1] Bug: Error checking balances and transactions

### ISSUE THREAD

**Issue by nanonerd** [leather-io/extension#1393]
Bug found testing Stacks Wallet for Web. It was working this morning when I had 50 accounts in wallet. I added 10 more accounts to reach 60. When I tried again a few hours later, I get these error messages.

Windows 10 Home
Brave browser

### Error

1) Normal check on stacks wallet shows this error:

"Error: Unable to fetch API data from https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SP20AJXBQR33JZH6PSM0BV6J6K12V7W0K7T1FMWTZ/balances Version:2.11.1"

2) When using "btc.us" and Signing In, I get this error. I currently have 60 accounts created for this wallet. Is there a limit of 50 per wallet?

**Loadable**: `accounts/CURRENT_ACCOUNT_DATA`
**Message**: `Error: Unable to fetch API data from https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SP20AJXBQR33JZH6PSM0BV6J6K12V7W0K7T1FMWTZ/transactions?limit=50`

### Environment

**Version**: `2.11.1`
**Branch**: `refs/heads/main`
**Commit**: `d807ddc6c0ec9aceaa773c1bb8f25d31a950562e`

**Comment by nanonerd** [comment]
Updated title. Please re-open.

**Comment by markmhendrickson** [comment]
Is this error persistent upon trying again today?

**Comment by nanonerd** [comment]
After a few hours, it is working again. So no idea what happened to cause the error for a few hours. 
Also, I guess it will be hard to reproduce and trace. So I am going to "Close with comment". 

Thanks.
