### ISSUE TITLE
Add ability to register free usernames

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1395]
Using subdomain registrar at registrar.stacks.co, similar to what we've had in the past for Blockstack Connect and Blockstack Browser.

We have the option of adding this functionality as part of the authentication flow for new users, or post-authentication as a subsequent step.

If you have a need for username registration as part of your app's onboarding flow, please leave a comment below with details about why you need it and how you are using usernames in your app's UX generally.

**Comment by pradel** [comment]
For Sigle, we require our users to register usernames. With blockstack connect this is something that users have to do when creating a new account.
For the extension, we are fine implementing the registration ourselves in our UI if a simple API is provided for this.
We use usernames to resolve the Gaia storage of a user on Sigle by using the `lookupProfile` function. It also provides user-friendly URLs when sharing your blog.
