### ISSUE TITLE
Web Wallet shows expired names but they're not really usable

### ISSUE THREAD

**Issue by dantrevino** [leather-io/extension#1401]
1.0 names that are expired show up in the Web Wallet
![image](https://user-images.githubusercontent.com/7738/124823989-67a51700-df37-11eb-9bc7-49a45479405c.png)

and is still accessible via the api [https://stacks-node-api.mainnet.stacks.co/v1/names/riot.id
](https://stacks-node-api.mainnet.stacks.co/v1/names/riot.id)

![image](https://user-images.githubusercontent.com/7738/124824360-e5692280-df37-11eb-8de2-a5ee0d19382b.png)

but we cant use them for logins because of lookup error during login
![image](https://user-images.githubusercontent.com/7738/124824674-51e42180-df38-11eb-9512-29fa7e86ddff.png)

https://core.blockstack.org/v1/names/riot.id
![image](https://user-images.githubusercontent.com/7738/124824164-9de29680-df37-11eb-98ce-b81659356c8e.png)

**Comment by markmhendrickson** [comment]
Related: https://github.com/blockstack/stacks-wallet-web/issues/1073 https://github.com/blockstack/stacks-wallet-web/issues/504

**Comment by markmhendrickson** [comment]
@dantrevino Are you still unable to authenticate with riot.id these days?

**Comment by markmhendrickson** [comment]
@janniks do you expect this issue to be resolved fully app-side with https://github.com/hirosystems/stacks.js/pull/1230?
