### ISSUE TITLE
Show total balances in accounts selection menu

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1403]
I've found several times now that I wanted to look for my account with a particular balance, but it's hard to do so since I have to select one at a time and check. It'd be nice to see the total balances at a glance from the accounts menu itself:

![image](https://user-images.githubusercontent.com/28991/124788573-c07dab00-df49-11eb-94ab-de23e471d068.png)

**Comment by whoabuddy** [comment]
+1 to this, let's say I'm registering a BNS name with a new account and can't remember which of the others to transfer STX from.

balance would be a great add here!
