### ISSUE TITLE
Show all username suffixes  

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1409]
Now that we have a variety of namespaces with active registration in production, we should revisit the decision to hide the `id.stx` in the UI so users have a more consistent experience.

Here for example you can see the `.btc` and `.stx` suffixes but not id.stx:

<img width="398" alt="Screen Shot 2021-07-08 at 15 09 52" src="https://user-images.githubusercontent.com/28991/124927390-e5802580-dffe-11eb-81e5-63dff1bc714e.png">

**Comment by dantrevino** [comment]
Fix .id first please

**Comment by aulneau** [comment]
We should just remove the logic to hide namespaces in general, so all names will correctly show

**Comment by Eshwari007** [comment]
@markmhx  Based on the input above, we are now supposed to see all user names with .btc,.stx and also id.stx. Am I correct in the understanding? Attaching the screenshot of a test account in which we have the above suffixes.
<img width="340" alt="Screen Shot 2022-03-16 at 6 41 35 PM" src="https://user-images.githubusercontent.com/38872890/158703314-5c260e62-5225-4eb6-9110-993c1fd20a7f.png">

**Comment by markmhendrickson** [comment]
Yes that's correct

**Comment by Eshwari007** [comment]
Thank you @markmhx .
Test has passed.

**Comment by dantrevino** [comment]
It should be showing old .id as well.

**Comment by markmhendrickson** [comment]
The above PR ensures that all suffixes appear
