### ISSUE TITLE
Preload images for Secret Key generation animation

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#141]
So that they don't flicker while loading at each step during the animation, smoothening out the experience.

![Screen Shot 2020-02-14 at 16.20.25.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/2f1a3e01-40ce-4cc3-b73b-21c8bd41bba2)

**Comment by hstove** [comment]
Hm - we already do, but we can do better by including the SVG in React itself.

**Comment by aulneau** [comment]
Yeah, generally any svg we are using internally should be react components.
