### ISSUE TITLE
Provide migration path for usernames from Stacks 1.0

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#1412]
Per this question https://discord.com/channels/621759717756370964/745197302255321108/862586116091674664
> In Boom, names are resolved by bns when transferring assets. pre-2.0-launch names are shown in the web extension for a different address than what bns is resolving (because of different derivation paths). Are there any work arounds how users can recover their assets? The explorer shows only partial information for the address of the address resolved by bns (e.g. https://explorer.stacks.co/address/SP3GWTV1SMF9HDS4VY5NMM833CHH266W4YBASVYMZ?chain=mainnet)

There exists a group of users that have names from before stacks 2.0 where the owner address is different from the address shown and used by the wallets. We should provide notice for accounts where this is the case, and give them the ability to transfer their names to the correct address.

**Comment by dantrevino** [comment]
100% we need this, in all of the aspects described above by @aulneau .

The biggest issue for me is that the web wallet shows one address and bns shows another.  Why isnt the wallet just using the bns lookup for the address display?

**Comment by markmhendrickson** [comment]
[From ZETRA on Discord:](https://discord.com/channels/621759717756370964/621759718192447502/877532382905896990)

> Registered the first names via Blockstack Browser early 2018. So yeah, pretty long time ago. Renewed them once and now they were renewed by stacks staff as a gift for launch of the Stack 2.0. The names should go along with their correct address (in my case at least), but I can't see them at all. Shows only Account1. No username and i guess Account1 is not even an old address of mine. Hope someone can make it happen in the near future so that i enter my (old) secret key and i see all my .ids from years ago. …but as i said, i also registered .btc names recently (with another secret key) and can't see them either. I do see all the accounts but not the usernames. It's showing only Account1, Account2, Account3 etc… Hope somebody can fix it! cheers

**Comment by markmhendrickson** [comment]
From another user via email support (after sending them the relevant API endpoints to confirm ownership of usernames not showing up in the wallet):

> Ok, now I am able to spend a ton of time checking if my ids still under my control by tracking if their addresses are changing or not, but I still can not use them in the wallet ?? 
I have seen the same frustration in several users who have expressed their discomfort and concern in the forum about being unable to use their ids in the wallet, according to my modest opinion it is a problem that needs priority and solution now, it cannot be within a year (maybe)... on the other hand I understand that it is August and you and the team do the best you can... I hope you can help us soon... no hard feelings

**Comment by friedger** [comment]
With the fix for signing the profile token this issue boils down for owners of stack 1.0 to transfer their name from their data address to their stx address with a simple name transfer. As names expire in 4-6 months, the users need to do a tx anyway.

For off-chain names, users have to make a change through their registrar. 

Alternatively, the stacks wallet web could be build as a stack 1.0 version.

Fortunately, the gaia data is not affected because the data is always handle by the data address and does not require a name. However, it is important that the identity address is returned in the auth response now and in the future. The identity address provides access to the users profile during the period where the profile token is singed by the wrong/other address (signature by stx address vs data address and vice versa)

**Comment by markmhendrickson** [comment]
@friedger as mentioned in the related discussion with https://github.com/blockstack/stacks.js/pull/1117#issuecomment-953008940, this particular issue seems as much to do with derivation path differences as key ones? Is it just the former or both?

**Comment by friedger** [comment]
@markmhx If I understand the questions correctly, it is both (derivation path => key)

**Comment by dantrevino** [comment]
I just noticed that my existing .id is expiring *soon* .. @jcnelson  is core.blockstack.org still reading from the system of record?
https://core.blockstack.org/v1/names/dantrevino.id
```
"expire_block": 707019,
"grace_period": true,
"last_txid": "1c7e828500628bafa21d7bfcb2a87658d9edd150181b1ed3a36b759fa6270296",
"renewal_deadline": 712019,
```

**Comment by markmhendrickson** [comment]
IIRC https://core.blockstack.org/v1/names/[name] retrieves legacy Stacks 1.0 data whereas this query will get you Stacks 2.0 data: https://stacks-node-api.mainnet.stacks.co/v1/names/dantrevino.id

**Comment by friedger** [comment]
@dantrevino Still soon, < 6 months I would guess.

**Comment by markmhendrickson** [comment]
I'm closing this in favor of https://github.com/hirosystems/stacks-wallet-web/issues/2287.
