### ISSUE TITLE
Microblocks : Have only one balance (microblocks included)

### ISSUE THREAD

**Issue by beguene** [leather-io/extension#1415]
We are now fetching all api endpoint with unanchored=true see https://github.com/blockstack/stacks-wallet-web/pull/1397
So the balance will take into account transactions from microblocks. But this balance is not final (there could be a chance that those microblocks transactions might be reorg). 
We decided to show both balances the 'anchored' and 'unanchored' balances

**Comment by beguene** [comment]
@jasperjansz @aulneau @kyranjamie @fbwoolf 
Below a first suggestion

![microblock-dual-balances](https://user-images.githubusercontent.com/1501454/125068998-72d28100-e0b6-11eb-8bfc-063733c99887.png)

The issue is that the user has no clue which is which. Any suggestion ?
When I look at it, it looks confusing now. Is it still a good idea to show both balances ?
I think showing only the unanchored balance might be a better UX and the user will have the feeling that everything is fast.

**Comment by jasperjansz** [comment]
@beguene 

> We decided to show both balances the 'anchored' and 'unanchored' balances

I don't recall this and I don't think it's a good idea for the same reason you mentioned — it's confusing. I think we should have one balance per token and it should update whenever there's a mutation in balance, regardless of whether that's the result of a microblock or anchor block. What do you think?

**Comment by beguene** [comment]
@jasperjansz I totally agree. That's what I meant in my last sentence.

**Comment by markmhendrickson** [comment]
Let's update this issue title to clarify that we want only one balance (comprising the net results of both microblock-included and anchor-block-included transactions) for each asset?
