### ISSUE TITLE
Provide better error messaging and guidance for when API is unavailable

### ISSUE THREAD

**Issue by 314159265359879** [leather-io/extension#1417]
Bug found testing with Stacks Wallet for Web, suddenly it does not load the page to show wallet balances/transactions and such. Switching network does nothing to resolve it, although the url changes in the error. First time I have encountered this. It happened shortly after I made two more accounts, but that may be unrelated. 

If I wait, eventually the window will show the wallet again and I can send transactions, see here:

https://user-images.githubusercontent.com/33360391/125104950-37e44380-e0de-11eb-898f-b9a098475262.mp4

### Error

**Loadable**: `accounts/CURRENT_ACCOUNT_DATA`
**Message**: `Error: Unable to fetch API data from https://stacks-node-api.regtest.stacks.co/extended/v1/address/ST2PBEZB3ZPHJE1XJHFQKGF6E08SV29K96WCRJA13/transactions?limit=50`

### Environment

**Version**: `2.11.1`
**Branch**: `refs/heads/main`
**Commit**: `d807ddc6c0ec9aceaa773c1bb8f25d31a950562e`
On Brave (latest) and windows 10

**Comment by markmhendrickson** [comment]
The underlying API experienced some problems around the time you reported this issue last week. Mind trying again to see if the behavior is resolved?

**Comment by 314159265359879** [comment]
Thanks, I have been testing the last hour and it has not reappeared, this behavior looks resolved to me.
