### ISSUE TITLE
Add sign out option to accounts screen

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#142]
![Screen Shot 2020-02-14 at 16.22.27.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/b35d6e74-faa5-4ada-a6c4-bf1505b0563d)

**Comment by jasperjansz** [comment]
https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=5721%3A11775

This would link to the Index page as we want to display the warning that they'll need their Secret Key to sign back in and provide an option for them to view it.

We could later upgrade this flow to show the above on this screen, in the popup.

**Comment by markmhendrickson** [comment]
Might the user be confused they have to effectively choose "sign out" twice with this approach (with the first selection simply taking them to the index instead of doing what they expect)?
