### ISSUE TITLE
[2.11.1] Bug: Unable to select testnet network

### ISSUE THREAD

**Issue by whoabuddy** [leather-io/extension#1423]
Bug found testing Stacks Wallet for Web.

### Error

**Loadable**: `accounts/CURRENT_ACCOUNT_DATA`
**Message**: `TypeError: Network request failed`

### Environment

**Version**: `2.11.1`
**Branch**: `refs/heads/main`
**Commit**: `d807ddc6c0ec9aceaa773c1bb8f25d31a950562e`

### Description

Today the testnet was reset, and when I went to change the network to testnet I received this error.

**Comment by aulneau** [comment]
It's likely the network is not yet really available to use

**Comment by whoabuddy** [comment]
Patience is my life lesson :laughing: 

Will wait and try again tomorrow!

**Comment by whoabuddy** [comment]
Working today - thank you!
