### ISSUE TITLE
Microblocks: Show indicator in the activity list

### ISSUE THREAD

**Issue by beguene** [leather-io/extension#1428]
We need to show a special indicator (new 'lightning' icon) in the activity list to distinguish anchored transactions from unanchored transactions

See design
https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/Wallet-%F0%9F%8C%90-web?node-id=2221%3A14454

**Comment by timstackblock** [comment]
This will be updated with the new figma designs to update the balance based on our last meeting. A new release will be ready for test this week.

**Comment by timstackblock** [comment]
This is good to go!

**Comment by timstackblock** [comment]
:shipit:
