### ISSUE TITLE
All token (send and receive) values should be viewable on Activity Tab

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1432]
<img width="394" alt="Screen Shot 2021-07-13 at 12 33 14 PM" src="https://user-images.githubusercontent.com/38872890/125490843-7a00127b-b311-4343-92a8-af0f62e3785a.png">
<img width="394" alt="Screen Shot 2021-07-13 at 12 33 20 PM" src="https://user-images.githubusercontent.com/38872890/125490846-a633d707-c5bd-45cd-8f51-ac48aa8d3040.png">
Environment:Testnet

Actual scenario:
User is only able to view -numeric values of Stacks token when it was send,however user is not able to view the - numeric values of other tokens when its send via the Activity tab
User is not able to view the receive activity for other tokens as well

Expected results:
User is supposedly to view all numeric values of send and receive of all the tokens(not just Stacks)

Attached the screenshot of the issue
<img width="384" alt="Screen Shot 2021-07-13 at 12 26 16 PM" src="https://user-images.githubusercontent.com/38872890/125490284-5c7f8d10-7737-425e-a595-cb158bdd0571.png">

**Comment by Eshwari007** [comment]
@beguene Am not able to view the non STX token value in both sender and receiver activity tab

**Comment by Eshwari007** [comment]
@beguene Is this ticket good to go for re testing?

**Comment by beguene** [comment]
@Eshwari007 Yes this is the same PR as https://github.com/blockstack/stacks-wallet-web/issues/1460

**Comment by Eshwari007** [comment]
@beguene Two quick questions arise during testing this ticket:
<img width="591" alt="Screen Shot 2021-10-12 at 1 58 20 PM" src="https://user-images.githubusercontent.com/38872890/137016686-0227a375-7512-4ac6-907e-094078b26cff.png">

The date is showing as Oct 7th while today is Oct 12th .Also we are seeing two tx one for the miami token transfer,one for the function and another tx-is this intended?

This issue is only in Mainnet.On testnet seems to be working fine
<img width="388" alt="Screen Shot 2021-10-12 at 3 28 17 PM" src="https://user-images.githubusercontent.com/38872890/137017290-86d090cb-a757-43ce-a84a-8022ff405eb4.png">

**Comment by Eshwari007** [comment]
The good part is test passed where non STX token values are shown(viewable) in both sender and receiver activity tab.

**Comment by Eshwari007** [comment]
https://user-images.githubusercontent.com/38872890/137020308-04178f07-690f-4bcb-a060-4875be277f98.mov

**Comment by beguene** [comment]
Thanks @Eshwari007. The first visual tx is the contract call, so I think it's useful to the user, the second is added to display the token transfer. I think we should keep the contract call.
I will check the date issue.

**Comment by beguene** [comment]
@Eshwari007 Can you give me the wallet address ?

**Comment by Eshwari007** [comment]
@beguene Will send it to you via DM

**Comment by Eshwari007** [comment]
@beguene Do you want me to create a separate ticket for the mainnet date and tx issue and close this one or shall I wait for code fix and retest the issue?

**Comment by beguene** [comment]
@Eshwari007 I tested on Mainnet and the dates are correct, but there is an issue with the 'queued' and pending transaction, it does not show up after sending, so you can't see the latest sent transactions. Maybe that's why you see an old tx, it was always there (7th of october). I will fix it after the refactor work. You can wait for the code fix and keep this issue (and the other ones  #1460 and #1713).

**Comment by Eshwari007** [comment]
@beguene Do ping when I can retest the issue.Thx

**Comment by beguene** [comment]
@Eshwari007 You can check now. I fixed the issue with the pending transaction not being visible. The dates should also be correct now.

**Comment by Eshwari007** [comment]
Test passed in the PR.Moving it to Test done
