### ISSUE TITLE
Stale balances persist when switching accounts from certain routes

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#1436]
I've determined how to reproduce https://github.com/blockstack/stacks-wallet-web/issues/1336

- sign in
- go to receive page
- switch accounts while still on that page
- go back home
- stale data is present

I spent some time this afternoon trying to debug it, and I have a few ideas -- but this is something that should be fixed before a release. I think ultimately it's related to this issue https://github.com/blockstack/stacks-wallet-web/issues/1048

Here is a video:

https://user-images.githubusercontent.com/11803153/125535034-404bd6d7-e384-457a-874a-da235dcbb3af.mp4

**Comment by Eshwari007** [comment]
@aulneau Mine is indicating a different behavior
Attaching a video recording-do kindly view till the first 20 sec as I continued with testing with the remaining testing.

https://user-images.githubusercontent.com/38872890/125536515-1c2f0373-cef5-4887-9e1c-f6912555d569.mov
