### ISSUE TITLE
The web wallet shows STX as received but when I try to send them I get an error message

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#1459]
Video of issue https://screencast-o-matic.com/watch/criYD7ViUxH

When hitting the send MAX amount button after I have received STX from a microblocks transaction the fees are taken out and the transaction should go through but it does not.

The web wallet shows STX as received but when I try to send them I get an error message. Should STX received in a microblock be available to send? They appear to be before the error message.

<img width="394" alt="Screen Shot 2021-07-20 at 11 56 30 AM" src="https://user-images.githubusercontent.com/49165468/126356451-dfa82f4d-0fce-4fd0-8da3-fc79b90c5810.png">

<img width="335" alt="Screen Shot 2021-07-20 at 11 56 12 AM" src="https://user-images.githubusercontent.com/49165468/126356466-96cb14c3-0130-4e43-8b53-f8418a05fb20.png">

**Comment by markmhendrickson** [comment]
@beguene you may want to look into how the API is responding in this case and follow up with Matt

**Comment by beguene** [comment]
@markmhx @timstackblock There is a limitation with the current API. Matt and the splat team are looking into it. I will keep you updated.

**Comment by beguene** [comment]
relevant discussion 
https://github.com/blockstack/stacks-blockchain/issues/2774
