### ISSUE TITLE
Show activity for tokens transferred via contracts

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1460]
User tried to send Stella token and Rocket token between two accounts
User also send STX token between another two accounts

All of the transfers were super fast and it was successful
However,user notices in the accounts where Stella and Rocket tokens were send and received,the activity tab is empty

Attaching the screenshot for perusal
cc @aulneau @beguene @timstackblock 
<img width="388" alt="Screen Shot 2021-07-20 at 12 17 44 PM" src="https://user-images.githubusercontent.com/38872890/126359905-ba60992e-d29a-44af-b311-4704f3c19fed.png">
<img width="385" alt="Screen Shot 2021-07-20 at 12 17 57 PM" src="https://user-images.githubusercontent.com/38872890/126359908-2c63167c-fda7-4d5d-9d11-fe53df3e662c.png">
<img width="391" alt="Screen Shot 2021-07-20 at 12 18 12 PM" src="https://user-images.githubusercontent.com/38872890/126359911-266ffd8d-b480-44e9-8883-292c8a2b2719.png">
<img width="380" alt="Screen Shot 2021-07-20 at 12 18 19 PM" src="https://user-images.githubusercontent.com/38872890/126359912-c93d9836-2264-4de2-963d-7b12b91058e0.png">

**Comment by aulneau** [comment]
This is expected -- "activity" for the recipient of these transfers is not yet displayed -- not so much a bug but enhancement needed

**Comment by Eshwari007** [comment]
Will change the type of ticket accordingly @aulneau

**Comment by Eshwari007** [comment]
@beguene  I am only seeing STX transfers in the receiving account activity tab
Am not able to view other tokens such as MIA and wrapped nothing upon transfer
<img width="405" alt="Screen Shot 2021-09-30 at 3 21 12 PM" src="https://user-images.githubusercontent.com/38872890/135517737-c2d7d633-5508-4613-931b-7489af7d9403.png">

<img width="437" alt="Screen Shot 2021-09-30 at 3 20 22 PM" src="https://user-images.githubusercontent.com/38872890/135517698-d55a3af1-4ab0-4ad7-9282-416eca70dd48.png">

**Comment by beguene** [comment]
@Eshwari007 There is an amount "-1" in the right column, this is the amount transferred for this 'miamicoin-token'.

**Comment by Eshwari007** [comment]
@beguene Agree but this is senders account.On the receivers account,am not able to view any tx besides STX.Is that what is expected?

**Comment by beguene** [comment]
@Eshwari007 Oh indeed you are correct. This is because the sender called the contract so we don't have the events on the receiver side . I will check, I think there is a way to show for both if I use the api instead.

**Comment by Eshwari007** [comment]
@beguene I am yet not able to view the value of token(non STX) being transferred both in sender and receiver (testing on mainnet and testnet)
<img width="528" alt="Screen Shot 2021-10-07 at 12 28 34 PM" src="https://user-images.githubusercontent.com/38872890/136437072-a96a5e1e-f5ba-43f3-adff-efb630faff8a.png">

**Comment by Eshwari007** [comment]
We use to be able to view value for non stx token in sender activity tab in your previous fix,only in receiver we werent able to view it
<img width="497" alt="Screen Shot 2021-10-07 at 6 33 18 PM" src="https://user-images.githubusercontent.com/38872890/136471282-564eeb9d-f075-4966-a85a-082a9fd62965.png">
cc @beguene

**Comment by beguene** [comment]
Can you try with stella token ? See below.
I think the api does not recognize miami token
<img width="471" alt="stella" src="https://user-images.githubusercontent.com/1501454/136548306-b0bb0596-97e7-4261-943a-b735de55c49c.png">
.

**Comment by Eshwari007** [comment]
@beguene It was working for MIA before and wrapped nothing,now none is working except for STX
Tested for both Stella and MIA both are empty values
<img width="382" alt="Screen Shot 2021-10-08 at 11 13 03 AM" src="https://user-images.githubusercontent.com/38872890/136581330-8391d9ba-7647-41bc-b9a1-251bcd74bfdd.png">

**Comment by beguene** [comment]
@Eshwari007 have you picked the correct build version here https://github.com/blockstack/stacks-wallet-web/pull/1747 ?

**Comment by Eshwari007** [comment]
Yes,just for sanity sake -I am retesting it again in #1747 
Noticed that the Stela token still doesnt have any value to it
<img width="371" alt="Screen Shot 2021-10-08 at 12 40 27 PM" src="https://user-images.githubusercontent.com/38872890/136593011-e3e72ac4-b028-493e-b444-4d5a152538ad.png">

**Comment by beguene** [comment]
@Eshwari007 I found the issue, the build in the PR was not produced from the latest commit. This is fixed now.

**Comment by Eshwari007** [comment]
Test passed for the above issue.Moving it to done
