### ISSUE TITLE
Improve account creation pending state

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1465]
Right now it says the user's account has been created before it's done creating per the pending state indicated by the button's spinner:

<img width="446" alt="Screen Shot 2021-07-20 at 20 37 45" src="https://user-images.githubusercontent.com/28991/126477695-1b0c0ac6-4ef8-49a6-9c76-67b3aabc57dd.png">

**Comment by pete-watters** [comment]
I tested this and it has been solved in Leather so closing off
