### ISSUE TITLE
Trigger username form submission with enter key

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#147]
Currently when I hit the enter key after entering a username, it doesn't do anything. It should submit the username and proceed to the next step of the onboarding flow.

![image.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/c085c387-addc-4dbb-92ea-04d4d4342486)

**Comment by aulneau** [comment]
fixed with https://github.com/blockstack/app/pull/175
