### ISSUE TITLE
Some of the base component icon is missing

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1470]
Environment:Testnet
User navigates to the new web wallet build
User notices only the lightning component is visible but not the pending nor failed icon

Attaching the screenschot for perusal
https://github.com/blockstack/stacks-wallet-web/pull/1430
Version #: v2.12.2.825

<img width="208" alt="Screen Shot 2021-07-21 at 12 28 40 PM" src="https://user-images.githubusercontent.com/38872890/126547444-2fb143fd-bf80-49cd-a10b-32dbf1865971.png">
<img width="363" alt="Screen Shot 2021-07-21 at 12 29 12 PM" src="https://user-images.githubusercontent.com/38872890/126547447-02fe01f4-dc2c-4e75-b588-528bd82b6dc5.png">
<img width="363" alt="Screen Shot 2021-07-21 at 12 29 33 PM" src="https://user-images.githubusercontent.com/38872890/126547448-326f3861-617f-4e97-95ae-692183674d1f.png">

**Comment by beguene** [comment]
@Eshwari007 Do you mean that you never see the 'pending' icon ?
I always see it but it says pending only for a few seconds.

<img width="455" alt="pending" src="https://user-images.githubusercontent.com/1501454/126604663-a42cdfd6-77eb-4afc-bc4a-7067feaff449.png">

Or do you mean that the icon are not matching the figma design ? If that is the case this is not specific to this microblock branch.

**Comment by markmhendrickson** [comment]
The pending icon in both of your screenshots appears different – an upward arrow in @beguene's and an "f" in @Eshwari007.

Are you both looking at the same version?

Can we get the clock-like pending icon from Figma into this release in any case if that's meant to be the one implemented regardless of microblocks?

**Comment by beguene** [comment]
@markmhx Her screenshot is from the figma design which is not completely implemented in the wallet. I can add the clock-like icon but I think what we have currently (arrow + color=orange) conveys more: The shape describes the type of the transaction (receive, send, contract etc..) and the color signals the state (pending, confirmed). 
However our microblock icon design does not follow this.
What do you think @jasperjansz ?

**Comment by Eshwari007** [comment]
@beguene This is for both pending and failed icon

**Comment by Eshwari007** [comment]
@beguene can you kindly share the link for the extension to test the feature above in web wallet according to the design in Figma?

**Comment by beguene** [comment]
@Eshwari007 You can check the linked PR here 
https://github.com/blockstack/stacks-wallet-web/pull/1552
At the top you can find the extension build. 
[here](https://github.com/blockstack/ux/actions/runs/1116141627)

**Comment by Eshwari007** [comment]
Thank you ,will take a look at it

**Comment by Eshwari007** [comment]
@beguene The failed and pending symbol are yet reflecting the respective function or contract call symbol in orange.
In explorer we have them according to the Figma design by @jasperjansz where we have the the failed icon as circle with a lash inside it and the pending as the clock icon in orange(they are also attached in the first snapshot on this ticket)
For consistency wise,we need them all reflecting same base component across destop,web wallet and explorer-is what I personally believe in order not to confuser user on the UX. Maybe @markmhx can add comments to my input here.Attaching the screenshot of the activity which I yet see from PR #1552 
<img width="363" alt="Screen Shot 2021-08-15 at 5 44 32 PM" src="https://user-images.githubusercontent.com/38872890/129493826-f039599e-cc90-4731-8b11-d408017aa0ee.png">
<img width="280" alt="Screen Shot 2021-08-15 at 5 45 41 PM" src="https://user-images.githubusercontent.com/38872890/129493828-dbdc7e97-d164-4056-afac-440cd1443fd3.png">

**Comment by markmhendrickson** [comment]
@jasperjansz please chime in here about the desired implementation changes.

**Comment by jasperjansz** [comment]
I created this file with a transaction component you can play with (you can't break anything!): https://www.figma.com/file/23YhHbfpiJVaPWcneC53v1/play-with-transactions?node-id=0%3A1

if you select it, you can toggle the type and state on the right here: 
![image](https://user-images.githubusercontent.com/25477905/129559588-e6ed66f3-b2b8-482c-a4d7-b3d7b57e38e3.png)

You can find a list for all types and states in the Components page of the Spec file: https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=28%3A1706

@markmhx Step one would be to implement it correctly in the web wallet. Should we also create an issue to standardize these across all 3 products?

**Comment by markmhendrickson** [comment]
@jasperjansz please do check each product for diffs, and both modify this issue to specify the exact change for the web wallet and create two new issues for the other products if necessary.

**Comment by Eshwari007** [comment]
Shall I move the ticket back to backlog or close it as we are planning to create two new issues in regards to the consistency of base component across the products?
cc @markmhx @jasperjansz

**Comment by Eshwari007** [comment]
Closing this ticket as follow up tickets will be created by @jasperjansz
