### ISSUE TITLE
Switching between networks  is disabled in Firefox extension

### ISSUE THREAD

**Issue by n4cr** [leather-io/extension#1471]
I use Stacks Wallet v2.12.2 on Firefox (v90). When I want to switch the network, all the networks are disabled.
If I use Chrome, I can easily switch the network. 

Here is a screenshot of the network switch pane:
<img width="390" alt="CleanShot 2021-07-22 at 11 29 55@2x" src="https://user-images.githubusercontent.com/1065473/126618054-d0e5c3aa-f484-4454-b192-4e4c78836b8f.png">

**Comment by beguene** [comment]
It's working fine for me
<img width="436" alt="firefox" src="https://user-images.githubusercontent.com/1501454/126763964-34444b0a-c0eb-4cc4-9040-ce494cf242c6.png">

**Comment by markmhendrickson** [comment]
See https://github.com/blockstack/stacks-blockchain-api/issues/540#issuecomment-885162028

@n4cr can you confirm whether this is working for you now?

**Comment by n4cr** [comment]
@markmhx I confirm it is fixed as well! Except for the Localnet which I believe is because I don't have a localnet running.

Thanks for the quick fix!
