### ISSUE TITLE
Display fungible token (FT) standard attributes with API (per SIP 010)

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1472]
We previously started to display FT standard attributes using client-side `read-only` calls with https://github.com/blockstack/stacks-wallet-web/issues/1070.

However, this isn't likely to scale well so we should start displaying them using API-based data provided by https://github.com/blockstack/stacks-blockchain-api/pull/576 once available.

We should also add support for the `token-uri` attribute and standard data provided by JSON (name, description and image)  as part of this implementation.

**Comment by whoabuddy** [comment]
Would love to see this! We have our branding/metadata setup [on the CityCoins CDN](https://cdn.citycoins.co/metadata/miamicoin.json) and I'm sure MIA holders would like to see the logo in their wallets.

![MiamiCoin](https://cdn.citycoins.co/logos/miamicoin.png)

**Comment by aulneau** [comment]
@whoabuddy please comment on this https://github.com/blockstack/stacks-blockchain-api/pull/576 issue if you'd like to see this prioritized -- the wallet is blocked on implementation until that PR in the API ships

**Comment by pstan26** [comment]
Really would appreciate it on behalf of the  now 10,000 people in the MiamiCoin community. OkCoin announced they'll be listing soon and the brand should really be showing up in the native web wallet before then.

**Comment by muneeb-ali** [comment]
I can +1 this. This project seems to have an enthusiastic community organically coming together and wallet support can help them!

**Comment by markmhendrickson** [comment]
The blocking API updates are now merged and ready for this client-side work.
