### ISSUE TITLE
Add fiat onramp option(s) to "fund your account" screen

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1473]
https://www.figma.com/file/vxDKlT2asJ8iUwh0UpyjDT/🔎-Buy?node-id=202%3A4773

Related: https://github.com/blockstack/stacks-wallet-web/issues/1479

Desired characteristics:

- Simple credit or debit card information entry
- Instant or near-instant availability of balance for STX transactions
- No KYC up to useful limit to get started with first basic contract calls (e.g. $50)

![136796960-5af9813e-77e4-4e36-b57c-d631756cc7ca](https://user-images.githubusercontent.com/28991/136972182-d5a488bf-0d7b-42c7-b6ef-30c38f9921fa.png)

- [x] #1940
- [x] #1941
- [x] #1942

**Comment by markmhendrickson** [comment]
@jasperjansz I've moved this to the board so we can track work on it in support of partner integrations.

Given discussions so far, I'm thinking we should update [the current mockups](https://www.figma.com/file/vxDKlT2asJ8iUwh0UpyjDT/%F0%9F%94%8E-Buy?node-id=32%3A5311) to make it clear that the user will get taken from the wallet to a 3rd party provider to complete the purchase.

I may recommend we still collect the desired STX purchase amount (and related USD estimate) upfront in the wallet then pass both that STX value and the user's Stacks address to the provider's website via GET parameters.

Then the provider can take the user through the entire purchase process and show a confirmation screen that encourages the user to open the wallet extension again and view their deposit there.

cc @jonastgerber

**Comment by markmhendrickson** [comment]
@jasperjansz Can you link to your latest designs for this flow and then remove yourself as an assignee and the issue from the design column?

**Comment by jasperjansz** [comment]
Yep, here it is: https://www.figma.com/file/vxDKlT2asJ8iUwh0UpyjDT/%F0%9F%94%8E-Buy?node-id=201%3A11002

**Comment by markmhendrickson** [comment]
See [Transak](https://transak.com/) documentation for WYSIWYG integration configuration: https://www.notion.so/Integrate-Transak-f43cbb5dc7fa4d068a044ef9589879bf

A preview version of the flow can be seen here: https://staging-global.transak.com/

The biggest issue with this provider seems to be that they need to support STX. But otherwise the offering appears to align very well with for our design goals here.

cc @jonastgerber 

![image](https://user-images.githubusercontent.com/28991/133604961-610e6f45-5de8-45a7-b8ee-5298a4f4f559.png)

**Comment by markmhendrickson** [comment]
Design needs finalization in spec. Currently just in drafts.

**Comment by markmhx** [comment]
@jasperjansz is this design finalized?

**Comment by markmhendrickson** [comment]
This issue needs decomposition into sub-issues.

**Comment by andresgalante** [comment]
- [ ] Create an MVP for the Fiat onramps UI
- [ ] Implement external vendor #1
- [ ] Implement Transact

**Comment by beguene** [comment]
@markmhx Since we have 2 providers how would we handle this in the UI ? Currently the design assumes only one provider.
Do we give a choice to the user ? Or shall we implement first with one provider then add the next later with a different UX.

**Comment by markmhendrickson** [comment]
I'm thinking we just repeat vertically the gray component for each provider with standard margins between them. 

That way we can also customize the copy for each provider to highlight its unique aspects (e.g. country support, KYC requirements, etc.)

I can update Figma to make this clear.

**Comment by beguene** [comment]
That works ! No real need to update figma, I understand what you mean.
