### ISSUE TITLE
Improve set password screen

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1476]
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=8%3A1262

- [x] update copy
- [x] add confirm step
- [x] improve password field with unmask option and the strength meter seen [here](https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=14%3A2056). Main component can be found [here](https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=14%3A2056). https://github.com/blockstack/stacks-wallet-web/issues/1205

![image](https://user-images.githubusercontent.com/28991/136795523-2390b888-72a5-476b-847c-f6c5fc0a4d59.png)

**Comment by markmhendrickson** [comment]
@eugeniadigon to add an illustration

**Comment by markmhendrickson** [comment]
While we're updating the "set password" screen here, we may want to update the "enter password" screen similarly:

- Add illustration
- Add header ("Your session is locked")
- Improve copy ("Enter the password you previously set to access your accounts on this device.")
- Add link to help FAQ for users who can't remember their password or enter it successfully ("Unable to enter your password? Learn more")

<img width="405" alt="Screen Shot 2021-11-12 at 11 15 11" src="https://user-images.githubusercontent.com/28991/141470843-516eb483-9bca-41da-b5fa-96014eef2ccf.png">

**Comment by kyranjamie** [comment]
Big +1 to this. I'm also eager to improve the experience of the, actually pretty long, delay while we unlock the wallet. Loads of  cool things we could do more creative than just showing a spinner.

**Comment by ginny-d** [comment]
There is already an updated design for Enter password (Unlock wallet):
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=604%3A13872

I can work on this to update a couple more things like the illustration, title, copy and password guidance.
For the spinner, could be fun to have a floating/jumping animated illustration while it's loading. We can explore that option

--
One thing I've been thinking regarding the password is that currently the only way to change the password is to reset the wallet with the secret key by following the "forgot password" process. Do we want to cover the case where a user would just want to, i.e, for security reasons, change their password?
I understand this would/should require as well entering the secret key, but at least I'd add some guidance i.e "Forgot or want to change password?". It doesn't feel intuitive if my desired action is to change the password, to click on "forgot password".

**Comment by markmhendrickson** [comment]
> Do we want to cover the case where a user would just want to, i.e, for security reasons, change their password?

Are you thinking this might be a new, separate option under the app's global menu e.g. "Change password"? I presume that's a more appropriate place than this particular screen, where the user would have to know their _old_ password before proceeding to set a new one (or alternatively sign out entirely and re-enter their key).

> There is already an updated design for Enter password (Unlock wallet):

This looks like a good base for this particular password entry screen. Perhaps we can update it with [the tweaks above](https://github.com/hirosystems/stacks-wallet-web/issues/1476#issuecomment-967100567).

**Comment by ginny-d** [comment]
1) 'Set password' screen updated with icon:
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=2227%3A12742
<img width="1352" alt="password" src="https://user-images.githubusercontent.com/78865845/150517720-8ee6dbe8-b22b-43de-b58e-0feebdcdf63c.png">
<img width="1352" alt="password-1" src="https://user-images.githubusercontent.com/78865845/150517729-57ce403d-d72c-48a6-a4f5-d65b171d1194.png">
<img width="488" alt="password-2" src="https://user-images.githubusercontent.com/78865845/150517740-1c07e28e-1736-40f3-a0b4-24ff921daf92.png">

**Comment by Eshwari007** [comment]
@fbwoolf 
Two findings:

- When a user is trying to set a password notice that the eye icon(hide or show password) is shown in the Figma design but is not visible in the actual implemented screen
<img width="618" alt="Screen Shot 2022-02-01 at 10 10 52 AM" src="https://user-images.githubusercontent.com/38872890/151995529-35aeeb0e-0d52-4e94-a714-a24995d54cb2.png">
<img width="442" alt="Screen Shot 2022-02-01 at 10 14 56 AM" src="https://user-images.githubusercontent.com/38872890/151995605-21682adb-14c3-47ca-9313-511d50225503.png">


While setting the password and trying to lock the account, noticed that we still have the old view on it (the Figma design  vs the actual popup wallet Lock account view). I do not see the design on Figma but notice the Lock design in this ticket mentioned above.https://github.com/hirosystems/stacks-wallet-web/issues/1476#issuecomment-1018415082
<img width="1207" alt="Screen Shot 2022-02-01 at 10 13 09 AM" src="https://user-images.githubusercontent.com/38872890/151995768-34f21209-26e1-48ef-82e6-4bfea9e933af.png">

**Comment by Eshwari007** [comment]
> @fbwoolf Two findings:
> 
> * When a user is trying to set a password notice that the eye icon(hide or show password) is shown in the Figma design but is not visible in the actual implemented screen
> 
> <img alt="Screen Shot 2022-02-01 at 10 10 52 AM" width="618" src="https://user-images.githubusercontent.com/38872890/151995529-35aeeb0e-0d52-4e94-a714-a24995d54cb2.png">
> 
> <img alt="Screen Shot 2022-02-01 at 10 14 56 AM" width="442" src="https://user-images.githubusercontent.com/38872890/151995605-21682adb-14c3-47ca-9313-511d50225503.png">
> 
> While setting the password and trying to lock the account, noticed that we still have the old view on it (the Figma design vs the actual popup wallet Lock account view). I do not see the design on Figma but notice the Lock design in this ticket mentioned above.[#1476 (comment)](https://github.com/hirosystems/stacks-wallet-web/issues/1476#issuecomment-1018415082) <img alt="Screen Shot 2022-02-01 at 10 13 09 AM" width="1207" src="https://user-images.githubusercontent.com/38872890/151995768-34f21209-26e1-48ef-82e6-4bfea9e933af.png">

**Comment by fbwoolf** [comment]
@Eshwari007 we will have to come back to redesigning the input overall bc that is shared everywhere. I can create an issue for it, but I think for this release we are ok.

Also, I didn't see the lock screen was included in this issue. Thx for catching it. I can separate that into a new issue and try to get that in quick today, but I don't think it should hold up releasing.

**Comment by fbwoolf** [comment]
Issues created:
https://github.com/hirosystems/stacks-wallet-web/issues/2198
https://github.com/hirosystems/stacks-wallet-web/issues/2199

I will start the one to redo the lock screen and remove it from this issue.

**Comment by Eshwari007** [comment]
Will move this ticket to merge as issues #2198 and #2199 has been created in regards to test findings above
