### ISSUE TITLE
Improve sign in screen

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1477]
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=8%3A1424

Only cosmetic changes here. Same title style and layout as other onboarding screens.

![image](https://user-images.githubusercontent.com/28991/136795653-cccd3156-3057-4ca8-ac0e-854c07390a96.png)

**Comment by markmhendrickson** [comment]
@eugeniadigon to add an illustration

**Comment by ginny-d** [comment]
Updated with icon:

https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=2223%3A13000
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=14%3A1439
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=2223%3A13410

<img width="1352" alt="sign in-1" src="https://user-images.githubusercontent.com/78865845/150517018-ae78f549-0404-4fd1-81ae-6c3b9d2625b9.png">
<img width="1352" alt="sign in" src="https://user-images.githubusercontent.com/78865845/150517027-a40fa99c-bccc-40af-b3c0-61a5d0aba1c3.png">
<img width="488" alt="Secret Key" src="https://user-images.githubusercontent.com/78865845/150517055-859c8ffc-06d3-480c-88cc-e62232a16909.png">

**Comment by Eshwari007** [comment]
Findings below:
<img width="1013" alt="Screen Shot 2022-02-01 at 10 46 37 AM" src="https://user-images.githubusercontent.com/38872890/152003104-186d5bf8-6834-4a25-a7ff-3c6d96e1fac8.png">
<img width="1310" alt="Screen Shot 2022-02-01 at 10 48 25 AM" src="https://user-images.githubusercontent.com/38872890/152003109-259bfe28-86ab-41e3-b8c6-fb317f56519d.png">
<img width="1259" alt="Screen Shot 2022-02-01 at 10 49 01 AM" src="https://user-images.githubusercontent.com/38872890/152003112-977c0dd7-ad53-45e7-b2a3-6b821368e216.png">
<img width="1205" alt="Screen Shot 2022-02-01 at 10 49 14 AM" src="https://user-images.githubusercontent.com/38872890/152003117-92a58c80-ef77-45c0-b2b1-7cbb1dac9e5a.png">
<img width="1305" alt="Screen Shot 2022-02-01 at 10 50 01 AM" src="https://user-images.githubusercontent.com/38872890/152003121-aa2eb028-da89-4748-a01d-c9f280bbebfb.png">

User was testing the sign in screen on the popup wallet and also on full mode view. Both of the wallet didnt seem to sync up when user enters the secret key nor password.I can create an enhancement ticket if the logic wasnt implemented in the new onboarding design cc @fbwoolf

**Comment by Eshwari007** [comment]
Also the eye icon,hide /show is not visible in the implemented version in the 'Sign in with secret key 'screen
<img width="1127" alt="Screen Shot 2022-02-01 at 11 00 29 AM" src="https://user-images.githubusercontent.com/38872890/152003858-ffd843a6-f526-4072-b0ec-6495a46900f0.png">

**Comment by fbwoolf** [comment]
> 
> User was testing the sign in screen on the popup wallet and also on full mode view. Both of the wallet didnt seem to sync up when user enters the secret key nor password.I can create an enhancement ticket if the logic wasnt implemented in the new onboarding design cc @fbwoolf

I'm not sure why this is being reported here? This is behavior that already existed. We have never kept these views in sync. This is fine and a non-issue. We would have to more work with routing, not these onboarding changes, to keep views constantly in sync. If you check prod, it is the same.

**Comment by fbwoolf** [comment]
> Also the eye icon,hide /show is not visible in the implemented version in the 'Sign in with secret key 'screen

This would be included with a redesign of our input field which I made a ticket for and linked in response to a previous issue today: https://github.com/hirosystems/stacks-wallet-web/issues/2198

**Comment by Eshwari007** [comment]
> > User was testing the sign in screen on the popup wallet and also on full mode view. Both of the wallet didnt seem to sync up when user enters the secret key nor password.I can create an enhancement ticket if the logic wasnt implemented in the new onboarding design cc @fbwoolf
> 
> I'm not sure why this is being reported here? This is behavior that already existed. We have never kept these views in sync. This is fine and a non-issue. We would have to more work with routing, not these onboarding changes, to keep views constantly in sync. If you check prod, it is the same.

Yes,while we have been redesigning the onboarding screen,was wondering if this can be made as an enhancement for future releases.

**Comment by Eshwari007** [comment]
> > > User was testing the sign in screen on the popup wallet and also on full mode view. Both of the wallet didnt seem to sync up when user enters the secret key nor password.I can create an enhancement ticket if the logic wasnt implemented in the new onboarding design cc @fbwoolf
> > 
> > 
> > I'm not sure why this is being reported here? This is behavior that already existed. We have never kept these views in sync. This is fine and a non-issue. We would have to more work with routing, not these onboarding changes, to keep views constantly in sync. If you check prod, it is the same.
> 
> Yes,while we have been redesigning the onboarding screen,was wondering if this can be made as an enhancement for future releases.Wanted your input from dev's point of view but guess will bring it to @markmhx input once he is here and move the ticket to merge.
