### ISSUE TITLE
Add "fund your account" screen

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#1479]
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/📏Spec?node-id=62%3A4511

related to #1478 

This screen would be replaced by the purchase flow (#1473 )if we decide to implement that.

- [ ] 'go' redirects user to the respective exchange
- [ ] 'view all' redirects to https://www.stacks.co/#trade-stx
- [ ] 'receive' opens the receive modal, or page if modal not implemented yet

![image](https://user-images.githubusercontent.com/28991/136796648-8a4d7beb-af22-4570-8e35-e4c7ab85d3ee.png)

**Comment by markmhx** [comment]
The Figma URL above doesn't appear to show the relevant designs here? https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec
