### ISSUE TITLE
Balance different between balances tab and send screen if tokens locked

### ISSUE THREAD

**Issue by whoabuddy** [leather-io/extension#1488]
Caught this today while making a transfer in `v2.12.0` from an account that's pooling STX.

On the balances screen, I see my unlocked balance:

![image](https://user-images.githubusercontent.com/9038904/126790666-d9246789-e703-4eb6-9b70-b483d0be4a94.png)

On the Send screen, I see the total balance:

![image](https://user-images.githubusercontent.com/9038904/126790814-033ecd21-3ca7-404a-bd8f-9b62c4b4166c.png)

The send `Max` button does nothing when I click on it, but the real kicker is that after I enter `5 STX` into the field, I get an error after clicking preview:

![image](https://user-images.githubusercontent.com/9038904/126791350-6b0a6f87-8e14-4568-b0a4-603f499c7784.png)

I tried this by following the same process without clicking max, switching accounts, and after logging out and back in with my secret key.

One thing I noticed, the negative balance might point to a math issue? The available balance shown is similar to `(total - available) - available`

- error `-65.609031 STX`
- available: `134.723 STX`
- total: `335.054851 STX`

Nothing to report in the console.

**Comment by Eshwari007** [comment]
Test passed,wasnt able to reproduce the issue from a pooling address

**Comment by markmhendrickson** [comment]
@whoabuddy are you still seeing this problem?

**Comment by fbwoolf** [comment]
> @whoabuddy are you still seeing this problem?

The PR fix for this has not been merged yet.
