### ISSUE TITLE
Broadcast error: "transaction rejected - TooMuchChaining"

### ISSUE THREAD

**Issue by GinaAbrams** [leather-io/extension#1490]
This is a first transaction I am doing today from this account. There are no pending txs to my knowledge, though the account was created and a failed name registration by someone else earlier. Not sure if this is expected behavior? Address: https://explorer.stacks.co/address/SP2EN86ACNBCTY58J0SJ22CB1ZJ592C2STDJ37HTZ?chain=mainnet

**Comment by friedger** [comment]
Duplicate to https://github.com/blockstack/stacks-wallet-web/issues/1482
