### ISSUE TITLE
Resolve infinite pending states for user with many usernames

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1499]
User is encountering an infinite spinner when loading their Account #1 with many domains already registered as well as infinite pending `name-preorder` and `name-register` transactions with the BTC app:

> On my first wallet where I have almost 1000 BTC domains I haven’t been able to login (here you will find the popup report you requested), please let me know if you need anything else. 
> 
>Then I opened 3 additional wallets so I could continue registering domains, but all of them got stuck and I have lost time and money. When I say “stuck” I mean that the domain pre-order or registration stays in “pending” mode and doesn’t resolve until the transactions fail. Please see pictures on the attached PDF. On the second wallet I was able to “preorder” 19 domains, then to find out that only 3 were successful and 16 were rejected. The transaction was dropped, which in turn means I lost the 2 STX for the pre-order. On the third wallet I preordered 6 domains and only 2 ended up successfully being registered prior to the system getting stuck, the rest are still pending. The forth wallet I was able to register only 1 domain then two domains got stuck/pending. 
>
>It seems that once 1 domain gets stuck, any preorder or register transaction after that also gets stuck. I was able to transfer STX from one account to another within the same wallet once the domains got stuck. 

<img width="1253" alt="Login error" src="https://user-images.githubusercontent.com/28991/127298564-45e7cd03-b463-4716-919d-9ff6f9a1aa44.PNG">

<img width="1325" alt="Screen Shot 2021-07-28 at 11 22 33" src="https://user-images.githubusercontent.com/28991/127298460-0535b26a-12d2-442b-a8d5-bd92a96d6e8a.png">
<img width="1359" alt="Screen Shot 2021-07-28 at 11 22 37" src="https://user-images.githubusercontent.com/28991/127298463-e16ce623-c59a-4ee5-8db2-22de4e820147.png">

cc @MarvinJanssen

**Comment by markmhendrickson** [comment]
@owenstrevor appears to be encountering a similar issue when trying to load the web wallet popup for sign in with a key that has ~100 accounts with usernames. The popup remains blank for quite a while and there are a ton of API calls:

<img width="633" alt="Screen Shot 2021-07-28 at 19 48 39" src="https://user-images.githubusercontent.com/28991/127475394-dbd462e1-e6a9-4003-a2fa-34ba7236e962.png">

Note that the above UI with "Choose an account" but without showing accounts is displayed _after_ a long wait when a completely blank screen is just shown.

**Comment by MarvinJanssen** [comment]
The same coincidentally happened to me. (Wallet with ~50 named accounts.) My guess is that some API calls fail which leads to an issue with transactions? (What if you are rate limited by the API when the Web Extension is trying to find the next nonce, for example?)

**Comment by icearc** [comment]
Hello,

This did not happened when the program was initially rolled out. I have opened several other wallets and it seems that if I register 2-3 or more domains at the same time the system produces errors and the domain registration somehow gets hanged up in a loop. With my initial wallet I was able to process +10 domain reserve/registrations and 10-20 internal STX transfers within accounts in the same wallet and the system worked well.

**Comment by andresgalante** [comment]
Possible solutions are:
- to paginate data for different accounts to reduce the number of API calls.
- infinite scrolling and calling only what's on view

**Comment by owenstrevor** [comment]
Still happening for me. Infinite scrolling would be a great solution, depending on how fast it is. If it takes 5 seconds to load each 10 accounts that would be really hard to scroll to the bottom and I would prefer pagination so I can jump to last. Pagination would be good if it's 10 per page, that way can easily jump to where you want to go.

**Comment by aulneau** [comment]
@owenstrevor @MarvinJanssen would you mind giving this build a try? https://github.com/blockstack/stacks-wallet-web/actions/runs/1105765699

you can read how to install it here https://github.com/blockstack/stacks-wallet-web#install-from-source
