### ISSUE TITLE
Ensure Secret Key display after user enters invalid then valid username value

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#150]
Onboarding reproduction:

1. Submit invalid username and see error message
2. Submit valid username and proceed to Copy Secret Key screen
3. Secret Key shows up blank

![image.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/b5e127d1-be4f-4058-b52e-3aa2fb4ce5cc)

**Comment by kyranjamie** [comment]
Can this consistently be replicated? I've tried a handful of things and have no been able to do so.

It'd be really great if we can get Sentry set up, to get better insights into less reproducable bugs. It might even be wise to get this done for wink release @markmhx ?

**Comment by markmhendrickson** [comment]
How fast is Sentry to set up? I'll try to replicate this one.

**Comment by markmhendrickson** [comment]
I'm unable to recreate the blank key issue as well so will close this out for now.
