### ISSUE TITLE
Registered btc domain names not showing

### ISSUE THREAD

**Issue by nanonerd** [leather-io/extension#1504]
Most of the BTC domain names that I registered show up. But a handful do not. Here is an example of one that is Confirmed for both Preorder and Register. When I open my web wallet, the name "mainevent" does not show. Instead the default "Account 30" still appears. 

QUESTIONS: Regardless of this bug where the name does not show up. I still own/control it, right? Any idea how to get it to show up in web wallet? Thanks.

Account:  SP34DZEJRNM64JA5T0ND8MNEB7KTEZY3D5F75S2Y

Preorder STX ID: https://explorer.stacks.co/txid/c2267b47e5c9cec76888ea4d06c561bf78a598336b79516725562ea9d09652d9?chain=mainnet
Preorder BTC block: https://www.blockchain.com/btc/block/00000000000000000001f965c2ee4d804eb6bd9f06cae77a6694f8a75b3a2cc4

Register STX ID: https://explorer.stacks.co/txid/fa7132b1767d24656f5ec3541a735f9e1e14ebd12e9c03386ff487fd61e5c814?chain=mainnet
Register BTC block: https://www.blockchain.com/btc/block/00000000000000000001f965c2ee4d804eb6bd9f06cae77a6694f8a75b3a2cc4

![image](https://user-images.githubusercontent.com/5571462/127483408-f43ed1da-c52d-4554-a71b-3c6b13bbe1d9.png)

![image](https://user-images.githubusercontent.com/5571462/127483445-b8b9ecb2-a70c-4851-b257-6c18b9f542ec.png)

**Comment by markmhendrickson** [comment]
I suspect we have a API retrieval, display or caching bug here. We'll investigate.

Your names should be owned by you if the transactions have confirmed.

**Comment by markmhendrickson** [comment]
This will likely get resolved by the deployment of code currently on the `develop` branch of the API. We should confirm this is indeed resolved once that code is deployed to production.
