### ISSUE TITLE
Unable to type spaces when entering secret key

### ISSUE THREAD

**Issue by whoabuddy** [leather-io/extension#1508]
Version: 2.12.4

When trying to enter a secret key on the screen below by manually typing it, I am unable to type a [space] between any of the words.

![image](https://user-images.githubusercontent.com/9038904/127556204-c2e837c1-499a-4c0e-8141-d6d790106809.png)

To reproduce:

1. Click Sign in wtih Secret Key
2. Try to manually type a key using spaces

Copy and paste works as expected.

**Comment by markmhendrickson** [comment]
I'm encountering the same problem:

![image](https://user-images.githubusercontent.com/28991/127639477-9510f95e-23c9-4eb5-a8cf-578a66af3fd5.png)

**Comment by 314159265359879** [comment]
Same problem here, it looks like some old code was introduced into the new wallet on the next screen I see mention of "Blockstack ID" and "Magic Recovery Code" or is that still used. Whatever password you type it is always wrong:
![image](https://user-images.githubusercontent.com/33360391/127753248-61ded560-e736-4717-948b-a4d11816ea33.png)

**Comment by 314159265359879** [comment]
![image](https://user-images.githubusercontent.com/33360391/127753277-8c76a22a-a8c0-4fe0-9362-b3f2ff028f9b.png)
