### ISSUE TITLE
README Add Extension for Firefox Fails to specify that manifest.json file is in dist/ directory.

### ISSUE THREAD

**Issue by qxotk** [leather-io/extension#1511]
Adding the web extension to Firefox requires selecting the `manifest.json` file for the extension.  This file is in the `dist/` sub-directory of the `stacks-wallet-web` directory, not in the project directory itself.

Suggested edit:
**Change:** _Select the `manifest.json` file._
**To:** _Select the `manifest.json` file from the `stacks-wallet-web/dist` directory._

**Comment by aulneau** [comment]
PRs welcome :)
