### ISSUE TITLE
404 errors appear in the wallet with an infinite spinner when trying to call the API

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#1514]
GET https://stacks-node-api-microblocks.testnet.stacks.co/v2/contracts/interface/ST297VG59W96DPGBT13SGD542QE1XS954X4ZSWW2J/demo-deploy-1627910690560?unanchored=true 404

GET https://stacks-node-api-microblocks.testnet.stacks.co/v2/contracts/interface/ST297VG59W96DPGBT13SGD542QE1XS954X4ZSWW2J/shiny-teal-snail?unanchored=true 404

GET https://stacks-node-api-microblocks.testnet.stacks.co/v2/contracts/interface/ST297VG59W96DPGBT13SGD542QE1XS954X4ZSWW2J/demo-deploy-1627910690560?unanchored=true 404
GET https://stacks-node-api-microblocks.testnet.stacks.co/v2/contracts/interface/ST297VG59W96DPGBT13SGD542QE1XS954X4ZSWW2J/shiny-teal-snail?unanchored=true 404

GET https://stacks-node-api-microblocks.testnet.stacks.co/v2/contracts/interface/ST297VG59W96DPGBT13SGD542QE1XS954X4ZSWW2J/demo-deploy-1627910690560?unanchored=true 404

GET https://stacks-node-api-microblocks.testnet.stacks.co/v2/contracts/interface/ST297VG59W96DPGBT13SGD542QE1XS954X4ZSWW2J/shiny-teal-snail?unanchored=true 404

GET https://stacks-node-api-microblocks.testnet.stacks.co/v2/contracts/interface/ST297VG59W96DPGBT13SGD542QE1XS954X4ZSWW2J/demo-deploy-1627910690560?unanchored=true 404

GET https://stacks-node-api-microblocks.testnet.stacks.co/v2/contracts/interface/ST297VG59W96DPGBT13SGD542QE1XS954X4ZSWW2J/shiny-teal-snail?unanchored=true 404

GET https://stacks-node-api-microblocks.testnet.stacks.co/v2/contracts/interface/ST297VG59W96DPGBT13SGD542QE1XS954X4ZSWW2J/demo-deploy-1627910690560?unanchored=true 404

GET https://stacks-node-api-microblocks.testnet.stacks.co/v2/contracts/interface/ST297VG59W96DPGBT13SGD542QE1XS954X4ZSWW2J/shiny-teal-snail?unanchored=true 404

<img width="1088" alt="Screen Shot 2021-08-02 at 9 29 28 AM" src="https://user-images.githubusercontent.com/49165468/127870919-83c12f32-8ae1-4a72-ab74-66c1c61d0af7.png">

**Comment by timstackblock** [comment]
This eventually works after closing out and coming back in several times.

**Comment by Eshwari007** [comment]
Attaching a video which is related to the API issue in Webwallet.Seems to be an issue only when the account has multiple token and contract calls.
https://user-images.githubusercontent.com/38872890/127871429-29f8d3d0-31e6-431f-89d8-20822dfe22e7.mov

**Comment by fbwoolf** [comment]
@timstackblock what is the best way for me to repro this?

**Comment by aulneau** [comment]
> > This eventually works after closing out and coming back in several times.
> 
> @timstackblock what is the best way for me to repro this?

this was likely fixed with https://github.com/blockstack/stacks-wallet-web/commit/bb046ee62c0be2bfca29fddba80c4bb54116ebf7

**Comment by fbwoolf** [comment]
> > > This eventually works after closing out and coming back in several times.
> > 
> > 
> > @timstackblock what is the best way for me to repro this?
> 
> this was likely fixed with [bb046ee](https://github.com/blockstack/stacks-wallet-web/commit/bb046ee62c0be2bfca29fddba80c4bb54116ebf7)

Ok, great, bc I can't seem to repro it! 😄

**Comment by timstackblock** [comment]
Video of the issue http://somup.com/crjDIAYNNb

We are waiting intermittently for several minutes for the balance screen to appear, this was fixed earlier but seems to come back.

<img width="1226" alt="Screen Shot 2021-08-16 at 9 02 29 AM" src="https://user-images.githubusercontent.com/49165468/129573047-4c9f15d0-ebcc-463e-81b3-ef79b664f35b.png">

**Comment by timstackblock** [comment]
The issue seems to be related to the wallet waiting for the contract deploy call which returns 404s in console.

<img width="449" alt="Screen Shot 2021-08-16 at 12 56 36 PM" src="https://user-images.githubusercontent.com/49165468/129605976-8fa01baa-4b3f-46ef-af53-7ed7846df5db.png">
<img width="190" alt="Screen Shot 2021-08-16 at 12 56 59 PM" src="https://user-images.githubusercontent.com/49165468/129605978-d247a681-0ec8-4638-88bf-8a299f23ccd8.png">
<img width="421" alt="Screen Shot 2021-08-16 at 12 58 56 PM" src="https://user-images.githubusercontent.com/49165468/129605979-3ddb57b5-5fb8-49de-8447-a8bab71b8883.png">

**Comment by timstackblock** [comment]
SUMMARY OF SCREEN SHOTS ABOVE

Tons of screenshots above but what I think we are seeing is the contract deploy call that is PENDING on the activity screen constantly fail in console and it appears to make the spinner run infinitely.

I can reproduce this by going to the test app and launching multiple contract calls, as you can see from the screen shot above in explorer my address has multiple contract calls pending. 

When I hit the API directly in the browser I get the message NO CONTRACT INTERFACE DATA FOUND as shown in the screen shot above. I believe this is because the contract is still in the process of being deployed. Once it is finished we get a success full return from the API via the URL using the browser directly.

While we are getting the 404s in console we see the wallet query struggle to return the balance screen and we see an infinite spinner.

**Comment by timstackblock** [comment]
<img width="1410" alt="Screen Shot 2021-08-16 at 12 52 52 PM" src="https://user-images.githubusercontent.com/49165468/129603546-960c8927-eaf0-4556-b81b-1bc6e3c6fc74.png">
<img width="11" alt="Screen Shot 2021-08-16 at 12 52 34 PM" src="https://user-images.githubusercontent.com/49165468/129603547-08b16fb4-c0dc-440e-85ef-adb336d43e0f.png">

**Comment by timstackblock** [comment]
<img width="1328" alt="Screen Shot 2021-08-16 at 12 51 26 PM" src="https://user-images.githubusercontent.com/49165468/129603548-d3f75ae2-3e45-4a17-a0fd-07b8c4a12bb3.png">
<img width="160" alt="Screen Shot 2021-08-16 at 12 52 25 PM" src="https://user-images.githubusercontent.com/49165468/129603549-e47c051a-1518-4501-b218-c7472d1d5156.png">
<img width="1342" alt="Screen Shot 2021-08-16 at 12 51 20 PM" src="https://user-images.githubusercontent.com/49165468/129603551-c3694f9d-9f47-4597-9362-efdb7b90d094.png">
<img width="616" alt="Screen Shot 2021-08-16 at 12 51 07 PM" src="https://user-images.githubusercontent.com/49165468/129603554-c7b21216-2328-4d8d-b686-0d25caadbdac.png">

**Comment by timstackblock** [comment]
It appears to takes a while for the API to return data for the contract deploy which results in errors

<img width="632" alt="Screen Shot 2021-08-16 at 12 52 38 PM" src="https://user-images.githubusercontent.com/49165468/129603544-2538a8c5-891a-4ffc-a61c-97f27c7bca7a.png">
<img width="1410" alt="Screen Shot 2021-08-16 at 12 52 52 PM" src="https://user-images.githubusercontent.com/49165468/129603546-960c8927-eaf0-4556-b81b-1bc6e3c6fc74.png">

<img width="1425" alt="Screen Shot 2021-08-16 at 12 53 53 PM" src="https://user-images.githubusercontent.com/49165468/129605894-82571543-89ad-4db9-9485-3dfe9041876b.png">

**Comment by fbwoolf** [comment]
@beguene @kyranjamie Thomas's branch did not end up fixing this bug. After rebasing and testing from the build, the issue was still present. It also started appearing for me running it locally. I did try to debug it on main after, but I didn't end up surfacing anything. The error does seem to be coming from `contractInterfaceResponseState` on `smartContractsApi.getContractInterface` but I can't seem to track down how to prevent the loading state. Hoping one of you has better luck tomorrow!

**Comment by beguene** [comment]
Thanks @fbwoolf, this is helpful. I am working on it.
cc @kyranjamie
