### ISSUE TITLE
Rocket token being displayed in explorer when it was STX token which was send

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1515]
Use case 1-Two accounts with two separate secret keys

User send 1 STX from  account 1 to another account (that has different secret key)
User selects the activity tab and notices STX -1(accurate)
User then selects the transaction,notices its indicates as -1 RTO in explorer which is inaccurate as its not Rocket token which was send

<img width="1259" alt="Screen Shot 2021-08-02 at 9 48 13 AM" src="https://user-images.githubusercontent.com/38872890/127872722-17744598-127c-45a3-9a3f-186fac0d5ac0.png">

Use case 2-Two accounts with same secret keys
If STX is send between two accounts that has the same secret key,this seems to work correct where the activity tab selection to explorer displays accurate 1 STX being send between the two account
<img width="1236" alt="Screen Shot 2021-08-02 at 9 55 40 AM" src="https://user-images.githubusercontent.com/38872890/127873204-5ab44983-a288-43dc-b303-7d0341f399ae.png">

**Comment by aulneau** [comment]
@Eshwari007 can you record a video of the process that results in the stx/rocket confusion?

Looking at your activity feed, I see the 1 stx transfer is this https://explorer.stacks.co/txid/0x41d068dcb11cef905c69532e880096746c8a4226321cf65cb34d8874e8ac4dfe?chain=testnet. I think the rocket tx you're seeing is a completely different transaction (and would not be displayed on the list as any value of tokens)

**Comment by aulneau** [comment]
Looking through your transactions, I see nothing wrong here:

![Screen Shot 2021-08-02 at 9 02 03 AM](https://user-images.githubusercontent.com/11803153/127873948-e09e1fa4-f603-4fcc-89b3-d5ccf9101477.png)

Is it possible you clicked on the transactions in a different order than you expected?

**Comment by Eshwari007** [comment]
@aulneau Looking into it as I did noticed that the account which I transferred the STX is empty.I took a second look at the address and you are correct,this maybe user error and am glad it was .Will close the ticket as the transaction above had different contract details.Found another issue related to this one,will create the ticket accordingly.Thank you for your input
