### ISSUE TITLE
Track user activity to better calculate nonce

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#1516]
In addition to using the new endpoint for calculating nonce, we also need to persist some activity locally. We could even just increment a nonce value and persist it to local storage, or have an array of nonce. I'd look at the implementation of the new api endpoint to think about how best to save data. This is important because a lot of the issues around nonces has to do with when the network is unstable.

**Comment by GAD2511** [comment]
I've called the boombox contract and the tx shows 10 nonces, but my account shows 9 as the next nonce.
Not sure how that can be fixed using the extension. 
https://explorer.stacks.co/txid/0x0a78ab144e64397b980f23be157ee66126fe14eb9e557cde5d5cadb9457278f1?chain=mainnet

Would you take a look at it, please?

**Comment by markmhendrickson** [comment]
Related: https://github.com/blockstack/stacks-wallet-web/issues/934

@GAD2511 We may have resolved your particular instance with this PR, which we'll release shortly: https://github.com/blockstack/stacks-wallet-web/pull/1530

**Comment by aulneau** [comment]
> Related: #934
> 
> @GAD2511 We may have resolved your particular instance with this PR, which we'll release shortly: #1530

Just a note -- this is blocked by the microblocks API deployment and will not be live before that is deployed. (unknown ETA on that)

**Comment by GAD2511** [comment]
So why is this happening to my address? I call this https://buy.syvita.org/ contract rn by https://explorer.stacks.co/txid/543187434cd911b7542583dc515a437ca5e4cbe2bdf17e69c01ee633db80faae?chain=mainnet and I can see the same issue. My account is showing 9 nonce while the tx is showing 1. Despite I update the web wallet and refresh the syvita page

**Comment by andresgalante** [comment]
Close in favor of https://github.com/blockstack/stacks-wallet-web/pull/1726
