### ISSUE TITLE
Better handle localhost check in console logs

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1526]
The console log always reports an error with localhost when there isn't a localnet running:

![image](https://user-images.githubusercontent.com/28991/128049220-444ac1e0-75c7-45e5-896d-6fe84c25d529.png)

Could / should we catch this so it doesn't show and perhaps confuse the user by indicating (incorrectly) that something is wrong?

This is perhaps a nit, but it comes up sometimes with customer support.

**Comment by aulneau** [comment]
This is expected, there is no way to hide this response.

**Comment by aulneau** [comment]
closing as this is expected
