### ISSUE TITLE
Prevent "copy address" tooltip from getting pushed rightwards by the username

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1527]
It should stay flush to the right-side of the copy button:

<img width="413" alt="Screen Shot 2021-08-03 at 18 22 40" src="https://user-images.githubusercontent.com/28991/128051351-f8afc872-9594-4fb9-8e19-6b34c2c79ad3.png">

**Comment by fbwoolf** [comment]
@markmhx in reproing this issue it seems like the tooltip in general has really inconsistent behavior, do you see the same? Sometimes I see the `Copied` tooltip but sometimes I don't. The `Copy address` sometimes appears but won't go away. Do you experience the same?

**Comment by fbwoolf** [comment]
Nvm, I think this was perhaps a local Chrome issue but let me know if you run into it. I was able to fix it fine in Brave.
