### ISSUE TITLE
My STX Address has 4 pending TX that seem to not resolve after over 16 hours (possible bad Nonce)

### ISSUE THREAD

**Issue by kcdenman** [leather-io/extension#1528]
Using Stacks Web Wallet (Chrome)
version v2.12.4

STX Address: SP3G4TRKSQ01TC5BNBS6DEBB3R2FEW0VPSCBP9676
Problem TX: 0x52cac91439f10337cf7a66ef578aae6f4b1bef99135ee2f4b4a0893bf9dff993

![image](https://user-images.githubusercontent.com/10832542/128075261-46b1f1a3-3908-4ad4-a3c4-880a1ce5c549.png)

A total of 4 TX are stuck in "Pending", but when I look at my STX Address on the explorer, the pending transactions are not there.

![image](https://user-images.githubusercontent.com/10832542/128075377-7b06086b-fc04-453a-9464-7104e1d88277.png)

I've been told it looks like I have a "bad nonce" but I do not know what that means.

**Comment by markmhendrickson** [comment]
I suspect you've encountered the issue reported here: https://github.com/blockstack/stacks-wallet-web/issues/934

We are working to resolve it. Please subscribe to that issue for updates. I'll close this one to keep things organized.
