### ISSUE TITLE
Pending symbol inconsistent between explorer and web wallet

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1531]
Web wallet version v2.12.4.152
User notices when there a bunch of other tokens,contract deploy and STX transaction being in Pending state,the symbol or the base component is not indicating the similar pending symbol as updated in the Explorer.
Attaching the screen shots of both Explorer transaction in Pending state along with Web Wallet in Pending state
Look and Feel -Visual wise we need to be consistent so that it doesnt confuses the user is my opinion.
<img width="763" alt="P1" src="https://user-images.githubusercontent.com/38872890/128192891-aabe685d-ec8f-401f-ac78-ec3240499a44.png">
![P2](https://user-images.githubusercontent.com/38872890/128192892-04216dd9-7b30-4631-985e-b6203d04c244.png)

**Comment by jasperjansz** [comment]
I'm closing this in favor of more specific issues for standardizing activity across our products
