### ISSUE TITLE
Lots of accounts - painfully slow

### ISSUE THREAD

**Issue by nanonerd** [leather-io/extension#1534]
Hi, I ran into issue when I added a 280 accounts to the web wallet. It runs painfully slow now. 

I don't know at what point it starts to slow down noticeably ... probably somewhere between 150-200. At first, I thought maybe the blockchain was getting a lot of activity so it was causing the lag. I was hoping things would settle and the speed would return. So I kept adding accounts. 

At the moment, on "bts.us" site, to go through the entire process of 1) Sign In  2) Preorder  3)  Register, it takes about 10 min. There is a bad lag at each step. 

I finally decided to create a new wallet and things are working very fast. So now I know it is not because the blockchain is getting bogged with activity. It must be the large number of accounts in my wallet causing the bad lag. 

1) Any way of improving performance as an enhancement for a future release?
2) In the meantime, if you are able to reproduce issue, then you might want to limit each wallet to (e.g., 150) accounts or display a warning message when the user gets to this number, etc.

Cheers !

**Comment by aulneau** [comment]
@nanonerd would you mind giving this build a try? https://github.com/blockstack/stacks-wallet-web/actions/runs/1105765699

you can read how to install it here https://github.com/blockstack/stacks-wallet-web#install-from-source

**Comment by nanonerd** [comment]
@aulneau - Hi, sorry for the delay. I am on travel and just got some time to try your build. I removed the existing web wallet (BRAVE browser) and ran your build per the github link instructions. 

Unfortunately, there is still a long delay when I try to SIGN IN on "bts.us". It does say "Hiro Wallet v2.12.4.742" so I am running your wallet build. Also, it takes a super long time for the domain names to appear. It shows "Account 1", "Account 2", etc for a very long time.  :-(

P.S., can you please REOPEN this ticket so that it remains on your radar, etc.? Thanks.

**Comment by Eshwari007** [comment]
@nanonerd I have tested with ~151 accounts on the web wallet.
So far test results are good and isnt painfully slow.
It does take a sec or two to load the activity and balance tab once the number of accounts grows but its not more than a two seconds so far.
Do let me know if the fix has resolved your issue 
cc @aulneau

**Comment by nanonerd** [comment]
@Eshwari007 - is this the build that I should test with?  #1572?

https://github.com/blockstack/stacks-wallet-web/actions/runs/1136793634

**Comment by Eshwari007** [comment]
@nanonerd Yes Clean up more network fetches, adds persistence #1572 will be the place to download the extension and test the issue.Do ping if you have any issues.Thanks

**Comment by aulneau** [comment]
@nanonerd if you'd like to try another build, https://github.com/blockstack/stacks-wallet-web/actions/runs/1160038537 this should hopefully improve your performance!

**Comment by nanonerd** [comment]
@aulneau - I tried your latest build. It seems to be good. I didn't actually purchase another domain but it brings up all accounts (even this part was slow) and I can click around pretty good. So hopefully, the rest is good. Thanks a lot! 

Also, I see in this build, you guys fixed my other issue where some domain names were not displaying. So that is great. 

QUESTION: when will this build go to production? Also, do I have to manually upgrade to new version or does the HIRO wallet silently update behind the scenes? Thanks a bunch !

**Comment by aulneau** [comment]
Awesome, that is great to hear! we are just wrapping up some final QA on it, and will be trying to do a release later today. You'll have to re-add the extension from the browser store for it to auto update. I'll comment here when it's been released and is available.
