### ISSUE TITLE
Add decimal number validation for amount field in send form

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#1536]
Unlimited amount of digits can be put in the amount field, when the user hits submit the number runs off the screen.

<img width="471" alt="Screen Shot 2021-08-05 at 4 50 44 PM" src="https://user-images.githubusercontent.com/49165468/128419581-244f4728-f19c-4104-882a-e2c7b9d14d88.png">

<img width="518" alt="Screen Shot 2021-08-05 at 4 50 31 PM" src="https://user-images.githubusercontent.com/49165468/128419589-09502e36-994e-4995-8156-09cffce394af.png">

**Comment by timstackblock** [comment]
@fbwoolf this is happening in the prod build as well

**Comment by kyranjamie** [comment]
We should add validation for the number of decimals used here. [This is how it's done in desktop wallet](https://github.com/blockstack/stacks-wallet/blob/7157802488f8860e15735c46d92b84ebe307add6/app/utils/form/validate-decimals.ts#L3-L15)

**Comment by markmhendrickson** [comment]
Is this type of validation suitable given @aulneau's comment [here](https://github.com/blockstack/stacks-wallet-web/issues/1538#issuecomment-893837983) about how any number of decimals is possible for a given token? If so, perhaps we should simply apply a CSS rule to prevent the run-off (e.g. by adding ellipses).

**Comment by kyranjamie** [comment]
We can definitely add for STX, and SIP-10 tokens, though. Perhaps this issue can be scoped to those, and adding an ellipsis. 

Indeed, others would need to have this validation disabled. Or, should we still set an upper bound? Do we allow 1,000 decimal places? 🤷🏼

**Comment by aulneau** [comment]
> We can definitely add for STX, and SIP-10 tokens, though. Perhaps this issue can be scoped to those, and adding an ellipsis.
> 
> Indeed, others would need to have this validation disabled. Or, should we still set an upper bound? Do we allow 1,000 decimal places? 🤷🏼

It is the case currently that a user is only ever presented an option to transfer an asset if they are STX or conform to the SIP10 standard, so we can easily validate the input against the known decimal units.
