### ISSUE TITLE
Decimal point varies between tokens

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1538]
PR:https://github.com/blockstack/stacks-wallet-web/issues/1519

Decimal points seems to vary between STX and other token s
<img width="341" alt="Screen Shot 2021-08-05 at 5 59 07 PM" src="https://user-images.githubusercontent.com/38872890/128426795-120ee525-a251-4c40-b1e1-2bd0738a5c72.png">
uch as Stella.Shouldnt all of the token needs same decimal points after the whole number?

**Comment by aulneau** [comment]
this is expected -- tokens can have any number of decimal places, there is no standard when it comes to how many. it is defined by the contract that creates the token. I'm going to close this issue
