### ISSUE TITLE
Sending different types of token in Mainnet throwing error

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1539]
PR:https://github.com/blockstack/stacks-wallet-web/issues/1519
User was trying to send Wrapped Nothing v8 token to another account in mainnet however ,the transaction didnt go through and reported something went wrong

https://user-images.githubusercontent.com/38872890/128428247-bb36cbd3-9b69-42c9-9977-d0baea45d6ab.mov

**Comment by kyranjamie** [comment]
Unable to replicate. I tried a handful of transactions on testnet and they seem to have gone through okay. (This PR doesn't have any mainnet-specific functionality)

**Comment by Eshwari007** [comment]
Agree the PR may not be the cause of the issue but will try to retest again

**Comment by Eshwari007** [comment]
Retested the issue in a later version extension.
The issue is not reproducible.
