### ISSUE TITLE
Submit sign in form when user hits enter key

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#154]
Instead of adding new line to textarea

![image.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/3d848574-8063-47c1-bb4b-03e835fe1549)

**Comment by timstackblock** [comment]
I cant get to this screen the link to enter your own secret key is not clickable

VIDEO OF BUG
http://somup.com/cYntIUhOzl

Let me know if something has changed that I am not aware of in a use case, the video link is above

**Comment by markmhendrickson** [comment]
@timstackblock I assume you're good now that we synced yesterday about which app to use for testing, yea?

**Comment by timstackblock** [comment]
This works as expected
