### ISSUE TITLE
Reconsider Firefox app bundling

### ISSUE THREAD

**Issue by kyranjamie** [leather-io/extension#1546]
App developers themselves may well be working with the production wallet build. We want them to be able to debug issues with their app, or the wallet, as easily as possible.

Currently we minify/obfuscate the Firefox production build. See these two examples of errors thrown when you omit the `appIcon` prop from the object passed to `showConnect`.

![image](https://user-images.githubusercontent.com/1618764/128707300-1d40f7a1-5688-4f50-834c-0b5979bfde1c.png)

We should disable the minification altogether, or find another way to retain rich error information.

**Comment by LNow** [comment]
Although I can understand reasons behind minifing code, the way it has been done can drive dapps developers nuts.

All errors should be easily accessible no matter which browser we use.
