### ISSUE TITLE
Conflicting nonce issue / perpetual "pending" 

### ISSUE THREAD

**Issue by exploriter** [leather-io/extension#1556]
I have tried to follow #934 and #1342 and have updated to `v2.12.5` but this has not fixed the problem.

I'm attempting to send STX from one of my accounts to another, here's the most recent `txid` as an example: `0xa1d005a1fb6caad2f0b379d3d082050a38d29b6311e5a11ac0e096fd1245e12a`

I tried 3 times with 2 different addresses to a single address on `v2.12.4` prior to updating. Then I updated and tried a 4th time (with the `txid` listed above). Note: The _pending_ queue from the previous attempts was (and is) still listed under **Activity** (I don't know how long that takes for those to disappear, it's been 18+ hours so far).

**Comment by morser2017** [comment]
Have same issue.  Started with web wallet.

**Comment by exploriter** [comment]
Someone is asking for more info, it's really quite straightforward:

- Open up the web wallet (`v2.12.4`)
- Switch account (from my main address to an alt)
- Send STX from that alt address to my main address
- Activity shows txid `0xc7744c73014d7ee15c8bd139aa5b10a415fd11644afce1b777e15aee5b1ef338`
- Repeat for a second alt address to my main address with a txid of `0xd5c9384382f81c94af98da8134393ddfec4f89292429596e1f1309fc87d1d6f1`
- Wait 4 hours and still "pending"
- Signed out and back in
- Tried another transaction, txid `0x12d1e96a0c720077b84a869524928bf63c4d9f835d4e06aef0011a4af9db5a94` ...still stuck in "pending"
- Signed out again, updated to `v2.12.5` and signed in again
- All the previous 3 transactions are still in the Activity list and show "pending"
- Tried yet another, txid `0xa1d005a1fb6caad2f0b379d3d082050a38d29b6311e5a11ac0e096fd1245e12a` and it has been pending for about 3 hours

**Comment by morser2017** [comment]
Pending transactions. Web wallet address and Desktop wallet address are the same.
1. 0xc909936ea755166bb8e0a2c331a52bbd9356060eff52d4bb3b5c4b879ae40e81   
2. 0x39648b742be62c6ee451d27fb6a62f4e74e25801eea6d73febb37d1a1e73fed8  `signed out/in
3. 0x08dee51ebc7a00950f2c65b92edd344e980d2f5ca0d17692370b30c482e5f72e  `reinstal extension
4. 0xd0369b7f88a5467478d2b57cd62f1422be09e828156e597583df0b05b4a9ac32  `from another web wallet address to desktop wallet address.

! Web wallet shows previous STX ballance. Desktop wallet shows 0 STX balance.
https://discord.com/channels/621759717756370964/625538774230892545/874646086185259028

!!  This transaction was successfully received from @asteria as "non bad nonce wallet"    

0x8afd8ea7d04be4aa01083f6707315b5e27be5acb51e252dc5da9ea3832299238

[https://explorer.stacks.co/txid/0x8afd8ea7d04be4aa01083f6707315b5e27be5acb51e252dc5da9ea3832299238?utm_source=stacks-wallet&chain=mainnet](url)

**Comment by markmhendrickson** [comment]
@gigawatson Thanks for this detailed report. 🙏 

I see on [your address page](https://explorer.stacks.co/address/SP2VMW797RBA6BDP9HMYDZ4T7DPJFWR1VK2MMC0CH?chain=mainnet) that [the last confirmed transaction](https://explorer.stacks.co/txid/0x6fc028c0818044429ce78ad75d602da6a00ad924a1563d06411a47fb92855c3f?chain=mainnet) has nonce `2`, yet the three subsequent attempts you've indicated ([1](https://explorer.stacks.co/txid/0xc7744c73014d7ee15c8bd139aa5b10a415fd11644afce1b777e15aee5b1ef338?chain=mainnet), [2](https://explorer.stacks.co/txid/0x12d1e96a0c720077b84a869524928bf63c4d9f835d4e06aef0011a4af9db5a94?chain=mainnet), [3](https://explorer.stacks.co/txid/0xa1d005a1fb6caad2f0b379d3d082050a38d29b6311e5a11ac0e096fd1245e12a?chain=mainnet)) that have remained pending have nonces `27`,`28` and `29`.

I believe we had an issue before (resolved in the latest release – v2.12.5) in which nonces were getting confused between various accounts in the extension. Had you previously sent transactions from other accounts / addresses from within the extension itself?

In any case, I would recommend waiting until all three of these transactions fail / leave pending state. Then initiate another transaction using the v2.12.5 wallet. Presumably this third pending transaction incorrectly used nonce `29` because the other two were still pending.

**Comment by markmhendrickson** [comment]
@morser2017 Your situation appears similar in that I'm also seeing these first three pending transactions sent from [your address](https://explorer.stacks.co/address/SP3QC4R6M7M0DAZBXSZCW4FWGDCNDD05FV8Y0AY8C?chain=mainnet) as using nonces `27`, `28` and `29` despite `2`, etc. having been expected. There may be something about that pattern. The fourth (received) transaction also has nonce `28` when `2` is expected, so it may be experiencing a similar issue.

Can you confirm you've upgraded to v2.12.5? As with @gigawatson's case, if any of the first transactions were initiated with a previous version, I'd suggest waiting until all pending transactions fail, then attempt to resend with v2.12.5.

**Comment by morser2017** [comment]
Can you provide info on this ?
 Web wallet shows previous full STX ballance. Desktop wallet shows 0 STX balance.
https://discord.com/channels/621759717756370964/625538774230892545/874646086185259028

**Comment by markmhendrickson** [comment]
@morser2017 Can you provide screenshots here of both wallets? This is for the following address, correct?

https://explorer.stacks.co/address/SP3QC4R6M7M0DAZBXSZCW4FWGDCNDD05FV8Y0AY8C?chain=mainnet

**Comment by morser2017** [comment]
https://cdn.discordapp.com/attachments/625538774230892545/874646207635529778/unknown.png

https://cdn.discordapp.com/attachments/625538774230892545/874646299968942140/unknown.png

**Comment by markmhendrickson** [comment]
Can you click "Receive" in the desktop wallet and provide a screenshot of what you see in the modal appears? I suspect you might have a different address loaded there since I don't see a confirmed 667.9201 STX transaction on the address page for `...AY8C`

**Comment by morser2017** [comment]
![image](https://user-images.githubusercontent.com/47498543/129024928-2de93947-279b-46b5-ad30-0d3eff36b2d5.png)

**Comment by exploriter** [comment]
@markmhx 

>Had you previously sent transactions from other accounts/addresses from within the extension itself?

Yes, but in reverse—from my main address to newly created ones (same 2 alts listed here; [eg](https://explorer.stacks.co/txid/0x07fe88acf010a8f33c82af8c1fccf5e427a4df0e2c85a0e49a28c8fcdbf6809a?chain=mainnet).)—without issue.

Will try again once these pending transactions cancel.

**Comment by morser2017** [comment]
Balance in Desktop Wallet Resumed. 

Thank you !

**Comment by exploriter** [comment]
And after letting the pending transactions clear... all is well with sending between accounts.

Going to close this. Thanks for taking a look, @markmhx!
