### ISSUE TITLE
[2.12.5] No scrolbar when selecting wallet account

### ISSUE THREAD

**Issue by 314159265359879** [leather-io/extension#1566]
![image](https://user-images.githubusercontent.com/33360391/129090887-b7075127-8c00-49d1-b799-6a5f88020b4a.png)

I used to get a scrollbar to select account 6 and beyond, this is on both Chrome and Firefox /Windows 10.

**Comment by markmhendrickson** [comment]
We just pushed a fix for this, which is live in Firefox but not Chrome quite yet. Mind retesting in Firefox after confirming that version v2.13.0 is installed?

**Comment by 314159265359879** [comment]
> 
> 
> We just pushed a fix for this, which is live in Firefox but not Chrome quite yet. Mind retesting in Firefox after confirming that version v2.13.0 is installed?

I just checked, the scrollbar is Firefox is back! thanks for the quick fix!
