### ISSUE TITLE
Change STX icon to purple version

### ISSUE THREAD

**Issue by ginny-d** [leather-io/extension#1568]
Currently, the STX token is displayed in the black version: 

<img width="394" alt="Screenshot 2021-08-11 at 18 51 1" src="https://user-images.githubusercontent.com/78865845/129070806-66be76da-0848-44c0-9516-4783a35c3fb0.png">

This is the version used generally for Stacks (the network) logos. For the token, we use the purple version, which is currently also being used on most exchanges:

<img width="394" alt="Group 5485" src="https://user-images.githubusercontent.com/78865845/129070931-f663c46e-56b0-4b7d-8ead-885c682b4fa7.png">

SVG file: https://www.dropbox.com/s/3phlquwhrj8vbee/stx-icon.svg?dl=0

Thanks

**Comment by fbwoolf** [comment]
@eugeniadigon should this be purple too?

![image](https://user-images.githubusercontent.com/6493321/129404876-701f6ebb-6e2f-490d-abc2-2cbb9b670591.png)

**Comment by fbwoolf** [comment]
I updated it bc I believe it is correct, see the linked PR for images.

**Comment by Eshwari007** [comment]
Tested the issue in PR #1578 ,the issue seems to be fixed.
