### ISSUE TITLE
Fix error upon sign in redirect for existing ID

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#157]
I encountered this only once and wasn't able to create.

When signing in with my existing Blockstack ID (markmhendrickson.id) for the first time with https://www2.winkdating.app/, the popup closed and redirected the parent window to the following broken URL:

![Screen Shot 2020-02-17 at 11.45.06.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/bdaeff3a-62f8-43a8-92eb-b6f99b4f1e03)

@timstackblock can you try recreating with an existing paid ID you have available?

**Comment by markmhendrickson** [comment]
Let's default the `redirectTo` parameter to the app domain index.

**Comment by hstove** [comment]
Issue moved to [blockstack/connect #58](https://github.com/blockstack/connect/issues/58) via [**ZenHub**](https://www.zenhub.com/)
