### ISSUE TITLE
Fix support for StacksRegtest

### ISSUE THREAD

**Issue by hecool108** [leather-io/extension#1575]
Hey guys: 

I was trying to run a contract call by 'openContractCall' like this:
No matter I set the param to **StacksTestnet** or **StacksRegtest**, the popup window will always point to **testnet**.

I had a look at stacks-wallet-web source code, and I found there is no support for StacksRegtest yet, 
only **StacksMainnet** and **StacksTestnet**. 

<img width="1224" alt="Screen Shot 2021-08-12 at 10 16 27 PM" src="https://user-images.githubusercontent.com/5652583/129300065-f109c30a-2326-43bd-9790-ededb0f4b8c3.png">

Hope the new version will support StacksRegtest soon, cuz the testnet is very slow now.

**Comment by aulneau** [comment]
The wallet does support regtest. If you set the url to regtest it will persist. Regtest is a different version of testnet, as such the chain id (testnet) is the same, but the coreApiUrl is different.

Hope this helps.

**Comment by JBotwina** [comment]
so should we set coreAPIURL like network.coreApiUrl = 'https://stacks-node-api.regtest.stacks.co';

**Comment by JBotwina** [comment]
Hey @aulneau, we made a change to the web wallet, setting the network.coreApiUrl to regtest link above and running a modified version of the wallet. This works, and we are able to use our Regtest balances and deploy contracts to RegTest. 

But are your saying that we should set the coreApiUrl to regtest in our app?

**Comment by pseudozach** [comment]
I've opened another issue before seeing this because it's not possible to set coreApiUrl, it's read-only.
I'm not clear how it's possible to use regtest/mocknet or any other network than mainnet/testnet.

**Comment by kyranjamie** [comment]
@JBotwina @pseudozach can you elaborate what you're doing run the wallet on regtest?

Can you not select it from the list? 🤔 

![image](https://user-images.githubusercontent.com/1618764/129858038-bc36194e-2cd5-4796-8e76-452b4021e180.png)

**Comment by pseudozach** [comment]
For me, localnet is selected. It makes no difference.
Another interesting thing is I have two front-end apps. Vue.js one works great, it can talk to localhost:3999 but react app always uses testnet. No matter what I use while calling the contract from the app.

**Comment by markmhendrickson** [comment]
@andresgalante it appears we have a bug related to StacksRegtest as reported here and StacksMocknet here: https://github.com/blockstack/stacks-wallet-web/issues/1590

**Comment by pseudozach** [comment]
Update: When I set `const mainnet = new StacksMainnet();` in openContractCall options, it actually tries to fetch the contract from mainnet.
But when I set `const mocknet = new StacksMocknet();` it tries to fetch the contract from testnet.

Note that there's no way to set coreapiurl on `const testnet = new StacksTestnet();` because it has been set to readonly recently.

**Comment by kyranjamie** [comment]
> Note that there's no way to set coreapiurl on const testnet = new StacksTestnet(); because it has been set to readonly recently.

[By design.](https://github.com/blockstack/stacks.js/issues/895) You now pass an object with a url parameter to the constructor, so it's immutable. `const testnet = new StacksTestnet({ url: 'https://' });`

**Comment by pseudozach** [comment]
> > Note that there's no way to set coreapiurl on const testnet = new StacksTestnet(); because it has been set to readonly recently.
> 
> [By design.](https://github.com/blockstack/stacks.js/issues/895) You now pass an object with a url parameter to the constructor, so it's immutable. `const testnet = new StacksTestnet({ url: 'https://' });`

yes I had tried that. in this case, this also doesn't help. wallet still tries to fetch from testnet.
