### ISSUE TITLE
Stacks  do not show up in the balance section of the wallet. RELEASE BLOCKER

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#1579]
@zone117x 
@aulneau 

VIDEO OF THE ISSUE http://somup.com/crjIrqYMm9

STX totals no longer show on the balance screen we see other assets but not STX

<img width="396" alt="Screen Shot 2021-08-13 at 5 27 29 PM" src="https://user-images.githubusercontent.com/49165468/129420084-b1bf0b4e-f80f-4c28-9fae-996c618eae6c.png">

When you go back to the balance page it will be an all white screen

<img width="401" alt="Screen Shot 2021-08-13 at 5 19 33 PM" src="https://user-images.githubusercontent.com/49165468/129420134-045b3d20-3426-48ae-8fc3-f3700b61aca2.png">

**Comment by timstackblock** [comment]
This is a release blocker something has broken from the last version we can no longer see the balance of STX in the web wallet

THE BALANCE SHOULD SHOW 19.99 STX

<img width="396" alt="Screen Shot 2021-08-13 at 7 08 33 PM" src="https://user-images.githubusercontent.com/49165468/129426091-8bde47b2-8e6b-404b-8263-b90602b33123.png">
<img width="1407" alt="Screen Shot 2021-08-13 at 7 08 20 PM" src="https://user-images.githubusercontent.com/49165468/129426092-f3624805-0c1d-4e73-ac1d-44e482f91b16.png">
<img width="390" alt="Screen Shot 2021-08-13 at 7 07 45 PM" src="https://user-images.githubusercontent.com/49165468/129426094-d9b18f64-4647-4865-bb8f-8c7d9765d787.png">

**Comment by aulneau** [comment]
Can you confirm which branch you're using ?

**Comment by timstackblock** [comment]
Sorry I am testing this branch https://github.com/blockstack/stacks-wallet-web/pull/1430

**Comment by markmhendrickson** [comment]
@kyranjamie should I assign this to you?

**Comment by beguene** [comment]
@markmhx I have already fixed it in the microblock branch
https://github.com/blockstack/stacks-wallet-web/pull/1430

**Comment by beguene** [comment]
@timstackblock This is fixed now

**Comment by Eshwari007** [comment]
Issue has been fixed.
Closing the ticket
