### ISSUE TITLE
Fix margin styles on password screen upon Magic Recovery Code entry during sign in

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#158]
![Screen Shot 2020-02-17 at 11.48.41.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/328ebe91-a1a5-4e66-9739-e6e26cbcfa47)

**Comment by timstackblock** [comment]
Padding has been added in between the button and the box above.

@markmhx  does this look better?

<img width="439" alt="Screen Shot 2020-02-17 at 2 15 52 PM" src="https://user-images.githubusercontent.com/49165468/74680912-06d53d00-5190-11ea-8447-e1beb14e58c0.png">

**Comment by markmhendrickson** [comment]
Assigning over to @jasperjansz to check the details

**Comment by markmhendrickson** [comment]
@timstackblock although in your screenshot is the username modal not the password one?

**Comment by timstackblock** [comment]
Wrong screenshot, here you go

<img width="440" alt="Screen Shot 2020-02-17 at 2 40 46 PM" src="https://user-images.githubusercontent.com/49165468/74682253-8284b900-5193-11ea-84d1-be8a1bf24bd2.png">
