### ISSUE TITLE
Resolve query performance issues related to many accounts

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1584]
PR:https://github.com/blockstack/stacks-wallet-web/pull/1572

https://user-images.githubusercontent.com/38872890/129623014-d6760470-3df4-49f9-8386-b7d97a2ca0a8.mov

Creating new accounts when it crosses 90 and above,notice some inconsistent patterns.
Either the new account create message vanishes by itself before the user selects done or it doesnt get populate at all.
I have a recording where the message box doesnt populate at all but could not reproduce the message vanishing within few seconds by itself.
Will attach the recording during my retest

**Comment by markmhendrickson** [comment]
It's not clear to me that there's anything happening differently above 90 accounts here. The API just appears to respond a bit more slowly during some of the subsequent requests upon creating more?

It seems like there'd be a connection with the number of accounts only if more queries are getting generated / we're querying data for accounts other than the one just created here.

**Comment by Eshwari007** [comment]
@markmhx Yes,after 90 or so accounts,it seems a little slow activity to create a new account.
One use case where I have 150 accounts and few accounts with large data and few with less data,the large data accounts are taking extra few sec longer to be populated than the less data account.This however isnt the issue when we have only abt 5 accounts with combination of large and small data in all 5 accounts.

**Comment by markmhendrickson** [comment]
@beguene Want to post the thoughts you shared with me during our 1:1 today here as a comment about modifying the querying / state behavior to avoid performance issues like the one captured here?

@kyranjamie ditto here for you seeing the chatter in Discord around this.

**Comment by beguene** [comment]
Yes, we will most likely be modifying the way we fetch resources and decouple it with the state management + fetch only the resource we need for the selected account. I think we will be working on it really soon.
