### ISSUE TITLE
Fix support for StacksMocknet

### ISSUE THREAD

**Issue by pseudozach** [leather-io/extension#1590]
I'm triggering a contract call from a react app to hiro wallet.
```
let mocknet = new StacksMocknet();
const options = {
  network: mocknet,
  contractAddress: stxcontractaddres,
  contractName: 'stxswap_v2',
  functionName: 'lockStx',
  functionArgs,
  appDetails: {
    name: 'stxswap',
    icon: window.location.origin + './favicon.ico',
  },
  postConditions,
  onFinish: data => {
    console.log('Stacks Transaction:', data.stacksTransaction);
  },
};
console.log("options: ", options);
await openContractCall(options);
```

I confirm it's set correctly in the browser console as below:
> options:
...
 network: StacksMocknet
_coreApiUrl: "http://localhost:3999"

wallet is giving an error because it's trying to fetch the contract from testnet
![image](https://user-images.githubusercontent.com/3731591/129812961-73cae363-57ce-4862-87d6-89b0b7f9fe51.png)

**Comment by markmhendrickson** [comment]
Is this same as reported here? https://github.com/blockstack/stacks-wallet-web/issues/1575#issuecomment-900785848

**Comment by pseudozach** [comment]
I've tried
- localStorage.clear() and connect wallet again.
- selecting another network in hiro wallet menu and selecting localnet back again.\
same result.

I can provide logs/video if needed.

This is blocking my development, I'll have to fork the wallet to continue development...

**Comment by markmhendrickson** [comment]
Thanks for the context 🙏 We'll discuss and work to resolve ASAP as a team.

**Comment by grahamulator** [comment]
FYI: I've also been experiencing the exact same issue as @pseudozach is describing. I've tried every combination possible of initializing a StacksNetwork object to pass in such as these as an example:
- const network = new StacksTestnet({url: 'http://localhost:3999'});
- const network = new StacksMocknet({url: 'http://localhost:3999'});

No matter what network I pass in (with the exception of a standard Mainnet), contract calls will *always* try to run against the public Testnet.

Actually, I just tried this with an older project that uses previous versions of `connect`/`connect-react`, and it worked with no issue. So it appears to not be a Web Wallet issue.

For reference, working versions are:
    "@stacks/connect": "5.5.0",
    "@stacks/connect-react": "10.0.0",

Non-working versions are:
    "@stacks/connect": "^6.0.0",
    "@stacks/connect-react": "^11.0.0",

**Comment by grahamulator** [comment]
Spoke too soon on the comment above. Downgrading "@stacks/network" from "2.0.1-beta.1" to "2.0.0-beta.0" resolved the issue for me. Latest versions of connect/connect-react are fine. I'm now about to make contract calls against my local Mocknet.

Spoke to @pseudozach on Discord and he confirmed this resolved for him as well.

@markmhx This can likely be closed, but I think a related issue should be opened for stacks.js right? I'm not sure the proper protocol here?

**Comment by markmhendrickson** [comment]
@grahamulator That sounds right to me as far as a next step. Mind opening it here with all the relevant details for the connect package of Stacks.js itself? https://github.com/blockstack/connect/issues/new

**Comment by Eshwari007** [comment]
Closing the ticket as it was resolved
