### ISSUE TITLE
Latest web wallet release is very slow in FF

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1592]
Environment:Latest release of Web wallet in FF-2.14.0
Download the extension in FF and use my pre existing account
Account that has ample of data and that has abt 150 accounts on it
Its super slow to the extend it the screen went to reload extension
<img width="1223" alt="Screen Shot 2021-08-18 at 11 01 54 AM" src="https://user-images.githubusercontent.com/38872890/129962831-d39479d7-6f77-4d7c-b3d1-a1074114b55e.png">

**Comment by Eshwari007** [comment]
Attaching video as well for perusal

https://user-images.githubusercontent.com/38872890/129962965-2c42c33c-1b67-4f7a-8516-5e3bde8029a5.mov

**Comment by fbwoolf** [comment]
@kyranjamie @beguene see if you can repro this tomorrow morning with Esh's account and debug it. It seems to only be in the FF popup for me, but I can't seem to launch the inspector window consistently to debug it. My browser just locks up and I have to reinstall. I think I did see a CORS error and something in `use-vault-messenger.ts`, but not much else as a lead yet.

**Comment by beguene** [comment]
@fbwoolf I will look into it.

**Comment by fbwoolf** [comment]
@aulneau wasn't this resolved by your release so we can close the issue?
