### ISSUE TITLE
Microblocks block height has incorrect time stamp 52 years ago

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#1595]
Microblocks block height has incorrect time stamp 52 years ago

<img width="1057" alt="Screen Shot 2021-08-19 at 9 53 02 AM" src="https://user-images.githubusercontent.com/49165468/130081245-2744893e-1154-4b3a-afe2-91c635c0f56f.png">

**Comment by fbwoolf** [comment]
This issue was opened in the wrong repo, so will close and reopen in the explorer.
