### ISSUE TITLE
Pending transaction in Mainnet is not to be found in Explorer chain

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1610]
https://github.com/blockstack/stacks-wallet-web/pull/1572

User is trying to make a transaction on mainnet,it has been pending for quite some time now.
User then selects the activity of tx and notices the direct explorer page is viewable as pending:https://explorer.stacks.co/txid/0xb3544f206f8b025d5c080cd881eb4db5e74506f7ebf3dc4c5ea8cc2fee0ed903?chain=mainnet

However when user select the url:https://explorer.stacks.co/transactions?chain=mainnet
User is not able to view the pending transaction

User tested similar scenario in testnet and they are working perfectly fine

https://user-images.githubusercontent.com/38872890/130655576-5db0494c-972b-4a10-b9e2-397b83d3bbe7.mov

**Comment by aulneau** [comment]
I don't think this is a bug -- it shows that there are many, many pending transactions being flooded into the list, and as such it's possible it was not on the first page of results. Can you reproduce it?

**Comment by Eshwari007** [comment]
@aulneau My previous tx of 0.55 was confirmed in anchor block but am not even able to view it in 'Mainnet chain Confirmed 'tab.
However my second tx of 0.3 which was included in Microblocks was viewable in Confirmed mainnet chain.I was not able to find it in Pending mainnet chain -Explorer though
<img width="408" alt="Screen Shot 2021-08-24 at 12 49 22 PM" src="https://user-images.githubusercontent.com/38872890/130657648-db576f97-6c32-4f91-83e5-5e7f10d0e1b4.png">
<img width="845" alt="Screen Shot 2021-08-24 at 12 49 29 PM" src="https://user-images.githubusercontent.com/38872890/130657652-eab1d5b6-9a3d-45fc-917c-659a7ec56d4c.png">
<img width="1320" alt="Screen Shot 2021-08-24 at 12 50 54 PM" src="https://user-images.githubusercontent.com/38872890/130657656-4b5fd6f8-c5c6-45d9-9d00-e0903d98e2e4.png">

**Comment by Eshwari007** [comment]
https://user-images.githubusercontent.com/38872890/130658033-b9fe2b9a-6c3e-4456-a775-557d45f8ecad.mov

**Comment by aulneau** [comment]
I see it here
![Screen Shot 2021-08-24 at 11 56 39 AM](https://user-images.githubusercontent.com/11803153/130658307-d8a35fa2-9e85-420d-9daf-e86b7b54cec1.png)

**Comment by Eshwari007** [comment]
Aha,I see it now.It was there earlier.Guess it showed up later as the tx was Pending for so long .My doubt was it didnt show up in Pending tab while tx was Pending,It showed up in Confirmed tab way later after the tx was Confirmed in WW.More than few minutes.It use to be a little faster than that in the past.
