### ISSUE TITLE
Fix ability to add new account

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#162]
When trying to add another account when signing into Note Riot, the pending state goes on seemingly forever:

![Kapture 2020-02-17 at 12.04.53.gif](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/94245b37-c8a2-43cc-bd2c-a2ce6dc1d6af)

**Comment by hstove** [comment]
I am unable to repro this issue - is it happening consistently?

**Comment by markmhendrickson** [comment]
Assigning to myself to reproduce

**Comment by markmhendrickson** [comment]
This is working for me on Wink now so I'll close until we can reproduce.
