### ISSUE TITLE
[2.15.0] Bug: trying to pay for .btc name in STX, click "Send" in preorder stage

### ISSUE THREAD

**Issue by vocafeuvre** [leather-io/extension#1632]
An error occurred while using Hiro Wallet for Web (`2.15.0`).

### Error
> Cannot read property 'username' of undefined

#### Stack trace
```bash
TypeError: Cannot read property 'username' of undefined
    at getAccountDisplayName (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:34322:15)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:54692:104
    at Ch (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:130231:137)
    at li (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:130254:154)
    at ki (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:130252:169)
    at ii (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:130251:178)
    at ck (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:130348:126)
    at bk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:130324:347)
    at ak (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:130324:278)
    at Tj (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:130324:138)
```

#### Reproduce steps
1. make an account in Hiro Desktop Wallet
2. import that account to Hiro Web Wallet extension using secret key method
3. try to preorder .btc name by clicking "Send"
4. popup appears with the stack trace displayed

**Comment by markmhendrickson** [comment]
I'm moving this to QA on our end to recreate with the BTC app https://btc.us/

**Comment by Eshwari007** [comment]
The issue yet persist.Am not able to purchase .btc name 
<img width="801" alt="Screen Shot 2021-09-07 at 4 44 28 PM" src="https://user-images.githubusercontent.com/38872890/132408637-089a8351-25b6-4650-9691-d559c7951b63.png">
<img width="1402" alt="Screen Shot 2021-09-07 at 4 44 49 PM" src="https://user-images.githubusercontent.com/38872890/132408640-3688a1e4-7b31-4de1-8707-ba9b5ea386f8.png">

**Comment by Eshwari007** [comment]
@MarvinJanssen and team
I tried to follow the steps of @umersaleem over the channel but seems to have found another issue now
I was initially logged in as account SP17Y....,logged out and signed back to use account SP3A,when I try to pre order a name,it yet indicates my first prod account which is SPI7Y,I tried refreshing and logged back in several times but doesnt seem to sign in with my new account.Attaching the screenshot of both account visible on the screen
<img width="976" alt="Screen Shot 2021-09-16 at 9 37 30 AM" src="https://user-images.githubusercontent.com/38872890/133622793-31a113b1-c16b-4301-b15a-d4e70a3721f4.png">
cc @markmhx

**Comment by markmhendrickson** [comment]
@Eshwari007 by "logged out", do you mean out of the wallet or the app itself? Only the latter will cause the app to recognize a different account.

**Comment by Eshwari007** [comment]
Great news!Am able to purchase the the name on .btc hence testing passed.I had to log out and sign back in with the preferred account as the auto recognizing with my existing wallet didn't work
cc @markmhx
