### ISSUE TITLE
Implement replace-by-fee

### ISSUE THREAD

**Issue by jcnelson** [leather-io/extension#1633]
Right now, a transaction that is pending in the mempool cannot be replaced by fee, even though the Stacks network protocols support it.  This means that if the network is congested, and your fee is too low, your transaction will not be mined.  The wallet should allow the user to re-submit a transaction with a higher fee.

**Comment by jcnelson** [comment]
See also https://github.com/blockstack/stacks-wallet-web/issues/1532

**Comment by jcnelson** [comment]
At the same time, the user ought to be able to set the fee they want to pay from the get-go.

**Comment by markmhendrickson** [comment]
> This means that if the network is congested, and your fee is too low, your transaction will not be mined.

_We have arrived 👏_
