### ISSUE TITLE
Extension icon is only visible upon user selection in Chrome

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1636]
Testing PR:https://github.com/blockstack/stacks-wallet-web/pull/1611

User notices upon extension download,the Stacks icon is not visible in the browser unless the user selects the extension icon
However this is not the case with Firefox

attaching the screen recording for perusal

https://user-images.githubusercontent.com/38872890/131350519-b5b51a4d-4656-4ac5-b8d3-aea0625da1a4.mov

**Comment by kyranjamie** [comment]
I think this is expected behaviour of Chrome, @Eshwari007. The icon doesn't stay in the toolbar unless you select the pin 

![image](https://user-images.githubusercontent.com/1618764/131350944-92d4c6d5-a6ad-4825-89e0-fa5684126e0e.png)
