### ISSUE TITLE
[RBF]Tweaking the nonce making the tx Pending despite tx is speed up

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1651]
User is sending Stella token
In the setting,user tweaked the nonce to =1 higher
User also speed up the transaction to 2x
Transaction was submitted successfully

User notices this tx has been pending for very long time
<img width="606" alt="Screen Shot 2021-09-01 at 10 05 10 AM" src="https://user-images.githubusercontent.com/38872890/131686987-fa1f3279-1ed1-45a4-bf38-317fb0b808ea.png">
<img width="553" alt="Screen Shot 2021-09-01 at 10 05 17 AM" src="https://user-images.githubusercontent.com/38872890/131686990-2d2c0442-e302-436e-9b32-b2706d923522.png">
<img width="530" alt="Screen Shot 2021-09-01 at 10 06 05 AM" src="https://user-images.githubusercontent.com/38872890/131687029-b11ee5e9-23f4-4e81-87f4-a8ec2f2f65fb.png">
<img width="954" alt="Screen Shot 2021-09-01 at 10 11 07 AM" src="https://user-images.githubusercontent.com/38872890/131687062-dccc949b-c04b-4572-a37e-c961e0c37e12.png">

**Comment by beguene** [comment]
@Eshwari007 If you increase the nonce by 1, it will always stay pending, unless you send another tx with the nonce number in between
For example for your https://explorer.stacks.co/txid/0x29b85616dfaa9dcbd7e7fcb11cf147b482622bf15f49b85d8c47581414506622
with nonce 296 and last confirmed nonce = 292
You need to send 3 txs with nonce 293, then 294, then 295, then the initial transaction will confirm.
