### ISSUE TITLE
[RBF]Speed up '2x,5x and 10x' displaying same amount

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1652]
User was sending Stella tx to another account
User tweaked the nonce(not sure if this is related to the issue)
User then prior to submitting tx selected 2 x which value was 1.9712
User tried to play around with 5x and 10x but all were displaying same results as 1.9712
User submit the tx,in explorer its being displayed as 1.9712 x2=3.9424
<img width="581" alt="Screen Shot 2021-09-01 at 10 06 00 AM" src="https://user-images.githubusercontent.com/38872890/131687542-a323aa29-e204-4d13-8eb4-61e54e6886aa.png">
<img width="530" alt="Screen Shot 2021-09-01 at 10 06 05 AM" src="https://user-images.githubusercontent.com/38872890/131687545-f7c4f10a-dc99-4a09-a1fd-cefb61ff8212.png">
<img width="562" alt="Screen Shot 2021-09-01 at 10 06 16 AM" src="https://user-images.githubusercontent.com/38872890/131687548-ef0347bb-6be2-4026-8728-99abacf35e59.png">
<img width="613" alt="Screen Shot 2021-09-01 at 10 06 21 AM" src="https://user-images.githubusercontent.com/38872890/131687549-360fb866-6ad8-490d-b65d-013332a45cf8.png">
<img width="954" alt="Screen Shot 2021-09-01 at 10 11 07 AM" src="https://user-images.githubusercontent.com/38872890/131687569-727d6b76-e927-41b6-930a-e314533d3efd.png">
ser tried to play around with 5x and 10x but all were displaying same results as 1.9712

**Comment by kyranjamie** [comment]
Afaik, this one was fixed pre-release

**Comment by Eshwari007** [comment]
Tested the issue and it passed
