### ISSUE TITLE
Moved the nonce up from 14 to 16 skipping 15 transaction is pending and was not pulled into 3 anchor blocks

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#1653]
Moved the nonce up from 14 to 16 skipping 15 transaction is pending and was not pulled into 3 anchor blocks

https://explorer.stacks.co/txid/0xb72ce827b9b8c0f4ad8aa065abd98f3571aec1aa5debcfb62e02742f6407dc8d?chain=testnet

3 anchor blocks have come through but my transaction was not pulled in

<img width="1352" alt="Screen Shot 2021-09-01 at 10 21 35 AM" src="https://user-images.githubusercontent.com/49165468/131688337-e0264885-f709-4997-a68f-a731ce326919.png">

<img width="905" alt="Screen Shot 2021-09-01 at 10 22 29 AM" src="https://user-images.githubusercontent.com/49165468/131688499-f927e4bd-d247-4aab-8151-856ca7fbc1e0.png">

**Comment by timstackblock** [comment]
It appears that moving the nonce has caused the transaction to stay in pending status and not be pulled into the anchor block. It also did not get pulled into a microblock, have you seen any transactions get confirmed after the nonce is updated?

**Comment by aulneau** [comment]
is it the case that transactions exist for nonces 14,15,16, or is it 14,16? if there is no transaction with nonce 15, any larger nonce will never succeed

**Comment by beguene** [comment]
See my comment here https://github.com/blockstack/stacks-wallet-web/issues/1651#issuecomment-910342590

**Comment by fbwoolf** [comment]
Maybe we need a tooltip around changing the nonce so users don't get confused?

**Comment by aulneau** [comment]
yeah there is def some work we can do to educate what this means, impose limits, etc

**Comment by fbwoolf** [comment]
There is text at the top of drawer that talks about changing the fee but nothing in regards to changing the nonce ...which is a bit weird considering you can change it there.

**Comment by timstackblock** [comment]
This is not a bug expected behavior, the team added an enhancement to educate users not to do this as this action will result in pending transactions forever
