### ISSUE TITLE
Gracefully handle replaced transaction 404

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1656]
User was able to view the activity of a tx which is pending in explorer.
User bumped up the fee to any amount that is differ than the default value in first tx
Tx was submitted successfully but the explorer page which was used to monitor flipped and produced page not found 

https://user-images.githubusercontent.com/38872890/131722902-48148246-17a7-4b21-a624-68acbfd1616b.mov

**Comment by markmhendrickson** [comment]
Could this be related to https://github.com/blockstack/explorer/issues/518?

**Comment by andresgalante** [comment]
Related to https://github.com/blockstack/explorer/issues/481

**Comment by Eshwari007** [comment]
@obycode has noticed a similar pattern where in his on words:"Something I've noticed that is related to the above, I think it is confusing that when you have a pending transaction open in the explorer, then it gets confirmed, instead of updating the page to show that it is confirmed, the page changes to "Page not found", but if I refresh, then it shows the confirmed transaction.
cc @markmhx @kyranjamie @fbwoolf @andresgalante @timstackblock

**Comment by 314159265359879** [comment]
This is resolved.
