### ISSUE TITLE
Speed up interactions with transaction signing

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1660]
User notices:

- The 'apply' in Settings took some few sec delay the first time I logged into the account but tx was submitted successfully.

- The 'Send' button is disabled( it was the same in the past) however its very prominent now that it may take longer sec to enable it than in the past

Both button loading time was slower than usual

**Comment by markmhendrickson** [comment]
> The 'Send' button is disabled( it was the same in the past) however its very prominent now that it may take longer sec to enable it than in the past

Mind clarifying what you mean about this item? Is it the wallet taking awhile to process the request once "Send" is clicked?

**Comment by markmhendrickson** [comment]
@Eshwari007 Mind retesting this in case the slowness was due to temporarily API issues?

**Comment by Eshwari007** [comment]
We had brought the ticket up during our last Monday 9/13th Team meeting.There is some underlying fetching of data which is causing the slowness of Send button to be activated.I will retest the issue and will close it if its within the 'agreeable' time frame.
