### ISSUE TITLE
[RBF]Custom set fee is incorrect upon confirmation 

### ISSUE THREAD

**Issue by Eshwari007** [leather-io/extension#1663]
User sets custom fees of 0.10 for a tx.
Upon confirmation,user notices it was tweaked as 0.099999
<img width="416" alt="Screen Shot 2021-09-01 at 5 38 29 PM" src="https://user-images.githubusercontent.com/38872890/131752131-2c36a0cb-f0ba-4666-b991-7c2b4b747c6c.png">
<img width="419" alt="Screen Shot 2021-09-01 at 5 38 38 PM" src="https://user-images.githubusercontent.com/38872890/131752133-49c6519b-15e6-4d32-b768-42a78c501e76.png">

**Comment by beguene** [comment]
@kyranjamie Are you taking this or shall I take it ?
