### ISSUE TITLE
[RBF] Nonce used twice after replacing a tx

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#1666]
I have 5 pending txs with nonce 10, 11, 12, 13, 14. 

I create a new tx to replace tx 10 by changing the nonce of the new tx to 10 and by adjusting the fees. The new tx is broadcasted. 

Next time I create a tx the suggested nonce is 10, it should be 15.

**Comment by friedger** [comment]
After using the "Edit nonce" feature, the extension has overwritten some of my txs without me noticing it. To me this is more than "P3".

**Comment by markmhendrickson** [comment]
@timstackblock do we have a related PR we can link here?

**Comment by beguene** [comment]
@friedger We made a fix to improve nonce calculation that was released after the day you posted this issue. I tested the above scenario and it's working fine now.
Can you try again ? It should work as expected now.

**Comment by markmhendrickson** [comment]
I'm closing until further notice that this remains a problem. 🙏
