### ISSUE TITLE
Fix width of overlay viewport when selecting "Recieve"

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1667]
The viewport suddenly grows horizontally in Firefox with v2.16.0 when selecting "Receive":

<img width="756" alt="Screen Shot 2021-09-02 at 11 21 16" src="https://user-images.githubusercontent.com/28991/131829495-02efedce-98e2-4efa-bb82-140775d3558a.png">

**Comment by markmhendrickson** [comment]
@timstackblock to retest in Firefox

**Comment by Eshwari007** [comment]
The bug is no longer seems to be an issue
Tested on Firefox version 100.0
with v3.7.2

<img width="387" alt="Screen Shot 2022-05-03 at 1 49 23 PM" src="https://user-images.githubusercontent.com/38872890/166510363-701e03e8-f975-494f-8390-f79e89a57a00.png">
cc @markmhx
