### ISSUE TITLE
[2.16.0] Advanced settings does not allow nonce 0

### ISSUE THREAD

**Issue by 314159265359879** [leather-io/extension#1675]
![image](https://user-images.githubusercontent.com/33360391/131984586-cf31b806-f934-4879-9191-45aadf2b01a3.png)

It should allow this because the nonce can be zero.

**Comment by Eshwari007** [comment]
Test passed.Moving it to done
<img width="402" alt="Screen Shot 2021-09-09 at 5 28 26 PM" src="https://user-images.githubusercontent.com/38872890/132765194-b0c61d52-ca97-4339-a487-1b5163e99703.png">
<img width="1064" alt="Screen Shot 2021-09-09 at 5 28 56 PM" src="https://user-images.githubusercontent.com/38872890/132765195-29c87606-21bf-4a4d-a60d-b1f15d504117.png">
