### ISSUE TITLE
Fix production install instructions

### ISSUE THREAD

**Issue by muneeb-ali** [leather-io/extension#1676]
The production install instructions:

Build from source
Run the following from within this repository's root directory if you've pulled it with Git:

> sh build-ext.sh

Hits an error like:

> 🛠  Packaging Browser Extension
> no ./dist dir found

We should assume that users trying this are doing it because they don't want to wait for the Chrome store approval and these users might not be very technical. We should make the instructions as easy as possible and test them on multiple operating systems and environments etc.

**Comment by markmhendrickson** [comment]
It looks like we must have changed something with the build script since these instructions were written. I'm getting the same error.

**Comment by aulneau** [comment]
I made a fix, you need to run `yarn && yarn build` before running the bash script.

**Comment by markmhendrickson** [comment]
I've also submitted a PR to link to our new Hiro.so-based instructions which should be easier for the average user: https://github.com/blockstack/stacks-wallet-web/pull/1680
