### ISSUE TITLE
Add illustration to analytics consent dialog during onboarding

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1678]

**Comment by jasperjansz** [comment]
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=426%3A4932

**Comment by markmhendrickson** [comment]
This design looks generally good to me, though for someone who's moving very fast and not reading, they may hit "No thanks" with the assumption that the modal is asking for something else, more time-intensive (e.g. taking a survey).

Perhaps the primary button should be something like "Allow anonymous metrics" and the secondary "Don't allow".

**Comment by markmhendrickson** [comment]
The button labels have been updated and "Learn more" link added.

Assigning to @eugeniadigon to help with an illustration.

**Comment by markmhendrickson** [comment]
@jasperjansz Can you make these copy changes so the messaging here corresponds to our legal policies most precisely?

![image](https://user-images.githubusercontent.com/28991/134857289-fc226d1e-9a90-4470-b5cc-3ed5814bb599.png)

**Comment by markmhendrickson** [comment]
Current version as integrated into desktop wallet:

![image](https://user-images.githubusercontent.com/28991/136792634-d5eeccbf-3168-4fbb-b2fe-5beb65841a09.png)

**Comment by ginny-d** [comment]
Add icon to dialog:

1) Web:
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=426%3A4932
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=426%3A4775
<img width="1352" alt="tracking consent" src="https://user-images.githubusercontent.com/78865845/150509104-88a193b4-083a-40aa-927f-3b7def2b096f.png">
<img width="488" alt="tracking consent-1" src="https://user-images.githubusercontent.com/78865845/150509122-c8e06904-9e71-499b-98fe-709b61ceefaa.png">

2) Desktop:
https://www.figma.com/file/GShZH28L05eyKjRZxPb8SK/%E2%9C%8F%EF%B8%8FIllustration-System?node-id=1%3A11554
https://www.figma.com/file/GShZH28L05eyKjRZxPb8SK/%E2%9C%8F%EF%B8%8FIllustration-System?node-id=1%3A11579
<img width="1352" alt="Help us improve - desktop" src="https://user-images.githubusercontent.com/78865845/150509186-98af5eaa-deb2-4875-bb0c-3e781ab24046.png">
<img width="1352" alt="Help us improve - desktop-1" src="https://user-images.githubusercontent.com/78865845/150509198-050380c5-2978-4783-8f68-015279ac8006.png">

**Comment by fbwoolf** [comment]
@eugeniadigon do you know why the text in the full page view and the popup are different? Also, I think it would be best to open an issue with the desktop update in the `stacks-wallet` repo so those aren't lost here once this issue is closed. I can make one for the these updates.

**Comment by fbwoolf** [comment]
New issue in desktop: https://github.com/hirosystems/stacks-wallet/issues/1035

**Comment by fbwoolf** [comment]
Currently, this has been implemented as a full page view, not a popup modal. I am going to leave it that way unless someone tells me it needs to be changed?

**Comment by fbwoolf** [comment]
Do we have a `Learn more` link for this?

**Comment by ginny-d** [comment]
> @eugeniadigon do you know why the text in the full page view and the popup are different? Also, I think it would be best to open an issue with the desktop update in the `stacks-wallet` repo so those aren't lost here once this issue is closed. I can make one for the these updates.

I don't have context on why the texts are different, nor where the Learn more link should point to, sorry I can't be of further help :/

Thank you for creating the issue on desktop, I'll handle those this way from now on

**Comment by Eshwari007** [comment]
> 👟 UserX Kanban [🚨 DEPRECATED in favor of https://github.com/orgs/hirosystems/projects/9/views/1]

As per @markmhx input above,"Learn more" link has been added but not sure on the exact location though

**Comment by fbwoolf** [comment]
@Eshwari007 I believe Mark was just referring to it being added in the designs but we are still on hold to know what it links to, so I think it will be left out for now. I have it in the code but commented out with a `TODO` note.
