### ISSUE TITLE
Add option to go back and view Secret Key to Save Secret Key screen

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#168]
Now that we've removed the screen to enter the Secret Key for confirmation, we should put its "Go back" option on this screen so the user has a second chance to view and copy their Secret Key:

![Screen Shot 2020-02-17 at 15.10.44.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/40a9f960-325f-40d5-90ff-f24b8a669dbb)

**Comment by jasperjansz** [comment]
Designs: https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=5721%3A12143

**Comment by markmhendrickson** [comment]
This looks sufficient to me for now, but wondering if we'll want to remove this link when we enable the browser's back button with https://github.com/blockstack/ux/issues/37? 

This link here seems a bit obtrusive in that it creates additional mental friction (by forcing the the user to think about two prominent options instead of one on this screen).
