### ISSUE TITLE
Allow lower fees for transactions in advanced settings

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#1682]
Currently it seems as though it's not possible to set a lower fee than the default after we implemented replace-by-fee. Users should be able to enter any fee that is equal or above the minimum the network requires.

**Comment by fbwoolf** [comment]
@aulneau I need to get access to this value in some way to know what is going to cause the `FeeTooLow` rejection? https://github.com/blockstack/stacks-blockchain/blob/974346423639566cf8275d74a98309f409ac05e0/src/chainstate/stacks/db/blocks.rs#L264

I am trying to locate that exposed through the api? Am I on the right track here?

**Comment by aulneau** [comment]
you can generate this yourself in the app. rather than using the [DEFAULT_FEE_RATE](https://github.com/blockstack/stacks-wallet-web/blob/main/src/store/common/constants.ts#L2), you'd use `1`, you multiply that by the byte length of the transaction, which gives the minimum fee.

**Comment by fbwoolf** [comment]
> you can generate this yourself in the app. rather than using the [DEFAULT_FEE_RATE](https://github.com/blockstack/stacks-wallet-web/blob/main/src/store/common/constants.ts#L2), you'd use `1`, you multiply that by the byte length of the transaction, which gives the minimum fee.

Ok, so likely won't change often, therefore we can just monitor updating ourselves. I'll make a note in the code. Thanks!

**Comment by fbwoolf** [comment]
@aulneau after looking at this again, I don't think this is an issue? I can set it lower than the default we autofill, but it does hit the `FeeTooLow` error correctly. So, I'm not sure I need to do anything here? I can successfully send a tx by changing the default fee (currently `0.072`) to `0.0072`. But, it does return the `FeeTooLow` error if I set it to `0.0001`.

**Comment by fbwoolf** [comment]
@Eshwari007 I am going to move this to QA bc I don't think it is an issue at this point. Can you also verify that you can set the fee lower than the default, but there is a point where you go too low and it returns the `FeeTooLow` error (see my last comment for clarification if needed)?

**Comment by Eshwari007** [comment]
@fbwoolf  Does this need to be tested in an extension download ?Or does it work with the latest release as well?

**Comment by fbwoolf** [comment]
> @fbwoolf Does this need to be tested in an extension download ?Or does it work with the latest release as well?

I think testing it on the newest release will be good.

**Comment by Eshwari007** [comment]
@fbwoolf 
That is true,only when user inputs `0.0001`,the FeeTooLow error is returned.Prior to that any other values such as 0.1,0.01,0.001 were all accepted.Moving the ticket to QA Done

**Comment by Eshwari007** [comment]
I did noticed an issue though,will create a ticket as I tried sending STX to the same account quickly and received nonce conflict error
<img width="1440" alt="Screen Shot 2021-09-28 at 11 50 41 AM" src="https://user-images.githubusercontent.com/38872890/135127142-4de4d683-0fb8-459d-ac29-dd9499bfbb91.png">

**Comment by fbwoolf** [comment]
@Eshwari007 thanks for testing this. 👍 I will close this issue.
