### ISSUE TITLE
Fix activity item clicks

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1685]
On v2.16.0 none of the activity items open to the Explorer upon click in either Chrome or Firefox for me:

![image](https://user-images.githubusercontent.com/28991/132196655-b9fdac57-6775-426d-83b2-36b9b2af1623.png)

**Comment by beguene** [comment]
@markmhx This is working fine for me. Can you try again ?

**Comment by markmhendrickson** [comment]
This works when clicking on the left-aligned text (green arrow), but not in other points of the overall hover-activated element (red arrows):

<img width="367" alt="Screen Shot 2021-09-09 at 13 51 13" src="https://user-images.githubusercontent.com/28991/132680937-4a0b7cc2-805a-44f7-84ab-e67e242fc84a.png">
