### ISSUE TITLE
[2.2.0] Bug: Unable to Send or Stack $MIA

### ISSUE THREAD

**Issue by enjoywithouthey** [leather-io/extension#1689]
I'm trying to stack $MIA from account : SP2M7K3YM8813404G1R7AXV106CPWH0Z5ZA80JVAV. Using Hiro Web Wallet.  The wallet doesn't tell me the version.

I'm also unable to send out $MIA because there is no memo field in my wallet. See screenshot:

Thanks,

-Justin
![MIA Wallet](https://user-images.githubusercontent.com/17732015/132391189-56ec980b-9d91-4202-9c66-211fdd616d5c.JPG)

Bug found testing Stacks Wallet for Web.

### Error

**Loadable**: `api.account-data`
**Message**: `Unable to fetch account data from https://stacks-node-api.mainnet.stacks.co`

### Environment

**Version**: `2.2.0`
**Branch**: `main`
**Commit**: `d508d14`

**Comment by aulneau** [comment]
We are currently on 2.16.0 of the wallet, you're using a _very_ out of date version. Please update -> https://www.hiro.so/wallet/install-web

**Comment by enjoywithouthey** [comment]
ok thanks.  works like a charm now
