### ISSUE TITLE
[RBF] Nonce 0  should be supported

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#1695]
RBF should be possible for nonce 0 as well.
Currently, the UI requires a positive number.

![Screenshot from 2021-09-09 11-52-20](https://user-images.githubusercontent.com/1449049/132664537-99b14f5a-1d84-4743-8a50-fc9f62fb26b2.png)

**Comment by markmhendrickson** [comment]
Thanks, closing this out since we have a report here and PR in the works to resolve: https://github.com/blockstack/stacks-wallet-web/issues/1675
