### ISSUE TITLE
Prevent display of password validation message during paste

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1697]
When I paste a valid password into the set password form, it still shows the "password is invalid" message regardless:

<img width="430" alt="Screen Shot 2021-09-09 at 13 50 34" src="https://user-images.githubusercontent.com/28991/132703694-aa91c5b4-d098-49a8-a66e-0c3625b0a6f3.png">

**Comment by pete-watters** [comment]
Closing this off as it's outdated and working now. You cannot set initial password in the extension popout anymore also
