### ISSUE TITLE
Web wallet crashes in FF and Chrome when user hits Preview button after an error message for amount (index.js:139497 Error: Missing queryFn)

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#1698]
Here is a video of the bug: http://somup.com/crQQ2CrUuJ

This is related to the error message screen when entering more than 6 decimals. If the user triggers the "STX can only have 6 decimals" error message. After you select preview the spinner starts then the app crashes.

Console log error index.js:139497 Error: Missing queryFn

Expected result = New screen displays send and you can edit the nonce

Actual result = The app crashes 2 times in a row, it worked the 3rd time and a 4th time as you can see in the video.

<img width="1175" alt="Screen Shot 2021-09-09 at 10 29 57 AM" src="https://user-images.githubusercontent.com/49165468/132708410-ec009135-d943-41ae-be08-410f42ff694e.png">

<img width="642" alt="Screen Shot 2021-09-09 at 10 42 55 AM" src="https://user-images.githubusercontent.com/49165468/132707845-7ebeb2bf-6575-4061-8331-31e35a37e4cf.png">

**Comment by fbwoolf** [comment]
The fix for this was merged but not linked so it didn't close automatically. I will close the issue.
https://github.com/blockstack/stacks-wallet-web/pull/1699
