### ISSUE TITLE
Selecting the enter key with a null/empty secret key box prompts the user for a password 

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#170]
Selecting the enter key with a null/empty secret key box prompts the user for a password. This should generate a error message telling the user to enter something.

<img width="443" alt="Screen Shot 2020-02-17 at 10 12 31 AM" src="https://user-images.githubusercontent.com/49165468/74665621-104dad80-516e-11ea-88ea-b5c1d6e641bc.png">
<img width="438" alt="Screen Shot 2020-02-17 at 10 12 40 AM" src="https://user-images.githubusercontent.com/49165468/74665623-104dad80-516e-11ea-9ae5-dbff25aaad9f.png">

**Comment by markmhendrickson** [comment]
Also handle invalid Magic Recovery Codes (eg too short)
