### ISSUE TITLE
Show FT token standard attributes in post conditions when signing transaction

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1700]
As reported by @philipdesmedt, the post conditions UI doesn't show standard attributes for tokens – particularly decimal points, which leads the user to think they are setting a condition for value that's very different than reality, such as for WST here:

![image](https://user-images.githubusercontent.com/28991/132838058-48035ed0-696e-4258-a138-be33e548cb32.png)

**Comment by philiphacks** [comment]
Very odd behaviour.

This does not work (swap y for x)
![image](https://user-images.githubusercontent.com/577420/133103464-64378302-04a5-4ee5-9545-b0d648cb4d46.png)

This works (swap x for y, essentially the same code & front-end code as well)
![image](https://user-images.githubusercontent.com/577420/133103916-29187554-e3d8-4b1d-830b-ece53674f3f4.png)

I have to say the developer experience is really bad right now for post conditions. Hard to figure out what they should exactly look like and little documentation is provided (a lot of digging in the source code on github). Then you have these seemingly random bugs, combined with the removal of allow mode... I have to say these post conditions make me go wild, and not in the way I like it 😂

**Comment by markmhendrickson** [comment]
@philipdesmedt your latest screenshots here suggests we may have other work to do here than simply apply the FT standard to this view, since the values don't line up even when taking decimals into consideration (~478 DIKO instead of ~399 DIKO and ~30 USDA instead of ~25 USDA).

Are you seeing other discrepancies here that haven't caught my eye?

**Comment by philiphacks** [comment]
@markmhx the discrepancies are just because I added a multiplier and did "less or equal" in the post condition... the actual values are fine, the decimals are just not parsed AFAIK

**Comment by fbwoolf** [comment]
@philipdesmedt I am trying to figure out how to reproduce this, can you confirm:

1. What api server are you using? Is it up to date?
2. What wallet version are you using?
3. Can I get the contract id to check the token metadata endpoint?

Just confirming those things first, then is there somewhere I can test this currently?

**Comment by philiphacks** [comment]
1. Hiro hosted & clarinet integrate (devnet) locally. Should all be up to date
2. Latest .17 as of today on Brave
3. Which contracts do you need?

**Comment by philiphacks** [comment]
You can test on testnet.arkadiko.finance

**Comment by fbwoolf** [comment]
> 3. Which contracts do you need?

Hoping for the contract id of the contract used in the images posted. Wanting to use here:
https://stacks-node-api.testnet.stacks.co/extended/v1/tokens/{contractId}/ft/metadata

**Comment by fbwoolf** [comment]
I bet I found the lines causing it ...L85 and L88 so prob no need for the contract id.
https://github.com/blockstack/stacks-wallet-web/blob/5338f80de00d2c940dc1edbe725a1429e3782c2b/src/pages/transaction-signing/components/post-conditions/single.tsx#L85

**Comment by philiphacks** [comment]
@fbwoolf great!

Just adding again that the tokens are found correctly in one direction but not in the other (see https://github.com/blockstack/stacks-wallet-web/issues/1700#issuecomment-918260376). Hope this helps!

**Comment by philiphacks** [comment]
Another one that is not working.. I bid 31 USDA on the auction, not parsed in the post condition
![image](https://user-images.githubusercontent.com/577420/134479246-e26ef0bd-3cb0-4060-a3bd-6f7f6b715676.png)

I assume all these come from the same bug

**Comment by fbwoolf** [comment]
@philipdesmedt can someone send DIKO and/or USDA to my testnet wallet?

**Comment by philiphacks** [comment]
@fbwoolf sure, can you drop your address here

**Comment by fbwoolf** [comment]
@philipdesmedt thanks! ST12SYBBE6B5P3KQR49WH448HT80JVV645ZP6Y6WY

**Comment by philiphacks** [comment]
@fbwoolf sent you DIKO. Could not send USDA since it did not show up in the web wallet to send... another bug?

![image](https://user-images.githubusercontent.com/577420/134557980-d3c8f879-320d-433e-bd27-1cc87bddca30.png)

**Comment by fbwoolf** [comment]
> @fbwoolf sent you DIKO. Could not send USDA since it did not show up in the web wallet to send... another bug?
> 

I believe we already have a fix in for this that just needs to be released. It is a caching issue (if same as reported from others).
https://github.com/blockstack/stacks-wallet-web/pull/1708

**Comment by fbwoolf** [comment]
If you sign out and then back in does it show up?

**Comment by fbwoolf** [comment]
@philipdesmedt I can't seem to post liquidity in the app? What am I missing here?

<img width="529" alt="Screen Shot 2021-09-23 at 1 09 35 PM" src="https://user-images.githubusercontent.com/6493321/134560992-61e1d6e2-369b-4146-851c-0d31826a8da0.png">

**Comment by fbwoolf** [comment]
Also, can you get me the contract id? Need to verify the token metadata.

**Comment by fbwoolf** [comment]
> Also, can you get me the contract id? Need to verify the token metadata.

^ I can prob get that myself once I can get the app working, nvm.

**Comment by fbwoolf** [comment]
I can recreate the issue now using USDA/DIKO add liquidity contract so all good.

**Comment by fbwoolf** [comment]
@philipdesmedt finally have some answers for you ...did some digging. Using USDA/DIKO add liquidity contract found the following:

- The post conditions we are getting are not accurate, see this info and will include screen shots of logs:

```
Post Condition:
assetName = "usda"
contractAddress = "ST26902A6NT1QSWQXXYM55EM579RY9CCPQDN02QW2"
contractName = ""arkadiko-token""

Post Condition:
assetName = "diko"
contractAddress = "ST26902A6NT1QSWQXXYM55EM579RY9CCPQDN02QW2"
contractName = "usda-token"

Post Condition:
assetName = "arkv1dikousda"
contractAddress = "ST26902A6NT1QSWQXXYM55EM579RY9CCPQDN02QW2"
contractName = "arkadiko-swap-token-diko-usda"

Asset Metadata:
name = "diko"
contractAddress = "ST26902A6NT1QSWQXXYM55EM579RY9CCPQDN02QW2"
contractName = "arkadiko-token"
```
In addition, our code will only match up assets the user has in their wallet. We don't request metadata for tokens they don't have (so it won't display accurately). This is an enhancement @aulneau has advocated for. I can create another issue for it, @markmhx? This is the code looking for the match (the asset is then `undefined` so we do not format it):

```js
const asset = assets?.find(
    asset =>
      asset.contractAddress === contractAddress &&
      asset.contractName === contractName &&
      asset.name === assetName
  );
```
Screenshot of tx:
![Screen Shot 2021-09-23 at 3 19 36 PM](https://user-images.githubusercontent.com/6493321/134578861-8107b7a5-3abe-47d9-a0b6-fbbc36751f37.png)

Screenshots of the two post conditions for assets logged data:
![Screen Shot 2021-09-23 at 3 04 57 PM](https://user-images.githubusercontent.com/6493321/134579702-5ea3bd5f-0833-4530-a871-c8f3a84ca59e.png)

![Screen Shot 2021-09-23 at 3 05 10 PM](https://user-images.githubusercontent.com/6493321/134579749-6177360c-ef31-47f1-a760-f458c930edeb.png)

Screenshot of my wallet DIKO token metadata:
![Screen Shot 2021-09-23 at 3 05 23 PM](https://user-images.githubusercontent.com/6493321/134579828-741f9582-e96c-4319-81ae-29dd63d06279.png)

**Comment by fbwoolf** [comment]
In summary, once the post conditions are correct on your end it should fix most of your issues. The only time you should still see the issue is if you don't have any of that particular token in your wallet.

**Comment by philiphacks** [comment]
@fbwoolf thanks!

could you point out exactly what is wrong (and how to fix it) though? The creation of post conditions is not very developer friendly atm... loads of trial and error, and if a little thing is wrong, it won't work apparently :)

**Comment by fbwoolf** [comment]
@philipdesmedt I think in the particular example I sent just the `assetName` and `contractName` are getting mixed up on your end. Once that is fixed, it should be good I think. So, here in your code:

https://github.com/arkadiko-dao/arkadiko/blob/85415b765f5c3ca2fe4640a24cfd72781e433476/web/components/add-swap-liquidity.tsx#L199

These must be getting mixed up:
```
tokenXParam,
tokenX['name'].toLowerCase()
```

On our end we are receiving:
```
"arkadiko-token"
"usda"
```

And for `Y`:
https://github.com/arkadiko-dao/arkadiko/blob/85415b765f5c3ca2fe4640a24cfd72781e433476/web/components/add-swap-liquidity.tsx#L233

```
tokenYParam,
tokenY['name'].toLowerCase()
```

We are receiving:
```
"usda-token"
"diko"
```

I think once those are sent into `createAssetInfo` correctly, it will fix it. 🤞 Will need to check other places post conditions and used. It seems like just some of the X and Y traits are getting mixed up before they are used with `createAssetInfo`.

**Comment by fbwoolf** [comment]
And, for ref, this is what I'm looking at in stacks.js:
https://github.com/blockstack/stacks.js/blob/626c5fccb4dff213f000923ab69c7ed4f5eb48a0/packages/transactions/src/types.ts#L425

**Comment by fbwoolf** [comment]
@aulneau also pointed out that the contractName is wrong in the logs I posted:

`"arkadiko-swap-token-diko-usda"`

This seems wrong here?
https://github.com/arkadiko-dao/arkadiko/blob/55d048043cda8a938e3319a17406b027c3e4d204/web/common/vault-utils.ts#L49

Used here:
https://github.com/arkadiko-dao/arkadiko/blob/85415b765f5c3ca2fe4640a24cfd72781e433476/web/components/add-swap-liquidity.tsx#L169

Both L45 and L49 have the same `name` and `swap` values.

**Comment by philipdesmedt** [comment]
@fbwoolf thank you!! I'm traveling today but will try this asap

**Comment by philiphacks** [comment]
@fbwoolf I tried your suggestions but I simply cannot figure things out, see screenshot

![image](https://user-images.githubusercontent.com/577420/134643350-71fb21ee-9590-407a-a12d-fa462f313aa2.png)

PR is here: https://github.com/arkadiko-dao/arkadiko/pull/222

It is not recognising the tokens (i.e. not parsing the decimals). Any ideas?

**Comment by philiphacks** [comment]
@fbwoolf the transaction succeeds if I multiply the amounts by 1.2 (20% higher margin) and change to LessEqual btw.. but the numbers are still not parsed
![image](https://user-images.githubusercontent.com/577420/134651377-7e2b15a0-4b1e-40db-87f3-e84f26670fe8.png)
![image](https://user-images.githubusercontent.com/577420/134651426-74f058f9-12de-4bbf-9c8f-974399a04bb8.png)

So the TX is accepted which means the info passed to the PC is correct I assume? Seems like a bug somewhere still in the wallet parsing the decimals?

**Comment by fbwoolf** [comment]
@philipdesmedt let me try your changes this morning. It seems like it should find those assets now in the conditional in our code. Let me look closer now that those changes have been made.

**Comment by fbwoolf** [comment]
@philipdesmedt it doesn't look like what you posted has the correct contract address for the tokens (they are the same for both)? That needs to match with the metadata from the token:

`ST26902A6NT1QSWQXXYM55EM579RY9CCPQDN02QW2`
https://stacks-node-api.testnet.stacks.co/extended/v1/tokens/ft/metadata

We query this and match it to your post condition, then we use that info to display it in the UI. If they don't match, it returns `undefined` and the decimals won't get parsed correctly.

Where is the contract address coming from that you are using?

**Comment by fbwoolf** [comment]
Looks like it is coming from an env variable?

**Comment by philiphacks** [comment]
@fbwoolf the contract address is the standard deployer address that is specified locally in Devnet.toml... I am not using testnet, I am using a local environment (clarinet integrate) to debug this. The contract address is 100% sure correct.

**Comment by philiphacks** [comment]
@fbwoolf would it maybe be due to the fact that FT metadata processing is not enabled?

When going to `http://localhost:3999/extended/v1/tokens/ft/metadata`, I get 
```{
  "error": "FT metadata processing is not enabled on this server"
}```

**Comment by aulneau** [comment]
> @fbwoolf would it maybe be due to the fact that FT metadata processing is not enabled?
> 
> When going to `http://localhost:3999/extended/v1/tokens/ft/metadata`, I get
> 
> ```
>   "error": "FT metadata processing is not enabled on this server"
> }```
> ```

This would 💯 cause it to fail in the ways you've described

**Comment by philiphacks** [comment]
@aulneau lol, damn :D sorry

can I enable it somewhere in settings?

**Comment by fbwoolf** [comment]
Well, at least we are incrementally getting this figured out! Ha. I am not familiar with how to get this working correctly on devnet so I'll do some digging.

**Comment by philiphacks** [comment]
@fbwoolf that'd be awesome, thanks! I asked Ludo and he told me to use & specify a custom docker image in Devnet.toml but I don't really know where to start here lol

**Comment by philiphacks** [comment]
@fbwoolf @aulneau I merged my local branch and deployed to testnet, and can confirm that adding liquidity post conditions now parse as expected
![image](https://user-images.githubusercontent.com/577420/134774828-437b8a83-ec7c-4d64-b581-4fb4a005e899.png)

Thanks! I think we'll have to figure out how to enable the FT metadata locally on devnet/mocknet, seems like something a lot of devs will run into as PCs need to be implemented more frequently.

**Comment by fbwoolf** [comment]
@philipdesmedt this is fantastic! Happy this got resolved for you. I have been reading through the devnet docs this morning. I'll make sure to bring this up on Monday to see what changes we can make to help out other devs with this. 👍 @markmhx

**Comment by markmhendrickson** [comment]
@agraebe @pgray-hiro perhaps you'd like to open a separate related docs issue here for helping developers configure DevNet with FT metadata support for situations like this one?
