### ISSUE TITLE
Subtract pending outbound tx amounts from available balance

### ISSUE THREAD

**Issue by kyranjamie** [leather-io/extension#1701]
For example, when sending a tx and then using the _Send max_ functionality, the outbound pending tx isn't considered.

**Comment by fbwoolf** [comment]
There has been conversation around not doing this, but it is still in the backlog? Should this be started? @aulneau I think you challenged not doing it?

**Comment by markmhendrickson** [comment]
I presume we still want this prioritized for the backlog, since we do this in the desktop wallet already and it seems to work well (and I don't recall the recent convo around not doing it). But curious to hear what @aulneau thinks if he has concerns.

**Comment by markmhendrickson** [comment]
@timstackblock to retest

**Comment by Eshwari007** [comment]
Findings:
`For example, when sending a tx and then using the Send max functionality, the outbound pending tx isn't considered.`

The use case mentioned above by @kyranjamie hasn't been fixed.

Testing scenario:

- I transferred STX from account 1 to account 2
- Tx is pending in account 1.

Results:

- Before the tx, I tested the account send max functionality with Low fee rate 
- After the tx, I retested the same account send max functionality with Low fee rate

They were the same amount which means that the `Send Max `didn't take into the account the STX tx which is yet pending

<img width="398" alt="Screen Shot 2022-05-03 at 4 00 21 PM" src="https://user-images.githubusercontent.com/38872890/166557013-45525358-efa7-425a-b2c8-a3c206a5de1d.png">
<img width="385" alt="Screen Shot 2022-05-03 at 4 00 28 PM" src="https://user-images.githubusercontent.com/38872890/166557016-129b2cb1-bd67-4127-abc5-585e6b1de25c.png">
<img width="388" alt="Screen Shot 2022-05-03 at 4 04 17 PM" src="https://user-images.githubusercontent.com/38872890/166557019-acb89b33-a429-4629-b4fc-cedb4eeb5879.png">

cc @markmhx 
Moving it back to the backlog.

**Comment by markmhendrickson** [comment]
@fbwoolf want to take this one?

**Comment by fbwoolf** [comment]
> @fbwoolf want to take this one?

Yep, for sure. 👍

**Comment by fbwoolf** [comment]
@kyranjamie I'm working on this, but do you think we should ask the api team to add a `pending_balance` to `/extended/v1/address/{principal}/stx`?

**Comment by fbwoolf** [comment]
Also, are we wanting to subtract out just pending txs or locally 'submitted' tx balances too?

EDIT: I put up a PR, so just did pending txs unless CR says otherwise.

**Comment by markmhendrickson** [comment]
If we expect submitted balances to eventually go through as pending, then I presume it'd be best to subtract them as well?

**Comment by kyranjamie** [comment]
I'd just use the mempool amounts to subtract "pending balances". We could also subtract submitted amounts, but this should only ever be a short-lived state, and sometimes it goes wrong, so I would avoid this to begin with. I don't think we need a new API prop.

This is how it's done in desktop wallet https://github.com/hirosystems/stacks-wallet/blob/d35bffa0a072a7d03212004f260bc59ff1259ea5/app/utils/tx-utils.ts#L67-L69

**Comment by Eshwari007** [comment]
Quick questions:

@fbwoolf 

- Is the use case above applicable when the user selects  `Max`amount only?
- Can the user input a specific amount and test the available balance with the pending outbound as well?

**Comment by Eshwari007** [comment]
As I was testing Max amount ,noticed the following:

- User send from account A to B with max amount of STX
- User notices that the tx is Pending
- User then selects account A-STX and when try to selects MAX,there were no action( no values were presented in the stx amount box)
- Though I understand the amount has been subtracted but felt it can be a little confusing when a user sees the balance value of STX yet visible(though the max tx is pending), no amount is presented when the user selects MAX.

The screen recording below can explain the scenario better.

https://user-images.githubusercontent.com/38872890/168320147-e8b188ba-fc37-4a10-a31d-52571f0a0579.mov


cc @markmhx @fbwoolf

**Comment by fbwoolf** [comment]
> 
> The screen recording below can explain the scenario better.
> 
Yep, that is expected but not sure if there is more info we want to provide if the pending tx is using all available STX? We could def provide an error message below the input field in this situation?

**Comment by Eshwari007** [comment]
> > The screen recording below can explain the scenario better.
> 
> Yep, that is expected but not sure if there is more info we want to provide if the pending tx is using all available STX? We could def provide an error message below the input field in this situation?

Yes, highly agree with you in providing an error message below the input field in this situation, esp for new users/beginners -the info will be helpful

@markmhx any inputs on the error message or warnings for the scenario mentioned above.

**Comment by Eshwari007** [comment]
Also is this applicable only for STX?
I did not see the max amount change for non STX token such as STSW and Wrapped nothing(these are tokens on the test account)

**Comment by fbwoolf** [comment]
> Also is this applicable only for STX? I did not see the max amount change for non STX token such as STSW and Wrapped nothing(these are tokens on the test account)

Yep, this is only for STX.

**Comment by Eshwari007** [comment]
> > Also is this applicable only for STX? I did not see the max amount change for non STX token such as STSW and Wrapped nothing(these are tokens on the test account)
> 
> Yep, this is only for STX.

Is there any future enhancement plan for the non-Stx tokens?
@markmhx

**Comment by Eshwari007** [comment]
Test passed except for the error message/warning which will be ideal for the use case above.
Pinged Mark on it along with a potential enhancement ticket for the non STX ticket

**Comment by markmhendrickson** [comment]
Ideally we should have this for STX and non-STX assets, even if we release both as separate enhancements. @Eshwari007 please do create a separate ticket for non-STX assets 🙏

**Comment by Eshwari007** [comment]
> Ideally we should have this for STX and non-STX assets, even if we release both as separate enhancements. @Eshwari007 please do create a separate ticket for non-STX assets 🙏

How abt the error message or warning when user selects Max while a pending tx with full Max tx is in the process as well thus has no inputs when the user selects the Max button.( the scenario on the video above)
cc @markmhx

**Comment by markmhendrickson** [comment]
Let's create a separate issue for this message as an enhancement 🙏

**Comment by Eshwari007** [comment]
https://github.com/hirosystems/stacks-wallet-web/issues/2418
https://github.com/hirosystems/stacks-wallet-web/issues/2417

The above tickets were created as Enhancements to address QA's findings.
