### ISSUE TITLE
Link to "Learn more about microblocks" directing to hiro.so

### ISSUE THREAD

**Issue by ginny-d** [leather-io/extension#1702]
<img width="388" alt="Screenshot 2021-09-11 at 09 33 10" src="https://user-images.githubusercontent.com/78865845/132940373-f7cf0ee8-9506-42ea-ae49-829447547a34.png">

When I click on the Learn more about microblocks tooltip, it just directs to Hiro's homepage

**Comment by markmhendrickson** [comment]
I believe @beguene fixed this but we haven't shipped the change quite yet it appears? https://github.com/blockstack/stacks-wallet-web/issues/1600
