### ISSUE TITLE
Names registers but page doesn't update.  Error adding an account on wink 

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#171]
When adding an additional account on my mobile phone after hitting the submit button the screen refreshes and I am still on the same screen. But when I enter the same account name again it says the name is taken. 

It appears the name has registered in the back ground but I am being routed to the same page.

![Screenshot_20200217-102333_Firefox](https://user-images.githubusercontent.com/49165468/74666663-e7c6b300-516f-11ea-8311-0b1b9be096a8.jpg)
![Screenshot_20200217-102320_Firefox](https://user-images.githubusercontent.com/49165468/74666661-e72e1c80-516f-11ea-8f31-7a8e9aaa685a.jpg)
![Screenshot_20200217-102346_Firefox](https://user-images.githubusercontent.com/49165468/74666666-e7c6b300-516f-11ea-8c71-4a63f3d8344e.jpg)

**Comment by timstackblock** [comment]
This bug was found on mobile Mozilla Firefox Galaxy 9

**Comment by hstove** [comment]
Is this still reproducible? I am not able to replicate.

**Comment by markmhendrickson** [comment]
I was just able to submit the username for an additional account using Wink on desktop (Mac / Chrome).
