### ISSUE TITLE
Disable iOS zoom on field focus and username capitalization

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#183]
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/4e59bf52-f5fa-4211-a27b-fa5284fac97f)

On iOS, the font-size triggers a zoom when you focus a field. Can we disable this (without increasing font size)?

The first letter is also capitalized by default on iOS, which is not allowed for a username. Need to use autocapitalize=none.

**Comment by kyranjamie** [comment]
I've added this attribute on the PR I just made.

I don't think there's a way around auto zoom, as this is an accessibility feature. Shall we make it 16px?
