### ISSUE TITLE
Update "name" property in tracking to use screen name value

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#187]
**See https://github.com/blockstack/app/issues/187#issuecomment-591887251 below for new instructions for this issue.**

––

It seems that although we've added `title` values per https://github.com/blockstack/app/issues/149, we're still reporting `name` values for these events and inaccurately at that:

![Screen Shot 2020-02-18 at 14.04.24.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/e6ac9854-9efa-489a-87aa-75e0cf39eb57)

Name values are unneeded now in general so we can remove them completely.

**Comment by hstove** [comment]
I thought we talked about this, and agreed that keeping (and using `name`) was good? Because the "title" may change, as a display property, but we can always keep "name" consistent.

Also, in this case, it was the title that was inaccurate, not the name.

**Comment by markmhendrickson** [comment]
I think I created this issue before our chat about keeping a more canonical attribute.

The value for `name` here is getting set as the same non-canonical page title value as the `title` attribute, and as such, we need to update it to use the screen state values found here: https://github.com/blockstack/app/blob/5934829a40338ac269b80783912c8dad17af1962/packages/app/src/store/onboarding/types.ts#L9

e.g. `screens/SECRET_KEY` instead of `Copy Secret Key`.

I'd also recommend simplifying those screen name values so they're not so verbose and uppercase (e.g. `secret_key` instead of `screens/SECRET_KEY`) unless we're relying on the current format for something.

Alternatively to the above approach, we could also pass a manually created URL into Segment for tracking state, which may be most elegant so no one viewing reports in the future has to remember this special one-off `name` attribute (something we ourselves are likely to forget months from now):

e.g. `https://app.blockstack.org/secret_key` passed as `url` to https://segment.com/docs/connections/spec/page/
