### ISSUE TITLE
Ensure every page view tracked accurately

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#201]
It doesn't appear as though we're accurately tracking all uniques to each page of the onboarding flow:

![image.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/5b83d0cb-c85d-4c53-9d7f-e88220fff89e)

![Onboarding.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/8477cd66-4637-47f4-bcda-a76fdb858b6a)

**Comment by hstove** [comment]
Can you be more explicit about what you think is missing?

The page after 'Save Secret Key' is now 'Username', also.

**Comment by markmhendrickson** [comment]
The biggest thing missing is the "Choose a username" page views not getting reported here except for 1.

Did we roll out a name change for this screen recently? It seemed to be called "Choose a username" via Wink earlier today. So despite that change, I'd expect to see more data for that page's view.

**Comment by hstove** [comment]
@markmhx this is in prod - please QA and close or add issues!

**Comment by markmhendrickson** [comment]
The funnel is tracking completely now: 

![Onboarding](https://user-images.githubusercontent.com/28991/75034716-20d39000-54ae-11ea-8648-06615dedddf4.png)
