### ISSUE TITLE
Add event for username submission 

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#204]
"Submit Username" for both onboarding and sign in:

![image.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/173ee04d-c17c-4ab1-be32-16e134f891d8)

**Comment by hstove** [comment]
Do you want "Submit Username" to fire even if it's invalid? I'm thinking we want "Submit Username - Validation Error", "Submit Username - Success" as well. We also just added "Username Registration Failed" if they get rate limited.

**Comment by markmhendrickson** [comment]
I'm happy with either firing this only when its valid / successful or adding those two variants you have in mind. I'm looking to track just the success scenario for now, but seeing failures could be helpful theoretically.

"Username Registration Failed" sounds good but let's keep this grammatically as "Fail Username Registration" (despite it sounding funny) given the standard is to use present tense a la https://segment.com/academy/collecting-data/naming-conventions-for-clean-data/

**Comment by markmhendrickson** [comment]
It'd be great to get this event instrumented today so we can run the full funnel over the weekend, now that https://github.com/blockstack/app/pull/212 resolves tracking in general.
