### ISSUE TITLE
Return user to same step of onboarding flow if they previously closed window

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#214]
As described [here](https://github.com/blockstack/connect/issues/8#issuecomment-588541390), if a user starts the authentication process for the first time during onboarding but closes the Blockstack App before submitting a username, they'll end up with a username-less keypair, which shows up as a username with random characters when they subsequently try to authenticate.

The user would encounter a similar problem if they initiated onboarding but closed the window before seeing or saving their Secret Key.

As such, we should save the user's step state until they successfully submit a username at the very end and use that state should they return to the Blockstack App to show them the last step they viewed so they can proceed from that point onward and complete onboarding fully.

**Comment by timstackblock** [comment]
Still getting the same key less pair, let me verify I am testing on the correct branch during the stand up.

[Uploading... Screen Shot 2020-03-13 at 8.42.19 AM.png ]
