### ISSUE TITLE
Provide option to view Secret Key from index

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#215]
If the user navigates to the Blockstack App's homepage / index, we can show an option to "View Secret Key" that displays it again for them, since currently we have no way for the user to review it should they have failed to persist it during onboarding but maintain a session.

And add option to choose account screen to get here.

**Comment by jasperjansz** [comment]
Design: https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=7265%3A146

assigning thomas as he's worked on the index

**Comment by timstackblock** [comment]
Broken image icon in the top left corner

![Screen Shot 2020-03-12 at 10.59.11 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/c873a4a7-c5cd-428d-9e56-8870b1606dd1)

**Comment by hstove** [comment]
Good catch @timstackblock - I've pushed a fix to prod, please confirm on your end :+1:

**Comment by friedger** [comment]
Works for me :-)
