### ISSUE TITLE
Ensure display of full username on choose account screen

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#217]
E.g. with overflow-wrap

<img width="455" alt="Screen Shot 2020-02-21 at 14 30 41" src="https://user-images.githubusercontent.com/28991/75038518-cc80de00-54b6-11ea-8366-586233998d95.png">

**Comment by jasperjansz** [comment]
We already have designs for this: https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=7059%3A0
