### ISSUE TITLE
Remove display of username domain in UI unless paid ID

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#221]
e.g.

- "mark" if "mark.blockstack.id" (free name)
- "mark.id" if "mark.id" (paid name)

![Screen Shot 2020-02-24 at 10.55.22.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/d6efc6e6-43da-4bca-a863-d29956a71116)

![Screen Shot 2020-02-24 at 10.55.31.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/8c295692-2070-4256-bb01-f6a29c34a4fd)

**Comment by hstove** [comment]
Ready for QA

**Comment by timstackblock** [comment]
The infinite spinner is blocking my test, once that is resolved I can retry.

**Comment by timstackblock** [comment]
this works as expected
