### ISSUE TITLE
Dashlane: password save prompt closes when window does

### ISSUE THREAD

**Issue by kyranjamie** [leather-io/extension#223]
When you're on the last step of the flow, choosing a username, clicking the button prompts the Dashlane dialog to open. When the username registration is successful, the popup auto-closes, which in turn causes the password prompt to close, regardless of whether you've saved the password or not.

**Demo of window closing before saving Secret Key**
![dashlane-issue](https://user-images.githubusercontent.com/1618764/75175695-2392e700-5733-11ea-838f-4e1ebe1f8d9f.gif)

**Comment by timstackblock** [comment]
This is resolved
