### ISSUE TITLE
LastPass doesn't prompt to save Secret Key

### ISSUE THREAD

**Issue by kyranjamie** [leather-io/extension#224]
As mentioned in article, LastPass might require elements to be hidden using DOM tricks, `opacity: 0`, rather than display none.

https://hiddedevries.nl/en/blog/2018-01-13-making-password-managers-play-ball-with-your-login-form

**Comment by kyranjamie** [comment]
It's worth waiting until we decide what to do with a final screen before attempting to fix this one, as that may in itself be the fix.

**Comment by timstackblock** [comment]
![Screen Shot 2020-03-06 at 8.35.02 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/a7d55a04-8598-4f3c-b68b-b33a5f84194d)
