### ISSUE TITLE
Support Chrome password manager

### ISSUE THREAD

**Issue by kyranjamie** [leather-io/extension#225]
As [discussed on our internal Slack](https://blockstackpbc.slack.com/archives/CD0CTNATW/p1582560772009100), there are some issues interacting with password managers relating to the dialog auto-closing when the userrname registration completes. Some extensions inject content into the DOM of the host window, or the behaviour is tied to the window. In either case you're often unable to save your password with an autoclosing window.

**Chrome MacOS**
![image](https://user-images.githubusercontent.com/1618764/75176503-90f34780-5734-11ea-8c15-b3ee79d37024.png)

As soon as you interact with the username field the password key appears. It is possible to save the password if you interact with the key before pressing `Continue` button. You lose the opportunity to save your password if you press continue before saving your password.

**Comment by jasperjansz** [comment]
Assigning to Kyran to see if we can do it on the 'Save Secret Key' screen. If not, assign back to me.

**Comment by timstackblock** [comment]
I am not getting a prompt to save my password in Chrome, this doesn't seem to trigger the action anymore.

**Comment by timstackblock** [comment]
My password setting are enabled

![Screen Shot 2020-03-10 at 8.53.24 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/c3019f08-18b6-423f-8063-72b3fac40cf5)
