### ISSUE TITLE
Apply color passed from Blockstack Connect to customize theme

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#229]
The color should replace all instances of our "Blockstack blue" throughout the app experience during the visit.

To work in conjunction with https://github.com/blockstack/connect/issues/78.

**Comment by kyranjamie** [comment]
Not to overthink this feature, but worth considering what happens when someone passes #fff, or some other incredibly pale colour. 

Do we need to pass a text colour, too? Should we prohibit colours that don't pass AA WAI-ARIA standards?

**Comment by jasperjansz** [comment]
I think for now we should just provide instructions in the readme on passing an acceptable colour
