### ISSUE TITLE
Disable email auto-suggestions for username prompt

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#246]
![Screen Shot 2020-02-27 at 12.11.46.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/3e95688a-20bc-4735-8a3c-752353a4cdc5)

**Comment by aulneau** [comment]
I'm not sure we want this. The autocomplete attrs was added for the password managers to pick it up. @kyranjamie if we remove autoComplete, will it render it useless for password managers to pick up?
