### ISSUE TITLE
Fix styles for modal close option in Safari

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#247]
![Screen Shot 2020-02-27 at 16.34.59.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/9f3db9cd-2549-4af8-a36d-d05d04fc3766)

**Comment by aulneau** [comment]
Tracked here: https://github.com/blockstack/ux/issues/243

**Comment by timstackblock** [comment]
resolved

![Screen Shot 2020-03-06 at 10.16.19 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/bf7e7e0e-92b9-4cab-b84b-ce62e8d3f6be)

**Comment by aulneau** [comment]
@timstackblock what staging are you testing?
