### ISSUE TITLE
Powered by blockstack is separated from logo

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#252]
When generating a secret key you will notice that Powered by blockstack is separated at the bottom.

<img width="429" alt="Screen Shot 2020-03-01 at 2 14 06 PM" src="https://user-images.githubusercontent.com/49165468/75632122-18263c80-5bc7-11ea-94eb-97ca79a9ac69.png">

**Comment by hstove** [comment]
Please also address https://github.com/blockstack/ux/issues/245

**Comment by kyranjamie** [comment]
I've tested in Chrome, Firefox and Safari and can't see this problem. @aulneau, did this get fixed with the scoped css stuff?

**Comment by markmhendrickson** [comment]
@aulneau do you want to take over here now that @kyranjamie is OOO?

**Comment by aulneau** [comment]
@markmhx yes
