### ISSUE TITLE
infinite spinner when trying to login using magic recovery code

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#253]
<img width="442" alt="Screen Shot 2020-03-01 at 2 55 16 PM" src="https://user-images.githubusercontent.com/49165468/75632687-b10b8680-5bcc-11ea-83d4-565e105002ab.png">

<img width="636" alt="Screen Shot 2020-03-01 at 3 09 28 PM" src="https://user-images.githubusercontent.com/49165468/75632935-c2559280-5bce-11ea-97fd-223164f4a5d0.png">

I get an infinite spinner when trying to login using my magic recovery code, this is consistent across all browsers

I enter the recover code and after I enter the password and press enter the infinite spinner occurs
 
PLEASE SEE VIDEO FOR DETAILS
http://somup.com/cYeVqshuKm

**Comment by markmhendrickson** [comment]
I'm getting the same problem

**Comment by timstackblock** [comment]
Resolved
