### ISSUE TITLE
Error when using @blockstack/connect - needs @blockstack/ui installed

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#254]
A discord user reported the following error when trying to use connect:

![image](https://user-images.githubusercontent.com/1109058/75636925-c9cd6980-5bd7-11ea-9b3f-04f8351274f7.png)

We should resolve this - either by making it clear that `ui` is a peerDependency, or by adding it as an explicit dependency.

**Comment by markmhendrickson** [comment]
@hstove is this dependency issue still relevant and worth resolving soon?

**Comment by hstove** [comment]
Not relevant after merging #582
