### ISSUE TITLE
Husky lint:fix

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#259]
I find that sometimes builds fail because of a prettier fix that could have been run automatically, and fixed, but isn't. Since we are using husky for commitlint, I feel like we could also easily use it to run prettier automatically as a pre-commit and fix the basic stuff. cc @hstove @kyranjamie

**Comment by kyranjamie** [comment]
I don't think we should do this. It gets very frustrating when there's a long delay after creating/amending a commit. 

I've tried before. Both myself, and the rest of the team, eventually learnt to add `--no-verify` to all their commits, mitigating the value of it anyway.

**Comment by hstove** [comment]
I agree that a pre-commit hook is undesirable.

I think the only reason Prettier doesn't get auto-fixed is because `eslint` only checks for `.ts/.tsx`, whereas the prettier command also checks for `.js`. We should just update eslint to check `.js` files.
