### ISSUE TITLE
Ensure page view trigger when going back to view Secret Key

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#276]
When I select the option to "View Secret Key again" to go back to the "Your Secret Key" screen, the latter's screen page view event doesn't get triggered.

<img width="443" alt="Screen Shot 2020-03-06 at 14 35 48" src="https://user-images.githubusercontent.com/28991/76088201-e7c01300-5fb7-11ea-842a-50163f4c858e.png">
<img width="448" alt="Screen Shot 2020-03-06 at 14 35 40" src="https://user-images.githubusercontent.com/28991/76088197-e5f64f80-5fb7-11ea-962a-65dc864ba43d.png">

**Comment by timstackblock** [comment]
resolved
