### ISSUE TITLE
Import recent changes from Wink into onboarding

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#28]
@kyranjamie - a week ago, I ported over the onboarding code from our beta app. I see you've added some changes to that app recently. Let's make sure those changes get incorporated here (if they're part of onboarding), and then also make sure we're not duplicating too much work moving forward.

Hopefully, we'll be able to ditch the dummy onboarding of the beta app soon, so we can focus on work in this repo.

**Comment by kyranjamie** [comment]
I made some relatively minor changes. Happy to jump in and help out, although probably better to work from this repo, than try copy/pasting in old code.

**Comment by hstove** [comment]
For sure, no need to blindly copy/paste. When I ported the code over, I did copy/paste, but I also did a ton of cleanup and refactoring to get it to a more durable state.
