### ISSUE TITLE
Confirm button for transaction signing not visible

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#302]
On smaller screens the confirm button is not visible

![Screenshot from 2020-03-30 18-27-01](https://user-images.githubusercontent.com/1449049/77937880-3b6f0500-72b5-11ea-9c49-181b1b9e94e5.png)

Related to #273

**Comment by hstove** [comment]
Are you able to scroll down? We can also increase the default height on this popup, but given that the height is dynamic, we can't be sure the button is always above the fold.

**Comment by friedger** [comment]
There is no way to scroll, that is the main issue

Hank Stoever <notifications@github.com> schrieb am Do., 2. Apr. 2020, 18:08:

**Comment by timstackblock** [comment]
@hstove There are issues here but it is only on firefox mobile. Firefox desktop works. 

The button appears normal in Chrome on a Samsung galaxy 9


![Screenshot_20200609-155438_Chrome.jpg](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/b54cd7bc-fc4b-44e4-8c32-4163ef8650bb)



I get an infinite spinner in Firefox on a Samsung galaxy 9

![Screenshot_20200609-155739_Firefox.jpg](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/387c1328-572e-4611-979f-d6d5bfaec519)

**Comment by markmhx** [comment]
@timstackblock Can you create a separate issue for this infinite spinner issue or link it here if already available?

And were you able to confirm that this modal now scrolls (apart from the spinner issue?)

**Comment by markmhendrickson** [comment]
I just tested this myself in Chrome and Firefox and it scrolls for me. So I'm going to close this out.

@friedger please re-open with more system information if you still can't scroll here.

![Screen Shot 2020-06-18 at 14.00.58.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/4647818a-a5a9-4610-8682-8e9502b049d9)
