### ISSUE TITLE
Execute JS Callback(s) after TX signed

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#304]

**Comment by markmhendrickson** [comment]
Can you write out a definition of all the callbacks here, their exact triggers, and they're parameters?

I believe based on previous conversation we discussed having callbacks at the following lifecycle moments:

- TX sign started / in process
- TX sign confirmed
- TX sign in process more than 10 seconds (or similar delay, for apps to handle if it's unexpectedly slow)?

I assume these are callbacks from the authenticator to the app, correct?

Also, is this issue's execution blocked by the availability of any external API?
