### ISSUE TITLE
Automatically fill STX wallet from faucet if necessary

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#306]

**Comment by markmhendrickson** [comment]
@jasperjansz Can you provide a link to the corresponding Figma design here (when the user has to wait for STX to fill their wallet upon initiation of transaction signing)?

@hstove can you reference a link to the faucet API work on this issue?

**Comment by jasperjansz** [comment]
https://www.figma.com/file/Wan0HuWjhyg77zJZK3yUKg/Transaction-signing?node-id=45%3A226
