### ISSUE TITLE
Show error messages during TX signing

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#307]

**Comment by markmhendrickson** [comment]
@jasperjansz Can you provide Figma guidance here for all possible message states?

**Comment by jasperjansz** [comment]
https://www.figma.com/file/Wan0HuWjhyg77zJZK3yUKg/Transaction-signing?node-id=97%3A1030


Couple questions here:
- In debug mode, do we want to show logs in case of an error? My assumption is yes.
- Are there potential errors before you click the confirm transaction button, or after, or both? This only includes after.

**Comment by markmhendrickson** [comment]
@timstackblock needs URL for host and deploy instructions to QA

**Comment by timstackblock** [comment]
Thanks @markmhx  @hstove please post the URL and deploy instructions here

**Comment by timstackblock** [comment]
I cant access https://www.figma.com/file/Wan0HuWjhyg77zJZK3yUKg/Transaction-signing?node-id=97%3A1030 ![Screen Shot 2020-05-01 at 8.32.52 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/a1caffa4-9506-43c3-b4a3-cc39d7095e1a)

**Comment by hstove** [comment]
You might need to request access - the link worked for me just now.

Also for those reading the thread, the URL to demo this stuff is at: https://deploy-preview-301--authenticator-demo.netlify.app

**Comment by timstackblock** [comment]
Linking the error below

https://github.com/blockstack/ux/issues/361

**Comment by timstackblock** [comment]
URLs are being updated to point to staging side car as crashy-stacky sidecar no longer works see images below.

<img width="1431" alt="Screen Shot 2020-05-08 at 11 05 10 AM" src="https://user-images.githubusercontent.com/49165468/81568393-b246f580-936b-11ea-9d7c-4fecd1a934c1.png">

**Comment by markmhendrickson** [comment]
This is getting updated as well on https://github.com/blockstack/blockstack.org/issues/1112

**Comment by hstove** [comment]
I need to update the sidecar URL away from crashy-stacky to our new URL.

**Comment by hstove** [comment]
@timstackblock can you re-QA this? I think everything should be steady now with error messages. I have a new ticket, #390, for showing an error in the case of a timeout.

**Comment by timstackblock** [comment]
To verify this on the Netlify link I need to generate a failed transaction for the following transaction types:

- Token transfer transactions
- Contract creation transaction
- Contract call transaction

Is this currently possible with sidecar.staging.blockstack.xyz?

**Comment by timstackblock** [comment]
Looks good 

![Screen Shot 2020-05-20 at 11.04.11 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/57daa08d-0d9c-445c-ae4e-637e307002de)
