### ISSUE TITLE
Show pending state during TX signing

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#308]

**Comment by markmhendrickson** [comment]
@jasperjansz Can you provide Figma guidance here?

**Comment by jasperjansz** [comment]
https://www.figma.com/file/Wan0HuWjhyg77zJZK3yUKg/Transaction-signing?node-id=97%3A1107

@hstove I animated the loading and confirmation icon. It's a simple .svg animation, so should be easy to implement. We can have Pending_animated.svg loop while the transaction is pending and play Confirmed_animated.svg once when it has been confirmed.

![Pending_animated.svg](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/6b0b1e29-3412-4d17-b23a-6bc8b9582e50)![Confirmed_animated.svg](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/d3b57ad0-f967-40a3-9612-dde606e45e44)
