### ISSUE TITLE
Handle Post Conditions

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#309]
- Allow developer to pass post-conditions via Connect
- Show post-conditions in debug mode
- Include post-conditions in the signed TX

**Comment by markmhendrickson** [comment]
@jasperjansz Can you provide Figma guidance here?

**Comment by jasperjansz** [comment]
https://www.figma.com/file/Wan0HuWjhyg77zJZK3yUKg/Transaction-signing?node-id=45%3A1

**Comment by markmhendrickson** [comment]
@hstove The related PR appears to be under development still. Should we move this issue back to development as well?

**Comment by hstove** [comment]
No - this is meant to be in "code review". It depends on the transaction signing PR infra - although I'm realizing maybe I should have pushed it to a new PR, on top of the TX signing branch.

**Comment by markmhendrickson** [comment]
I see, so it's finished code review but awaiting deployment to staging for QA (dependent on that transaction signing infra).

**Comment by hstove** [comment]
Yes - also dependent on https://github.com/blockstack/stacks-transactions-js/pull/101
