### ISSUE TITLE
Support read-only contract calls

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#313]

**Comment by markmhendrickson** [comment]
@hstove Can you indicate what API is blocking this issue's execution and who's expected to provide it?

**Comment by friedger** [comment]
For connect, doContractCall opens the window and tries to make public call, this fails with NoSuchPublicFunction.

Instead doContractCall should have a flag `read-only` and then just call the read-only api

**Comment by hstove** [comment]
We don't want to have to make the user open the popup, because they don't need to sign anything to call the read-only function. It can be called with the RPC API directly.

This repo has the [RPC Client](https://github.com/blockstack/ux/blob/master/packages/rpc-client/src/index.ts#L89) API, which has a `callReadOnly` function. I think we're still figuring out the best place for this code. I wrote that package to use it within this repo, but we may move it outside or to a different repo. You can view examples of calling the read-only API in the test-app.

**Comment by hstove** [comment]
> Instead doContractCall should have a flag read-only and then just call the read-only api

I like the idea of having this exposed within Connect, so the developer API for all things Clarity is in one place.

**Comment by yknl** [comment]
I think we should move the RPC client to the network package in the new Stacks monorepo. https://github.com/blockstack/blockstack.js/issues/810

cc @zone117x has been working on an API client as well. https://github.com/blockstack/stacks-blockchain-api/issues/170

**Comment by hstove** [comment]
Yes, this API call should be part of the API client library, not part of the UX monorepo. I'm going to close this one.
