### ISSUE TITLE
Feature Idea/Request: Customize The Authentication Interface

### ISSUE THREAD

**Issue by laytond** [leather-io/extension#315]
It could be nice to lightly modify the appearance or language of the authentication modal.

For example, an app may use standard login/logout/signup/account terminology, but then users are introduced to "secret key" and encryption language in the authenticator modal. So this app may want to supplement or tweak language in the authenticator so it feels more cohesive within the user's context of the app. Maybe the first line about protecting everything you do would become something like, _"You're creating an account and will receive a secret key that encrypts everything in it"_ 

Sounds like there may already be branding customization in the works, but if not it would be nice to support color and icon swapping as well as changing copy.

**Comment by markmhendrickson** [comment]
Thanks for submitting this idea, @laytond! Mind if I ask for which app you'd like to have this so I can take a look?

**Comment by laytond** [comment]
To be honest this is just something I'm spinning around in my head @markmhx, it's not necessarily for a specific app at the moment.

I think I was mostly getting hung up on semantics a bit, thinking about how "get started" may not feel right as the primary call to action if they were in an app that provided functionality before being authenticated.

In an example app like Banter you can't post without authentication, so you need to get started... That makes sense.

If you have an app that provides utility before authentication, say a shopping app where you can browse the catalog and build a shopping cart, but you authenticate when you want to save shopping history for later...then I feel like a more generic "log in" or "sign up" CTA may make more sense to the user. Then again something like "my account" could work decently in this case....

Anyway this is certainly not a high priority, as I can't even give you a specific example right now 😄. I suppose I just want to be able to modify copy on the app and authenticator side, so the flow feels cohesive and contextual.

**Comment by markmhendrickson** [comment]
Good thoughts 🙏  I agree the case in which the user has already gotten started doesn't work well with our framing here. @jasperjansz and I have explored ways in which this UI can be deferred entirely, though we should look more into the shopping app case in particular to make sure our research aligns.

We'll also consider ways to make the UI customizable in the meantime.

**Comment by laytond** [comment]
Awesome, thanks guys!

**Comment by markmhendrickson** [comment]
It looks like stale bot wanted to close this out, but cc'ing @jasperjansz since we're doing a bunch of holistic design work on the onboarding flow again, so he can perhaps absorb these feedback into that.
