### ISSUE TITLE
The apps array in user profile is not getting populated

### ISSUE THREAD

**Issue by muneebm** [leather-io/extension#316]
It seems like the new authentication doesn’t create entries in apps array in user profile.
Please see below the code I am using for authentication:

```javascript
const authOptions = {
          userSession: new UserSession({
              appConfig: new AppConfig(['store_write', 'publish_data'], window.location.origin)
          }),
          appDetails: {
            name: 'xordrive',
            icon: iconPath
          },
          sendToSignIn: signIn,
          finished: ({ userSession }) => {
            // set user session
          }
        }
showBlockstackConnect(authOptions)
```

**Comment by hstove** [comment]
@muneebm I've pushed a fix to the authenticator that should fix this - there was an issue with how we were handling scopes. We had the logic setup properly to update the `apps` array, but there was an issue with how we handled scopes in a certain part of the flow. Please try again and let me know if it's still an issue.

**Comment by muneebm** [comment]
That fixed it! Thanks @hstove
