### ISSUE TITLE
[connect] showBlockstackConnect shows error

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#319]
When calling `showBlockstackConnect`, the react app shows:

`This must be used within the ConnectProvider component.`

My understanding was that using `showBlockstackConnect` does not require any react related components.

Source code for a demo app is my animal kingdom: https://github.com/friedger/animal-kingdom-1/tree/feature/connect

**Comment by hstove** [comment]
@friedger, looks like it's working now?

Either way, you should _not_ be using `showBlockstackConnect` from within a React app. It is designed for the opposite purpose. Inside this function, it's calling `ReactDOM.render`, so you now would have nested React apps. Recipe for disaster.

**Comment by hstove** [comment]
The method `showBlockstackConnect` also does include React. That's how it shows our UI - it's importing ReactDOM under the hood.

**Comment by timstackblock** [comment]
@hstove from your comments above this seems to not be an issue, is this still a valid bug. Can we  access animal kingdom through the netlify link or should I run this locally?
