### ISSUE TITLE
Rewrite Connect UI in non-React way

### ISSUE THREAD

**Issue by jorishermans** [leather-io/extension#320]
Stencil.js is a build tool that uses JSX to create web components that can be used in any front-end framework. Stenciljs is from the team of ionic, they made it so that they are less dependend on angular.

https://stenciljs.com/

This will make it more appealing to a lot more developers.

**Comment by dantrevino** [comment]
@jorishermans I'm 100% in favor of reducting size and dependencies, but would this really reduce dependencies if i'm pulling in stencil libs vs react libs?  Have you looked at the overhead?

**Comment by jorishermans** [comment]
@dantrevino stenciljs is a build tool, it has no stenciljs library that will ship with it, this reduces the size and dependencies. Ionic has build this tool because of this reason, in the past ionic was build on top of angular, now they want to create components with zero dependencies.

Stenciljs builds code to vanila web components, but you still have the tools with jsx and others on development time. So for this purpose a great tool to look into in my opinion. The only right path to move forward with.

I don't want to have a dependency on whatever framework in these kind of libraries because of less usage of functionality, size, big dependency when not using in this case react.js. So we need to find a solution here.

**Comment by jorishermans** [comment]
You can find more info here https://stenciljs.com/docs/overview

**Comment by kyranjamie** [comment]
Thanks for the suggestion @jorishermans

**Comment by kyranjamie** [comment]
@markmhx The potential kB saving isn't the primary goal of @jorishermans' suggestion.

[Some users](https://forum.blockstack.org/t/blockstack-new-auth-signin-not-working-angular/10520/1) have reported difficulties using our React implementation of Connect with other frameworks. Stencil.js presents one way of implementing a framework agnostic library.

**Comment by markmhendrickson** [comment]
@jorishermans are you finding it difficult to integrate Connect with a specific library at the moment? Asking just to confirm the precise problem we're trying to solve here for you.

**Comment by jorishermans** [comment]
@markmhx I am developing my application in vue.js and now I am going with nuxt.js (serverside vue.js) 

Having less dependencies is a nice to have win, together with the savings of KB's.

With this, connect and other UX components will be closer to web standards, because stencil.js builds web components. 

It will also be a better sign to other developers that they can use web components and not a specific framework like react. I know that there is a guide to use it with es6 and that is also what I am using at the moment.

**Comment by markmhendrickson** [comment]
@hstove is going to investigate how to remove React here as a dependency
