### ISSUE TITLE
[app] Add support for collections

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#321]
The authenticator should handle collection scopes

**Comment by markmhendrickson** [comment]
@hstove got a general idea of the work involved to make this happen?

**Comment by friedger** [comment]
It requires that the authenticator 
1. creates a requested keys for the collections.
1. writes an encrypted file to gaia storage containing the keys

**Comment by hstove** [comment]
It's definitely a non-trivial amount of work. The technical details have already been implemented by Ken in the Browser, and we'd also want to consider the UI changes.

**Comment by friedger** [comment]
There is no UX for "publish_data", why bother for collection scopes ;-)

**Comment by dantrevino** [comment]
A request should be for a specific collection type.  "collections_documents", for instance.

**Comment by hstove** [comment]
> There is no UX for "publish_data"

Actually there is, if you are selecting an ID that has already done `publish_data` with a different app. We warn the user that they'll be able to be cross-identified.

**Comment by friedger** [comment]
This is still important to me!
