### ISSUE TITLE
[app] Profile might be reset

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#322]
Under certain conditions the profile is reset

https://github.com/blockstack/ux/blob/69d03ee4c7c535981ddf49493984d21014603f33/packages/keychain/src/identity.ts#L53

This could happen for apps with permission `publish_data` and if fetching the profile fails

**Comment by hstove** [comment]
Thanks @friedger, this is a good point. I don't have a fix yet but we're looking into it.

**Comment by hstove** [comment]
Fixed in the above commits, good catch Friedger 👍
