### ISSUE TITLE
Make react a peer dependency for Connect

### ISSUE THREAD

**Issue by njordhov** [leather-io/extension#323]
Unresolved issue:
https://github.com/blockstack/connect/issues/74

**Comment by markmhendrickson** [comment]
@hstove mind providing your latest thinking about this dependency here?

**Comment by hstove** [comment]
Yes, we definitely need to update this. I have the fix in the PR for transaction signing - I'll get it pulled into the master branch so it can be published. Thanks @njordhov , sorry this has taken so long.
