### ISSUE TITLE
Implement BTC Faucet

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#325]

**Comment by diwakergupta** [comment]
Tagging some folks to make sure we're all on the same page: my assumption is while this needn't be a Neon blocker, we need it quickly thereafter to open up mining up testnet.

cc/ @lgalabru @markmhx 

@hstove do you have an ETA?

**Comment by markmhendrickson** [comment]
@hstove mentioned on our kick-off call today that this should be ready by EOW

**Comment by diwakergupta** [comment]
@markmhx @hstove can you confirm updated ETA on this?

**Comment by hstove** [comment]
Current focus this week is on finalizing the general release of the authenticator before getting back into testnet work. No current ETA on the bitcoin faucet

**Comment by hstove** [comment]
FYI - pull request for the BTC faucet is in the sidecar here: https://github.com/blockstack/stacks-blockchain-sidecar/pull/70

**Comment by markmhendrickson** [comment]
@hstove anything else that needs to be done for the BTC faucet to go live aside from @zone117x's review of the above PR? And can we get a staged version of the faucet set up today for website integration tests on staging?

**Comment by timstackblock** [comment]
This works and the front end is wired up, but there are some performance issues and random 500 errors that are associated with the sidecar or staging node that are actively being worked on.

![Screen Shot 2020-05-12 at 8.23.17 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/32e1a381-29d7-4ba4-9a91-9788ffdb357c)
