### ISSUE TITLE
Publish & document RPC API client

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#327]
There's a WIP RPC API in the UX monorepo. We should get this published on NPM and have some documentation available.

**Comment by markmhendrickson** [comment]
@hstove mind describing a bit just how this API will be used and when by a developer?

**Comment by hstove** [comment]
I think it'll be tough to outline all of the different use cases. Here's the [list of RPC methods](https://github.com/blockstack/stacks-blockchain/blob/master/docs/rpc-endpoints.md). Some of these are more helpful for PBC use right now, and some are very relevant to developers. Either way, it's important to have a library that handles this, for both internal and external use.
