### ISSUE TITLE
Validation of all steps in the onboarding flow

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#33]
- Seed phrase (sign in and sign up)
- Username stuff
- What else?

https://paper.dropbox.com/doc/New-Blockstack-integration-and-app-specification--Ap6H2nurG02HzEH36YuWIsciAg-ThtvzBu5VM6ftdUqH1vyB

@moxiegirl

**Comment by markmhendrickson** [comment]
@hstove is this issue still relevant?
