### ISSUE TITLE
Username is an empty string, after creating a user with empty name

### ISSUE THREAD

**Issue by jorishermans** [leather-io/extension#330]
To link my content to a specific user, I need the username of the current loggedin user.

```
userData = session.loadUserData();
const person = new Person(userData.profile);
const username = userData.username;
```

This is a show stopper for my application, I need at least the username ... 

It will allow me to build up a share link.

My old data from loggin in with blockstack.js is also lost on my localhost session, so I am not sure if the UserSession is working like it should be. The appPrivateKey is also different in both ways.

**Comment by jorishermans** [comment]
For me it is not clear how to log in with an already existing user ... I have the secret of that user but I am not able to provide it to login with the same user as with browser.blockstack.org.

I was able to create a user with an empty name ...

**Comment by talhasch** [comment]
@markmhx i think this happens due to ip based restriction on username registration endpoint.

**Comment by markmhendrickson** [comment]
@hstove is this the same underlying problem as found in https://github.com/blockstack/ux/issues/314?

**Comment by friedger** [comment]
@markmhx This issue is about empty username, #314 is about missing public profile (that is not loaded by default by connect library)

**Comment by hstove** [comment]
@jorishermans I think I understand the problem, but I'm having a hard time figuring out exactly what is going wrong here. When I re-use an older secret key from the Browser, I am able to use it in the new authenticator, and I get the same usernames and `appPrivateKey`. Are you using a magic recovery code? Or just the twelve words?

**Comment by hstove** [comment]
Also, are you really able to just register a username with an empty string? We have validation on this, and if you leave the onboarding flow and come back, you'll still be forced to enter a username. I just tried, and I'm not able to get through the flow without a username. Could you post a video maybe (obviously without the secret key)

**Comment by timstackblock** [comment]
> @markmhx i think this happens due to ip based restriction on username registration endpoint.

@jorishermans can you use a vpn and verify that username creation is not being blocked due to rate limiting IP restrictions
