### ISSUE TITLE
Fix title shown as "undefined" in choose account screen of auth

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#335]
![Screen Shot 2020-04-17 at 09.05.11.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/b2ff2172-6898-4f8d-a8b2-a56f65282e8d)

**Comment by hstove** [comment]
QA:

- View sample app (prod will be deployed in ~10)
- Sign in to an account (via any means)
- Re-sign in (it should send you to "Choose Account")
- See that the `document.title` is "Choose Account", and not "undefined" as in the screenshot

**Comment by timstackblock** [comment]
This is still appearing on banter.pub


![Screen Shot 2020-04-24 at 12.04.21 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/33b5a489-561e-4a58-8885-c6645b7da999)

**Comment by timstackblock** [comment]
resolved
