### ISSUE TITLE
Fix page centering of auth index

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#336]
![Screen Shot 2020-04-17 at 09.05.23.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/c7c0b79f-b7e4-4208-934a-f60adb01a2fd)

**Comment by hstove** [comment]
I'm unable to repro - is this a specific Browser?

**Comment by markmhendrickson** [comment]
Hmm I'm unable to recreate now as well so will close out.
