### ISSUE TITLE
Add support for 'watching' TX status

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#345]
At the moment, I'm not 100% sure how we can do this yet, with available APIs.

**Comment by markmhendrickson** [comment]
@hstove good for sprint 2 or should we icebox until the necessary APIs become available?

**Comment by hstove** [comment]
I'm thinking we should wait on this - still unclear exactly what kind of UX / DX we want to provide, and we will likely be better off right now by simply documenting how to get a transaction status - https://github.com/blockstack/docs.blockstack/pull/648/
