### ISSUE TITLE
Connect to support relative icon URL

### ISSUE THREAD

**Issue by njordhov** [leather-io/extension#348]
Can Connect allow a relative URL for `appDetails.icon`?

That way, when somebody forks an app template like [REBL One](https://github.com/REBL-Stack/starter-app) that uses a relative icon URL, the app icon is served from their clone as they should expect, rather from some hardcoded server.

**Comment by hstove** [comment]
Could you just construct the icon URL from `location.origin`?

**Comment by friedger** [comment]
yes, and it is inline with the icon definition of the web manifest

**Comment by njordhov** [comment]
> Could you just construct the icon URL from location.origin

Yes. Or better, Connect takes care of it so developers don't have to. ;-)

**Comment by friedger** [comment]
My comment was in favor of relative icon urls. Please add support for it!

**Comment by njordhov** [comment]
Thanks.
