### ISSUE TITLE
Add "Magic Recovery Code" support

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#35]
Some users will only have a "magic recovery code" from the legacy browser, which is just an encrypted 12-word seed. We need to:

- dial in the language for what we call this thing
- handle the case where users enter their recovery code in the "seed phrase" prompt
- error messaging and handling
- UI to enter your password to decrypt the recovery code

These screens are already designed in Figma, but are not in the codebase yet.

**Comment by markmhendrickson** [comment]
@jasperjansz we've designed everything needed for this issue / legacy handling correct?

**Comment by markmhendrickson** [comment]
@moxiegirl  will added error message guidance here
