### ISSUE TITLE
[Connect] app urls in profile do not end with "/"

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#356]
Connect adds apps urls in the public profile without a trailing "/" for apps that request "publish_data" permission.

![Screenshot from 2020-04-30 22-59-52](https://user-images.githubusercontent.com/1449049/80787833-e3634100-8b87-11ea-861d-2fa2b9912a59.png)

What is the contract for the profile.json? Do client libraries (like blockstack.js) deal with both types of urls (with and without "/")?

**Comment by hstove** [comment]
Fixed in #379
