### ISSUE TITLE
Tests are very brittle and fail often

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#369]
Currently it's pretty hard to contribute to this repo for a few reasons:

- my dependencies seem to get out of sync often, it's unclear how and when deps across packages need to stay in sync
- the playwright implementation we have is failing all the time with no clear reason why: `Chromium revision is not downloaded. Run "npm install"` The browsers don't always install correctly on circleci.

**Comment by kyranjamie** [comment]
Tried to run CI locally and ran into this issue, not sure if related

```sh
❯ circleci local execute
Docker image digest: sha256:f5d8aa8d08da999501fcbf71e5a5ebabd9e1119581e609666dccf3a03af87bed
====>> Spin up Environment
Build-agent version 1.0.24132-7e56487c (2020-01-16T13:27:22+0000)
Error: Configuration errors: 1 error occurred:

* Cannot find a job named `build` to run in the `jobs:` section of your configuration file.
If you expected a workflow to run, check your config contains a top-level key called 'workflows:'
Step failed
Task failed
Error: 1 error occurred:

* Cannot find a job named `build` to run in the `jobs:` section of your configuration file.
If you expected a workflow to run, check your config contains a top-level key called 'workflows:'```

**Comment by hstove** [comment]
@kyranjamie you can do `circleci local execute --job test_web`

**Comment by markmhendrickson** [comment]
What's the latest here?
