### ISSUE TITLE
Errors importing react components in vue project

### ISSUE THREAD

**Issue by mijoco-btc** [leather-io/extension#376]
The intro screen for **blockstack/connect** in a vue blockstack app is a bit of a Picasso. 

After loading the component either by; 

`npm install --save @blockstack/connect`
`npm i --save-dev react react-dom`

or using the global variable;

`script src="https://unpkg.com/@blockstack/connect"`

leads to the svg icons used in the splash screen stretching to full width of their containers.

**Comment by hstove** [comment]
This is a duplicate of #378 I'm pretty sure? I'm going to close this one, since the other one has a screenshot. Thanks for reporting!
