### ISSUE TITLE
[app] Public profile fetched from wrong url

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#377]
My public profile is located at 

```
https://gaia.blockstack.org/hub/1Maw8BjWgj6MWrBCfupqQuWANthMhefb2v/0/profile.json
```
but `app` fetches it from 
```
https://gaia.blockstack.org/hub/1Maw8BjWgj6MWrBCfupqQuWANthMhefb2v/profile.json
```

Relevant code:
https://github.com/blockstack/ux/blob/master/packages/keychain/src/identity.ts#L111

**Comment by friedger** [comment]
Probably related to #354 , #314

**Comment by ryanarndtcm** [comment]
@timstackblock @hstove can you take a look at this? It is a blocker for using Connect.

**Comment by hstove** [comment]
Yes - I understand the issue here, and what we need to do to solve it. Let's make sure this gets scheduled for the sprint starting on Monday.

**Comment by markmhendrickson** [comment]
@hstove are you taking a new approach to this?

**Comment by friedger** [comment]
@hstove Could you please reopen it? The profile is written to the wrong location!
