### ISSUE TITLE
Resolve CSS issues with introductory modal for Loopbomb

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#378]
See https://test.loopbomb.com/

![8068e496bcd55ade231c47a9efd3f6b59b6560c7.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/7491044d-62e5-41df-9421-b3b793f4d279)

Reported by @radicleart

**Comment by markmhendrickson** [comment]
@hstove good for sprint 2?

**Comment by hstove** [comment]
I'm not sure if they changed their site, but I don't see any way to view the intro modal on test.loopbomb.com. It'll be hard to see exactly what styles they're overriding without that

**Comment by mijoco-btc** [comment]
Hi,

I removed the intro screen as we needed to go live.

Just added it back here test.loopbomb.com.

Using Connect 2.7.5.

Mike.

**Comment by markmhendrickson** [comment]
Moving this to code review since I presume it's getting resolved with https://github.com/blockstack/ux/pull/521

**Comment by hstove** [comment]
I'm moving back to "Development", given that #521 is still stuck.
