### ISSUE TITLE
[ui] New jazzy button

### ISSUE THREAD

**Issue by kyranjamie** [leather-io/extension#397]
New Stacking wallet includes new purple buttons. I'd propose we call this variant "alternate", unless anyone has better suggestions.

```typescipt
const AlternateBtn = () => <Button variant="alternate" />;
```

![image.png](https://images.zenhubusercontent.com/5d765e279cf7af0001b78a5e/921e0f85-126e-4669-8877-f5b6521025d8)

Assigned to you @jasperjansz. Assign back to me when various states are in design system 👍🏼

**Comment by aulneau** [comment]
I would say these should be secondary buttons, not alternate

**Comment by aulneau** [comment]
I see that these diverge from the two we have already in the design system. Seems to me this is a secondary action, @jasperjansz how come we have three variants? would be helpful to understand the different reasons someone would use them. The issue I take with 'alternate' is that it's not clear by the word when this would be used.

**Comment by kyranjamie** [comment]
Issue with `secondary` is that we already have one, so this would be to avoid breaking changes. Open to alternatives, or just introducing breaking changes.

**Comment by aulneau** [comment]
For sure. I wonder if this would technically be a "breaking" change, as it's only affecting the style of a button, nothing to do with the implementation of the button. I think it's okay if we want to have three or more variants of the button, but we should think about and define the contexts in which someone would use each variant.
