### ISSUE TITLE
Add extension option to sign-in modal

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#404]

**Comment by jasperjansz** [comment]
https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Authenticator?node-id=5721%3A11775

**Comment by markmhendrickson** [comment]
Should we add a link to manual install instructions for both the Chrome and Firefox prompts so we have something available ahead of having the extension available in their stores?

We may even want to go live tomorrow with these manual instructions as a default since we don't know how long approval will take. That way approval isn't a blocker.

It may be easiest to create a page on GitHub with these instructions for now since we don't really have user-oriented documentation anymore.

**Comment by timstackblock** [comment]
works as expected
