### ISSUE TITLE
Remove browser action popup from extension

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#405]
When you click on the Blockstack extension icon, this little popup shows up. This is called a "Browser Action". I added this little stub page a while back, but it seems like we won't use it for the general release. So, we need to remove it.

Questions:
- Should we show the icon at all? The only benefit I could see is to go to the "home page" (full screen, new tab)
- Is there any way we want to keep the popup, for now? We could show the home screen view, which allows for signing out.

![image](https://user-images.githubusercontent.com/1109058/83423571-04fe5500-a3e0-11ea-9a9b-8c3c0c73b02d.png)

**Comment by markmhendrickson** [comment]
@hstove Mind linking the PR here?

**Comment by hstove** [comment]
@markmhx it's in #385 - you'll have to [follow these steps](https://github.com/blockstack/ux/pull/385#issuecomment-635973958) to get the latest for QA.

**Comment by hstove** [comment]
Hey @timstackblock , do QA this:

- Have the extension installed
- Click the blockstack icon in the task bar
- it should open a new tab with the authenticator's home page

**Comment by timstackblock** [comment]
@hstove This currently does not navigate to the home page, below are the two pages that the user will see.


If I am logged in it takes me to the sign-out page and I see the message below

![Screen Shot 2020-06-15 at 9.00.18 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/dbd13754-3897-40cd-9613-e9aae7ec7bb6)

If I am logged out it takes me to this page and I see the message below

![Screen Shot 2020-06-15 at 9.01.07 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/be034dbf-1c17-42f0-8c02-e823bfb18dcd)

**Comment by markmhendrickson** [comment]
This looks like expected / desired behavior to me.

**Comment by timstackblock** [comment]
Thanks
