### ISSUE TITLE
Add better error handling to testnet demo app

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#406]
One unfortunate UX issue with the testnet demo is that the testnet resets occasionally. When this happens, we need to re-deploy the contracts that this app uses. When they're not deployed, certain actions fail silently.

We should add light error handling to simply say things like "This contract has not been deployed".

**Comment by markmhendrickson** [comment]
@hstove want to add some basic handling here for the current sprint and we can improve upon it afterwards once @jasperjansz takes his hand at refreshing the app's design in general?

**Comment by hstove** [comment]
Moving to QA. Some additional error handling:

- If the sidecar API is inaccessible for any reason
- If the contracts are not deployed

I also removed the 'Waiting for TX to confirm' stuff and only link to the explorer. The explorer can handle pending TX's pretty well now, so I think that's a better experience.

**Comment by timstackblock** [comment]
![Screen Shot 2020-06-29 at 9.39.25 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/e5ac22bc-5e29-4c73-9abb-ecd9a9a718a1)
