### ISSUE TITLE
Extension error: Requests to the server have been blocked by an extension.  ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#407]
I am having the same issue when using the zip filen here is the error the connect pop up displays.

<img width="441" alt="Screen Shot 2020-06-01 at 11 58 29 AM" src="https://user-images.githubusercontent.com/49165468/83427874-6d106380-a3ff-11ea-8d09-8f259f189a99.png">

Here is the Manifest.json file 

<img width="847" alt="Screen Shot 2020-06-01 at 12 24 11 PM" src="https://user-images.githubusercontent.com/49165468/83430089-0db45280-a403-11ea-9734-e81673721deb.png">

I get this error in console

<img width="643" alt="Screen Shot 2020-06-01 at 12 42 05 PM" src="https://user-images.githubusercontent.com/49165468/83431477-6ab10800-a405-11ea-9dba-88caeade634e.png">

**Comment by markmhendrickson** [comment]
I'm closing this issue since I believe we've resolved it fully by now during pre-release cycles.
