### ISSUE TITLE
Create API parity between Connect and Stacks-Transactions methods

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#408]
Ideally, the Connect methods for transaction signing should pretty much the same exact options as exposed in 
the `stacks-transactions` library. So far, we only have partial support. Additional options include things like `fee`, `postConditions`, etc.

**Comment by friedger** [comment]
This also includes postconditions and other parameters in e.g. makeContractCallToken in https://github.com/blockstack/ux/blob/3c6688714b070a38c2eefe0d93a6218163917c53/packages/connect/src/transactions/index.ts#L65
