### ISSUE TITLE
Determine which components should live in @blockstack/ui

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#41]
Currently most of the UI for the onboarding flow is contained in this app, much of it can and should be abstracted out to exist in the `@blockstack/ui` library.

**Comment by hstove** [comment]
Also related to #39

**Comment by jasperjansz** [comment]
Aside from general components (buttons, inputs, etc.) found in the design system (https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/Design-System?node-id=1%3A3), there are some components that are reused in the onboarding, such as the headers. You can find those here:
https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=4396%3A0

**Comment by markmhendrickson** [comment]
@aulneau has this been completed already?

**Comment by aulneau** [comment]
@markmhx it's on going
