### ISSUE TITLE
Connect debugger faucet displays error "No results after 2 minutes. Something may have gone wrong"

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#410]
Connect debugger faucet displays error "No results after 2 minutes. Something may have gone wrong"

The network tab in console displays 404 errors when trying to fetch the transaction data please see screen shots below.

Link used: https://deploy-preview-301--authenticator-demo.netlify.app/
Chrome Version 83.0.4103.61
Addresses used
ST2BY0YAH29CPRGB6MH36THMXE4C25DR3RQR8ZCGM
ST28G8W0BRSA2ZNSDQZKNEHEYQ5M4QJZC2YJGVZWP

Both addresses worked with the in the faucet at 
https://testnet.blockstack.org/faucet

<img width="1432" alt="Screen Shot 2020-06-03 at 10 04 16 AM" src="https://user-images.githubusercontent.com/49165468/83646454-a7a20980-a581-11ea-9eab-59d7b41fa5f4.png">
<img width="1168" alt="Screen Shot 2020-06-03 at 10 03 07 AM" src="https://user-images.githubusercontent.com/49165468/83646456-a83aa000-a581-11ea-9848-e4b14eb2b489.png">

**Comment by hstove** [comment]
Yeah - the transaction just isn't confirmed after 2 minutes. Which is pretty normal. I'll update the timeout.

**Comment by hstove** [comment]
@timstackblock you can click the 'Waiting for TX to Confirm' link and it'll open the explorer. From there, you can try refreshing periodically until the transaction gets confirmed.

**Comment by hstove** [comment]
I'm going to close this ticket:

- All that happened here was that the TX took a while to confirm, which is normal for testnet. Blocks have been more speedy lately, according to the status website.
- I removed the 'waiting' text on the test app, and simply link directly to the explorer. The explorer can handle mempool TXs now, so I think going to the explorer is a much better UX.
