### ISSUE TITLE
Clicking read status button, doesn't open a pop up window.

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#411]
When I enter an address an click the Read Status button nothing happens. The button displays a circle spinner for about 2 seconds and refreshes with no action. 

The expected result would be a pop up window or an error message.

The user is not notified if the transaction failed, succeeded or if the functionality is broken.

A video of the issue is here http://somup.com/cY1e20Qn9T

<img width="1440" alt="Screen Shot 2020-06-03 at 10 18 00 AM" src="https://user-images.githubusercontent.com/49165468/83648424-07011900-a584-11ea-90bc-9711861142cf.png">

**Comment by hstove** [comment]
This actually isn't a bug - no popup is opened for reading a status (or reading the counter value). For read-only queries, you don't have to sign anything.

The bug was related to error handling - #406 should have taken care of it.
