### ISSUE TITLE
Website sign in lagged inputs

### ISSUE THREAD

**Issue by giraffekey** [leather-io/extension#416]
I'm on Firefox.

Every time I sign into my account it takes about 10 seconds or so for the inputs to properly focus and the button to show a hover cursor in each individual step in the sign in process.

If I type in an input box no text appears until this "lag period" is over.

It makes the authentication process come off as very slow, would be nice if it were fixed.

**Comment by markmhendrickson** [comment]
@timstackblock can you see if you can recreate this?

**Comment by timstackblock** [comment]
@GiraffeKey I do not see this error can you tell me what version of FF you are using and what device you are using. Also please check to see if you have the STRICT security setting enabled. I will retest this with your exact setup and see if I can find the bug.
