### ISSUE TITLE
Inputs and Source design approach

### ISSUE THREAD

**Issue by stackatron** [leather-io/extension#418]
Assume most end users can't interpret the inputs or source very well. Imagine there is a more elegant solution here. Maybe explain in english with links to explode out this section – maybe even expand the window size to help with scrolling. Maybe place it below the confirm button. 

![Screen Shot 2020-06-09 at 11 24 37 AM](https://user-images.githubusercontent.com/767828/84168868-ed5d4700-aa45-11ea-9706-87522c45f85d.png)

We have any updated designs for this? @jasperjansz

**Comment by markmhendrickson** [comment]
I'm closing this out since we're redesigning this whole flow.
