### ISSUE TITLE
Demo test app has overlapping web elements and some part are unusable on mobile

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#420]
Demo test app has overlapping web elements and some part are unusable on mobile.

As you can see in the picture below there is no spacing between buttons and the status contract text input fields are overlapping.

Chrome
Galaxy 9

![Screenshot_20200609-155202_Chrome](https://user-images.githubusercontent.com/49165468/84196210-e6e2c580-aa6d-11ea-89c9-ed64aa3d371c.jpg)

![Screenshot_20200609-154939_Chrome](https://user-images.githubusercontent.com/49165468/84196331-0a0d7500-aa6e-11ea-8626-fd8ac131bed6.jpg)

**Comment by markmhendrickson** [comment]
I'm closing this out in favor of QA'ing responsiveness against https://github.com/blockstack/ux/issues/425 since we've redesigned the app.
