### ISSUE TITLE
Refresh Testnet Demo app design

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#425]
The "Blockstack Testnet Demo" app could use a general design refresh with @jasperjansz's help, mainly keeping all the functionality already there but improving its UI design and perhaps making the steps more sequential.

https://authenticator-demo.netlify.app/

cc @hstove

**Comment by markmhendrickson** [comment]
Designs: https://www.figma.com/file/TL4egClS7NIKJyPVha7jCo/Testnet-demo-app?node-id=0%3A1

**Comment by markmhendrickson** [comment]
I'm getting `Clarity type: undefined` when trying to write status:

![Kapture 2020-07-15 at 12.41.47.gif](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/8c355ab4-7bc3-40fa-b8c0-293a26ad1ad8)

**Comment by markmhendrickson** [comment]
These buttons could use some padding between them when stacked vertically given viewport width:

![Screen Shot 2020-07-15 at 12.37.25.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/075d0f16-9675-4d64-8642-ce02b2a1c058)

**Comment by markmhendrickson** [comment]
There are some style details that would be nice to get into place from the Figma designs so the app has the same general aesthetic as our other products (e.g. white background, blue selected tab bottom border).

# Designs 

![Screen Shot 2020-07-15 at 13.03.36.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/061076bc-5f40-4273-84ea-4a629281a35d)

# Current

![image.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/72e037f9-84a0-4914-a5fa-09bbf71e722f)

**Comment by markmhendrickson** [comment]
Links like this one should be `display: inline` to avoid stretching horizontally:

![Screen Shot 2020-07-15 at 13.05.00.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/4984569e-c62b-4103-8a50-fb812bfd04ae)

**Comment by markmhendrickson** [comment]
The latest changes and statuses sections are missing, which seems like a key piece of UX to include for release. Otherwise this app just feels so lonely / dead:

![Screen Shot 2020-07-15 at 13.05.47.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/3a892723-0438-4b8b-a641-7e8c09b8ca47)

![Screen Shot 2020-07-15 at 13.06.18.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/f86532ac-8aa4-44d7-b00c-97cc02587a8e)

**Comment by markmhendrickson** [comment]
The placeholders for these inputs should provide better guidance. E.g. "Enter your status" and "Enter your STX address" respectively.

We should also provide a way for the user to see their STX address clearly for sharing with other users for input here. Can we simply list it out below the input? cc @jasperjansz 

![Screen Shot 2020-07-15 at 13.06.59.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/bf1b4013-12c0-4b4d-b820-c89f0104233b)

**Comment by markmhendrickson** [comment]
"Sign out" option is missing:

![Screen Shot 2020-07-15 at 14.17.02.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/ccc638f8-623d-4949-b46a-132e8322b846)

**Comment by hstove** [comment]
Good feedback, @markmhx ! I've pushed all of these suggestions. Please use [this comment](https://github.com/blockstack/ux/pull/301#issuecomment-656152620) for test-app links - we're now using Vercel for all PR preview stuff, so that we're consistent across projects.

I've pinged on Slack to try and get the sidecar deployed, so you can see recent transactions. Agreed that it makes it much better.

I've also added a little copy with your STX address, so you can read your own status. Please advise on any changes you'd like to see here:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/1109058/87594151-5ec19280-c6a1-11ea-8024-66aac527b5c1.png">

**Comment by markmhendrickson** [comment]
Looking good. I'm no longer getting the error above, but now getting a "Transaction not found" error when visiting the Explorer transaction page with the write status link.


![Kapture 2020-07-16 at 15 30 57](https://user-images.githubusercontent.com/28991/87676843-62284d00-c779-11ea-9e4c-f49a5b6fc507.gif)

**Comment by markmhendrickson** [comment]
Also the counter value stays the same even after incrementing several times in a row and waiting minutes:

<img width="508" alt="Screen Shot 2020-07-16 at 16 56 18" src="https://user-images.githubusercontent.com/28991/87686840-4a56c600-c785-11ea-8887-8168b58006a9.png">

**Comment by markmhendrickson** [comment]
Do we mean to pronounce this as "S.T.X. address" or "Stacks address"? If the former, "an" makes sense. If the later, "a" does.

<img width="335" alt="Screen Shot 2020-07-16 at 17 01 52" src="https://user-images.githubusercontent.com/28991/87687483-129c4e00-c786-11ea-9975-b3b49cd7fd7b.png">
