### ISSUE TITLE
Transaction Failed Unable to find contract BUG in authenticator-demo.netlify.app 

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#429]
When you go to authenticator-demo.netlify.app and register a new user by default after login the STATUS CONTRACT is displayed at the top of the app. This is the first thing the new user sees.

But when the user attempts to use the contract the error message below displays. I am assuming this is because the contract is not deployed and or the address no longer exist as a result of the core node restart. 

Is there a way to add this contract and address to the list of transactions that the DevX team  and @yknl  is automating to be auto created every time the core node is restarted and the testnet is relaunched?

Or please let me know if I am incorrect and this issue is the result of something else and there is another issue/solution. Like deploying the status app again each time and not having it appear by default.

<img width="1409" alt="Screen Shot 2020-06-15 at 10 09 22 AM" src="https://user-images.githubusercontent.com/49165468/84667776-cc3aa180-aef0-11ea-813d-02650f0c8717.png">

**Comment by hstove** [comment]
Yes, we should definitely add it to the list of contracts to be re-deployed every time the network restarts. That would be good. I'm not sure if we should keep this ticket open. The contracts are deployed now, and we're at least properly handling the error.

**Comment by markmhendrickson** [comment]
@yknl Do you want to create a separate issue for tracking this automation then we'll close out this one?

**Comment by noumanahmad001** [comment]
Hi, 
I am still facing the same issue. Is there any workaround for this?
One more thing is this app available on git, I just want to see how to use these features using connect. 

<img width="1093" alt="Screenshot 2020-07-03 at 2 38 09 PM" src="https://user-images.githubusercontent.com/18707532/86455990-dc4ce080-bd3a-11ea-93b6-b4d091ba5a89.png">

**Comment by asimm241** [comment]
Hi,
I am still facing the same issue. Is there any workaround for this?
One more thing is this app available on git, I just want to see how to use these features using connect.

<img width="1093" alt="Screenshot 2020-07-03 at 2 38 09 PM" src="https://user-images.githubusercontent.com/25453806/86456387-6e54e900-bd3b-11ea-9d4a-bfaacda8c022.png">

**Comment by markmhendrickson** [comment]
@asimm241 Sorry for the trouble here, I'm looking into a fix.

@hstove I don't see we've published this app's repo anywhere yet so I've created an issue to track that work: https://github.com/blockstack/ux/issues/487

**Comment by markmhendrickson** [comment]
@asimm241 you can find the app code here:  https://github.com/blockstack/ux/tree/master/packages/test-app

**Comment by asimm241** [comment]
> @asimm241 you can find the app code here: https://github.com/blockstack/ux/tree/master/packages/test-app

Thanks @markmhx

**Comment by markmhendrickson** [comment]
Closing this out since we now have a procedure for re-deploying this contracts

**Comment by agnelvishal** [comment]
@markmhx Getting the error again as of Today
![Screenshot from 2020-10-29 20-36-48](https://user-images.githubusercontent.com/10105332/97596067-5dd32780-1a2a-11eb-8bac-d83fc66e283d.png)
