### ISSUE TITLE
Setup event tracking

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#43]
We can just integrate segment during a pre-release, but before a developer preview we need to remove any 3rd party scripts, and proxy events instead (similar to how the Browser works).

There is already a function setup which gets called during all the events we want, it just isn't integrated with Segment yet.

**Comment by markmhendrickson** [comment]
@kyranjamie any updates here?

**Comment by markmhendrickson** [comment]
Moving this back to "in progress" since events not showing up in Segment debugger yet

**Comment by kyranjamie** [comment]
See #111
