### ISSUE TITLE
Android Firefox transaction signing shows an infinite spinner

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#435]

**Comment by markmhendrickson** [comment]
First reported with https://app.zenhub.com/workspaces/userx-5deade0e95ddf8ab213b2460/issues/blockstack/ux/302#issuecomment-641539852

**Comment by hstove** [comment]
@timstackblock , I just tried this with Firefox on a Macbook. It worked as expected. Is this only happening on Firefox on Android?

**Comment by markmhendrickson** [comment]
@timstackblock confirmed separately that this is indeed happening on Firefox on Android
