### ISSUE TITLE
Error when selecting account during sign in with Chrome extension

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#439]
Spinner just keeps going after error hit as shown in console:

<img width="1099" alt="Screen Shot 2020-06-19 at 15 29 58" src="https://user-images.githubusercontent.com/28991/85137760-f9b18300-b241-11ea-823a-936da5736963.png">
<img width="1104" alt="Screen Shot 2020-06-19 at 15 30 10" src="https://user-images.githubusercontent.com/28991/85137769-fd450a00-b241-11ea-947e-81bac279bc15.png">

**Comment by timstackblock** [comment]
There is currently a bug causing an issue loading the extension when this is resolved I will continue. 

![Screen Shot 2020-06-22 at 2.17.20 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/142fc899-cffe-4375-ac8e-2f71fade6aef)

**Comment by timstackblock** [comment]
I will close this when the other chrome issue #441 is fixed because I need to create multiple users to test this issue and this functionality is currently broken in chrome.

**Comment by timstackblock** [comment]
This is resolved
