### ISSUE TITLE
Settings / home off-center when viewed inside Chrome extension

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#440]
<img width="470" alt="Screen Shot 2020-06-19 at 15 33 19" src="https://user-images.githubusercontent.com/28991/85137963-49904a00-b242-11ea-9051-8606bf7d6842.png">

The problem is intermittent. I'm also seeing it show up fine on subsequent use with a different Secret Key:

<img width="487" alt="Screen Shot 2020-06-19 at 15 39 05" src="https://user-images.githubusercontent.com/28991/85138443-100c0e80-b243-11ea-9901-fb86469d1eb7.png">

**Comment by timstackblock** [comment]
There is currently a bug causing an issue loading the extension when this is resolved I will continue. 

![Screen Shot 2020-06-22 at 2.17.20 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/142fc899-cffe-4375-ac8e-2f71fade6aef)

**Comment by timstackblock** [comment]
This is resolved

![Screen Shot 2020-06-23 at 11.18.12 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/42ccbbaf-d623-48e5-84e5-afe3725ae0c4)

![Screen Shot 2020-06-23 at 11.18.19 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/d6a1c0ba-7480-4507-8196-307423474a38)
