### ISSUE TITLE
Unable to proceed upon adding new username during sign in with Chrome extension

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#441]
Submitting the username form after selecting the option to add a new account during sign-in shows this error in the console:

<img width="1136" alt="Screen Shot 2020-06-19 at 15 36 29" src="https://user-images.githubusercontent.com/28991/85138238-bc99c080-b242-11ea-93a4-c87ac226aec0.png">

Note that when navigating back through sign in afterwards, the username _does_ show up and can be selected.

<img width="519" alt="Screen Shot 2020-06-19 at 15 37 47" src="https://user-images.githubusercontent.com/28991/85138361-e94dd800-b242-11ea-95ba-ff9e3730dceb.png">

**Comment by timstackblock** [comment]
This is still broken
![Screen Shot 2020-06-23 at 10.57.19 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/fe9f27b3-7ebf-40ca-aced-5ce0f3635b04)

**Comment by hstove** [comment]
Hey @timstackblock , I was able to figure out how to reproduce this, and have pushed the fix. When this job is done, the fixed build should be in the artifacts. https://app.circleci.com/pipelines/github/blockstack/ux/967/workflows/57c9f2a1-2131-4607-994d-7b8c4c40813d/jobs/977/steps

**Comment by timstackblock** [comment]
This is resolved
