### ISSUE TITLE
Icon missing in top left hand corner of connect pop us cosmetic bug in Firefox only

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#446]
Top left hand corner of connect has a small cosmetic bug.

"Testing app" over laps on the work Test in mozilla firefox there should be an icon there please compare this with the chrome image below

![Screen Shot 2020-06-24 at 10.52.38 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/678d5633-3f8a-4057-8520-13eb007357b1)

This works well in chrome

![Screen Shot 2020-06-24 at 10.56.36 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/38c0e52f-d488-4eaa-becf-f93b117c3b6c)

**Comment by hstove** [comment]
I believe this is fixed, moving to QA

**Comment by timstackblock** [comment]
Resolved
