### ISSUE TITLE
Disable autocorrect on username input

### ISSUE THREAD

**Issue by larrysalibra** [leather-io/extension#447]
Autocorrect capitalizes the first letter which generates an invalid username. This should be disabled.

![2FA70418-FA7E-4FD7-8B8B-32300156A9C3](https://user-images.githubusercontent.com/597182/85782029-e417ee00-b758-11ea-8e0a-22f434272948.png)

**Comment by timstackblock** [comment]
Thanks @larrysalibra this is a known issue we will prioritize it
https://github.com/blockstack/ux/issues/419

**Comment by markmhendrickson** [comment]
Thanks, Larry. I'm closing this out in favor of https://github.com/blockstack/ux/issues/419, which we'll tackle in the sprint beginning today.
