### ISSUE TITLE
Test extension from Chrome Web Store

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#452]
Once the extension is approved for the Chrome Web Store, we should test it fully as installed from there.

@hstove please assign this issue to @timstackblock once you've gotten notice of approval.

**Comment by timstackblock** [comment]
I get the same issue in both FF and Chrome when I click the Blockstack icon in the top right corner.

Please review the video in the link http://somup.com/cYiV2iQpsO

![Screen Shot 2020-07-01 at 10.08.53 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/cf1f7d54-904e-4c8c-b2f3-31eb961aa5e3)

I was expecting to see this page

![Screen Shot 2020-07-01 at 10.09.43 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/bd1bb93f-71b3-4517-8a03-f9f54ae26ef8)

**Comment by markmhendrickson** [comment]
That appears to be the right page. Does the link for "Find an app to use" not work?

**Comment by markmhendrickson** [comment]
@timstackblock I believe you mentioned during stand-up that this issue is now ready to close out?
