### ISSUE TITLE
Test extension from Firefox Add-ons

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#453]
Once the extension is approved for the Firefox Add-ons store, we should test it fully as installed from there.

@hstove please assign this issue to @timstackblock once you've gotten notice of approval.

**Comment by timstackblock** [comment]
Clicking the blockstack button in the top right hand corner of FF gives me this window and I am stuck on this page.

![Screen Shot 2020-07-01 at 10.01.08 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/360ea98b-ed53-449c-87cc-34cfd05c0f49)

**Comment by markmhendrickson** [comment]
Hmm that screenshot looks like expected behavior. But what do you mean by "stuck" exactly?

**Comment by markmhendrickson** [comment]
@timstackblock I believe you mentioned during stand-up that this issue is now ready to close out?
