### ISSUE TITLE
Cancel pending selection state when "Go back" on account confirmation modal

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#454]
![Kapture 2020-06-29 at 16.33.50.gif](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/c5a2e909-ce6e-4df3-9af0-9f912d924ea8)

**Comment by markmhendrickson** [comment]
@hstove mind linking the PR for this one?

**Comment by markmhendrickson** [comment]
@hstove ping on the PR link needed here 🐝

**Comment by hstove** [comment]
Sorry about that! @timstackblock this fix is included in #519 . To QA, I'd suggest installing the extension via the CircleCI build in #519 , and then using multiple multi-player apps, which triggers the bug related to this ticket. That PR also fixes #464 .
