### ISSUE TITLE
Ensure placement of close icon within intro modal

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#456]
It shows up to further to the left on http://humans.name/

![Screen Shot 2020-06-29 at 16.35.38.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/fd15d452-421e-4409-a38d-25806daae1fd)

**Comment by hstove** [comment]
I'm not seeing this on humans - did you change something?

**Comment by markmhendrickson** [comment]
Yep I removed the app's `button` tag styles entirely

**Comment by markmhendrickson** [comment]
Moving this to code review since I presume it's getting resolved with https://github.com/blockstack/ux/pull/521
