### ISSUE TITLE
Add pending indication when selecting 

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#464]
When a user clicks the button to confirm the usage of an account that's already been used with other apps, there's currently no indication that the action is pending before the popup closely entirely. This leaves the user with the feeling that perhaps taking action with the button didn't work. We should add some sort of pending state here so the user knows simply to wait.

<img width="469" alt="choose-account-confirmation" src="https://user-images.githubusercontent.com/28991/87231529-35aab480-c3b8-11ea-8ebd-6096c3ab2168.png">

**Comment by jasperjansz** [comment]
We have a component available in our design system that we should use: https://blockstack.design/components/button#button-loading-state
