### ISSUE TITLE
Remove expired usernames from display on "choose accounts" screen

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#465]
Perhaps adding a link to documentation about renewing or re-buying expired usernames.

![Screen Shot 2020-07-01 at 15.08.22.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/85590a54-732c-4a91-a3d9-39c041014938)

**Comment by jasperjansz** [comment]
https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Authenticator?node-id=7829%3A89907

**Comment by aulneau** [comment]
I'm not sure hiding or disabling them would be the right course to choose. Even if a username is expired, the account could still use apps that don't require them

**Comment by markmhendrickson** [comment]
That's a good point. Perhaps we should flag that expiration and provide a path for renewal, but otherwise allow the user to authenticate with just the associated address.

**Comment by aulneau** [comment]
> otherwise allow the user to authenticate with just the associated address.

just to clarify, regardless of if an account has a username, the associated address is what is always authenticating.

**Comment by hstove** [comment]
> just to clarify, regardless of if an account has a username, the associated address is what is always authenticating.

👍🏼 I think the main issue is that `@stacks/auth` will fail if an expired username is included in the `authResponse`, so simply being smarter about that (and not including the username) is the main impact

**Comment by markmhendrickson** [comment]
Expired names should no longer impede the selection of accounts for app authentication now that @janniks has removed username-checking from auth in general with https://github.com/hirosystems/stacks-wallet-web/pull/2333.

However, these expired names still do appear on the "choose accounts" screen. I've renamed this issue to focus on their removal from there, reverting back to "Account N" just as how things work on the home screen as desired:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/28991/165738685-7cba943a-e219-4c58-8e88-62338df32005.png">

<img width="427" alt="image" src="https://user-images.githubusercontent.com/28991/165738705-f2041a6e-177b-424c-af58-7c05112648af.png">
