### ISSUE TITLE
Change button label in introductory modal from "Get started"

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#466]
We currently have a conflict in that we encourage apps to display "Get started" as an option on their landing pages to trigger the introductory modal, but then we display "Get started" again in the modal for triggering the generation of a Secret Key.

We should update the latter to something like "Generate Secret Key" to prevent confusion with users who question why they're getting prompted for the same thing twice.

![Screen Shot 2020-07-01 at 15.10.01.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/d56b0dc9-f7de-4360-a9b0-93581d80ca0d)

**Comment by jasperjansz** [comment]
We don't tell developers to use 'Get started'. We say: "Provide a generic button for users that are new to your app and Blockstack." 

I predict that your proposed label would perform worse than what we have now as it can be interpreted as something the user has to do. If developers care about the sequential 'get started' labels, they would use a different label for theirs.

**Comment by markmhendrickson** [comment]
Fair, though we do use "Get started" in [this docs](https://docs.blockstack.org/develop/connect/overview.html#provide-an-easy-way-in-for-new-users) graphic so perhaps we should update it to something else:

![](https://docs.blockstack.org/develop/images/connect-call-to-action-branding.png)

**Comment by jasperjansz** [comment]
I think we can change it to "Get your Secret Key" https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Authenticator?node-id=5721%3A12547
