### ISSUE TITLE
Add option to install extension during onboarding

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#469]
So that users to want to avoid the hosted Blockstack app from the start can do so without having the leave the app context to search for the Blockstack extension and install it before returning to complete their onboarding.

It may make the most sense to add the option here as "Install extension", having it pop up https://www2.blockstack.org/install-extension in a new tab. And perhaps we should add a message upon installing the extension that says something to the extent of `If you've installed the Blockstack extension to authenticate an app, please return to that app's tab now and proceed by selecting "Get Started" or "I already have a Secret Key".`

![Modal](https://user-images.githubusercontent.com/28991/86340279-f2807100-bc54-11ea-9277-25fc2007d995.png)

**Comment by jasperjansz** [comment]
It's going to be hard to fit in here, especially on smaller mobile devices. What's the security consideration here? We don't ask for re-entry. If it's all the same we could put it at the end of the flow as an optional upgrade, after username.

**Comment by markmhendrickson** [comment]
The hosted authenticator could be maliciously modified to siphon the newly generated key.

**Comment by jasperjansz** [comment]
https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Authenticator?node-id=5721%3A12547

This will require changing the "I already have a Secret Key" label to "Sign in" to prevent wrapping which will cause the modal to be bigger than the screen on small mobile devices.

**Comment by markmhendrickson** [comment]
It'd be great to user test this change, but I think it's safe enough to push and see what happens with production data.
