### ISSUE TITLE
Display prompt to install extension on sign-in screen

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#471]
We currently show a prompt to install the extension on the account selection screen. We should also show it on the sign-in screen so users who don't want to authenticate with the hosted Blockstack App first can install it before proceeding.

Rough mockup:

![sign-in-extension-prompt.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/3fc28519-0ecd-4041-85f5-01ca779debde)

**Comment by timstackblock** [comment]
this works as expected
