### ISSUE TITLE
Disable spellcheck on username field

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#472]
I could have swore we had this disabled before and this could be a regression? 🤔

![Screen Shot 2020-07-02 at 11.53.07.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/d6af06ea-971e-4428-b1fc-bfab710ae143)

**Comment by timstackblock** [comment]
Its fixed in this build 

![Screen Shot 2020-07-31 at 2.37.34 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/82bf012c-b886-44e0-97c5-71a496edc533)
