### ISSUE TITLE
Make extension landing page the app landing directly + resolve that it shows this page even when logged in

### ISSUE THREAD

**Issue by cuevasm** [leather-io/extension#474]
When clicking the extension, it should jump directly to the app choices page or your wallet/profile management area vs. this mostly blank page. 
![image](https://user-images.githubusercontent.com/6131188/86368600-a7c71f00-bc7d-11ea-8e79-124db4a94e55.png)

Also, it tells me I'm logged out even when I'm logged in

**Comment by kyranjamie** [comment]
Was right about to suggest the same. After installing most will instinctively press the newly-appeared button, so can come up with something more helpful here (hopefully with a super cool illustration!).
