### ISSUE TITLE
Icon for dark mode / dark theme

### ISSUE THREAD

**Issue by whoabuddy** [leather-io/extension#480]
Small request, but if there is a way to enable a white (or at least brighter) logo for people who use dark mode / a dark theme, it would provide a cleaner experience! Below are my extensions lined up and the Blockstack one is difficult to see:

![2020-07-06 07 41 15 mdhmgoflnkccjhcfbojdagggmklgfloo 08d08350538a](https://user-images.githubusercontent.com/9038904/86611287-55c71780-bf63-11ea-90b5-4b1c4b3df288.png)

Possible example here: https://stackoverflow.com/questions/58880234/toggle-chrome-extension-icon-based-on-light-or-dark-mode-browser

**Comment by jasperjansz** [comment]
Seems this requires some custom code, as per [this link](https://stackoverflow.com/questions/58880234/toggle-chrome-extension-icon-based-on-light-or-dark-mode-browser). 

@hstove If you have any appetite for taking this on, here's a .zip with white logos: 
[blockstack white.zip](https://github.com/blockstack/ux/files/5069850/blockstack.white.zip)

The easiest fix would be to use this periwinkle icon color that works on both light and dark mode, we do this on our website too: [blockstack periwinkle.zip](https://github.com/blockstack/ux/files/5069810/blockstack.periwinkle.zip). I'd be fine with that.
