### ISSUE TITLE
Add link to testnet demo app to README

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#487]
https://authenticator-demo.netlify.app/

**Comment by hstove** [comment]
The demo app is published in this repo itself :) https://github.com/blockstack/ux/tree/master/packages/test-app

**Comment by markmhendrickson** [comment]
Innnnteresting 😁 This UX repo can get a bit confusing (e.g. can't search GitHub for that app's repo name). Should we add it to the repo's README at least?

**Comment by hstove** [comment]
Yep we should at it to the readme. I agree that the monorepo can have downsides like what you're saying.
