### ISSUE TITLE
Display apps with Blockstack Connect on home

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#490]
We should display a selection of apps that have integrated Blockstack Connect on the homepage when the user is both authenticated and unauthenticated, which is especially important in the context of the extension where users are much more likely to visit this page post-install before authenticating any app.

This would save the user a step from having to click "Find an app to use" and reduce confusion as to why the screen is so blank.

We could use an API we set up with the data source that @cuevasm is planning with GitHub data to automate the apps shown here.

![Screen Shot 2020-07-08 at 15.42.22.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/aefd6381-7926-473a-b50b-f1abbbd01370)

**Comment by jasperjansz** [comment]
https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Authenticator?node-id=7838%3A6

**Comment by markmhendrickson** [comment]
This design generally looks like it's on the right track. But we need to update some pieces:

- The logo shouldn't say App.co for this issue. Though we've discussed hosting the app there, it's not decided or part of this issue per se.
- We should remove search for now since it's a nice-to-have that'll make this issue a lot more complicated as-is.

**Comment by markmhendrickson** [comment]
I'm closing this out since we're removing the home screen in general for Connect 2.0, and users who authenticate outside of any app will get directed to App.co at the end per https://github.com/blockstack/ux/issues/673.
