### ISSUE TITLE
Replace total to fee estimate

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#495]
I'm seeing 0 STX for writing a status with the testnet demo app:

![Screen Shot 2020-07-09 at 14.43.34.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/110e2752-08cb-4093-a9d9-ea53cc15be91)

**Comment by hstove** [comment]
It's not rounded down - there is no fee estimation implemented at all. The total cost is a shim from a while ago that needs to be updated.

**Comment by markmhendrickson** [comment]
Ah I see. Should we include replacing this shim for the debug mode release?

**Comment by markmhendrickson** [comment]
Let's change provisionally to "Fee estimate"
