### ISSUE TITLE
Enable adding existing keys with 'authenticate' or Why authenticate and showBlockstatckConnect

### ISSUE THREAD

**Issue by dantrevino** [leather-io/extension#502]
With the `authenticate` and `showBlockstackConnect` options, I'm forced to either force users to create a new key if they haven't ever used the current browser (authenticate option) or, force users to indicate that they have a key already **_everytime with each authorization_**, even if they've used the current browser (showBlockstackConnect option).  I dont understand why the two options are mutually exclusive.

A simple yes/no before generating a new key, in the 'authenticate' process would make things much more streamlined, so that I can just enter my current key, if I havent used the current browser before.

**Comment by markmhendrickson** [comment]
This is good feedback. I'm closing out this issue since it'll be incorporated into https://github.com/blockstack/ux/issues/671 as part of Connect 2.0 upon which apps won't have to indicate upfront whether the user is new or existing.
