### ISSUE TITLE
List out names and domains for apps already used with chosen username during auth

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#503]
On this screen for clarity since it's not always easy to recognize the existing apps by their icons:

<img width="469" alt="choose-account-confirmation" src="https://user-images.githubusercontent.com/28991/87231477-05fbac80-c3b8-11ea-8200-fcaec524ceff.png">

**Comment by jasperjansz** [comment]
https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Authenticator?node-id=5721%3A11526

We'll need to truncate at some point("..., and 3 more"). I'd suggest after 3

**Comment by markmhendrickson** [comment]
I'm closing out this issue since the need will be addressed in Connect 2.0 as part of #671.
