### ISSUE TITLE
Fix ability to authenticate with renewed username

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#504]
My username `markmhendrickson.id` expired but remained listed in the "Choose username" modal during authentication. Having since re-purchased it, I'm unable to authenticate with any apps (e.g. https://app.sigle.io/, http://humans.name/).

The selection interaction for this username works in the popup, but then I see an error in the app's console after the popup closes automatically.

<img width="1269" alt="Screen Shot 2020-07-11 at 20 54 23" src="https://user-images.githubusercontent.com/28991/87231605-d0a38e80-c3b8-11ea-846b-3159db893bd4.png">

<img width="1212" alt="Screen Shot 2020-07-11 at 20 54 49" src="https://user-images.githubusercontent.com/28991/87231607-d7ca9c80-c3b8-11ea-892b-98f867123c39.png">

**Comment by markmhendrickson** [comment]
This issue may become particularly relevant again soon since usernames are set to expire en masse after their 1-year extension upon the launch of Stacks 2.0. Those who renew their usernames in time may find themselves subsequently unable to authenticate.

**Comment by fbwoolf** [comment]
@markmhx when I look at your username, the expire block is `52595` and the current block is `51673`, so why do you think your username is expired? https://stacks-node-api.mainnet.stacks.co/v1/names/markmhendrickson.id

**Comment by fbwoolf** [comment]
I can't reproduce this with the secret key @kyranjamie gave me bc his is the same: https://stacks-node-api.mainnet.stacks.co/v1/names/kyranjamie.id

**Comment by fbwoolf** [comment]
There are 3 requests made to the names endpoint 2 are successful and 1 returns an error:

200 Success:
https://stacks-node-api.mainnet.stacks.co/v1/names/kyranjamie.id.blockstack
https://stacks-node-api.stacks.co/v1/names/kyranjamie.id.blockstack
![Screen Shot 2022-03-09 at 7 34 29 PM](https://user-images.githubusercontent.com/6493321/157569730-4d885121-e1b4-464d-82c1-c5b030f62927.png)

400 Error:
https://registrar.stacks.co/v1/names/kyranjamie.id.blockstack
![Screen Shot 2022-03-09 at 7 36 07 PM](https://user-images.githubusercontent.com/6493321/157569872-444fa15b-3eed-4e3d-9109-c0aaa987152f.png)

**Comment by fbwoolf** [comment]
I feel like I am seeing a different welcome screen than shown in the issue description for Sigle:
![Screen Shot 2022-03-09 at 7 39 58 PM](https://user-images.githubusercontent.com/6493321/157570343-1f749ab7-9da6-4e97-9b3b-f36f71b11908.png)

**Comment by fbwoolf** [comment]
Going to drop a few links here in stacks.js that might be relevant to this issue:

`handlePendingSignIn`
https://github.com/hirosystems/stacks.js/blob/48159007703933326f0e5a1ff6a2c061f2c753e6/packages/auth/src/userSession.ts#L260

`verifyAuthResponse`
https://github.com/hirosystems/stacks.js/blob/48159007703933326f0e5a1ff6a2c061f2c753e6/packages/auth/src/verification.ts#L278

`doPublicKeysMatchUsername`
https://github.com/hirosystems/stacks.js/blob/48159007703933326f0e5a1ff6a2c061f2c753e6/packages/auth/src/verification.ts#L82

**Comment by fbwoolf** [comment]
https://stacks-node-api.mainnet.stacks.co/v1/names/fara.btc

My `expire_block` is `0` so now I'm confused?

**Comment by fbwoolf** [comment]
I see the zonefile now for `markmhendrickson.id` does show the name is expired: https://gaia.blockstack.org/hub/13ceLK6xjw367B8QpVLX6i2mDtoYg6iawt/profile.json

But, `kyranjamie.id` is not (which is likely why I can't repro the issue):
https://gaia.blockstack.org/hub/1JH5sHigAypQ5hTjioLRK31uasnv2HG35d/profile.json

**Comment by andresgalante** [comment]
@markmhx please confirm that this is still a bug and provide steps to reproduce it

**Comment by markmhendrickson** [comment]
I tried to authenticate with `markmhendrickson.id` again but the app (Arkadiko) didn't detect it.

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/28991/158204820-5501d269-3e33-41c9-b796-1b7112e40959.png">

Note the errors appear different than my original report from the days of Stacks 1.0.

**Comment by fbwoolf** [comment]
> 
> Note the errors appear different than my original report from the days of Stacks 1.0.

Looks like the error is coming from `handlePendingSignIn` which I had suspected might be where we would need to make changes ...linked to it in stacks.js here: https://github.com/hirosystems/stacks-wallet-web/issues/504#issuecomment-1064171378

**Comment by larrysalibra** [comment]
I have a similar error when signing in with a `.id` that has NOT yet been renewed since the stacks 2.0 launch but has been "upgraded" (transferred from the legacy owner key to the wallet key)

Digging around it seems like the error is coming not from the wallet but from Stacks Connect.

<img width="1109" alt="Screen Shot 2022-03-16 at 17 25 28" src="https://user-images.githubusercontent.com/597182/158558931-e1e84ec0-3acd-4b12-b527-342b61b50512.png">

**Comment by fbwoolf** [comment]
> 
> Digging around it seems like the error is coming not from the wallet but from Stacks Connect.
> 
Yes, Connect uses @stacks/auth `userSession`.

**Comment by fbwoolf** [comment]
@markmhx It looks like it is making a call to this endpoint and failing: https://registrar.stacks.co/v1/names/markhendrickson.id

It is throwing the error here: https://github.com/hirosystems/stacks.js/blob/b0d039671b8fe5bc0f35ed1bb9557c08d1f9e3b4/packages/auth/src/userSession.ts#L262

I suspect that `doPublicKeysMatchUsername` is returning false and throwing that error?

How do we tackle a fix needed in stacks.js?

**Comment by markmhendrickson** [comment]
@janniks could you possibly help determine and execute the fix here on the Stacks.js side?

**Comment by janniks** [comment]
Yes, I can look into this.

Do we have testnet id's (or something similar) for an expired and a valid id, for reproducing?

**Comment by markmhendrickson** [comment]
Good question. @Eshwari007 @timstackblock do you have any such usernames in your arsenal?

**Comment by Eshwari007** [comment]
> Good question. @Eshwari007 @timstackblock do you have any such usernames in your arsenal?

@markmhx @janniks We do have a couple of IDs in our test account. Not sure if they were from v1 though.
<img width="421" alt="Screen Shot 2022-03-17 at 9 55 24 AM" src="https://user-images.githubusercontent.com/38872890/158824503-b379a292-9cfa-496c-8a6c-2e63dc94ecd4.png">

**Comment by markmhendrickson** [comment]
Those usernames appear to be registered on Stacks 2.0 and therefore haven't expired yet.

@janniks it may be easiest if we meet via Zoom with screen share since I have an expired username in my personal wallet?

**Comment by larrysalibra** [comment]
I spent a bit more time digging into this today. I'm using the name "newinternetlabs.id" which was both renewed and transferred to the wallet address (aka upgraded). I haven't been able to sign in with it using Stacks connect since i transferred it to the wallet address.

Signing in with stacks todos sample app gives me a bit more information than in an app using Stacks Connect.

It says that that there was an error checking `doPublicKeysMatchUsername`.

In this function, we look at the issuer address from the authentication token and compare it to the address that owns the name.

Unfortunately, I can't figure out how to print out the token to console so that I can inspect its contents. Prior to stacks connect, this was passed in the address bar URL, but another method seems to be used. Happy to take a look if someone can point me in the right direction.

> It looks like it is making a call to this endpoint and failing: https://registrar.stacks.co/v1/names/markhendrickson.id

With regards to that error, I don't think that is the root of this problem. The function that verifies the username owner has several look up addresses and if any one of them succeeds, then the authentication will succeed. From what I've seen, this url: https://registrar.stacks.co/v1/names/ fails even on successful authentications because that url doesn't actually look up names. Perhaps it should be removed as a fallback url?


<img width="1094" alt="Screen Shot 2022-03-22 at 20 57 10" src="https://user-images.githubusercontent.com/597182/159487042-8c4fd089-4c11-405c-8503-9030c874b57d.png">

**Comment by markmhendrickson** [comment]
@janniks has prepared this build that removes all logic for checking usernames from the authentication process: https://www.dropbox.com/s/zpjwoddge0soy13/stacks-wallet-chromium.zip?dl=0

It can be used to test whether this issue is resolved, and whether there are any undesired side effects to doing so.

@larrysalibra our suspicion here is that it's not necessary to block authentication with such checks in general, and it's most expeditious to just get rid of them if they're causing issues with renewed and expired names. Do you recall why these lookups were integrated into blockstack.js in the first place?

**Comment by MountainMaster** [comment]
The DEV-Version (3.3.0?) did not work for me.
On btc.us it does not login without any response and on arkadiko I get the following error

```
code: "login_failed"
message: "Failed to login: Invalid authentication response."
name: "LoginFailedError"
```
![image](https://user-images.githubusercontent.com/7562077/159667963-00da77da-0820-4d2b-ac58-a87e0a60033c.png)

**Comment by markmhendrickson** [comment]
I'm getting the same – note the "doPublicKeysMatchUsername" error checking message

<img width="867" alt="image" src="https://user-images.githubusercontent.com/28991/159727906-bc7e8c97-aaeb-483c-9139-84e7f7e70cd7.png">

<img width="418" alt="image" src="https://user-images.githubusercontent.com/28991/159728177-625f6d08-fa6c-449b-b39b-6812aa80ad67.png">

**Comment by markmhendrickson** [comment]
@janniks do you expect this issue to be resolved fully app-side with https://github.com/hirosystems/stacks.js/pull/1230?
