### ISSUE TITLE
Show apps used with username when selected from homepage

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#505]
Right now, we show the pointer cursor on hover but the interaction doesn't do anything. We should show the apps already authenticated by the user with a particular username upon selection, linked off to those apps for convenience.

<img width="676" alt="Screen Shot 2020-07-11 at 20 58 04" src="https://user-images.githubusercontent.com/28991/87231656-44459b80-c3b9-11ea-8d8b-c9e98810d3d2.png">

**Comment by jasperjansz** [comment]
@markmhx I don't think we need this. Because we'll have app.co with a select number of apps as the homepage and because only Blockstack employees have this many accounts.

**Comment by markmhendrickson** [comment]
I'm thinking developers who try out the ecosystem and play with a few apps might want to see which they've authenticated per identity. But I'm happy to icebox for now until we get requests for this.
