### ISSUE TITLE
Improve header for homepage when authenticated

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#506]
Currently it says "Sign out" which isn't that appropriately contextually above the list of usernames. Perhaps simply "My usernames" would be better.

<img width="676" alt="Screen Shot 2020-07-11 at 20 58 04" src="https://user-images.githubusercontent.com/28991/87231686-76ef9400-c3b9-11ea-9aa1-55e6e6ada1da.png">

**Comment by jasperjansz** [comment]
This was the design all along: https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Authenticator?node-id=5721%3A12488

I think it should say account considering we use account everywhere else when referring to the combination of username + data:

![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/6e54f3a0-ef7b-415a-944d-0a7c3220080a)

**Comment by markmhendrickson** [comment]
@jasperjansz The screenshot you've posted above refers to the "Choose account" screen during authentication whereas this issue pertains to the home screen of the Blockstack App once authenticated already.

**Comment by jasperjansz** [comment]
I know, that's not the design

**Comment by markmhendrickson** [comment]
I presume it's [this one](https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Authenticator?node-id=7838%3A492) but needs updating with removal of App.co logo.

Also, does it make sense to link to "My accounts" if we're already viewing them? I guess it's okay as a standard / constant nav.

**Comment by jasperjansz** [comment]
The homepage view would be the apps, not accounts. You can navigate to view accounts.

app.co when authed: https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Authenticator?node-id=7838%3A6

click 'my accounts' in menu: https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Authenticator?node-id=7838%3A492

app.co when not authed:
https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Authenticator?node-id=7838%3A252

**Comment by markmhendrickson** [comment]
True, with https://github.com/blockstack/ux/issues/490, this accounts page will get removed from the home position
