### ISSUE TITLE
Connect: Users without a username should be prompted to set one on first login

### ISSUE THREAD

**Issue by agraebe** [leather-io/extension#527]
Some users don't set a username (https://github.com/blockstack/ux/issues/526). When they use their Secret Key to log in, they should be prompted to set their username before the login completes.

Users without usernames can create issues within apps when they assume usernames are always available.

**Comment by markmhendrickson** [comment]
I'm closing out this issue since the need will be addressed in Connect 2.0 as part of https://github.com/blockstack/ux/issues/671.
