### ISSUE TITLE
Support multiple transactions in row for given user and contract

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#530]
Currently subsequent transactions fail due to nonce considerations

**Comment by markmhendrickson** [comment]
@hstove will QA this first before passing to @timstackblock

**Comment by markmhendrickson** [comment]
@hstove might it be best to hand this directly over to @timstackblock for QA?

**Comment by timstackblock** [comment]
@markmhx @hstove your call just let me know either way.

**Comment by timstackblock** [comment]
This is not working as expected. It allowed me to do 2 in a row but after the 3rd try I was rejected.

<img width="637" alt="Screen Shot 2020-11-09 at 2 57 33 PM" src="https://user-images.githubusercontent.com/49165468/98589950-16eff800-229c-11eb-878c-7e760d0481c9.png">
<img width="1426" alt="Screen Shot 2020-11-09 at 2 57 13 PM" src="https://user-images.githubusercontent.com/49165468/98589954-17888e80-229c-11eb-8bac-7a224ed194b5.png">

**Comment by timstackblock** [comment]
Testnet demo not working, user cannot access the page

<img width="1346" alt="Screen Shot 2020-12-09 at 8 57 00 AM" src="https://user-images.githubusercontent.com/49165468/101638930-af44de00-39fc-11eb-805d-fb0b13626581.png">

**Comment by markmhendrickson** [comment]
@timstackblock I presume you need to use the instance on the connected PR? https://github.com/blockstack/ux/pull/601#issuecomment-696480324

Although the console shows a 500 error suggesting we have an API problem.

**Comment by hstove** [comment]
Closing this, since we are going with a microblock approach for this problem.
