### ISSUE TITLE
Add link to faucet or automatic deposit if user has insufficent funds in testnet mode

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#532]
In the transaction signing popup within testnet mode, we should link to https://www.blockstack.org/testnet/faucet somehow if the user doesn't have sufficient funds instead of dead-ending them.

We may also want to include a refresh button they can use once the faucet transaction has been triggered and confirmed on chain.

Alternatively, we could also trigger a faucet call automatically from within Connect if the user has no funds in testnet mode, showing a message and spinner until the transaction is subsequently recognized and the user can continue to confirmation.

**Comment by jasperjansz** [comment]
https://www.figma.com/file/Wan0HuWjhyg77zJZK3yUKg/Transaction-signing?node-id=160%3A1319
