### ISSUE TITLE
Mask Secret Key during sign in

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#533]
Currently we display it in full view. It'd be safer to mask the inputted value and provide a secondary option to display it for correction or typing purposes.

<img width="416" alt="Screen Shot 2020-07-21 at 16 15 44" src="https://user-images.githubusercontent.com/28991/88065945-7f8c5b00-cb6d-11ea-92d7-986583709e6c.png">

**Comment by jasperjansz** [comment]
https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Authenticator?node-id=7829%3A90114

**Comment by friedger** [comment]
Same for "View Secret Key" (#/settings/secret-key)! Should be masked initially.

**Comment by markmhendrickson** [comment]
I'm closing out this issue since the need will be addressed in Connect 2.0 as part of #671 and https://github.com/blockstack/ux/issues/688.

The Secret Key value will be masked upon entry during authentication and protected by password entry upon subsequent view.
