### ISSUE TITLE
@blockstack/connect@testnet  appears to be incompatible with the authenticator extension

### ISSUE THREAD

**Issue by dantrevino** [leather-io/extension#535]
Just curious how the recommended development environment should be set up.  If I want to test connect@testnet, is there a version of the authenticator extension that I can also test with?

**Comment by markmhendrickson** [comment]
@hstove should know best on how to set up a dev environment with the extension.

Note that we've had to push back the release of transaction signing support this week given uptime issues with testnet. It's TBD just when things will be operational again and we can officially go live with testnet support for Connect.

**Comment by hstove** [comment]
Hey @dantrevino , you're right, two things here:

- We need to submit a new version of the extension. I have this on my list for tomorrow.
- The transaction signing stuff in Connect is now released. You can use it in the latest version, i.e. `2.10.1`.

I'll update this ticket once the extension version is published.

**Comment by hstove** [comment]
Extensions have been submitted!
