### ISSUE TITLE
Move Blockstack App to new domain (e.g. App.co)

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#543]
Once we've added apps to the homepage with https://github.com/blockstack/ux/issues/490, the Blockstack App and App.co will serve redundant purposes for app discovery.

We should host the Blockstack App on App.co to resolve this redundancy and gain the shorter App.co domain for the Blockstack App, which is much better than app.blockstack.org.

With upcoming PBC rebrand work, we'll have to change the name of "Blockstack App" as well. So perhaps we can simply start calling it App.co and even keep the logo.

**Comment by friedger** [comment]
Your identity wallet becomes an app store? Hm, not sure whether I as a user would like to give app developers or app store editors access to the "home screen" of my identity wallet. That could be a security issue.

**Comment by markmhendrickson** [comment]
I don't imagine we'd give any developers or editors access to your home screen or data by default as part of this move, nor in regards to #490 itself where I'd expect any personalization of app discovery based on user data to be completely opt-in

**Comment by friedger** [comment]
If my identity wallet becomes the main place for discovering apps then the identity wallet is the place to focus on attention buying. Why not keep two apps?

I haven't used apps like tokenpocket for this reason.

**Comment by markmhendrickson** [comment]
I'm not sure what you mean by "the place to focus on attention buying" exactly?

The general idea here with consolidating into one app is usability, since the authenticator will likely benefit from showing _authenticated_ apps at the very least. And there seems little reason to send someone off to another property to discover _unauthenticated_ ones.
