### ISSUE TITLE
Update Chrome and Firefox extension store descriptions

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#544]
Note the new use of `https` for the links and instructions for building from source in particular:

> Access privacy-friendly apps that keep you in control of your data and identity.
> 
> The Blockstack extension is a full client-side authenticator for accessing apps built with Blockstack Connect without having to create or enter your Secret Key with Blockstack PBC’s hosted authenticator at https://app.blockstack.org/.
> 
> The extension will automatically handle all attempts to authenticate such apps instead of redirecting you to the hosted authenticator. There is no need for configuration.
> 
> Instructions for building from source are also available at https://www.blockstack.org/install.

cc @zone117x

**Comment by hstove** [comment]
All set!
