### ISSUE TITLE
Fix icon loading in Blockstack extension

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#545]
Icons aren't loading for me when using the extension with the testnet demo at http://testnet-demo.blockstack.org/

![Screen Shot 2020-07-23 at 11.25.46.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/e929685f-9d37-49fb-ae9d-14b14ae8d3ce)

**Comment by hstove** [comment]
I am unable to reproduce this bug, unfortunately. @timstackblock can you repro?
