### ISSUE TITLE
Fix authentication callback for extension with testnet demo

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#546]
At the end of authentication it says that the app can't be reached. This problem doesn't arise with the extension disabled.

![Screen Shot 2020-07-23 at 11.26.27.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/42d5c98e-34c4-4a2e-a4ee-e4562808c197)

**Comment by hstove** [comment]
Can you try this again? I'm not able to reproduce.

**Comment by markmhendrickson** [comment]
I can't reproduce either
