### ISSUE TITLE
"Choose account" popup remains open after authenticating

### ISSUE THREAD

**Issue by john-light** [leather-io/extension#549]
After clicking "I already have a secret key" on a Blockstack app (any Blockstack Connect-enabled app, presumably), the Blockstack App extension opens in a "Choose account" popup window. I click my account and log in. A new tab opens in my main browser window, showing I am logged in to the app. The "Choose account" popup window is still open.

I think a better ux would be for the "Choose account" popup window to close itself if I successfully authenticate and log in to the app I'm trying to use.

**Comment by markmhendrickson** [comment]
I haven't seen this behavior personally, in that the "Choose account" popup always closes for me upon selection. Mind checking the related windows' console logs?

I assume you're using the same system and browser as with other issues you've created (Browser: Firefox 78.0.2, OS: Linux Mint 18.3)?

cc @timstackblock in case he's spotted this before

**Comment by john-light** [comment]
> I assume you're using the same system and browser as with other issues you've created (Browser: Firefox 78.0.2, OS: Linux Mint 18.3)?

Yes

> Mind checking the related windows' console logs?

![popup1](https://user-images.githubusercontent.com/9424721/88445239-6397ec00-cdef-11ea-8142-ee50de681b64.png)

![console2](https://user-images.githubusercontent.com/9424721/88445245-672b7300-cdef-11ea-816d-dcedbc683177.png)

**Comment by cytns** [comment]
Hi guys. You can play with it in fullscreen mode on MacOS (chrome, safari).

[YouTube video with bug](https://youtu.be/t12heP9q0yE)

**Comment by timstackblock** [comment]
@eugeneive thank you for the video, I see where you went wrong. You never selected the button that confirms you copied your seed phrase. This is a step that you skipped in the creation process which caused your issue.

You closed the popup that asked you to confirm that you copied your seed phrase, then you selected create again, this is what caused the issue you are seeing, this is not a bug.

**Comment by timstackblock** [comment]
@john-light thanks for creating this issue, I was not able to reproduce this bug. I did see that the connect screen was maximized in the browser to full screen. I know it does maximize if a connect popup is closed so I think that it could be possible that this is a user flow issue and not a bug.

Here is a video of me running through the use case.
https://screencast-o-matic.com/watch/cYj6b2GrPR

**Comment by timstackblock** [comment]
Hey @john-light could you send me a video of your issue. Hank has an open PR and would like to see if the current PR will fix any problems around authentication staying open. @eugeneive this fix may help with any issues you see if you x out of a pop up and then click the previous startup.

**Comment by john-light** [comment]
@timstackblock a change must have been merged since this issue was first opened as it now works as expected. the auth window is now closing when I select the account I want to auth with. closing the issue.
