### ISSUE TITLE
Sign in button in test demo app doesn't seem to work without the extension.

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#567]
sign in button in test demo app doesn't seem to work without the extension. If I disable the extention the 
<img width="1438" alt="Screen Shot 2020-07-31 at 2 04 13 PM" src="https://user-images.githubusercontent.com/49165468/89065116-2ecced00-d339-11ea-9a3b-8b14a4c8b03e.png">
button does not work

**Comment by hstove** [comment]
I am not able to repro. There is an issue where, if you load the demo app home page, and then disable the extension, and then try to sign in, it will fail. You get the same error message as the one you posted.

I don't think there is a good fix for that, or if we should bother fixing it. However, if I load the demo app without the extension installed (or simply disabled), then it works just fine.

**Comment by markmhendrickson** [comment]
@timstackblock does it indeed work for you without the extension if you refresh the page after disabling the extension before trying to auth?
