### ISSUE TITLE
Changes to the Ink colours

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#568]
I've recently made changes to the Ink colours to improve contrast. These changes enable a better contrast between body copy and headers.

See Figma: https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/Design-System?node-id=166%3A45

**Comment by markmhendrickson** [comment]
Should these changes to be applied to our properties anywhere in particular? The UI library?

**Comment by jasperjansz** [comment]
yes UI library
