### ISSUE TITLE
Remove download the extension from mobile

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#575]
Currently when you use mobile you see a desktop link to download the desktop brows
<img width="298" alt="Screen Shot 2020-08-17 at 9 15 06 AM" src="https://user-images.githubusercontent.com/49165468/90400596-b4a3a480-e06a-11ea-8f27-f957a381cab4.png">
er extension

**Comment by markmhendrickson** [comment]
@hstove can we move this to QA and assign @timstackblock ?
