### ISSUE TITLE
String continuations are not recommended

### ISSUE THREAD

**Issue by njordhov** [leather-io/extension#576]
When using `@blockstack/ui` the linter informs me that _String continuations are not recommended_, explaining that:

> Do not use line continuations (that is, ending a line inside a string literal with a backslash) in either ordinary or template string literals. Even though ES5 allows this, it can lead to tricky errors if any trailing whitespace comes after the slash, and is less obvious to readers.

The offending code is 

https://github.com/blockstack/ux/blob/fd845ae39256ed6deed1cb2ccdefeb4fb675df88/packages/ui/src/highlighter/language-definition.tsx#L49-L53

https://github.com/blockstack/ux/blob/fd845ae39256ed6deed1cb2ccdefeb4fb675df88/packages/ui/src/highlighter/language-definition.tsx#L65-L67

https://github.com/blockstack/ux/blob/fd845ae39256ed6deed1cb2ccdefeb4fb675df88/packages/ui/src/highlighter/language-definition.tsx#L75-L76

**The fix is to replace the string continuations with concatenations, like using `+` to concatenate each line.**

**Comment by hstove** [comment]
@njordhov when you say "the linter" are you referring to our ESLint rules? I assume we're not violating ESLint, because we'd be getting CI notifications for it. Also, our ESLint rules prevent trailing whitespace, which should prevent this error.

I'm happy to see this change implemented, but I'm going to leave this ticket unassigned in case someone wants to pick it up. It should be a good "first issue".

**Comment by njordhov** [comment]
> when you say "the linter" are you referring to our ESLint rules?

No, the warning is coming from the [Closure transpiler](https://github.com/google/closure-compiler) when including `@blockstack/ui` as an external dependency. ESLint does have a rule to [disallow multiline strings](https://eslint.org/docs/rules/no-multi-str) but I presume it is disabled.

This is obviously not critical. I just noticed it when compiling and pass it on as a courtesy. It's a good first issue or an update next time that part of the code is touched.

**Comment by markmhendrickson** [comment]
@njordhov is this still relevant and should be reopened?
