### ISSUE TITLE
[connect] dependency errors

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#587]
Using the latest connect, it does not automatically install `@blockstack/stacks-transactions`

```
error - ./node_modules/@blockstack/connect/dist/connect.cjs.development.js:12:0
Module not found: Can't resolve '@blockstack/stacks-transactions'
```

**Comment by kyranjamie** [comment]
[Same issue reported on discord as well, I think](https://discordapp.com/channels/621759717756370964/623217767356694547/754986737100390441)

**Comment by hstove** [comment]
Working on this - also updating stacks-transactions to 0.7.0, but getting about a dozen TS errors

**Comment by hstove** [comment]
This is fixed on the Stencil branch
