### ISSUE TITLE
Connect expects legacy Blockstack SDK

### ISSUE THREAD

**Issue by njordhov** [leather-io/extension#588]
When installing Connect the log says it _requires a peer of blockstack@^19 but none is installed_ despite an explicit dependency on `"blockstack": "^21.0.0"`. 

The reason is that Connect has a **peer dependency** on `"blockstack": "^19"` which only covers the legacy versions of the SDK.

A fix is to change the peer dependency to **allow all later versions of the SDK**, such as `"blockstack": ">=19"`.

**Comment by markmhendrickson** [comment]
@njordhov mind providing a PR for this change? And am I understanding it correctly that this doesn't block usage, just present a warning?

**Comment by njordhov** [comment]
PR #653 updates the dependency.

> am I understanding it correctly that this doesn't block usage, just present a warning?

Yes, although I suspect the confusing warning during installation can be a turnoff for some.
