### ISSUE TITLE
Transaction id returned from openSTXTransfer() returns transaction id without the hex identifier

### ISSUE THREAD

**Issue by dantrevino** [leather-io/extension#595]
It would be more consistent for devs if you returned the hex identifier as part of the txId returned in the callback.
For instance, `0x72fcc60956862....` instead of `72fcc60956862....` in the example below.

```javascript      
openSTXTransfer({
        recipient: this.recipient,
        amount: this.amount,
        memo: this.memo,
        appDetails: {
          name: "Webby",
          icon: "https://heywebby.app/app-logo-128x128.png"
        },
        finished: data => {
          console.log("transaction data: ", data);
        }
 });
```

```json
{
txId: "72fcc60956862ada3b39f6dc75bb45a920efb33aa49c6266b69b290196a54c53", 
txRaw: "80800000000400139e0d344a29feae1ccb77510915e06bc757…0000000000000000000000000000000000000000000000000", 
source: "blockstack-app"
}```

**Comment by dantrevino** [comment]
also, shouldn't `source` be returning app details, rather than hard-coded 'blockstack-app'?

**Comment by markmhendrickson** [comment]
The authenticator itself is called "the Blockstack App" (yea...it's confusing) so I presume that's why source is labeled as such here.

Assigning to @hstove to take a look at the hex change.

**Comment by hstove** [comment]
Yep, this is a good change to make, I'll try and fit it into an upcoming sprint.

> also, shouldn't source be returning app details, rather than hard-coded 'blockstack-app'?

In this case "source" is just an artifact of how we pass messages with `window.postMessage`. It shouldn't be in the `onFinished` callback, though, so I can address that as well.

**Comment by markmhendrickson** [comment]
@hstove can we close out this issue now that https://github.com/blockstack/ux/pull/651 is merged?
