### ISSUE TITLE
[ui] Add stories to document the components

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#599]
[Storybook](https://storybook.js.org) seems to be a nice tool to document the ui components

![Screenshot from 2020-09-21 12-02-54](https://user-images.githubusercontent.com/1449049/93754697-6c941680-fc02-11ea-81d3-3fb2b249322b.png)

**Comment by markmhendrickson** [comment]
@aulneau @kyranjamie thoughts on this tool?

**Comment by kyranjamie** [comment]
I'd love for us to use Storybook. This'll help tremendously building out and testing components. Thanks @friedger

**Comment by aulneau** [comment]
I'm very open to it, too! There is a pr here that you can work from @friedger https://github.com/blockstack/ui/pull/48

**Comment by friedger** [comment]
Closing this in favor of https://github.com/blockstack/ui/issues/50
