### ISSUE TITLE
Clicking the sign in option and then the "create a secret Key" link opens an empty box with no secret key

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#605]
Clicking the sign in option and then the "create a secret Key" link opens an empty box with no secret key.

<img width="439" alt="Screen Shot 2020-09-24 at 8 19 33 AM" src="https://user-images.githubusercontent.com/49165468/94144402-12cc6000-fe3f-11ea-81af-5658fccda48f.png">

Video of the issue
http://somup.com/cYQZlqXRH9

Since the secret key never generates the user is stuck with an infinite spinner if it tries to enter a username and proceed. Even after closing out and going back in the user is stuck in this state and cannot generate a secret key. 

This bug seems pretty serious as the user experience is really bad and the user is stuck on the username screen.

**Comment by hstove** [comment]
@timstackblock this is in Chrome, yeah? I am unable to repro this right now.
