### ISSUE TITLE
[connect] ContractAddress vs StacksAddress

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#609]
The stacks-blockchain-api and connect library use an address and name parameter to specify a contract, e.g. in `doContractCall` The stacks blockchain api client library uses `stacksAddress` as parameter name, connect uses `contractAddress`.

This issue is to raise awareness. The solution probably only affects the stacks blockchain api repo, see: https://github.com/blockstack/stacks-blockchain-api/issues/258

**Comment by markmhendrickson** [comment]
@agraebe let's include this consideration in the upcoming DevX discussion about Stacks-related library organization? cc @hstove

**Comment by agraebe** [comment]
yeah, let's align on the convention and do the changes incrementally. Being consistent across tools will remove a lot of the confusion that exists nowadays
