### ISSUE TITLE
Persist checkbox to not show warning again and improving info architecture for saving this preference

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#61]
[Prototype](https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=4396%3A0)

    - Updated with proposal F → always ask for username & the warning message
    - Put the mobile design in the desktop one so you can compare easily (flow is exactly the same)
    - Error/success states
    - Magic recovery support flow
    - Components that I’ve used

**Comment by markmhendrickson** [comment]
Still in progress: persisting checkbox to not show warning again and improving info architecture for saving this preference

**Comment by markmhendrickson** [comment]
@hstove Any update on this one? Seems like we can finish this as part of the developer release, given it's for sign-in.

**Comment by hstove** [comment]
Hey Tim, here are the QA steps:

- Login to banter.pub (it doesn't matter if you create a new account or use an existing one)
- Login to staging.banter.pub, and make sure you re-use the same username that you used in the previous step
- A popup should appear that warns you about re-using this username
- You should be able to continue and re-use that username
- If you select the "don't show me again" checkbox, then this warning should never appear again, on any of the usernames you have for this secret key.

**Comment by timstackblock** [comment]
I am guessing that this is not merged, I am still seeing the blank secret key. I will retest once this is ready to go.


<img width="1266" alt="Screen Shot 2020-02-13 at 10 52 57 AM" src="https://user-images.githubusercontent.com/49165468/74452404-07e43280-4e4f-11ea-8555-68af5dbb9752.png">

**Comment by hstove** [comment]
This is indeed ready to go and everything is deployed/up-to-date. The error you're seeing is unrelated here.

**Comment by timstackblock** [comment]
I still do not get a popup window when I try to use the same username on staging.banter.pub that I just created on banter.pub @hstove @markmhx 

Please take a look at the video below

http://somup.com/cYnIqGhoOE


Let me know if I have the use case wrong or if this is a bug or if the code is not deployed.

**Comment by timstackblock** [comment]
This is working as expected.
