### ISSUE TITLE
ERROR MESSAGE BROKEN IN FF: IP rate limiting pop up displays in Chrome browser but not in FF browser

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#611]
While testing I hit a rate limit for my IP address as expected.

In chrome I got the expected error message 

<img width="1426" alt="Screen Shot 2020-09-28 at 9 23 07 AM" src="https://user-images.githubusercontent.com/49165468/94438061-99997980-016c-11eb-9562-9d15c4cc3424.png">

In Mozilla FF the browser refreshed the page with no error message but I can see the failure in console. I believe the error messaging for FF was broken in the last build. 
Please see the video below.

http://somup.com/cYQuIZlfPB

Firefox browser has no error message pop up, the original page just refreshes, but the error displays in console.

<img width="1436" alt="Screen Shot 2020-09-28 at 9 27 02 AM" src="https://user-images.githubusercontent.com/49165468/94438260-df564200-016c-11eb-8f8f-d028f99f792c.png">

**Comment by hstove** [comment]
Hey @timstackblock , interesting issue. I think in this case, given the error message you're seeing, you actually weren't IP blocked in Firefox. I'm not sure exactly how that could happen, if you were already IP limited. But, the "requires transit key" error is unrelated, and is closer to behavior that can happen when you're trying lots of authentications at once.
