### ISSUE TITLE
safari browser bug: Get your secret key pop up never goes away

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#613]
When running through the sign up flow after on a DESKTOP MAC in SAFARI. When I sign up I am not taken into the app, the "Get your secret key" pop up is displayed and I am back where I started.

Here is a video of the bug 
http://somup.com/cYQuI9lhVj

<img width="1087" alt="Screen Shot 2020-09-28 at 9 59 05 AM" src="https://user-images.githubusercontent.com/49165468/94442067-8210bf80-0171-11eb-97c1-9ae07dc8e10a.png">

**Comment by timstackblock** [comment]
This is still broken please see the video HERE http://somup.com/cY6iITlZwY

Safari Version 14.0 (14610.1.28.1.9)

**Comment by hstove** [comment]
Hey @timstackblock , can you try this again? Safari has some laggy message passing, which was causing a timeout to be called. I've increased the length of that timeout, and it seems to consistently work, now.

**Comment by timstackblock** [comment]
@hstove it's a tricky error to recreate. The bug is actually in the **sign-up flow**. 

The sign-in flow works once your cookied in. I just recreated the issue in the video pasted below. You will see the cookied in sign-in flow work. Then you will see the error upon initial sign up. Let me know if this is still unreproducible I will try to find another way to surface the issue.

This is a video of the issue:
http://somup.com/cY6rr6lLiE

**Comment by timstackblock** [comment]
My audio didn't record in the video for some reason let me know if you need me to make another.

**Comment by markmhendrickson** [comment]
@hstove should this be QA'ed before we close out?
