### ISSUE TITLE
[app] Provide configuration details to run the app locally and with mocknet

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#618]
Currently, the 

* `WalletSigner.getNetwork` is hardcoded.
* `getRPCClient` chooses between localhost and a hardcoded url based on location.origin

For app developers it is not possible to test their apps against a local mocknet.

The setup should be configurable and documented.

**Comment by friedger** [comment]
~~As a first step, I suggest to add a parameter localnode=1 to authOrigin when the local stacks node on port 3999 should be used.~~
The payload does contain a network specification, this should be used in the signing call.

**Comment by hstove** [comment]
I think it's more complicated then simply accepting the node value from `authOptions`. That options is really just to signal "testnet" vs "mainnet". What we need is a way for users to set their node value. And, you'll want to switch between different networks for local development.

I think we can figure out an easier solution for enabling developers, and we'll need something more robust for mainnet / end users.

**Comment by friedger** [comment]
@hstove Indeed, you are right. I have updated my comment. We could just use the network from the payload for now for developers. 

For mainnet, would the authenticator take the network from the payload or if there is a UI from the authenticator UI?

**Comment by friedger** [comment]
As a temporary workaround you can use the authenticator from `https://github.com/friedger/blockstack-app-1/tree/fix/network` 

In your app provide `authOrigin` as `localhost:8080` in your `AuthOptions`.

Launch the authenticator with `yarn dev` (you might need to edit package.json and remove the testapp if your app runs on port 3000)

**Comment by markmhendrickson** [comment]
@psq has also indicated a desire to see this addressed soon

**Comment by friedger** [comment]
I'll send a PR to update the relevant doc
