### ISSUE TITLE
Publish Connect under @stacks/connect

### ISSUE THREAD

**Issue by yknl** [leather-io/extension#624]
The Connect package should be published under @stacks/connect as discussed. References to Blockstack in code should be removed or replaced with Stacks.

**Comment by markmhendrickson** [comment]
@yknl is this still pending?

**Comment by yknl** [comment]
Looks like it's been published: https://www.npmjs.com/package/@stacks/connect cc @hstove

**Comment by hstove** [comment]
The PR is linked to this issue now. The package is technically published, but the PR is not merged to master. We'll merge it all on Monday along with the stencil stuff. All the dev work is done.

**Comment by markmhendrickson** [comment]
I see the linked PR is now merged. Can we close this issue out?
