### ISSUE TITLE
Fix authentication with extension in Chrome Incognito mode

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#625]
It appears that authentication is generally broken in Chrome Incognito mode:

<img width="891" alt="Screen Shot 2020-10-08 at 13 06 56" src="https://user-images.githubusercontent.com/28991/95450870-3d520900-0967-11eb-9519-8bb5c08c419e.png">

Notify the Pravica team once resolved.

**Comment by aulneau** [comment]
Extensions are generally disabled in incognito mode, right?

**Comment by markmhendrickson** [comment]
By default yea, but you can selectively turn them on for Incognito.
