### ISSUE TITLE
App authentication popup has a very verbose log message

### ISSUE THREAD

**Issue by sdsantos** [leather-io/extension#628]
This log message looks unecessary, and it's triggering every 250ms when the app is opened: https://github.com/blockstack/ux/blob/3c6688714b070a38c2eefe0d93a6218163917c53/packages/connect/src/popup.ts#L102

Can it be removed?

**Comment by markmhendrickson** [comment]
Yep, mind submitting a PR for this? That could expedite the release on our end :pray:
