### ISSUE TITLE
Currently in PROD I noticed the blockstack logo appearing twice in the safari connect sign in window

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#629]
noticed the blockstack logo appearing twice in the safari connect sign in window

<img width="1347" alt="Screen Shot 2020-10-15 at 9 38 13 AM" src="https://user-images.githubusercontent.com/49165468/96137130-48a6b680-0eca-11eb-904f-58c11d13bf1a.png">

**Comment by markmhendrickson** [comment]
I'm seeing this as well, notably in Safari but not Chrome

**Comment by markmhendrickson** [comment]
@timstackblock recently saw this in Chrome and Safari

**Comment by timstackblock** [comment]
This is happening in Chrome, Safari & FF now, when the user attempts to sign in using the latest build https://pr-637.testnet-demo.stacks.engineering/

FIREFOX

<img width="1433" alt="Screen Shot 2020-11-05 at 2 14 55 PM" src="https://user-images.githubusercontent.com/49165468/98286301-ca41af80-1f71-11eb-98a9-7260f8679094.png">

SAFARI
<img width="1395" alt="Screen Shot 2020-11-05 at 2 14 39 PM" src="https://user-images.githubusercontent.com/49165468/98286307-cc0b7300-1f71-11eb-988c-cacce44d251c.png">

CHROME
<img width="1425" alt="Screen Shot 2020-11-05 at 2 14 18 PM" src="https://user-images.githubusercontent.com/49165468/98286309-cca40980-1f71-11eb-802c-59dcd27a3f98.png">

**Comment by timstackblock** [comment]
Still broken

<img width="1436" alt="Screen Shot 2020-11-18 at 8 43 50 AM" src="https://user-images.githubusercontent.com/49165468/99538277-ba1ace80-297a-11eb-81ea-376486faa8be.png">

**Comment by markmhendrickson** [comment]
@timstackblock to retest with this PR's build
