### ISSUE TITLE
Improve connect header and navigation

### ISSUE THREAD

**Issue by whoabuddy** [leather-io/extension#632]
There are a couple snags I run into when navigating around Connect, and these observations come from using app.blockstack.org:

1. From the index, if I click Settings then it shows my usernames, but there is no option to go back. 
    - On that same page, hovering over a username looks like I can click it, but clicking a username does not appear to do anything. It would be great if this could expand to show additional info such as the full ID or similar.

1. After clicking View Secret Key from the settings page, it was not immediately clear that clicking Copy Secret Key would take me back to the settings page. It would be helpful to have a back button, or alternatively, a Settings link at the top-right to match the format of the Choose an account page.
    - This could be important especially if the user is on a public device and decides they do not want to copy the secret key for some reason.
    - Also, after clicking Copy Secret Key, I'm taken back to the settings page with no way back to the Choose an account page. 

One easy solution could be to keep the icon / app name at the top-left and link it to the [choose account](https://app.blockstack.org/index.html#/connect/choose-account) page, then use the top-right to change options based on context.

A quick mock-up is below, and this would avoid the need for a back button as well as make the top header for each page consistent.

![Screenshot from 2020-10-16 08-49-08](https://user-images.githubusercontent.com/9038904/96280656-1611c200-0f8d-11eb-9e1a-b215bdbfb05f.png)

![Screenshot from 2020-10-16 08-49-13](https://user-images.githubusercontent.com/9038904/96280666-19a54900-0f8d-11eb-9ddd-33d8c4856dc6.png)

**Comment by markmhendrickson** [comment]
cc @jasperjansz since he's currently working on designs that could impact this screen and incorporate the feedback here
