### ISSUE TITLE
Fix window titles during authentication

### ISSUE THREAD

**Issue by whoabuddy** [leather-io/extension#633]
The window titles do not seem to follow the context of the page content, and it does not always update, such that:

1. If I click Settings then use `Alt + Left Arrow` to go back a page, the title remains "Secret Key".
    - Also, is "Secret Key" the correct window title? Should it be "Settings" to match the link?
1. If I close the window with either the "Secret Key / Settings" or "View your Secret Key" page open, then the next time I open connect, that window title is restored over the top of the initial "Blockstack" title on the choose an account screen.
    - Refreshing the page fixes this and the title reverts to "Blockstack"

![Screenshot from 2020-10-16 09-01-22](https://user-images.githubusercontent.com/9038904/96281698-8b31c700-0f8e-11eb-9800-fc0eb12f4285.png)

**Comment by markmhendrickson** [comment]
Is this still relevant given the switch to extension-only?

**Comment by whoabuddy** [comment]
Nope, I think we can close this one out!
