### ISSUE TITLE
Add bigger warning around saving secret key

### ISSUE THREAD

**Issue by whoabuddy** [leather-io/extension#634]
Given the importance of a secret key for the user's identity, the user's data, and their overall experience of using Stacks applications, I think there should be more emphasis on the importance of saving the secret key.

Currently, there is some text that alludes once lost it cannot be recovered, but I think this should be highlighted more, example below:

![Screenshot from 2020-10-16 09-09-34](https://user-images.githubusercontent.com/9038904/96282523-b668e600-0f8f-11eb-8b36-542ee4c19f21.png)

It could be accompanied by a :warning: or :information_source: icon.

**Comment by markmhendrickson** [comment]
cc @jasperjansz since he's currently working on designs that could impact this screen and incorporate the feedback here
