### ISSUE TITLE
Connect: References

### ISSUE THREAD

**Issue by agraebe** [leather-io/extension#638]
I'm not sure if this already exists, but I'd love to include references for connect inside our documentation. I was struggling to figure out what methods & properties to use when I extended the todo app. With Connect being more important for developers (due to tx signing), we should make some references available

**Comment by agraebe** [comment]
This came up in the past:
- https://github.com/blockstack/docs/issues/563
- https://github.com/blockstack/docs/issues/611

**Comment by markmhendrickson** [comment]
I agree with the sentiment, although should we track this work in the docs repo?

**Comment by agraebe** [comment]
I think if it's in a different repo, this will likely be skipped during prioritization for upcoming sprints. I also believe this could entail change in the project itself- to generate the references

**Comment by markmhendrickson** [comment]
As pointed out by @friedger, this is related to https://github.com/blockstack/docs/issues/732

**Comment by agraebe** [comment]
I'd not make #732 a blocker for this. some references are better than none. a first iteration - even if manual and not according to later design decisions - would be great

**Comment by markmhendrickson** [comment]
I'm closing this out in favor of https://github.com/blockstack/docs/issues/926.
