### ISSUE TITLE
Connect: String types for function arguments

### ISSUE THREAD

**Issue by agraebe** [leather-io/extension#639]
I noticed that the [new Clarity value types](https://docs.blockstack.org/references/language-clarity) are missing in the connect library:

```js
export enum ContractCallArgumentType {
  BUFFER = 'buffer',
  UINT = 'uint',
  INT = 'int',
  PRINCIPAL = 'principal',
  BOOL = 'bool',
}
```

This update would require updating the [signing transactions tutorial](https://docs.blockstack.org/smart-contracts/signing-transactions#passing-clarity-types-with-function-arguments) as well.

**Comment by friedger** [comment]
Contract calls to functions with a string argument in Sandbox do silently fail.

**Comment by markmhendrickson** [comment]
Is this still relevant? Please re-open if so.
