### ISSUE TITLE
Fix authentication to Testnet Demo with extension

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#642]
Currently a new tab gets triggered to a 404 page:

![Kapture 2020-10-21 at 13 46 54](https://user-images.githubusercontent.com/28991/96715473-ebb47000-13a3-11eb-9c34-a0e0f84d6249.gif)

**Comment by agnelvishal** [comment]
In Brave Browser, with Blockstack extension available in Chrome store , after I sign in, a new tab doesn't open for me like @markmhx mentioned. Instead it shows 'setting up'' for infinite time as how below.
![Screenshot from 2020-10-29 19-23-05](https://user-images.githubusercontent.com/10105332/97582835-383f2180-1a1c-11eb-87c2-50775089335d.png)


In Firefox Browser, I get no response when signing in. I get Browser console error 'No Auth request found as shown below
![Screenshot from 2020-10-29 19-35-05](https://user-images.githubusercontent.com/10105332/97584516-20689d00-1a1e-11eb-90ec-eb9706fa49ac.png)
'

**Comment by agnelvishal** [comment]
I tried with blockstack extension compiled from source and I was able to login after several retries.

**Comment by timstackblock** [comment]
@markmhx This is broken in both Firefox and Chrome 

In Chrome you can see it bringing up the extension pop up with the error message BLOCKED

Video of the bug http://somup.com/cYXQ2QIu1j

<img width="1162" alt="Screen Shot 2020-11-09 at 9 06 10 AM" src="https://user-images.githubusercontent.com/49165468/98551512-60741f00-226b-11eb-894f-fe149f2245ad.png">


<img width="1391" alt="Screen Shot 2020-11-09 at 9 18 34 AM" src="https://user-images.githubusercontent.com/49165468/98552571-9d8ce100-226c-11eb-9dea-2a63cd919a30.png">



I am having trouble getting in with the FF browser still popping a new tab for every sign in attempt for me.

FIREFOX

<img width="1314" alt="Screen Shot 2020-11-09 at 9 30 22 AM" src="https://user-images.githubusercontent.com/49165468/98554065-4b4cbf80-226e-11eb-8cc7-6d8a510eadce.png">

<img width="640" alt="Screen Shot 2020-11-09 at 9 34 22 AM" src="https://user-images.githubusercontent.com/49165468/98554495-c910cb00-226e-11eb-9aea-8b0a801a895a.png">

**Comment by hstove** [comment]
Thanks - making this and #602 high priority

**Comment by hstove** [comment]
It appears that login is working (at least I couldn't replicate across any browser), but the fix for TX signing is in #674

**Comment by timstackblock** [comment]
Fixed please view the video http://somup.com/cYXXDnIyBu
