### ISSUE TITLE
Automatically deploy Testnet Demo contracts upon network reset

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#643]
@yknl has suggested we could possibly extend the "status app" deployment system for redeploying the two contracts needed by the Testnet Demo instead of having to manually deploy them each time, which we haven't been doing consistently.

**Comment by agnelvishal** [comment]
Yeah. The contract https://testnet-explorer.blockstack.org/txid/STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6.status does not exist which is used in "status app"

**Comment by markmhendrickson** [comment]
I was able to redeploy the counter contract manually but hit an error with the status one for some reason.

I’m getting a `TypeError: Cannot read property 'functions' of null` when trying to load the deployed contract at https://stacks-node-api.blockstack.org/extended/v1/debug/broadcast/contract-call/STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6.status

cc @hstove @zone117x

**Comment by zone117x** [comment]
@markmhx what are you trying to use the `v1/debug` endpoints for? Those are primarily for internal testing and haven't been needed or used for a while. The explorer's sandbox is better for that. 

Use this path to lookup a contract directly with the API:
https://stacks-node-api.blockstack.org/extended/v1/contract/STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6.status

If you pull up the contract's transaction, you'll notice it was aborted:
 https://stacks-node-api.blockstack.org/extended/v1/tx/0xed35f2cc03c24ab0036ba8a533f9b970fb4afe6fc9c4c26ed4e4e8a72730c278

**Comment by markmhendrickson** [comment]
I'm using them per the "Deploying UX Demo Contracts" Paper document's instructions on how to re-deploy manually the contracts used by the Testnet Demo app each time testnet resets.

Is there an updated `broadcast` endpoint as well available?

**Comment by markmhendrickson** [comment]
I'm de-prioritizing this issue off the backlog board now that we're sending external users to the Explorer Sandbox and reserving the Testnet Demo app for internal purposes.
