### ISSUE TITLE
[app] Can't make a transfer without fees - Overwrite coreApiUrl

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#645]
Currently, the authenticator uses the default coreApiUrl of blockstack.js (`testnet-master.blockstack.org:20443`). For the authenticator, this results in failed cors calls

![Screenshot from 2020-10-22 23-14-36](https://user-images.githubusercontent.com/1449049/96930677-61abfa80-14bc-11eb-9fbf-801c1f414782.png)

The authenticator (or event blockstack.js) should use stacks-node-api.blockstack.org as a reasonable default.

**Comment by markmhendrickson** [comment]
I'm a bit confused by the screenshot here, suggesting that it's trying to connect to stacks-node-api.blockstack.org in the UI error on the left but testnet-master.blockstack.org:20443 in the console error on the right?
