### ISSUE TITLE
[app] Contract calls use default coreApiUrl to get source code

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#646]
I try to use a local authenticator without running a local stack-api-node (due to https://github.com/blockstack/stacks-blockchain-api/issues/301)

However, contract call fail because the authenticator tries to look up the source using the `client = getRPCClient` ignoring my network settings. This results in a call to `localhost:3999` because the app url contains `localhost` (see `getRPCClient` implementation). This call fails obviously.

**Comment by markmhendrickson** [comment]
Is this something you could help fix by submitting a PR?

**Comment by friedger** [comment]
I suggest to add a network parameter to `getRPCClient` and to not have a local variable. The method returns the cached client if the network is the same. If not a new instance is created and cached.

In the future, this cached client can also be changed by an UI dropdown for network selection.

**Comment by friedger** [comment]
Probably better than caching would be to add the network in the constructor
