### ISSUE TITLE
Connect: network configuration to support StacksMocknet

### ISSUE THREAD

**Issue by agraebe** [leather-io/extension#648]
With the recent `@stacks/network` version, a `StacksMocknet` property will be provided. The last [network support PR](https://github.com/blockstack/ux/pull/621/) doesn't include that yet:

```js
import {
  StacksMainnet,
  StacksTestnet,
} from '@blockstack/stacks-transactions';
```

cc @friedger

**Comment by psq** [comment]
This is a good idea.  This should not preclude letting the client apps setting the URLs to use for each of these networks.

**Comment by friedger** [comment]
If I understand the code correctly, it does not matter. A provided network will always be respected whether it is mainnet, testnet or mocknet. The code in the mentioned PR is misleading.

**Comment by agraebe** [comment]
Ah, I saw [this section](https://github.com/blockstack/ux/pull/621/files#diff-0574de57ec8894da857fb31a970c0aa706472142dd6f3191dd7e200becb085b4R105) and thought it was an update to connect. I think you're right @friedger, I'm closing this
