### ISSUE TITLE
Extension no longer listed in Firefox Add-Ons or Chrome Store

### ISSUE THREAD

**Issue by agnelvishal** [leather-io/extension#652]
Firefox extension does not exist in https://addons.mozilla.org/en-US/firefox/addon/blockstack or any other place.
![Screenshot from 2020-10-29 19-39-59](https://user-images.githubusercontent.com/10105332/97584942-966d0400-1a1e-11eb-8e62-b5ee231c9333.png)

**Comment by markmhendrickson** [comment]
@hstove is this something we can fix ASAP?

**Comment by markmhendrickson** [comment]
It also appears missing from the Chrome store: https://chrome.google.com/webstore/search/blockstack?hl=en


<img width="1138" alt="Screen Shot 2020-11-02 at 14 00 27" src="https://user-images.githubusercontent.com/28991/97870892-eb0cc980-1d13-11eb-873e-ccdd1e68ed0f.png">

**Comment by markmhendrickson** [comment]
The extension back up on the Chrome Store though pending re-submission to Firefox since the reviewers there want a docker file for building from source, which is getting prepared with https://github.com/blockstack/ux/pull/677.

**Comment by markmhendrickson** [comment]
Mozilla has confirmed that it's begun review and is currently looking to run docker for the extension. @hstove is in contact with them via email.

**Comment by timstackblock** [comment]
There is a UNOFFICIAL version in the firefox store are you aware of this, @markmhx 

<img width="1429" alt="Screen Shot 2020-11-18 at 8 43 34 AM" src="https://user-images.githubusercontent.com/49165468/99538154-8c358a00-297a-11eb-8358-1ea284cc74e5.png">


In the CHROME store 

<img width="1412" alt="Screen Shot 2020-11-18 at 8 42 45 AM" src="https://user-images.githubusercontent.com/49165468/99537780-17fae680-297a-11eb-8780-e0920dde74c9.png">

Not in the FF store 

<img width="1439" alt="Screen Shot 2020-11-18 at 8 44 12 AM" src="https://user-images.githubusercontent.com/49165468/99538015-601a0900-297a-11eb-9bf1-d8c94d8e57c8.png">

**Comment by markmhendrickson** [comment]
I'm closing this in favor of the following milestone, which involves re-releasing the extension to both Chrome and Firefox stores: https://github.com/blockstack/stacks-wallet-web/milestone/39
