### ISSUE TITLE
[connect] change finished callback name

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#654]
- `ContractDeployOptions`
- `ContractCallOptions`
- `STXTransferOptions`

all accept `finished` as a callback where they should take `onFinish` to be in line with `showConnect`

Also, `STXTransferOptions` -> `StxTransferOptions`

**Comment by markmhendrickson** [comment]
@aulneau I may recommend opening a PR with this change if it's quick enough so it doesn't get lost in the icebox.
