### ISSUE TITLE
Ensure extension installs permanently for Firefox

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#656]
[The extension install instructions](https://www.blockstack.org/install) indicate that the user should use the "Load Temporary Add-on…" option in Firefox to install the extension from source. However, this appears to result in the extension getting removed automatically upon reload of Firefox each time.

![Kapture 2020-11-02 at 14 44 23](https://user-images.githubusercontent.com/28991/97874850-e814d780-1d19-11eb-92ec-5c07572c29a1.gif)

If I alternatively try to use the "Install Add-on from file" option, it doesn't recognize any of the files for selection:

![Kapture 2020-11-02 at 14 46 36](https://user-images.githubusercontent.com/28991/97875105-37f39e80-1d1a-11eb-9cb7-347b168595e6.gif)

If I try to zip the "dist" folder and upload, it says it's corrupt:

<img width="411" alt="Screen Shot 2020-11-02 at 14 46 21" src="https://user-images.githubusercontent.com/28991/97875152-4641ba80-1d1a-11eb-8db2-00df30f8632c.png">

Furthermore, before restarting Firefox, Blockstack apps don't appear to detect the extension during authentication anyway. I'm still getting redirected to the hosted version where I'm prompted to "Get the Firefox extension":

![Kapture 2020-11-02 at 14 41 00](https://user-images.githubusercontent.com/28991/97874559-73da3400-1d19-11eb-928d-252ff7dd60e2.gif)

**Comment by markmhendrickson** [comment]
@timstackblock can you confirm the same behavior on your end here?

**Comment by timstackblock** [comment]
@markmhx Is this with the latest refactored extension version that is in test or the prod extension version?

**Comment by markmhendrickson** [comment]
Prod extension version

**Comment by timstackblock** [comment]
Yup that one is broken your videos are exactly what I was seeing. It should be fixed in the executable on @hstove latest PR, not sure if its merged into master yet.

**Comment by markmhendrickson** [comment]
I'm getting the following `Can't resolve '@stacks/connect-ui'` error when I try to run `yarn prod:ext` per the instructions with the latest code merged into master.

@timstackblock mind seeing if you can recreate from source?

```
$ yarn prod:ext
yarn run v1.22.4
$ cross-env NODE_ENV=production EXT_ENV=prod webpack -p --config webpack-ext.config.js
Starting type checking service...
clean-webpack-plugin: pausing due to webpack errors
Hash: c58187562689fea124cc
Version: webpack 4.43.0
Time: 3033ms
Built at: 11/04/2020 2:56:24 PM
 4 assets
Entrypoint background = background.js
Entrypoint inpage = inpage.js
Entrypoint message-bus = message-bus.js
Entrypoint index = index.js
[072K] ./src/common/dev/store.ts 53 bytes {1} [built]
[2YZa] ./src/index.tsx 885 bytes {1} [built]
[7ets] ./src/extension/inpage.ts 3.47 KiB {3} [built]
[9KIl] ./src/store/onboarding/types.ts 1.83 KiB {1} {2} [built]
[BhN1] ./src/store/index.ts 1.02 KiB {1} {2} [built]
[IPBg] ./src/extension/content-scripts/message-bus.ts 858 bytes {0} [built]
[Kack] ./src/store/transforms.ts 2.33 KiB {1} {2} [built]
[QKQq] ./src/common/hooks/use-message-pong.ts 905 bytes {1} [built]
[Vn5Y] ./src/store/onboarding/reducer.ts 2.65 KiB {1} {2} [built]
[cZO5] ../connect/src/index.ts 127 bytes [built]
[iCcP] ./src/store/ext-store.ts 2.3 KiB {1} {2} [built]
[kiQV] ./package.json 4.79 KiB {1} [built]
[nUtP] ./src/extension/background.ts 554 bytes {2} [built]
[t06s] ./src/common/utils.ts 5.43 KiB {0} {1} [built]
[tWL+] ./src/common/track.ts 6.64 KiB {1} [built]
    + 947 hidden modules

ERROR in ../connect/src/ui.ts
Module not found: Error: Can't resolve '@stacks/connect-ui' in '/private/var/www/ux/packages/connect/src'
 @ ../connect/src/ui.ts 8:0-58 10:2-22
 @ ../connect/src/index.ts
 @ ./src/common/utils.ts
 @ ./src/extension/content-scripts/message-bus.ts
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [Z3W6] /private/var/www/ux/node_modules/html-webpack-plugin/lib/loader.js!./public/html/index.html 521 bytes {0} [built]
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by timstackblock** [comment]
@markmhx when did stacks.js get merged into the connect master branch without passing through QA stacks.js was only tested on the devX side in the TODOs app and the CLI this was never tested with connect or the authenticator for any build that came through the UX team. I am pretty sure thats why we have errors on that branch.

**Comment by timstackblock** [comment]
Looks like https://github.com/blockstack/ux/issues/624 was merged on Monday, I definitely didn't QA this on Monday before the merge, I can take a look now.

**Comment by markmhendrickson** [comment]
@hstove to provide latest command guidance

**Comment by hstove** [comment]
You need to run `yarn lerna run build --scope @stacks/connect-ui`

**Comment by markmhendrickson** [comment]
@hstove the above command doesn't appear to generate a `dist` directory for me

**Comment by markmhendrickson** [comment]
I was able to install from source for Firefox and authenticate successfully with the modified instructions provided by @hstove above:

```
git clone https://github.com/blockstack/ux && cd ux
yarn
cd packages/app 
yarn lerna run build --scope @stacks/connect-ui
yarn lerna run prod:ext
```

![image](https://user-images.githubusercontent.com/28991/99961499-d9589800-2d8e-11eb-8350-458046b9e29a.png)

However, I still can't use the "Install Add-on from file" option to install the extension permanently (it shows the same "appears to be corrupt error if I zip the `dir` directory as before). And it keeps going away upon browser restart if I use "Load Temporary Add-on…".

@hstove ideas on how to install the extension permanently from source for Firefox here?

**Comment by markmhendrickson** [comment]
I tried [the above instructions](https://github.com/blockstack/ux/issues/656#issuecomment-732130164) for building the extension on a new device but ran into a lerna error when running inside `packages/app`:

```
yarn lerna run build --scope @stacks/connect-ui
yarn run v1.3.2
(node:13747) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error Command "lerna" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

@hstove any ideas?

**Comment by markmhendrickson** [comment]
`yarn` was getting called in the wrong directory. I've submitted a fix to the instructions here: https://github.com/blockstack/ux/pull/700

**Comment by hstove** [comment]
Hey - did some looking into this. In order to permanently install an extension in Firefox, the extension has to be signed. Fortunately, this is not too tricky - Mozilla provides a nice CLI. #703 added a new Github Action that creates this signed extension (called an `.xpi` file). So, you can go to a PR (try #703), click the link to "view latest builds" in the PR description, and then download the artifact from there.

This is actually the first step towards self-hosting - as that `.xpi` is what we'd distribute. But for now, this is better for beta testing.

**Comment by markmhendrickson** [comment]
Sounds great. Does this change require any updates to the build and install instructions re: https://github.com/blockstack/ux/pull/700?
