### ISSUE TITLE
Integrate new authentication flows from apps without browser extension support

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#672]
If loading intro modal from app with user agent that doesn't support extension (e.g. mobile, desktop Safari):

- User sees intro modal with subtitle "Connect gives you control over your digital assets and data in apps like [APP NAME]." and “Connect to [APP NAME]” button without icon ([see design]
    - If user selects button and has no Connect session, user taken to the hosted authenticator where they see the "Connect is installed" screen but with "Connect to [APP NAME]" for header instead ([see design](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=323%3A17197))
      - If user chooses "I'm new to Connect":
          - Secret Key is generated during animation sequence (**needs design**) then stored in local storage
          - Users sees the "Your Secret Key" modal ([see design](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=323%3A18966))
          -  Upon selection of "I've saved it", user sees the "Set a password" modal ([see design](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=323%3A19011))
          - Upon password submission, if app had passed “publish_data” scope, user is presented with username setting screen [(see design)](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=377%3A12064)
              - Upon submission, user is taken back to the app
          - Otherwise, user is taken back to the app
      - If user chooses "Continue with Secret Key":
          - User sees “Continue with Secret Key” screen ([see design](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=323%3A18033))
          - Upon submission, user is presented with password setting screen ([see design](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=323%3A18046))
          - Upon submission, user sees account selection screen ([see design](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=357%3A1333))
          - Upon account selection or username creation,
              - If user has already authenticated one or more other apps with the same account, user is presented with selection confirmation screen (**needs design**)
              - If app had passed “publish_data” scope and user hadn’t previously set a username for selected address / account, user is presented with username screen ([see design](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=377%3A12064))
                  - Upon submission, user is taken back to the app
              - Otherwise, user is taken directly back to the app
  - If user selects button and has Connect session, user is taken to hosted authenticator and shown "Enter password" screen ([see design](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=377%3A9535))
    - Upon submission, user is shown "Choose an account" modal ([see design](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=357%3A1333))
    - Upon account selection or username creation,
      - If user has already authenticated one or more other apps with the same account, user is presented with selection confirmation screen (**needs design**)
      - If app had passed “publish_data” scope and user hadn’t previously set a username for selected address / account, user is presented with username screen ([see design](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=377%3A12064))
         - Upon submission, user is taken back to the app
       - Otherwise, user is taken directly back to the app
  - If user selects "How Connect works", they are taken to https://www.blockstack.org/questions/how-does-connect-work

**Comment by markmhx** [comment]
I'm closing this since we've provisionally decided to drop support for the hosted authenticator.

**Comment by markmhendrickson** [comment]
@jasperjansz I've updated the spec with the hosted authenticator. It'd be good to get your review of the flows and Figma links where mockups aren't yet fully available.
