### ISSUE TITLE
Readme links result in 404

### ISSUE THREAD

**Issue by whoabuddy** [leather-io/extension#679]
While looking over the ux repo I noticed two links that don't work in the readme:

- `@stacks/ui`: Blockstack's internal design system and React component library
(full URL: https://github.com/blockstack/ux/blob/master/packages/ui)
- `ui-docs`: A documentation site for `@blockstack/ui`.
(full URL: https://github.com/blockstack/ux/blob/master/packages/ui-docs)

I think the issue is related to #592 (thanks @agraebe for that link) - but I wasn't sure if these links just need to be removed or replaced with a new destination.

The old [blockstack/ui](https://github.com/blockstack/ui) repo references the same broken link as the first one for the "new location" as well.

*Edit: those relative links did funny things in the issue, so removed them*

**Comment by aulneau** [comment]
This is no longer relevant to this repo as those projects are now in their own repo. Closing :)
