### ISSUE TITLE
Missing defineCustomElements

### ISSUE THREAD

**Issue by njordhov** [leather-io/extension#685]
With @stacks/connect:4.2.2 calling `showConnect` results in a _TypeError: connectUi.defineCustomElements is not a function._

Although `defineCustomElements` is [imported by Connect](https://github.com/blockstack/ux/blob/128ffa28d47468e001c137d5f1e18bc1458fe5f2/packages/connect/src/ui.ts#L2) it doesn't seem to be exported by connect-ui:

https://github.com/blockstack/ux/blob/128ffa28d47468e001c137d5f1e18bc1458fe5f2/packages/connect-ui/src/index.ts#L1

Possibly related: https://github.com/blockstack/ux/pull/582#issuecomment-688027120

**Comment by markmhendrickson** [comment]
@hstove @yknl thoughts here?

**Comment by njordhov** [comment]
Still happening for ClarityTools with @stacks/connect:4.3.0, @stacks/connect-ui:2.17.0 and @stacks/transactions:1.0.0-beta.13

**Comment by markmhendrickson** [comment]
I'm personally finding that `showBlockstackConnect` works for me instead of `showConnect` with `@stacks/auth": "^1.0.0-beta.13"`.

**Comment by njordhov** [comment]
@markmhx `@stacks/auth` re-exports all exports from `@stacks/connect` where `showBlockstackConnect` is just an alias for `showConnect`, so it is surprising if you get a different outcome using `showBlockstackConnect` :

https://github.com/blockstack/ux/blob/585a731847dd505cc0c1508ad78f2c50f06d8ff2/packages/connect/src/ui.ts#L46

**Comment by njordhov** [comment]
**Calling `showConnect` works as expected after monkeypatching** `defineCustomElements` in @stacks/connect-ui by setting it to the same from the generated `@stacks/connect-ui/dist/custom-elements`.

This suggest that the fix is changing the source path of the [import](https://github.com/blockstack/ux/blob/128ffa28d47468e001c137d5f1e18bc1458fe5f2/packages/connect/src/ui.ts#L2) to something like:
```
import { defineCustomElements } from 'connect-ui/dist/custom-elements';
```

**Comment by markmhendrickson** [comment]
I'm finding that `showConnect` works in this implementation:

```
import { AppConfig, UserSession, showConnect } from '@stacks/auth';

const appConfig = new AppConfig(['store_write', 'publish_data']);

export const userSession = new UserSession({ appConfig });
export const storage = new Storage({ userSession });

export function authenticate() {
  showConnect({
    appDetails: {
      name: 'Todos',
      icon: window.location.origin + '/logo.svg',
    },
    redirectTo: '/',
    finished: () => {
      window.location.reload();
    },
    userSession: userSession,
  });
}
```

[View source](https://github.com/blockstack/todos/blob/d088ce866a9002114528e11a263dca9d8427123b/src/stacks.js)

**Comment by njordhov** [comment]
> I'm finding that showConnect works in this implementation

I also have `showConnect` working for an app using another build environment. Surprisingly, given the missing import. 

But it doesn't work when building with _Google Closure_, with `showConnect` failing due to a missing `connectUi.defineCustomElements` - just as expected from it not being imported. The conundrum is that `defineCustomElements` is imported by https://github.com/blockstack/ux/blob/128ffa28d47468e001c137d5f1e18bc1458fe5f2/packages/connect/src/ui.ts#L2 without being exported by 
https://github.com/blockstack/ux/blob/128ffa28d47468e001c137d5f1e18bc1458fe5f2/packages/connect-ui/src/index.ts#L1

**Comment by markmhendrickson** [comment]
Hmm I'm not sure. @hstove or @yknl may have ideas about that behavior you're seeing.

**Comment by markmhendrickson** [comment]
@njordhov is this still an issue for you? If so, please re-open.
