### ISSUE TITLE
Add username validation

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#70]
Scope out all the behaviors and edge cases for validation

**Comment by hstove** [comment]
- Length and characters in username (instant)
- Username taken (relatively fast, has some loading time)
- Some error happens during generation of the wallet

**Comment by jasperjansz** [comment]
Here are the username error states: https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=6621%3A797

We can show a little help text on focus of the field for the allowed characters. This uses the "Field with help text" component (https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/Design-System?node-id=189%3A52). For errors, we use the Error component: https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/Design-System?node-id=520%3A0.

Instant validation:
- Invalid characters. The error message shows examples of what is allowed and what is not.

After submit:
- Username unavailable
- Too short or too long

**Comment by markmhendrickson** [comment]
@hstove to add test and assign to @timstackblock for QA today

**Comment by hstove** [comment]
@timstackblock for QA:

- must be at least 8 characters, and no more than 37
- must only contain `_`, letters (lower-case only), and numbers
- cannot register a subdomain that is already taken

**Comment by kyranjamie** [comment]
I was very much under the impression it's lowercase only. It has been built to reject uppercase letters.

**Comment by markmhendrickson** [comment]
I'm seeing validation on Banter now. @timstackblock can you test the edge cases?

![Screen Shot 2020-02-14 at 12.23.44.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/1032e41d-8ef7-4def-9227-020294df7d61)

![Screen Shot 2020-02-14 at 12.22.31.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/4ae1bdc9-0f31-469f-95bc-5c6e9c012920)

**Comment by markmhendrickson** [comment]
Let's modify "you can only use letters" to "you can only use lowercase letters"

**Comment by markmhendrickson** [comment]
@timstackblock I see the two related PRs are now merged (https://github.com/blockstack/keychain/pull/20 and https://github.com/blockstack/app/pull/113). Should we close this issue?

**Comment by timstackblock** [comment]
Should the error message say 37 characters instead of 38 since it does not except 38 characters

> Must be at least 8 characters, and no more than 37


![Screen Shot 2020-02-17 at 9.11.42 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/58ffdff6-8cd6-47e6-a29c-2700f4988e9f)

**Comment by markmhendrickson** [comment]
That character length change is now tracked here: https://github.com/blockstack/app/issues/169

@timstackblock want to close out this issue if there aren't any other username validation issues to report?

**Comment by timstackblock** [comment]
The remaining issues will be tracked in the open bugs
