### ISSUE TITLE
Fix Banter deployment

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#711]
😢 

![image](https://user-images.githubusercontent.com/28991/102679076-0c832100-41ad-11eb-8fe0-c121f19067cd.png)

It's worth fixing since we reference it from our documentation.

**Comment by markmhendrickson** [comment]
@CharlieC3 @wileyj is this something you could help us get back up and running? We'll need it soon for https://github.com/blockstack/ux/issues/737 in particular.

**Comment by wileyj** [comment]
who owns banter.pub? if they can transfer the domain to us - possibly.

**Comment by markmhendrickson** [comment]
@hstove @aulneau is either of you the owner of banter.pub?

**Comment by markmhendrickson** [comment]
I spoke with the team and we won't actually need this for #737 after all, though it'd be good to get Banter up regardless since it's referenced by documentation.

**Comment by markmhendrickson** [comment]
I'm closing this particular issue since it's tracked with devops here: https://github.com/blockstackpbc/devops/issues/547
