### ISSUE TITLE
Display recommendation if user authenticates with large amounts of STX

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#713]
Recommendation would be displayed upon entry of Secret Key and detection of STX holdings over N threshold, advising that the user consider the desktop Stacks Wallet with a hardware device for increased security.

This might help educate users as to the best practice of using separate Secret Keys across separate wallet types.

cc @MarvinJanssen

**Comment by MarvinJanssen** [comment]
Trezor does this when sending a large amount.
