### ISSUE TITLE
Connect 2 cannot add username 504 error

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#716]
Connect 2 I cannot add a username I get a 504 error in the console

Screen shot of issue

<img width="1073" alt="Screen Shot 2020-12-23 at 9 12 57 AM" src="https://user-images.githubusercontent.com/49165468/103003642-200cef80-44ff-11eb-9904-9d868ba8c9b8.png">

**Comment by hstove** [comment]
There appears to be an issue with the registrar - hence the 504 error.

**Comment by markmhendrickson** [comment]
We should show a more accurate and generic error for 504s, yea? E.g. "Error connecting to the network. Please try again later."

This one misleads the user into thinking they should keep trying other strings until one is available.
