### ISSUE TITLE
Entering the same 12 word seed phrase in connect 2 and into V2 wallet bring back different address

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#717]
Is this because connect 2 is currently using the main-net derivation path and the stacks wallet V2 is using test-net? I was under the impression they would both be using the testnet?

Video of issue: http://somup.com/cYl0202doT in the video I will use seed phrase van praise reform tiger open rhythm buyer dizzy royal curve setup voice

<img width="432" alt="Screen Shot 2020-12-23 at 9 26 08 AM" src="https://user-images.githubusercontent.com/49165468/103007191-fa80e580-4500-11eb-8bab-4b651247e4b8.png">

<img width="1009" alt="Screen Shot 2020-12-23 at 9 25 15 AM" src="https://user-images.githubusercontent.com/49165468/103007151-e76e1580-4500-11eb-9871-ad8efc4368dc.png">

**Comment by markmhendrickson** [comment]
@hstove @kyranjamie thoughts here?

**Comment by timstackblock** [comment]
wallet balance is also different

**Comment by kyranjamie** [comment]
This is because the wallet is using the derivation for identities, right?

**Comment by markmhendrickson** [comment]
This appears to be dependent on the derivation path updates that @hstove is making.
