### ISSUE TITLE
When a user logs out the plugin popup reshapes to a slim rectangle and remains that way after user logs back in

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#718]
When a user logs out the plugin popup reshapes to a slim rectangle and remains that way after user logs back in

Chrome extension

Video of issue http://somup.com/cYl02y2doW

<img width="364" alt="Screen Shot 2020-12-23 at 9 21 15 AM" src="https://user-images.githubusercontent.com/49165468/103007717-e5588680-4501-11eb-98f1-9130a3e54b81.png">

**Comment by markmhendrickson** [comment]
@hstove is this ready for re-QA?

**Comment by hstove** [comment]
@timstackblock use #731 for QA

**Comment by timstackblock** [comment]
fixed
