### ISSUE TITLE
Login flow for an existing user repeats signup flow steps

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#721]
Video of issue: http://somup.com/cYl02N2dbF

The screen shots below are the steps the user goes through when they **sign into** connect. They are asked to set a password and copy and paste the seed phrase that they entered in like they are signing up. I think there are several flow issues here that need resolving.

<img width="186" alt="Screen Shot 2020-12-23 at 9 54 31 AM" src="https://user-images.githubusercontent.com/49165468/103009628-0e2e4b00-4505-11eb-9278-550a58ad8a28.png">
<img width="447" alt="Screen Shot 2020-12-23 at 9 54 38 AM" src="https://user-images.githubusercontent.com/49165468/103009630-0e2e4b00-4505-11eb-9568-9696bc913eef.png">
<img width="450" alt="Screen Shot 2020-12-23 at 9 54 44 AM" src="https://user-images.githubusercontent.com/49165468/103009631-0ec6e180-4505-11eb-8c0b-abf0ba5979b4.png">
<img width="443" alt="Screen Shot 2020-12-23 at 9 54 52 AM" src="https://user-images.githubusercontent.com/49165468/103009632-0f5f7800-4505-11eb-8754-813fc2a5d3c5.png">
<img width="445" alt="Screen Shot 2020-12-23 at 9 55 28 AM" src="https://user-images.githubusercontent.com/49165468/103009634-0f5f7800-4505-11eb-92db-839329795e6f.png">

**Comment by markmhendrickson** [comment]
@hstove is this ready for retesting?

**Comment by timstackblock** [comment]
This works but the user gets this screen after logging in and has to click the blockstack icon to actually get into the wallet. I think they should just be take into the wallet what do you think @markmhx Mark? 

Video of issue
http://somup.com/crVf2r299w

**Comment by markmhendrickson** [comment]
Ah that's true. If the user is setting up within the context of the extension modal, they should arrive directly at the home screen when done instead of seeing the "You're all set!" screen. 

@hstove @jasperjansz it may be worth discussing this flow a bit more.

**Comment by hstove** [comment]
@timstackblock can you indicate what branch/commit you're using?

**Comment by timstackblock** [comment]
PR 731 then click download latest release
