### ISSUE TITLE
Hint for secret key says 12 words instead of 12 or 24 words

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#726]
Hint for secret key says 12 words instead of 12 or 24 words

![Screenshot from 2020-12-29 18-12-56](https://user-images.githubusercontent.com/1449049/103301352-83b48280-4a01-11eb-9172-223e845c7ace.png)

**Comment by markmhendrickson** [comment]
Suggestion: "Enter your 12 or 24-word Secret Key"

**Comment by markmhendrickson** [comment]
LGTM

![image](https://user-images.githubusercontent.com/28991/104310089-6dafc300-54d3-11eb-813e-293df3aa7bc7.png)
