### ISSUE TITLE
I cannot send micro stacks with connect 2 the count goes to -1 

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#729]
I cannot enter .001 into the amount field and the down arrow goes to -1 

<img width="442" alt="Screen Shot 2020-12-29 at 3 46 26 PM" src="https://user-images.githubusercontent.com/49165468/103314028-cc634000-49ef-11eb-871c-9be3922165f0.png">

**Comment by kyranjamie** [comment]
https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

**Comment by timstackblock** [comment]
This works in chrome and only seems like an issue in FF please see the video below. I tried this is both chrome and FF.

VIDEO OF ISSUE: http://somup.com/crVYYNouI3

**Comment by timstackblock** [comment]
Resolved
