### ISSUE TITLE
[Intro modal] Vertical rhythm

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#73]
We're not using spacing (see Waffle) correctly. Sticking to multiples of 4 will allow us to create a sense of vertical rhythm that is currently missing, see design:

![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/a05fb0c2-bfe3-4a3b-8374-6da0d31415f8)

16, 28, 16, 16, 8, 20, 24.

In the implementation, I'm seeing 17.5, 70, 10.5, etc. Not only are these far off, they also don't follow our rule of multiples of 4.

![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/63e11207-aacb-4c96-9a09-95f81fbf01d3)

**Comment by aulneau** [comment]
> In the implementation, I'm seeing 17.5, 70, 10.5, etc. Not only are these far off, they also don't follow our rule of multiples of 4.

This is not accurate. We are using multiples of four, how did you get these numbers?

**Comment by jasperjansz** [comment]
@aulneau it is accurate. I think it's because 1rem is 14px instead of 16px.

**Comment by kyranjamie** [comment]
This relates to REM issue now merged in @blockstack/ui.
