### ISSUE TITLE
Replace all "Connect" references with "Stacks Wallet"

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#732]
Needs replacement throughout app. For example:

<img width="868" alt="Screen Shot 2021-01-04 at 11 41 12" src="https://user-images.githubusercontent.com/28991/103526974-f13d3480-4e81-11eb-955a-8c3bda9c94dd.png">

**Comment by hstove** [comment]
@markmhx up to you if you want to QA or Tim.

**Comment by markmhendrickson** [comment]
@timstackblock please review if you can and I'll try to do so myself soon this week
