### ISSUE TITLE
Add form validation for set password screen

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#733]
I can proceed through this form without any password value at the moment:

![image](https://user-images.githubusercontent.com/28991/103527775-2c8c3300-4e83-11eb-9776-90371c21b2d8.png)

**Comment by markmhendrickson** [comment]
Related to https://github.com/blockstack/ux/issues/720

**Comment by hstove** [comment]
@kyranjamie can you give a :+1: to d8f6832 ? The code should look pretty familiar.

**Comment by timstackblock** [comment]
I must enter a password to move from this page, I no longer see this bug
