### ISSUE TITLE
Test authentication UX against testnet with migrated names

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#737]
Once Radon is available per https://github.com/blockstackpbc/devops/issues/544, we should smoke test the new Stacks Wallet with ~Banter~ Explorer Sandbox and BlockSurvey in full ahead of Stacks 2.0 Mainnet.

**Comment by markmhendrickson** [comment]
1. Ensure that https://github.com/blockstack/stacks-blockchain-api/pull/363 has all backwards capability BNS needs (eg https://core.blockstack.org/#name-querying-get-names-owned-by-address) and gets merged
2. Modify web wallet to query Stacks 2.0 data
3. Get fully migrated names onto testnet via https://github.com/blockstackpbc/devops/issues/544
4. Test Explorer Sandbox (updated to latest stacks.js/connect) and Blocksurvey (previous library integration) with latest web wallet build, looking to ensure that 2.0 data pulled for both wallet and app

**Comment by markmhendrickson** [comment]
@hstove anything we need to do here for step #2 above so that @timstackblock can start testing per step #4?

Steps 1 and 3 appear complete.

**Comment by hstove** [comment]
@markmhx @timstackblock , the BNS import has not been merged or pushed live on the staging API server that we have set up for this purposes. At least, that was true yesterday afternoon.

**Comment by hstove** [comment]
To be concrete, we need both of these:

https://github.com/blockstack/stacks-blockchain-api/pull/388
https://github.com/blockstack/stacks-blockchain-api/pull/389

**Comment by markmhendrickson** [comment]
@zone117x Any estimate available for when the two issues above might get merged in?

**Comment by zone117x** [comment]
These are merged. The BNS API deployment needs modified to include the Stacks 1.0 migration data, being tracked here: https://github.com/blockstackpbc/devops/issues/566

**Comment by timstackblock** [comment]
The extension is working with my old connect name and I can use the explorer and blocksurvey

<img width="1188" alt="Screen Shot 2021-01-13 at 5 01 14 PM" src="https://user-images.githubusercontent.com/49165468/104525339-edba5380-55cd-11eb-9bf3-d10cdd11adbe.png">

<img width="1202" alt="Screen Shot 2021-01-13 at 5 57 27 PM" src="https://user-images.githubusercontent.com/49165468/104525326-e5faaf00-55cd-11eb-8ce5-a77f316bded8.png">
