### ISSUE TITLE
Remove menu from screens that require user action

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#738]
When the user is going through a flow, such as registration, we should hide the menu to reduce the chance they bail prematurely and keep them focused.

E.g. when setting a username:

<img width="477" alt="Screen Shot 2021-01-04 at 08 40 46" src="https://user-images.githubusercontent.com/28991/103538341-50a53f80-4e96-11eb-947a-3bafe0ea21d7.png">

**Comment by timstackblock** [comment]
Add a Username functionality is removed, we cant test this @markmhx

**Comment by hstove** [comment]
True, but two other pages were fixed for this - the initial "get started" page, and the "enter secret key" page. They should not longer have the menu.

**Comment by timstackblock** [comment]
Yes it is removed from those 2 pages so we can close it out.
