### ISSUE TITLE
Set cursor to pointer for all menu hovers

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#739]
Currently the cursor alternates between default and selection:

<img width="477" alt="Screen Shot 2021-01-04 at 08 40 46" src="https://user-images.githubusercontent.com/28991/103538479-8f3afa00-4e96-11eb-9c80-0456c8204b07.png">

**Comment by timstackblock** [comment]
Mouse over still alternates from a pointer to a finger to a selector all seem like they are appropriate to me, I am not sure this is a bug see screen shots below.

UPDATED screen shots do not show mouse pointer so I deleted them.
