### ISSUE TITLE
PR 731 when I open the extension the main page does not render correctly

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#741]
Video of issue http://somup.com/crVf2229PS

This is on Chrome, while attempting to test the new build after installation, when I open the extension this is what I am getting? 

<img width="479" alt="Screen Shot 2021-01-04 at 9 09 06 AM" src="https://user-images.githubusercontent.com/49165468/103543470-95b47c00-4e6c-11eb-8a92-ad83c0e94584.png">

<img width="641" alt="Screen Shot 2021-01-04 at 9 11 57 AM" src="https://user-images.githubusercontent.com/49165468/103543677-ed52e780-4e6c-11eb-84d4-745adcd047d6.png">

**Comment by timstackblock** [comment]
Duplicate of https://github.com/blockstack/ux/issues/735

**Comment by timstackblock** [comment]
Could be a network issue preventing the display of latest transactions and tokens in wallet @hstove any thoughts.

<img width="1369" alt="Screen Shot 2021-01-04 at 9 32 18 AM" src="https://user-images.githubusercontent.com/49165468/103546234-a8c94b00-4e70-11eb-8ed5-9ede4ffcf942.png">

**Comment by markmhendrickson** [comment]
@timstackblock mind testing again?

**Comment by hstove** [comment]
Yep, now you should see the 'cannot connect to ...' message if the node is down again.
