### ISSUE TITLE
Ensure password works after first confirmation

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#756]
It appears that entering my password to unlock the wallet works the first time but not subsequently.

Steps:

1. Sign up via https://pr-725.testnet-demo.stacks.engineering/, setting password as new user through https://pr-725.app.stacks.engineering/
2. Wait for faucet transaction to confirm
3. Select "Contract call" and unlock wallet successfully
4. Close popup
5. Select "Contract" call again and password error shown despite providing same value

![image](https://user-images.githubusercontent.com/28991/104121703-a23f4580-5340-11eb-8ed2-6b409c47c2a8.png)

**Comment by hstove** [comment]
I don't think this was a bug in the extension, but let's just verify this in the extension for QA.
