### ISSUE TITLE
Some nits

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#757]
Some text/inputs aren't respecting the color mode of the app:

![Screen Shot 2021-01-10 at 2 14 24 PM](https://user-images.githubusercontent.com/11803153/104135634-fc4b0580-5356-11eb-85bf-54f24ce8cf97.png)

Action not attached to bottom. Seems like there is too much space below it
![Screen Shot 2021-01-10 at 3 15 12 PM](https://user-images.githubusercontent.com/11803153/104135638-01a85000-5357-11eb-8a77-4fd597dd18df.png)

Scroll bar seems to be enabled on the bottom drawer. No "X" icon to close (I know you can hit the backdrop, but folks might not intuit that).
![Screen Shot 2021-01-10 at 3 15 47 PM](https://user-images.githubusercontent.com/11803153/104135645-0967f480-5357-11eb-8be5-5e681257ae60.png)

On account switch screen, it overflows horizontally due to address + check icon
![Screen Shot 2021-01-10 at 3 16 59 PM](https://user-images.githubusercontent.com/11803153/104135652-108f0280-5357-11eb-9308-64f9ced1fa0e.png)

I really wish I knew which account I was on in this view:
![Screen Shot 2021-01-10 at 3 20 32 PM](https://user-images.githubusercontent.com/11803153/104135706-6e234f00-5357-11eb-85bc-813ea1b94115.png)

Code bg is not dark: 
![Screen Shot 2021-01-10 at 3 21 05 PM](https://user-images.githubusercontent.com/11803153/104135725-7da29800-5357-11eb-854f-01f64dafc5bd.png)

**Comment by hstove** [comment]
@markmhx @andresgalante can we break this up into smaller issues? I think the only remaining issue is around the scrollbar. Not sure if that needs to block the audit, though.

**Comment by markmhendrickson** [comment]
Is this the issue you mean in regards to the scrollbar?

![image](https://user-images.githubusercontent.com/28991/106743915-44400e00-661f-11eb-8cc8-46d800ca93a9.png)

If so, please create a separate issue for that and assign yourself. Then move this issue into QA and assign to Tim. He can then test all but the scrollbar-related one.

Let's make sure to add separate issues from the start for this sort of feedback going forward.

**Comment by markmhendrickson** [comment]
On second thought, let's hold off assigning for QA in general since we'll be focusing on this issue's milestone in a future sprint.
