### ISSUE TITLE
leave the wallet idle and come back, user is locked out and not able to reopen

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#760]
Video of issue http://somup.com/crVXY6oQLj

I was logged into the extension wallet through Chrome and then I went off to FF for an hour to do some testing there when I came back the wallet was not open so I clicked the icon to open the wallet and this is what displayed.

<img width="436" alt="Screen Shot 2021-01-11 at 3 37 12 PM" src="https://user-images.githubusercontent.com/49165468/104235388-e571e500-5422-11eb-9c6a-6454df9a08c9.png">

<img width="445" alt="Screen Shot 2021-01-11 at 3 07 27 PM" src="https://user-images.githubusercontent.com/49165468/104235322-cffcbb00-5422-11eb-9640-72560a2816a5.png">

I never logged out so I was expecting to see a page asking me for my wallet password.
This seems like a bug that is happening instead of it prompting me to enter my password.

**Comment by timstackblock** [comment]
this is working

**Comment by timstackblock** [comment]
This is back seems to be a regression

**Comment by andresgalante** [comment]
@markmhx how would to like to prioritize regressions, should we bundle it together with the beta release or tackle it before?

**Comment by markmhendrickson** [comment]
I'd suggest bundling with the beta release to keep things simple for now.

**Comment by hstove** [comment]
I fixed this in #1036 , and it is live in production. Moving to QA

**Comment by andresgalante** [comment]
Closes #1029
