### ISSUE TITLE
Fix spacing issues

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#764]
I'm still seeing spacing / padding issues on screens:

![image](https://user-images.githubusercontent.com/28991/104331679-a2317800-54ef-11eb-9d1a-fe4eadae31ec.png)

**Comment by timstackblock** [comment]
<img width="1408" alt="Screen Shot 2021-01-20 at 3 41 46 PM" src="https://user-images.githubusercontent.com/49165468/105232189-05e22380-5b36-11eb-90de-b0a7fdfb1719.png">
