### ISSUE TITLE
Transaction popup page is titled "Blockstack"

### ISSUE THREAD

**Issue by dantrevino** [leather-io/extension#769]
This should be "Stacks", at minimum

![image](https://user-images.githubusercontent.com/7738/104352258-4baa4680-54bb-11eb-96ba-88e2953c6335.png)

**Comment by markmhendrickson** [comment]
This is fixed on #761

![image](https://user-images.githubusercontent.com/28991/104459585-3a416700-55ad-11eb-8ccf-0cd98e9a7b35.png)
