### ISSUE TITLE
After restoring a wallet, user does not immediately see the same number of accounts that they've generated in the past

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#775]
User can create accounts which are additional addresses but once they log out they cannot recover those addresses
After login the second time the extension only shows the first wallet the other "add an account" wallets are lost.

Video of issue
http://somup.com/crVlYVolo4

Image of the switch address option with 3 addresses
<img width="443" alt="Screen Shot 2021-01-12 at 1 19 21 PM" src="https://user-images.githubusercontent.com/49165468/104366462-6b576400-54e7-11eb-8358-75e66d9420b7.png">

user logs out and logs back in switch accounts is not available

<img width="434" alt="Screen Shot 2021-01-12 at 3 04 22 PM" src="https://user-images.githubusercontent.com/49165468/104366554-8d50e680-54e7-11eb-932b-daac1075bd95.png">

**Comment by hstove** [comment]
Just to be clear, because I had to double check this stuff, the addresses are the exact same when you create the second, third, etc, account. The problem (which is legit) is that they don't show up right away.

**Comment by timstackblock** [comment]
> Just to be clear, because I had to double check this stuff, the addresses are the exact same when you create the second, third, etc, account. The problem (which is legit) is that they don't show up right away.

Could you elaborate, the address in the picture looks to be 3 different addresses. So the issue is its just supposed to make the same address over again right?

**Comment by hstove** [comment]
Oh! I see. That is perfectly expected. A wallet is "hierarchical", so there is sort of a "master wallet", and then from there unlimited accounts can be generated from it. This is different than how our other Stacks Wallets have been built, but they can technically also derive multiple accounts. And, with the same secret key, you will always get the same exact address for account 1, account 2, etc, but they _will_ be different. And no one can "link" the accounts together except for you (they're private in that way).

> So the issue is its just supposed to make the same address over again right?

Yep!

**Comment by hstove** [comment]
Basically, when you use the desktop wallet, you're only seeing "Account 1".

**Comment by timstackblock** [comment]
Got it, so the only issue is that we want it to persist after logout and relogin

**Comment by hstove** [comment]
Ready for QA - it will even restore usernames from the old authenticator.
