### ISSUE TITLE
No secret key displayed

### ISSUE THREAD

**Issue by stackatron** [leather-io/extension#777]
<img width="1278" alt="Screen Shot 2021-01-13 at 5 16 19 PM" src="https://user-images.githubusercontent.com/767828/104517127-7bdd0c80-55c3-11eb-8fc3-3676d051859d.png">

No key displayed. There is just an empty div where it appears to belong. 

Looked for an error: 

index.js:23 GET https://gaia.blockstack.org/hub/139NbLNxZPLktChevb3yHGxj6NyBWLN25B/wallet-config.json 404

Installing this build: https://storage.googleapis.com/wallet-extensions/stacks-wallet-chromium.zip

**Comment by hstove** [comment]
lol. this is actually correct. there are major issues with the spacing of the button which makes you think it's broken. you're supposed to just click the button. the next step is the actual key. but this first step was designed for a slightly different flow - it makes sense during sign up to skip this step.

**Comment by stackatron** [comment]
Sure. I got beyond this step and then something froze up. I ended up with a clean install and then must have forgot that i need to progress. I did encounter a problem but can't reproduce yet. But we can close...
