### ISSUE TITLE
Identity list does not differentiate between .id names and subdomain names.

### ISSUE THREAD

**Issue by dantrevino** [leather-io/extension#812]
I have two registered ids:
riot.id
riot.id.blockstack

In the id selection list, they are not differentiated in any way.  Both are presented simply as "riot".

As a user I should be able to identify the specific identity that I wish to use, without guessing.

![ink (5)](https://user-images.githubusercontent.com/7738/104763667-1d2aa680-571b-11eb-85d4-86cefa210341.png)

**Comment by markmhendrickson** [comment]
I'd suggest we stop hiding the subdomain in general now that we're on Stacks 2.0 and going to be encouraging the implementation of many possible subdomain registrars going forward.

**Comment by markmhendrickson** [comment]
I'm closing this out in favor of https://github.com/hirosystems/stacks-wallet-web/issues/1409
