### ISSUE TITLE
[Your Secret Key] Styling issues

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#87]
- [ ] Button font-size -> 14px --> https://github.com/blockstack/ui/issues/28
- [x] "Your Secret Key" in the box -> Caption regular (12px)
- [x] center align the secret key text
- [x] Secret Key padding top: 16px, padding bottom 20px

![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/8164307d-ff56-44df-87d3-bd3f60f003af)

**Comment by kyranjamie** [comment]
How important is centring the text? This is a `textarea` to make it selectable, which cannot be centre aligned.

**Comment by aulneau** [comment]
> How important is centring the text? This is a textarea to make it selectable, which cannot be centre aligned.

You can do `text-align: center` to a `textarea`. I've added it to mine.

**Comment by kyranjamie** [comment]
I am indeed mistaken. 

Thanks.

**Comment by timstackblock** [comment]
![Screen Shot 2020-02-19 at 8.45.09 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/39c03225-5b11-4c0c-822d-192ee7a4db96)
