### ISSUE TITLE
[Save your SK] Vertical rhythm

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#89]
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/920f42bf-eff0-401a-91cb-421585c03c40)

24, 8, 24, 32

**Comment by aulneau** [comment]
What about spacing between paragraphs?

**Comment by jasperjansz** [comment]
@aulneau In the design this is just a line break. If you'd like to separate it into two, the spacing would be 20px. That is equivalent to the body line-height.

**Comment by aulneau** [comment]
Ok cool, just FYI we almost never use line breaks when we implement it.
