### ISSUE TITLE
Can't import useConnect() because "screen is not defined"

### ISSUE THREAD

**Issue by AtlantisPleb** [leather-io/extension#919]
The new [Authentication tutorial](https://docs.blockstack.org/build-apps/guides/authentication) includes a section [Usage in React Apps](https://docs.blockstack.org/build-apps/guides/authentication#usage-in-react-apps) with the following example:

```
import { useConnect } from '@stacks/connect-react';

const AuthButton = () => {
  const { doOpenAuth } = useConnect();
  return <Button onClick={() => doOpenAuth()}>Authenticate</Button>;
};
```

Implementing this ([here](https://github.com/ArcadeCity/forever/blob/60dc086451bdaa48650587b7ca721641da03d6c1/pages/test.tsx)) throws an error: "ReferenceError: screen is not defined"

Looks like the [useConnect() definition](https://github.com/blockstack/ux/blob/master/packages/connect-react/src/react/hooks/use-connect.ts) is trying to export `screen` and a couple other variables either undefined or not in scope.

Happens with the current npm versions as well as the "@launch-misc" versions:

```
"@stacks/connect": "^4.3.15",
"@stacks/connect-react": "^2.17.15",
"@stacks/connect-ui": "^2.17.16",
```

```
"@stacks/connect": "^4.3.16-alpha.75e60a4.0",
"@stacks/connect-react": "^2.17.16-alpha.75e60a4.0",
"@stacks/connect-ui": "^2.17.17-alpha.75e60a4.0",
```

**Comment by hstove** [comment]
🤦🏼 there used to be a `screen` variable exported. Typescript didn't flag this because `screen` is a valid global in browsers. And I didn't see this because I'm only using `useConnect` on the client side. Nice catch! Fixed in 48233557.
