### ISSUE TITLE
banner moves "ive saved it" button out of view

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#926]
banner moves "ive saved it" button out of view, user has to scroll down to see it some may not realize they can scroll in an extension pop up.

BEFORE SCROLL
<img width="658" alt="Screen Shot 2021-01-20 at 3 21 02 PM" src="https://user-images.githubusercontent.com/49165468/105230390-45f3d700-5b33-11eb-999f-db29d497756f.png">

AFTER SCROLL
<img width="608" alt="Screen Shot 2021-01-20 at 3 21 08 PM" src="https://user-images.githubusercontent.com/49165468/105230423-4f7d3f00-5b33-11eb-89fa-6a685c1ece0d.png">

**Comment by timstackblock** [comment]
I'm also having trouble scrolling how is this user experience for anyone else?

**Comment by hstove** [comment]
I've pushed a change in #761 to improve this. Unfortunately it seems like the max height of that popup is 600px (enforced by the browser), so I made some tweaks to fit better in that viewport.
