### ISSUE TITLE
Horizontal padding

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#93]
There are three variations with regards to horizontal padding:

**1. Center aligned with 40px on desktop**
Center aligned screens have more padding because otherwise, the discrepancy between something small in width and large in width is jarring.
Screens: Choose an account, Sign in, Loading, Connect, Confirmation

example:
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/9b2edea2-ebff-4003-8f6a-35f40d380cf3)

**2. Left aligned with 32px on desktop**
Screens: username, how it works, password, secret key

example:
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/e1d50f28-68e1-40b9-b3c7-67d48fd5eeef)

**3. Intro modal**
No general padding because the lines span the entire width. 
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/1db88ce6-6786-4745-ab88-c0f7f4d364b1)

On mobile, all screens have use 24px (regardless of alignment) instead of the 32px and 40px on desktop.

**Comment by aulneau** [comment]
I am a bit confused about this ticket. We have different horizontal spacings between pages. The secret key pages go to the connect page, and so we go from 32px directly to 40px. It's pretty jarring.

@jasperjansz Is there anyway we can reduce the level of complexity with these units? There are so many instances, and it doesn't seem to follow a specific system.

**Comment by kyranjamie** [comment]
In this instance, I think it will be strange to have content jump 8px on page change. Even if not, the question has to be asked if 3 dynamic margins varying by such a small amount are worth the complexity.

More generally, I'd love us to get spacing units/general whitespace right, first time. So we don't have to make sweeping changes to our work to match designs, lessening the workload for both @jasperjansz in reviewing and @aulneau and I in fixing. I have some thoughts on how we do this:

Firstly, we need to follow an implementation pattern where all components are, by default, void of any margins, so they can be explicitly spaced in their individual contexts. Only very high level abstractions should contain predefined margins.

Second, we need to define and enforce constraints better. Which means annotating in the design system what units are allowed — ideally disallowing a certain multiples of 4. I'm looking at 28px. And ensuring that @blockstack/ui actively warns against a developer trying to use values that aren't allowed by the system.

**Comment by jasperjansz** [comment]
I changed it to be 32px on desktop (for all screens) and 24px: https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=5721%3A11775.
