### ISSUE TITLE
Improve data store security

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#932]

**Comment by markmhendrickson** [comment]
@hstove Mind bullet pointing the changes here for context? I don't recall very well which improvements we're making to support the store listing.

**Comment by hstove** [comment]
Oh - it's not related to the Chrome / Firefox public extension store. By "store" I mean the internal data structures used by the app itself, like a "data store". Totally understandable misunderstanding 🤣

**Comment by markmhendrickson** [comment]
Aaah okay, I just updated the title then 👍  

I do still think it'd be helpful to bullet point the intended improvements here, perhaps as a checklist so we can track progress more clearly and understand just what security risks they resolve.
