### ISSUE TITLE
[1.20.16.907] Bug: contract call with NFT post condition fails

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#935]
![Screenshot from 2021-01-29 14-11-17](https://user-images.githubusercontent.com/1449049/106279243-63fcbe00-623c-11eb-9489-499c9f6fefd8.png)

Bug found testing Stacks Wallet for Web.

### Error

**Loadable**: `transaction.signedTransaction`
**Message**: `TypeError: t.value.toArrayLike is not a function`

### Environment

**Version**: `1.20.16.907`
**Branch**: `feat/launch-misc`
**Commit**: `0ce2c74`

I made a contract call with non fungible post condition using `NonFungibleConditionCode.DoesNotOwn`

The UI shortly showed "You own" with the asset and the displayed the error dialog.

**Comment by MarvinJanssen** [comment]
Can you explain how to reproduce this bug? I managed to successfully created post conditions to transfer BNS names.

```JS
```

**Comment by MarvinJanssen** [comment]
Can you explain how to reproduce this bug? I managed to successfully created post conditions to transfer BNS names.

Here is a snippet:

```JS
export async function transfer(domain,new_owner,zonefile)
	{
	let address = stx_address();
	if (!address)
		throw Error('Not signed in');
	domain = clean_check_domain(domain);
	let hash = await zonefile_hash(zonefile || '');
	let asset_name = tupleCV({name: bufferCVFromString(domain),namespace: bufferCVFromString(DOMAIN_NAMESPACE)});
	let asset = createAssetInfo(BNS_CONTRACT_ADDRESS,BNS_CONTRACT_NAME,'names');
	return await contract_write(
		'name-transfer',
		[bufferCVFromString(DOMAIN_NAMESPACE),bufferCVFromString(domain),standardPrincipalCV(new_owner),someCV(bufferCVFromString(hash))],
		[makeStandardNonFungiblePostCondition(address,NonFungibleConditionCode.DoesNotOwn,asset,asset_name)]
		);

	//TODO- Add recipient post condition once the following issue is fixed: https://github.com/blockstack/ux/issues/969
	// makeStandardNonFungiblePostCondition(new_owner,NonFungibleConditionCode.Owns,asset)
	}
```

**Comment by friedger** [comment]
@MarvinJanssen It is about the extension. If you use connect's openContractCall

**Comment by MarvinJanssen** [comment]
@friedger right. I should have clarified. With Connect Canary and the code above I can successfully generate post conditions for NFTs. `contract_write` is a simple wrapper I made for `openContractCall` that returns a Promise. The key is properly encoding the asset name and info.

**Comment by hstove** [comment]
Yes, this was fixed since the time this issue was opened. I've personally tested this with Boom's "transfer NFT" functionality.
