### ISSUE TITLE
Fix intermittent iPad authentication issues

### ISSUE THREAD

**Issue by 0xc22b** [leather-io/extension#940]
I think it's because Connect uses window.popup and postMessage which are not reliable on phones and tablets.

I saw there is a user agent checking in the source code that if it's an iPad, don't use popup. But since iOS 13+, word 'iPad' is not included in Safari user agent anymore. It is now indistinguishable from the desktop version of macOS Safari ([ref](https://www.whatismybrowser.com/guides/the-latest-user-agent/safari)). Anyway, I think it's still worth to not open Connect popup on Safari so that sign in and sign up with Connect on iPad is more reliable.

I suggest to insert these lines below in connect/src/auth.ts:49.
```javascript
if (/Mac OS X/.test(ua) && /Safari/.test(ua) && !/Chrome/.test(ua) && !/Firefox/.test(ua)) {
  return true;
}
```
I've tested with user agents below and it works fine.

**iPad**
*Firefox*: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
*Chrome*: Mozilla/5.0 (iPad; CPU OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1
*Safari*: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15

**Mac OS X**
*Firefox*: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:85.0) Gecko/20100101 Firefox/85.0
*Chrome*: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
*Safari*: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15

**Android**
*Firefox*: Mozilla/5.0 (Android 9; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0
*Chrome*: Mozilla/5.0 (Linux; Android 9; SM-J730GM) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Mobile Safari/537.36

**Ubuntu**
*Firefox*: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
*Chrome*: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

Please let me know if you want me to create a pull request.

**Comment by markmhendrickson** [comment]
Thanks for the report! Mind indicating the app you've used to try signing up with Connect? So we can identify the exact version involved.

**Comment by 0xc22b** [comment]
I've used [brace.to](https://brace.to) with @stacks/connect version 4.3.15. Other dependency information can be found [here](https://github.com/bracedotto/brace-client/blob/master/packages/web/package.json).
