### ISSUE TITLE
Input bug on onboarding dialog

### ISSUE THREAD

**Issue by cuevasm** [leather-io/extension#942]
There's an easy to miss little bug in the new extension with the password logic (where it forces you to do a stronger password after the restore process). Once you reach whatever the minimum length is, it actually takes your cursor out of the box, so you're no longer typing in it. For passwords I look down more than in regular typing, so I missed that I was pulled out of the box and the button went blue so the instinct was to smash enter.

I happened to notice my input looked short once I refocused my eyes, but I think you'll have a lot of people thinking they typed 2359134alongpassword, but actually got the first 10 or whatever digits of it.

🙏 (Chrome, Windows)

**Comment by andresgalante** [comment]
I can confirm this bug also happens in mac chrome

**Comment by aulneau** [comment]
I will pick this up today. I also have some other improvements for various inputs:
- we can handle pasting keys a bit better, trim them, etc.
- show some helpful information for password requirements, etc.

**Comment by hstove** [comment]
Yep, I'm also a fan of how Kyran build the password validation UI in the wallet, and would like if we adopted that approach
