### ISSUE TITLE
[1.20.16.515] Bug: Unable to fetch interface

### ISSUE THREAD

**Issue by whoabuddy** [leather-io/extension#943]
I am trying to create a new NFT using [boom.money](https://boom.money) and ran into an issue with the Stacks Wallet for Web.

On the first few tries the wallet would quickly show the sign transaction screen, then cover it with the error message listed below.

### Error

**Loadable**: `transaction.contract-interface`
**Message**: `Unable to fetch interface for contract SP1K1A1PMGW2ZJCNF46NWZWHG8TS1D23EGH1KNK60.boom-nfts`

### Environment

**OS**: Linux Mint 19
**Browser**: Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)

**Version**: `1.20.16.515`
**Branch**: `release/canary`
**Commit**: `c1180a3`

### Screenshots

Shown for a split second:

![20210201_004_Selection](https://user-images.githubusercontent.com/9038904/106502374-859ab700-6481-11eb-8115-b9fa5054e51e.png)

Shown immediately afterward:

![20210201_005_Selection](https://user-images.githubusercontent.com/9038904/106502396-8a5f6b00-6481-11eb-8bc5-cb835e0d385a.png)

### Additional Info

This error seemed to resolve itself in the last 10 minutes, but I wanted to file the issue anyway to try and track down *why this could happen* considering there was no easy way to figure it out as a user.

Also, I am seeing the following console errors on any page I visit:

```none
DevTools failed to load SourceMap: Could not load content for chrome-extension://ojgfjcgbbffepgbjdfeiopojmhmjpmik/message-bus.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://ojgfjcgbbffepgbjdfeiopojmhmjpmik/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by markmhendrickson** [comment]
The message suggest to me that perhaps the contract you were trying to sign here hadn't fully deployed until after about 10 minutes. Had you deployed the contract right before trying to sign?

**Comment by whoabuddy** [comment]
Nope, the explorer shows it as [deployed 7 days ago](https://explorer.stacks.co/txid/0xfbf5125588bdb720864686862364e0fe37a42099f8ed073061d258f8d9c40b4e?chain=mainnet) and it's been used a few times since.

I tested again this morning and it's working as expected.

**Comment by markmhendrickson** [comment]
Hmm weird. I'm not sure how we'd go about recreating this for testing. Perhaps we'll need to sit on this for a bit to see if the problem reappears, unless @hstove has any immediate ideas.

**Comment by markmhendrickson** [comment]
@whoabuddy I'm closing this as stale but please re-open if it's an active issue for you.
