### ISSUE TITLE
The wallet dimensions are not the same after install, in chrome I get a skinny rectangle.

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#944]
The wallet dimensions are not the same after install, in chrome I get a skinny rectangle.

<img width="509" alt="Screen Shot 2021-02-01 at 11 50 27 AM" src="https://user-images.githubusercontent.com/49165468/106528101-358a1780-64b6-11eb-9d3c-e68e24b9aa79.png">

**Comment by hstove** [comment]
This one is really annoying - can anyone replicate this? @markmhx ? I swear I've "fixed" this multiple times, there are just wonky behaviors with how Chrome renders that frame. I'm unfortunately unable to replicate to be able to diagnose this. I will dig deeper, and have some thoughts for how to potentially make this more robust.

**Comment by andresgalante** [comment]
yes, I could replicate it, it was narrow the first time I install it.

If it's CSS related we can troubleshoot it together.

**Comment by aulneau** [comment]
This has been resolved, closing
