### ISSUE TITLE
Extension allows me to send STX to a test address from the mainnet (this transaction is not broadcast)

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#945]
Extension allows me to send STX to a test address from the mainnet (this transaction is not broadcast) and it cannot go through but there should be an error message for the user.

As you can see in the picture below but the icon I am on the "mainnet" but the test address is accepted and the transaction looks successful from the UI

<img width="341" alt="Screen Shot 2021-02-01 at 11 59 00 AM" src="https://user-images.githubusercontent.com/49165468/106528735-3d968700-64b7-11eb-9c2e-e2a8434fd728.png">

**Comment by hstove** [comment]
@markmhx is the reason we removed from QA due to the board changes? How should we track the state of this?

FYI the fix is in #936

**Comment by markmhendrickson** [comment]
I've put it back on the board, seeing it's actually tackled for the alpha canary merge. I presumed it was meant for the beta release.
