### ISSUE TITLE
Support sponsored transactions through the web wallet

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#947]
This flow would unlock great user experiences for apps that could let their users make Stacks 2.0 transactions without owning any STX.

For example:
- NFT app wants to mint an NFT for a user
- NFT uses Connect to open a contract call, with `{ sponsored: true }` (keeping consistency with `@stacks/transactions` API)
- User signs transaction, but the transaction is not broadcasted
- App signs as a sponsor 
  - App handles the callback to get the TX
  - passes the signed TX to their server
  - signs it as a sponsor
  - broadcasts the TX
- App notifies the user that their tx was broadcasted (link to explorer, etc)

**Comment by andresgalante** [comment]
Thanks @hstove 🙇 

@markmhx how should I label a feature proposal, should it go to the backlog?

**Comment by markmhendrickson** [comment]
Yep! I'll do both now, that's the right idea.
