### ISSUE TITLE
Migrate connect package to Stacks.js repository

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#954]
We should move the connect package to the Stacks.js repository since we're moving away from treating this repository as a mono repo, and developers already expect to install connect as a Stacks.js package via npm and yarn. This will clarify its relationship with that set of libraries.

**Comment by hstove** [comment]
Closing this in favor of #1055 - we can move to stack.js after more conversation with the platform team around ownership of the Connect packages.
