### ISSUE TITLE
Integrate Stacks Blockchain API for username-related functionality

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#956]
For both products:

- [ ] Stacks Wallet
- [ ] Blockstack Connect (app.blockstack.org)

This is presumably possible now that https://github.com/blockstack/stacks-blockchain-api is merged into the API.

**Comment by hstove** [comment]
@andresgalante and @markmhx can we split this into three issues, for each project? It'll be three different issues.

Didn't we also decide that updating the Blockstack Browser was not necessary, or at least not a priority?

And in the spirit of breaking down issues into smaller pieces, each chunk of work (separately for app.blockstack.org and for the web wallet) would be:

- Enable subdomain registration
- Restore identities from the new 2.0 APIs

**Comment by markmhendrickson** [comment]
We already have one for Stacks.js here: https://github.com/blockstack/stacks.js/issues/945

Could one of you create the others? Please chunk down work proactively here where you see fit.

I don't remember deciding the Blockstack Browser wasn't a priority here, but perhaps we did decide that. However, wouldn't that mean we can't re-enable username registrations for that product in general since they wouldn't show up / get surfaced by core.blockstack.org? 

We have https://github.com/blockstack/blockstack-browser/issues/2066, which presumably wouldn't make sense to execute without the core.blockstack.org change, and we've been promising the restoration of username functionality with https://github.com/blockstack/ux/issues/946.
