### ISSUE TITLE
Cannot call the counter contract on test demo app: ERROR transaction rejected - ConflictingNonceInMempool

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#958]
This works well for an existing account trying to see why this failed for the newly created account

CHROME EXTENSION

Cannot call the counter contract on test demo app

The user can bring up the pop up for transaction signing but when they select confrim they get the error below

 ERROR transaction rejected - ConflictingNonceInMempool

VIDEO OF BUG http://somup.com/crneFXoPZ5

<img width="1149" alt="Screen Shot 2021-02-03 at 1 14 12 PM" src="https://user-images.githubusercontent.com/49165468/106790593-c7626380-6621-11eb-9321-8ed4ded4c332.png">
<img width="1391" alt="Screen Shot 2021-02-03 at 1 14 20 PM" src="https://user-images.githubusercontent.com/49165468/106790597-c8939080-6621-11eb-8c29-b395f94f9a87.png">
<img width="1397" alt="Screen Shot 2021-02-03 at 1 14 25 PM" src="https://user-images.githubusercontent.com/49165468/106790601-c92c2700-6621-11eb-8099-2c27b72bb982.png">

**Comment by hstove** [comment]
@timstackblock can you paste the STX address here?

**Comment by timstackblock** [comment]
Sure it works well for an existing account not sure why this newly create account is failing I am still testing. I think it might be related to the pending connect token request

ST1ZV5Z31HP25E2D3XA9W32S45MD2KZ177RT6R8TN

**Comment by andresgalante** [comment]
We closing this issue because #960 will fix it

**Comment by timstackblock** [comment]
@aulneau encountered this issue today while testing the security patch

**Comment by timstackblock** [comment]
This popped back up today lets reopen the issue

**Comment by hstove** [comment]
We can keep this issue open, but #960 gets at the root cause, so we should not keep both of them open

**Comment by markmhendrickson** [comment]
I'm closing this in favor of https://github.com/blockstack/stacks-wallet-web/issues/960.
