### ISSUE TITLE
Ability to detect if a users cancels / closes a transaction window

### ISSUE THREAD

**Issue by MarvinJanssen** [leather-io/extension#959]
There is currently no way to detect if the user cancelled / closed a transaction window. (Opened with `openContractCall()` for example.) It makes it quite cumbersome to create specific user interactions or stage multiple transactions in sequence.

**Comment by dantrevino** [comment]
Needed!

**Comment by MarvinJanssen** [comment]
@markmhx I know it is in the icebox, but any updates on this?

**Comment by markmhendrickson** [comment]
Not yet, but I just moved it to the top of the web wallet column in the icebox so we take a prioritized look at it once this milestone is achieved: https://github.com/blockstack/stacks-wallet-web/milestone/39

**Comment by agraebe** [comment]
+1 on this, a need for my sample app too

**Comment by fbwoolf** [comment]
The PR for this will need to be paired with: https://github.com/blockstack/connect/pull/122 in `connect`.
