### ISSUE TITLE
Handle delay in account sign on

### ISSUE THREAD

**Issue by kyranjamie** [leather-io/extension#96]
Clicking on an account in this screen triggers the `doGenerateWallet`  ( 🤔) action.

This takes a while, so there's a delay between pressing the button and window close / sign into account.

<img src="https://user-images.githubusercontent.com/1618764/73852289-35b5ef80-482f-11ea-8605-1afda9ab8dd0.png" width="420px" />

We need a way of handling this better than just a pause.

**Comment by jasperjansz** [comment]
https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=6847%3A827

![ezgif.com-video-to-gif (2).gif](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/832748d7-aa76-482c-bd3a-6870a04e1097)
