### ISSUE TITLE
Handle race condition that causes conflicting nonce

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#960]
Yesterday, Tim saw a "conflicting nonce" error happen when submitting a second transaction. The wallet is supposed to handle this - and it does. We tried many times to reproduce, and couldn't reproduce it.

Today Marvin (BTC.us dev) saw this issue again, and I have an idea for how it can happen. Basically, the wallet gets some data from the API to determine what the "next correct nonce" is. However, if the next popup happens right around when the previous transaction was confirmed, then this "conflicting nonce" issue can happen. Mainly because it gets the nonce from our load balancer of `stacks-node`s, and those are not 100% in sync. There is a race condition where the conflicting nonce can occur.

This can be mitigated - one way would be to "re-calculate" the correct nonce before submitting the transaction. Hopefully this is an edge case that doesn't happen often, but we should keep an eye on it, and also solve the issue.

**Comment by andresgalante** [comment]
closes #958

**Comment by aulneau** [comment]
this should be fixed by https://github.com/blockstack/stacks-wallet-web/commit/557e1e9a475a29d2512a199e22b7845bca527d34
