### ISSUE TITLE
Properly handle re-creating post conditions when switching accounts

### ISSUE THREAD

**Issue by hstove** [leather-io/extension#969]
When you make a transaction with Connect to the web wallet, the developer can include post conditions. Currently, the web wallet makes the assumption that the post conditions are meant to be for the sending account. This way, an app can start a transaction with pre-set post conditions set to the current user (aka logged in user of that app). However, users can switch accounts in this popup and complete the transaction from a different account. When the user switches accounts, the web wallet automatically re-creates the post conditions, using the new account's address. Otherwise, the transaction would likely fail, because the post conditions would be for a different account.

However, it's possible and valid for a transaction to set post conditions for an account other than the sending account. For example, I'm logged in as account 1, and I could set a post condition that says "X contract sends Y tokens".

The issue is that the web wallet will always overwrite the principal for a post condition. We can be smarter about it, though. For example, in Connect, you can set an `stxAddress` in the transaction payload, and Connect will switch to that account by default. We can have logic that says "if `stxAddress` !== `postCondition.principal`, then don't change it".

**Comment by MarvinJanssen** [comment]
+1. I'm adding post conditions for transferring a name on BNS for both the sender and recipient so this bug affects me.

**Comment by unclemantis** [comment]
+1 this bug affects my contract too.

**Comment by andresgalante** [comment]
Hi @unclemantis @MarvinJanssen this issue is up on our backlog but at the moment we are prioritizing security improvements over bugs.

I was wondering if you'd like and have time to take a stab at fixing it. If you do and have any questions please jump into the `-userx` Discord channel and the team will be more than happy to collaborate with you.
