### ISSUE TITLE
Editing your name causes the secret key does not appear when creating a data vault

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#97]
When I select the option to create a data vault and go through the creation flow intermittently I see that the secret key box is empty.

I have run through the creation flow multiple times and it has worked but I have captured a video of the bug and also shares screen shots of console. This is caused by shortening or editing you account/ user name during the creation process.

Video of the issue
https://screencast-o-matic.com/watch/cYnhoqwDgf

<img width="390" alt="Screen Shot 2020-02-05 at 10 16 38 AM" src="https://user-images.githubusercontent.com/49165468/73854504-a98cd380-4800-11ea-9b5c-b6d319654001.png">

<img width="1176" alt="Screen Shot 2020-02-05 at 10 13 11 AM" src="https://user-images.githubusercontent.com/49165468/73854520-adb8f100-4800-11ea-8529-d25d1b1739c7.png">

**Comment by kyranjamie** [comment]
This bug relates to the issue of username validation #70.

Currently, when an invalid username is entered, it silently fails and allows you through to the next step.

**Comment by hstove** [comment]
There is also the problem of the username registration API sometimes failing. I've seen it fail for unknown reasons periodically - maybe rate limiting, even on the test registrar.

We definitely need to address what to do if the username registration fails

**Comment by markmhendrickson** [comment]
I've created a separate issue to handle errors generated by the subdomain registrar: https://github.com/blockstack/connect/issues/46

And I'm moving this issue into QA alongside #70.
