### ISSUE TITLE
Make stacks.co repo public and link to it from the site

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#974]
There should be a way for people to submit issues for stacks.co. For example for getting their project listed under resources, or as a stacking service, or for general updates or feature requests.

Once that repo is public I would add links from stacks.co to create issues. For example at the Resources, I could add "Don't see your resource? Submit an issue."

The reason I think we should have this is because I can't keep up with all the developments in the ecosystem and it's important the site stays up to date.

**Comment by markmhendrickson** [comment]
We can start by linking to the "blockstack/blockstack.org" repository and migrating issues when @andresgalante sets up the new repos per https://github.com/blockstackpbc/devops/issues/603.

**Comment by friedger** [comment]
It is here: https://github.com/stacksgov/stacks-co
This issue can be closed.
