### ISSUE TITLE
[design] Update web wallet intro modal type

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#976]
![image](https://user-images.githubusercontent.com/25477905/108344189-20fb8e00-71dd-11eb-9457-155f1714a88d.png)

It doesn't follow our design system. The weight is too thick and size too large.

**Comment by markphd** [comment]
I would love this to be my first issue.. but after running the local server, I have no idea where to find this component. I see in some Typescript file where it uses styled component (eg ux/packages/app/src/components/seed-textarea/index.tsx) so I thought maybe I am looking at the wrong directory.

**Comment by markmhendrickson** [comment]
Thanks for your interest and help here! It appears to be [here](https://github.com/blockstack/ux/blob/release/canary/packages/connect-ui/src/components/modal/modal.tsx) in the `stacks-ui` package of this repository specifically (and on the `canary` branch, since that has all the latest changes).

**Comment by markmhendrickson** [comment]
@jasperjansz Mind linking to design system resources that'd be useful here for @markphd?

**Comment by markphd** [comment]
<img width="578" alt="modal" src="https://user-images.githubusercontent.com/1754675/109046623-61cc3900-76ee-11eb-8812-c03c48fff4aa.png">
Is this slightly better? :)

I copied the style from https://www.stacks.co/

**Comment by markmhendrickson** [comment]
You're making progress!

@aulneau may want to chime in here about the related UI library and how it can be used to standardize styling most consistently.

**Comment by aulneau** [comment]
I would ask @jasperjansz to chime in here. The connect-ui doesn't actually use `@stacks/ui` because it's built in stencil.js, not react.
