### ISSUE TITLE
Sign in hangs indefinitely

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#977]
![image](https://user-images.githubusercontent.com/25477905/108345554-b21f3480-71de-11eb-89e7-50bf4cded806.png)

Not sure if this is an issue with testnet or the web wallet.

**Comment by markmhendrickson** [comment]
We should add error handling for whatever is occurring here, testnet-based or otherwise.

**Comment by jasperjansz** [comment]
Could be issue with the Sandbox because it worked with the testnet demo app

**Comment by aulneau** [comment]
I don't think this is a bug that exists anymore. I think we can close this issue.

**Comment by hstove** [comment]
I'm pretty sure this is related to apps that have an older version of Connect. There was a breaking change to the underlying API. It made things much better (and more secure) but does have this consequence.

Related issue around backwards compatibility: #937 

Closing this, but feel free to re-open if you think that's best.
