### ISSUE TITLE
Remove confirmation prompt displaying other apps upon account selection

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#978]
![image](https://user-images.githubusercontent.com/25477905/108367253-8bbac280-71f9-11eb-915d-249308cb274c.png)

Context for Andy maybe: When you use multiple apps with the same key you get this warning. The reason is because the apps you've used is public.

When privacy was our only selling point we thought letting people know was a good idea. Now with 2.0, I'm not so sure and it just seems weird to me. Curious if others are thinking the same?

**Comment by markmhendrickson** [comment]
I suspect the basic premise still holds. We could probably create an updated version of it for clarity about what privacy means on Stacks 2.0.

**Comment by dantrevino** [comment]
No

**Comment by fbwoolf** [comment]
Just to confirm, I am supposed to remove this prompt completely?

**Comment by aulneau** [comment]
> Just to confirm, I am supposed to remove this prompt completely?

@fbwoolf no need to take this on -- I can remove it as I have a PR where much of this code has already been affected, if we do it in another PR conflicts will arise

**Comment by fbwoolf** [comment]
Ok, thanks, should I just close the issue or reassign it to you?
