### ISSUE TITLE
Update to use the latest from blockstack/ui

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#979]
![image](https://user-images.githubusercontent.com/25477905/108367525-d9372f80-71f9-11eb-98f3-4fa888425b34.png)

Throughout I see a lot of the old blue brand color and Inter for titles instead of Open Sauce. I see blockstack/ui has the right values for these so it seems to me you're maybe using an old version of it.

**Comment by markmhendrickson** [comment]
This appears resolved
