### ISSUE TITLE
Choose account: replace app name in title with our logo

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#981]
![image](https://user-images.githubusercontent.com/25477905/108368363-a3df1180-71fa-11eb-8374-bc342402e688.png)

Link: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=357%3A1333

**Comment by markmhendrickson** [comment]
This appears resolved

![image](https://user-images.githubusercontent.com/28991/111163079-12ff1a00-859d-11eb-862a-ab93666fbdd6.png)
