### ISSUE TITLE
Choose account: Type styles

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#982]
![image](https://user-images.githubusercontent.com/25477905/108369008-65962200-71fb-11eb-8533-7ac02da09a6b.png)

1. Title: Open Sauce and Ink/100
2. B3 (that's 16px) and Ink/90
3. B3 bold Ink/100
4. C2 Ink/60

**Comment by markmhendrickson** [comment]
This appears in need of updating still:

![image](https://user-images.githubusercontent.com/28991/114562117-7ea4d780-9c6e-11eb-83fb-a85ddf43e72c.png)
