### ISSUE TITLE
Home menu: replace logo and menu icon

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#983]
The logo is huge and the menu icon too prominent

![image](https://user-images.githubusercontent.com/25477905/108369951-6bd8ce00-71fc-11eb-82c5-dcba4de9a02a.png)

You can find the logo here: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=231%3A10153

And the menu icon here: https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/%E2%9D%96-Design-System?node-id=1167%3A0

I'm tracking the design task of the net indication here: #984

**Comment by markmhendrickson** [comment]
This appears resolved

![image](https://user-images.githubusercontent.com/28991/114563119-6aada580-9c6f-11eb-8835-817cdc27fe66.png)
