### ISSUE TITLE
Align popover menu to the menu icon

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#986]
![image](https://user-images.githubusercontent.com/25477905/108373331-14d4f800-7200-11eb-9ddb-2e512827d785.png)

I don't really know where to click to close it. Specifically, it's 8px below the icon and right-aligned.

**Comment by markmhendrickson** [comment]
This appears better now, but needing adjustment downward still so that the menu icon remains shown for clicking to close:

![image](https://user-images.githubusercontent.com/28991/111166916-e5b46b00-85a0-11eb-9e4b-e5c10d137767.png)
