### ISSUE TITLE
View Secret Key title and text styles

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#988]
![image](https://user-images.githubusercontent.com/25477905/108377477-5bc4ec80-7204-11eb-9684-6b9a78b7b43e.png)

1a. Add back arrow to title. You can find the component for titles with a back arrow here: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=231%3A8212
1b. Title font size: H4, which is Open Sauce at 24px
1c. Hide menu icon, also not sure we need the testnet indicator here (?)
2. I'd make this copy C1 (14px) so it takes up less space. That way the secret key and buttons are visible.
3. Same as above

**Comment by markmhendrickson** [comment]
This appears resolved

![image](https://user-images.githubusercontent.com/28991/111166660-9837fe00-85a0-11eb-98c4-43c3ba59eca5.png)
