### ISSUE TITLE
Redesign or remove alpha status warning

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#989]
![image](https://user-images.githubusercontent.com/25477905/108500212-b9624300-72af-11eb-9246-dfe5158e3179.png)

If we are keeping this, or any similar, message for the beta release I think we should redesign it to take up less space or be less prominent because it makes the UI really cluttered.

Another option would be for it to not persist, but show at the start of every new session.

**Comment by markmhendrickson** [comment]
We should be able to remove this entirely by the time we reach the beta milestone and finish the audit.
