### ISSUE TITLE
Redesign account info

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#990]
![image](https://user-images.githubusercontent.com/25477905/108500387-fc241b00-72af-11eb-9f80-cb9dcf29b472.png)

So in the designs we just show the address:

![image](https://user-images.githubusercontent.com/25477905/108500455-14943580-72b0-11eb-82ed-41d3de966444.png)

I do agree having some indication of which account you're using beyond the address is valuable. However I don't think this design with the long address works well.

Here is a draft I came up with a while ago, but it requires some more thinking: 

https://user-images.githubusercontent.com/25477905/108500646-65a42980-72b0-11eb-89d4-0c3f525525cc.mov

**Comment by markmhendrickson** [comment]
See also: https://github.com/blockstack/ux/issues/689
