### ISSUE TITLE
Clean up menu on subpages

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#994]
![image](https://user-images.githubusercontent.com/25477905/108504964-01d12f00-72b7-11eb-931e-e501f85a0653.png)

The menu on subpages shouldn't have all bells and whistles, instead it should be minimal so the user can focus on the task at hand. E.g. for sending, they navigated here presumably because they want to send.

On all these subpages we should have just the title and the back arrow. We can debate whether we want to keep any or indications of things like "testnet mode" or the alpha warning, but my default answer would be to hide those too.

You can find the subpage header component here: https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=231%3A8212

**Comment by markmhendrickson** [comment]
This appears resolved
