### ISSUE TITLE
[Send] Design choose token flow

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#995]
Currently when you open the send flow it starts with the dropdown open:

![image](https://user-images.githubusercontent.com/25477905/108505553-df8be100-72b7-11eb-805d-c943370c8fb3.png)

I think this is a strange UI pattern, especially if you only have STX to begin with (probably most users). I suggest we default to the token that's on the top of the user's list. So if I own just STX it would look like this: 
![image](https://user-images.githubusercontent.com/25477905/108505747-2aa5f400-72b8-11eb-90fc-60fc00d23f67.png)

This would require us to think of some logic as to which token is at the top of the list. Can be last updated balance, alphabetical, etc.

Another option is to not default to anything if they own multiple tokens, which I would prefer to the current state:
![image](https://user-images.githubusercontent.com/25477905/108505938-65a82780-72b8-11eb-90db-8e3377b450db.png)

**Comment by markmhendrickson** [comment]
@jasperjansz Do you want to assign this for a quick integration win? Or replace with an issue addressing the broader changes you want to make to the send form?
