### ISSUE TITLE
Add fees to send form

### ISSUE THREAD

**Issue by jasperjansz** [leather-io/extension#999]
![image](https://user-images.githubusercontent.com/25477905/108507578-d4868000-72ba-11eb-8a52-3beffb5121ae.png)

When I select "send max" it fills my entire balance of 499.99856 STX. I click preview, and it shows me this breakdown:

![image](https://user-images.githubusercontent.com/25477905/108507735-0bf52c80-72bb-11eb-89a0-694be11a72e8.png)

It is unclear to me whether I'm sending 499.99856 – 0.00018 STX, or that I actually require a balance of 499.99856 + 0.00018 STX to complete this transaction.

If the former, the "send max" should subtract the fee from the amount. Also suggest showing the fee on the first send page like in the design: 
![image](https://user-images.githubusercontent.com/25477905/108507896-4959ba00-72bb-11eb-9ea1-7335989cf4b1.png)

**Comment by markmhendrickson** [comment]
This appears resolved in the latest implementation

![image](https://user-images.githubusercontent.com/28991/123177586-d8532a80-d485-11eb-9ef9-cc2fd42dd9f7.png)
